/*
 * Copyright (c) 2014 Intel Mobile Communications GmbH
 *
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 */

#ifndef __STM_XGOLD_REGS_H
#define __STM_XGOLD_REGS_H
/*
This is a generated file - do not edit !
*/

/* REGISTER : STM_CLC */

#define REG_STM_CLC_OFFSET	0x0

/*	BITFIELD : FSOE */
  #define STM_CLC_FSOE_OFFSET	0x5
  #define STM_CLC_FSOE_LENGTH		0x1
  #define STM_CLC_FSOE_MASK	0x1
    #define STM_CLC_FSOE_FSOE_DIS	0x0
    #define STM_CLC_FSOE_FSOE_EN	0x1

/*	BITFIELD : SBWE */
  #define STM_CLC_SBWE_OFFSET	0x4
  #define STM_CLC_SBWE_LENGTH		0x1
  #define STM_CLC_SBWE_MASK	0x1
    #define STM_CLC_SBWE_SPEN_NO_CHANGE		0x0
    #define STM_CLC_SBWE_SPEN_CHANGE	0x1

/*	BITFIELD : EDIS */
  #define STM_CLC_EDIS_OFFSET	0x3
  #define STM_CLC_EDIS_LENGTH		0x1
  #define STM_CLC_EDIS_MASK	0x1
    #define STM_CLC_EDIS_EDIS_EN	0x0
    #define STM_CLC_EDIS_EDIS_DIS	0x1

/*	BITFIELD : SPEN */
  #define STM_CLC_SPEN_OFFSET	0x2
  #define STM_CLC_SPEN_LENGTH		0x1
  #define STM_CLC_SPEN_MASK	0x1
    #define STM_CLC_SPEN_OCDS_SLEEP_DIS		0x0
    #define STM_CLC_SPEN_OCDS_SLEEP_EN	0x1

/*	BITFIELD : DISS */
  #define STM_CLC_DISS_OFFSET	0x1
  #define STM_CLC_DISS_LENGTH		0x1
  #define STM_CLC_DISS_MASK	0x1
    #define STM_CLC_DISS_RUNNING	0x0
    #define STM_CLC_DISS_STOPPED	0x1

/*	BITFIELD : DISR */
  #define STM_CLC_DISR_OFFSET	0x0
  #define STM_CLC_DISR_LENGTH		0x1
  #define STM_CLC_DISR_MASK	0x1
    #define STM_CLC_DISR_RUN	0x0
    #define STM_CLC_DISR_STOP	0x1

/* REGISTER : STM_ID */

#define REG_STM_ID_OFFSET	0x8

/*	BITFIELD : ID */
  #define STM_ID_ID_OFFSET	0x8
  #define STM_ID_ID_LENGTH		0x8
  #define STM_ID_ID_MASK	0xff

/*	BITFIELD : REV */
  #define STM_ID_REV_OFFSET	0x0
  #define STM_ID_REV_LENGTH		0x8
  #define STM_ID_REV_MASK	0xff

/* REGISTER : STM_TIM0 */
#define REG_STM_TIM0_OFFSET   0x20

/* REGISTER : STM_TIM1 */
#define REG_STM_TIM1_OFFSET   0x24

/* REGISTER : STM_TIM2 */
#define REG_STM_TIM2_OFFSET   0x28

/* REGISTER : STM_TIM3 */
#define REG_STM_TIM3_OFFSET   0x2C

/* REGISTER : STM_TIM4 */
#define REG_STM_TIM4_OFFSET   0x30

/* REGISTER : STM_TIM5 */
#define REG_STM_TIM5_OFFSET   0x34

/* REGISTER : STM_TIM6 */

#define REG_STM_TIM6_OFFSET	0x38

/*	BITFIELD : SYSTIM */
  #define STM_TIM6_SYSTIM_OFFSET	0x0
  #define STM_TIM6_SYSTIM_LENGTH		0x18
  #define STM_TIM6_SYSTIM_MASK	0xffffff

/* REGISTER : STM_CAP */

#define REG_STM_CAP_OFFSET	0x3c

/*	BITFIELD : SYSTIM */
  #define STM_CAP_SYSTIM_OFFSET		0x0
  #define STM_CAP_SYSTIM_LENGTH		0x18
  #define STM_CAP_SYSTIM_MASK	0xffffff

/* REGISTER : STM_CMP0 */
#define REG_STM_CMP0_OFFSET   0x40

/* REGISTER : STM_CMP1 */
#define REG_STM_CMP1_OFFSET   0x44

/* REGISTER : STM_CMCON */

#define REG_STM_CMCON_OFFSET	0x48

/*	BITFIELD : MSTART1 */
  #define STM_CMCON_MSTART1_OFFSET	0x18
  #define STM_CMCON_MSTART1_LENGTH		0x5
  #define STM_CMCON_MSTART1_MASK	0x1f
    #define STM_CMCON_MSTART1_LB0	0x0
    #define STM_CMCON_MSTART1_LB1	0x1
    #define STM_CMCON_MSTART1_LB30	0x17
    #define STM_CMCON_MSTART1_LB31	0x18

/*	BITFIELD : MSIZE1 */
  #define STM_CMCON_MSIZE1_OFFSET	0x10
  #define STM_CMCON_MSIZE1_LENGTH		0x5
  #define STM_CMCON_MSIZE1_MASK		0x1f
    #define STM_CMCON_MSIZE1_COMP0	0x0
    #define STM_CMCON_MSIZE1_COMP1	0x1
    #define STM_CMCON_MSIZE1_COMP30	0x1e
    #define STM_CMCON_MSIZE1_COMP31	0x1f

/*	BITFIELD : MSTART0 */
  #define STM_CMCON_MSTART0_OFFSET	0x8
  #define STM_CMCON_MSTART0_LENGTH		0x5
  #define STM_CMCON_MSTART0_MASK	0x1f
    #define STM_CMCON_MSTART0_LB0	0x0
    #define STM_CMCON_MSTART0_LB1	0x1
    #define STM_CMCON_MSTART0_LB23	0x17
    #define STM_CMCON_MSTART0_LB24	0x18

/*	BITFIELD : MSIZE0 */
  #define STM_CMCON_MSIZE0_OFFSET	0x0
  #define STM_CMCON_MSIZE0_LENGTH		0x5
  #define STM_CMCON_MSIZE0_MASK		0x1f
    #define STM_CMCON_MSIZE0_COMP0	0x0
    #define STM_CMCON_MSIZE0_COMP1	0x1
    #define STM_CMCON_MSIZE0_COMP30	0x1e
    #define STM_CMCON_MSIZE0_COMP31	0x1f

/* REGISTER : STM_CMPXIR0_IRQSM */

#define REG_STM_CMPXIR0_IRQSM_OFFSET	0x58

/*	BITFIELD : CMP1EN */
  #define STM_CMPXIR0_IRQSM_CMP1EN_OFFSET	0x1
  #define STM_CMPXIR0_IRQSM_CMP1EN_LENGTH		0x1
  #define STM_CMPXIR0_IRQSM_CMP1EN_MASK		0x1
    #define STM_CMPXIR0_IRQSM_CMP1EN_NC1IR0	0x0
    #define STM_CMPXIR0_IRQSM_CMP1EN_C1IR0	0x1

/*	BITFIELD : CMP0EN */
  #define STM_CMPXIR0_IRQSM_CMP0EN_OFFSET	0x0
  #define STM_CMPXIR0_IRQSM_CMP0EN_LENGTH		0x1
  #define STM_CMPXIR0_IRQSM_CMP0EN_MASK		0x1
    #define STM_CMPXIR0_IRQSM_CMP0EN_NC0IR0	0x0
    #define STM_CMPXIR0_IRQSM_CMP0EN_C0IR0	0x1

/* REGISTER : STM_CMPXIR1_IRQSM */

#define REG_STM_CMPXIR1_IRQSM_OFFSET	0x5c

/*	BITFIELD : CMP1EN */
  #define STM_CMPXIR1_IRQSM_CMP1EN_OFFSET	0x1
  #define STM_CMPXIR1_IRQSM_CMP1EN_LENGTH		0x1
  #define STM_CMPXIR1_IRQSM_CMP1EN_MASK		0x1
    #define STM_CMPXIR1_IRQSM_CMP1EN_NC1IR1	0x0
    #define STM_CMPXIR1_IRQSM_CMP1EN_C1IR1	0x1

/*	BITFIELD : CMP0EN */
  #define STM_CMPXIR1_IRQSM_CMP0EN_OFFSET	0x0
  #define STM_CMPXIR1_IRQSM_CMP0EN_LENGTH		0x1
  #define STM_CMPXIR1_IRQSM_CMP0EN_MASK		0x1
    #define STM_CMPXIR1_IRQSM_CMP0EN_NC0IR1	0x0
    #define STM_CMPXIR1_IRQSM_CMP0EN_C0IR1	0x1


/* REGISTER : STM_CMPXIR0_IRQSC */
#define REG_STM_CMPXIR0_IRQSC_OFFSET   0x60

/*	BITFIELD : CMP1CL */
  #define STM_CMPXIR0_IRQSC_CMP1CL_OFFSET	0x1
  #define STM_CMPXIR0_IRQSC_CMP1CL_LENGTH	0x1
  #define STM_CMPXIR0_IRQSC_CMP1CL_MASK		0x1

    #define STM_CMPXIR0_IRQSC_CMP1CL_NC		0x0
    #define STM_CMPXIR0_IRQSC_CMP1CL_CLRC1	0x1

/*		BITFIELD : CMP0CL */
  #define STM_CMPXIR0_IRQSC_CMP0CL_OFFSET	0x0
  #define STM_CMPXIR0_IRQSC_CMP0CL_LENGTH	0x1
  #define STM_CMPXIR0_IRQSC_CMP0CL_MASK		0x1

    #define STM_CMPXIR0_IRQSC_CMP0CL_NC0	0x0
    #define STM_CMPXIR0_IRQSC_CMP0CL_CLRC0	0x1

/* REGISTER : STM_CMPXIR1_IRQSC */

#define REG_STM_CMPXIR1_IRQSC_OFFSET   0x64

/*	BITFIELD : CMP1CL */
  #define STM_CMPXIR1_IRQSC_CMP1CL_OFFSET	0x1
  #define STM_CMPXIR1_IRQSC_CMP1CL_LENGTH	0x1
  #define STM_CMPXIR1_IRQSC_CMP1CL_MASK		0x1

    #define STM_CMPXIR1_IRQSC_CMP1CL_NC		0x0
    #define STM_CMPXIR1_IRQSC_CMP1CL_CLRC1	0x1

/*	BITFIELD : CMP0CL */
  #define STM_CMPXIR1_IRQSC_CMP0CL_OFFSET	0x0
  #define STM_CMPXIR1_IRQSC_CMP0CL_LENGTH	0x1
  #define STM_CMPXIR1_IRQSC_CMP0CL_MASK		0x1

    #define STM_CMPXIR1_IRQSC_CMP0CL_NC		0x0
    #define STM_CMPXIR1_IRQSC_CMP0CL_CLRC0	0x1

/* REGISTER : STM_RIS */

#define REG_STM_RIS_OFFSET	0x80

/*	BITFIELD : IR1 */
  #define STM_RIS_IR1_OFFSET	0x1
  #define STM_RIS_IR1_LENGTH		0x1
  #define STM_RIS_IR1_MASK	0x1
    #define STM_RIS_IR1_NO_INT	0x0
    #define STM_RIS_IR1_INT_PEND	0x1

/*	BITFIELD : IR0 */
  #define STM_RIS_IR0_OFFSET	0x0
  #define STM_RIS_IR0_LENGTH		0x1
  #define STM_RIS_IR0_MASK	0x1
    #define STM_RIS_IR0_NO_INT	0x0
    #define STM_RIS_IR0_INT_PEND	0x1

/* REGISTER : STM_IMSC */

#define REG_STM_IMSC_OFFSET	0x84

/*	BITFIELD : IR1 */
  #define STM_IMSC_IR1_OFFSET	0x1
  #define STM_IMSC_IR1_LENGTH		0x1
  #define STM_IMSC_IR1_MASK	0x1
    #define STM_IMSC_IR1_INT_DIS	0x0
    #define STM_IMSC_IR1_INT_EN		0x1

/*	BITFIELD : IR0 */
  #define STM_IMSC_IR0_OFFSET	0x0
  #define STM_IMSC_IR0_LENGTH		0x1
  #define STM_IMSC_IR0_MASK	0x1
    #define STM_IMSC_IR0_INT_DIS	0x0
    #define STM_IMSC_IR0_INT_EN		0x1

/* REGISTER : STM_MIS */

#define REG_STM_MIS_OFFSET	0x88

/*	BITFIELD : IR1 */
  #define STM_MIS_IR1_OFFSET	0x1
  #define STM_MIS_IR1_LENGTH		0x1
  #define STM_MIS_IR1_MASK	0x1
    #define STM_MIS_IR1_NO_INT	0x0
    #define STM_MIS_IR1_INT_PEND	0x1

/*	BITFIELD : IR0 */
  #define STM_MIS_IR0_OFFSET	0x0
  #define STM_MIS_IR0_LENGTH		0x1
  #define STM_MIS_IR0_MASK	0x1
    #define STM_MIS_IR0_NO_INT	0x0
    #define STM_MIS_IR0_INT_PEND	0x1

/* REGISTER : STM_ISR */

#define REG_STM_ISR_OFFSET	0x90

/*	BITFIELD : IR1 */
  #define STM_ISR_IR1_OFFSET	0x1
  #define STM_ISR_IR1_LENGTH		0x1
  #define STM_ISR_IR1_MASK	0x1
    #define STM_ISR_IR1_NO_CHANGE	0x0
    #define STM_ISR_IR1_SET_INT		0x1

/*	BITFIELD : IR0 */
  #define STM_ISR_IR0_OFFSET	0x0
  #define STM_ISR_IR0_LENGTH		0x1
  #define STM_ISR_IR0_MASK	0x1
    #define STM_ISR_IR0_NO_CHANGE	0x0
    #define STM_ISR_IR0_SET_INT		0x1

#endif /* __STM_XGOLD_REGS_H */
