#
# Copyright (C) 2012-2013 Intel Mobile Communications GmbH
#
# This software is licensed under the terms of the GNU General Public
# License version 2, as published by the Free Software Foundation, and
# may be copied, distributed, and modified under those terms.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#

#ccflags-$(CONFIG_IDI_DEBUG) := -DDEBUG

#
# AG6x0 : AG610,AG620
#
obj-$(CONFIG_IDI_AG6X0) += ag6x0.o

