# Copyright (C) 2011-2014 Intel Mobile Communications GmbH.
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License Version 2
#  as published by the Free Software Foundation.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#  You should have received a copy of the GNU General Public License Version 2
#  along with this program. If not, see <http://www.gnu.org/licenses/>.

obj-y += dsp_audio.o dsp_audio_communication.o dsp_audio_drv.o dsp_audio_hal.o dsp_audio_interrupt.o

ccflags-y += -I$(srctree)/sound/soc/xgold/xgold_dsp/include
ccflags-y += -I$(srctree)/sound/soc/xgold/include
