/*
 *******************************************************************************
 *
 *  Component: XGold MIPI DSI driver
 *
 *  Copyright (C) 2014, Intel Mobile Communications GmbH.
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License Version 2
 *  as published by the Free Software Foundation.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 *  You should have received a copy of the GNU General Public License Version 2
 *  along with this program. If not, see <http://www.gnu.org/licenses/>.
 *
 *******************************************************************************
 */

#include <linux/types.h>
#include <linux/io.h>
#include <linux/delay.h>

#include "dsi_hwregs.h"

#define EXTREG(_id_, _addr_, _mask_, _shift_) \
	{#_id_, _addr_, _mask_, _shift_}

struct dsi_command dsi_regs[] = {
[EXR_DSI_CLC] =
	EXTREG(EXR_DSI_CLC, DSI_CLC, 0xFFFFFFFF, 0),
[EXR_DSI_CLC_RUN] =
	EXTREG(EXR_DSI_CLC_RUN, DSI_CLC, 0x3, 0),
[EXR_DSI_CLC_STAT] =
	EXTREG(EXR_DSI_CLC_STAT, DSI_CLC_STAT, 0xFFFFFFFF, 0),
[EXR_DSI_CLC_STAT_RUN] =
	EXTREG(EXR_DSI_CLC_STAT_RUN, DSI_CLC_STAT, 0x1, 0),
[EXR_DSI_CLC_STAT_MODEN] =
	EXTREG(EXR_DSI_CLC_STAT_MODEN, DSI_CLC_STAT, 0x1, 1),
[EXR_DSI_CLC_STAT_KID] =
	EXTREG(EXR_DSI_CLC_STAT_KID, DSI_CLC_STAT, 0x1, 7),
[EXR_DSI_ID] =
	EXTREG(EXR_DSI_ID, DSI_ID, 0xFFFFFFFF, 0),
[EXR_DSI_FIFO_ID] =
	EXTREG(EXR_DSI_FIFO_ID, DSI_FIFO_ID, 0xFFFFFFFF, 0),
[EXR_DSI_SRB_MSCONF_ID] =
	EXTREG(EXR_DSI_SRB_MSCONF_ID, DSI_SRB_MSCONF_ID, 0xFFFFFFFF, 0),
[EXR_DSI_SWCID] =
	EXTREG(EXR_DSI_SWCID, DSI_SWCID, 0xFFFFFFFF, 0),
[EXR_DSI_FIFO_CFG] =
	EXTREG(EXR_DSI_FIFO_CFG, DSI_FIFO_CFG, 0xFFFFFFFF, 0),
[EXR_DSI_FIFO_CTRL] =
	EXTREG(EXR_DSI_FIFO_CTRL, DSI_FIFO_CTRL, 0xFFFFFFFF, 0),
[EXR_DSI_MRPS_CTRL] =
	EXTREG(EXR_DSI_MRPS_CTRL, DSI_MRPS_CTRL, 0xFFFFFFFF, 0),
[EXR_DSI_RPS_STAT] =
	EXTREG(EXR_DSI_RPS_STAT, DSI_RPS_STAT, 0xFFFFFFFF, 0),
[EXR_DSI_TPS_CTRL] =
	EXTREG(EXR_DSI_TPS_CTRL, DSI_TPS_CTRL, 0xFFFFFFFF, 0),
[EXR_DSI_TPS_CTRL_TPS] =
	EXTREG(EXR_DSI_TPS_CTRL_TPS, DSI_TPS_CTRL, 0xFFFF, 0),
[EXR_DSI_FIFO_STAT] =
	EXTREG(EXR_DSI_FIFO_STAT, DSI_FIFO_STAT, 0xFFFFFFFF, 0),
[EXR_DSI_FIFO_STAT_RXFFS] =
	EXTREG(EXR_DSI_FIFO_STAT_RXFFS, DSI_FIFO_STAT, 0xFF, 0),
[EXR_DSI_RIS] =
	EXTREG(EXR_DSI_RIS, DSI_RIS, 0xFFFFFFFF, 0),
[EXR_DSI_IMSC] =
	EXTREG(EXR_DSI_IMSC, DSI_IMSC, 0xFFFFFFFF, 0),
[EXR_DSI_MIS] =
	EXTREG(EXR_DSI_MIS, DSI_MIS, 0xFFFFFFFF, 0),
[EXR_DSI_ISR] =
	EXTREG(EXR_DSI_ISR, DSI_ISR, 0xFFFFFFFF, 0),
[EXR_DSI_DMAE] =
	EXTREG(EXR_DSI_DMAE, DSI_DMAE, 0xFFFFFFFF, 0),
[EXR_DSI_ICR] =
	EXTREG(EXR_DSI_ICR, DSI_ICR, 0xFFFFFFFF, 0),
[EXR_DSI_CFG] =
	EXTREG(EXR_DSI_CFG, DSI_CFG, 0xFFFFFFFF, 0),
[EXR_DSI_CFG_CFG_LAT] =
	EXTREG(EXR_DSI_CFG_CFG_LAT, DSI_CFG, 0x1, 0),
[EXR_DSI_CFG_HEAD_LAT] =
	EXTREG(EXR_DSI_CFG_HEAD_LAT, DSI_CFG, 0x1, 1),
[EXR_DSI_CFG_GATE] =
	EXTREG(EXR_DSI_CFG_GATE, DSI_CFG, 0x1, 2),
[EXR_DSI_CFG_TX] =
	EXTREG(EXR_DSI_CFG_TX, DSI_CFG, 0x1, 3),
[EXR_DSI_CFG_LP] =
	EXTREG(EXR_DSI_CFG_LP, DSI_CFG, 0x1, 4),
[EXR_DSI_CFG_MODE] =
	EXTREG(EXR_DSI_CFG_MODE, DSI_CFG, 0x1, 5),
[EXR_DSI_CFG_EOT] =
	EXTREG(EXR_DSI_CFG_EOT, DSI_CFG, 0x1, 6),
[EXR_DSI_CFG_TURN] =
	EXTREG(EXR_DSI_CFG_TURN, DSI_CFG, 0x1, 7),
[EXR_DSI_CFG_VALID] =
	EXTREG(EXR_DSI_CFG_VALID, DSI_CFG, 0x1, 8),
[EXR_DSI_CFG_DATA] =
	EXTREG(EXR_DSI_CFG_DATA, DSI_CFG, 0x1, 9),
[EXR_DSI_CFG_STP] =
	EXTREG(EXR_DSI_CFG_STP, DSI_CFG, 0x1, 10),
[EXR_DSI_CFG_ULPS] =
	EXTREG(EXR_DSI_CFG_ULPS, DSI_CFG, 0x1, 11),
[EXR_DSI_CFG_EN] =
	EXTREG(EXR_DSI_CFG_EN, DSI_CFG, 0x1, 12),
[EXR_DSI_CFG_LANES] =
	EXTREG(EXR_DSI_CFG_LANES, DSI_CFG, 0x3, 13),
[EXR_DSI_CFG_ID] =
	EXTREG(EXR_DSI_CFG_ID, DSI_CFG, 0x3, 15),
[EXR_DSI_CFG_TXS] =
	EXTREG(EXR_DSI_CFG_TXS, DSI_CFG, 0x1, 17),
[EXR_DSI_CFG_TE] =
	EXTREG(EXR_DSI_CFG_TE, DSI_CFG, 0x1, 18),
[EXR_DSI_CFG_FIN] =
	EXTREG(EXR_DSI_CFG_FIN, DSI_CFG, 0x1, 19),
[EXR_DSI_CFG_VSYNC] =
	EXTREG(EXR_DSI_CFG_VSYNC, DSI_CFG, 0x1, 24),
[EXR_DSI_CFG_PSYNC] =
	EXTREG(EXR_DSI_CFG_PSYNC, DSI_CFG, 0x1, 25),
[EXR_DSI_CFG_SOURCE] =
	EXTREG(EXR_DSI_CFG_SOURCE, DSI_CFG, 0x1, 31),
[EXR_DSI_CLK] =
	EXTREG(EXR_DSI_CLK, DSI_CLK, 0xFFFFFFFF, 0),
[EXR_DSI_HEAD] =
	EXTREG(EXR_DSI_HEAD, DSI_HEAD, 0xFFFFFFFF, 0),
[EXR_DSI_HEAD_HEADER] =
	EXTREG(EXR_DSI_HEAD_HEADER, DSI_HEAD, 0xFF, 0),
[EXR_DSI_HEAD_WCNT] =
	EXTREG(EXR_DSI_HEAD_WCNT, DSI_HEAD, 0xFFFF, 8),
[EXR_DSI_HEAD_CMD] =
	EXTREG(EXR_DSI_HEAD_CMD, DSI_HEAD, 0xFF, 24),
[EXR_DSI_TO0] =
	EXTREG(EXR_DSI_TO0, DSI_TO0, 0xFFFFFFFF, 0),
[EXR_DSI_TO1] =
	EXTREG(EXR_DSI_TO1, DSI_TO1, 0xFFFFFFFF, 0),
[EXR_DSI_VID0] =
	EXTREG(EXR_DSI_VID0, DSI_VID0, 0xFFFFFFFF, 0),
[EXR_DSI_VID0_HFP_BYTES] =
	EXTREG(EXR_DSI_VID0_HFP_BYTES, DSI_VID0, 0xFF, 0),
[EXR_DSI_VID0_HBP_BYTES] =
	EXTREG(EXR_DSI_VID0_HBP_BYTES, DSI_VID0, 0xFF, 8),
[EXR_DSI_VID0_HSA_BYTES] =
	EXTREG(EXR_DSI_VID0_HSA_BYTES, DSI_VID0, 0xFF, 16),
[EXR_DSI_VID0_HFP] =
	EXTREG(EXR_DSI_VID0_HFP, DSI_VID0, 0x1, 24),
[EXR_DSI_VID0_HBP] =
	EXTREG(EXR_DSI_VID0_HBP, DSI_VID0, 0x1, 25),
[EXR_DSI_VID0_HSA] =
	EXTREG(EXR_DSI_VID0_HSA, DSI_VID0, 0x1, 26),
[EXR_DSI_VID0_HFP_LP] =
	EXTREG(EXR_DSI_VID0_HFP_LP, DSI_VID0, 0x1, 27),
[EXR_DSI_VID0_HBP_LP] =
	EXTREG(EXR_DSI_VID0_HBP_LP, DSI_VID0, 0x1, 28),
[EXR_DSI_VID0_HSA_LP] =
	EXTREG(EXR_DSI_VID0_HSA_LP, DSI_VID0, 0x1, 29),
[EXR_DSI_VID1] =
	EXTREG(EXR_DSI_VID1, DSI_VID1, 0xFFFFFFFF, 0),
[EXR_DSI_VID1_VACT_LINES] =
	EXTREG(EXR_DSI_VID1_VACT_LINES, DSI_VID1, 0xFFF, 0),
[EXR_DSI_VID1_MODE] =
	EXTREG(EXR_DSI_VID1_MODE, DSI_VID1, 0x3, 12),
[EXR_DSI_VID1_ID] =
	EXTREG(EXR_DSI_VID1_ID, DSI_VID1, 0x3, 14),
[EXR_DSI_VID1_PIXEL] =
	EXTREG(EXR_DSI_VID1_PIXEL, DSI_VID1, 0x3, 16),
[EXR_DSI_VID1_FILL_BUFFER_TO] =
	EXTREG(EXR_DSI_VID1_FILL_BUFFER_TO, DSI_VID1, 0x3FF, 18),
[EXR_DSI_VID1_LAST_CS] =
	EXTREG(EXR_DSI_VID1_LAST_CS, DSI_VID1, 0xF, 28),
[EXR_DSI_VID2] =
	EXTREG(EXR_DSI_VID2, DSI_VID2, 0xFFFFFFFF, 0),
[EXR_DSI_VID2_VFP] =
	EXTREG(EXR_DSI_VID2_VFP, DSI_VID2, 0xFF, 0),
[EXR_DSI_VID2_VBP] =
	EXTREG(EXR_DSI_VID2_VBP, DSI_VID2, 0xFF, 8),
[EXR_DSI_VID2_VSA] =
	EXTREG(EXR_DSI_VID2_VSA, DSI_VID2, 0xFF, 16),
[EXR_DSI_VID3] =
	EXTREG(EXR_DSI_VID3, DSI_VID3, 0xFFFFFFFF, 0),
[EXR_DSI_VID3_PIXEL_PACKETS] =
	EXTREG(EXR_DSI_VID3_PIXEL_PACKETS, DSI_VID3, 0xFFFF, 0),
[EXR_DSI_VID3_PIXEL_BYTES] =
	EXTREG(EXR_DSI_VID3_PIXEL_BYTES, DSI_VID3, 0xFFFF, 16),
[EXR_DSI_VID4] =
	EXTREG(EXR_DSI_VID4, DSI_VID4, 0xFFFFFFFF, 0),
[EXR_DSI_VID4_BLANK_PACKETS] =
	EXTREG(EXR_DSI_VID4_BLANK_PACKETS, DSI_VID4, 0xFFFF, 0),
[EXR_DSI_VID4_BLANK_BYTES] =
	EXTREG(EXR_DSI_VID4_BLANK_BYTES, DSI_VID4, 0xFFFF, 16),
[EXR_DSI_VID5] =
	EXTREG(EXR_DSI_VID5, DSI_VID5, 0xFFFFFFFF, 0),
[EXR_DSI_VID5_LINE_TIME] =
	EXTREG(EXR_DSI_VID5_LINE_TIME, DSI_VID5, 0xFFFF, 0),
[EXR_DSI_VID5_BLLP_TIME] =
	EXTREG(EXR_DSI_VID5_BLLP_TIME, DSI_VID5, 0xFFFF, 16),
[EXR_DSI_VID6] =
	EXTREG(EXR_DSI_VID6, DSI_VID6, 0xFFFFFFFF, 0),
[EXR_DSI_VID6_LAST_BLANK] =
	EXTREG(EXR_DSI_VID6_LAST_BLANK, DSI_VID6, 0xFFFF, 0),
[EXR_DSI_VID6_LAST_PIXEL] =
	EXTREG(EXR_DSI_VID6_LAST_PIXEL, DSI_VID6, 0xFFFF, 16),
[EXR_DSI_PHY0] =
	EXTREG(EXR_DSI_PHY0, DSI_PHY0, 0xFFFFFFFF, 0),
[EXR_DSI_PHY0_SHARE] =
	EXTREG(EXR_DSI_PHY0_SHARE, DSI_PHY0, 0x1, 0),
[EXR_DSI_PHY0_M] =
	EXTREG(EXR_DSI_PHY0_M, DSI_PHY0, 0xF, 1),
[EXR_DSI_PHY0_N] =
	EXTREG(EXR_DSI_PHY0_N, DSI_PHY0, 0xFF, 5),
[EXR_DSI_PHY0_POWERUP] =
	EXTREG(EXR_DSI_PHY0_POWERUP, DSI_PHY0, 0x3F, 13),
[EXR_DSI_PHY0_CALIB] =
	EXTREG(EXR_DSI_PHY0_CALIB, DSI_PHY0, 0x3F, 19),
[EXR_DSI_PHY0_TO_LP_HS_REQ] =
	EXTREG(EXR_DSI_PHY0_TO_LP_HS_REQ, DSI_PHY0, 0x3F, 25),
[EXR_DSI_PHY1] =
	EXTREG(EXR_DSI_PHY1, DSI_PHY1, 0xFFFFFFFF, 0),
[EXR_DSI_PHY1_TO_LP_HS_DIS] =
	EXTREG(EXR_DSI_PHY1_TO_LP_HS_DIS, DSI_PHY1, 0x3F, 0),
[EXR_DSI_PHY1_TO_LP_EOT] =
	EXTREG(EXR_DSI_PHY1_TO_LP_EOT, DSI_PHY1, 0x3F, 6),
[EXR_DSI_PHY1_TO_HS_ZERO] =
	EXTREG(EXR_DSI_PHY1_TO_HS_ZERO, DSI_PHY1, 0x3F, 12),
[EXR_DSI_PHY1_TO_HS_FLIP] =
	EXTREG(EXR_DSI_PHY1_TO_HS_FLIP, DSI_PHY1, 0x3F, 18),
[EXR_DSI_PHY1_LP_CLK_DIV] =
	EXTREG(EXR_DSI_PHY1_LP_CLK_DIV, DSI_PHY1, 0x3F, 24),
[EXR_DSI_PHY2] =
	EXTREG(EXR_DSI_PHY2, DSI_PHY2, 0xFFFFFFFF, 0),
[EXR_DSI_PHY2_HS_CLK_PRE] =
	EXTREG(EXR_DSI_PHY2_HS_CLK_PRE, DSI_PHY2, 0x3FF, 0),
[EXR_DSI_PHY2_HS_CLK_POST] =
	EXTREG(EXR_DSI_PHY2_HS_CLK_POST, DSI_PHY2, 0x3FF, 10),
[EXR_DSI_PHY2_DAT_DELAY] =
	EXTREG(EXR_DSI_PHY2_DAT_DELAY, DSI_PHY2, 0xF, 20),
[EXR_DSI_PHY2_CLK_DELAY] =
	EXTREG(EXR_DSI_PHY2_CLK_DELAY, DSI_PHY2, 0xF, 24),
[EXR_DSI_PHY2_LPTX_TFALL] =
	EXTREG(EXR_DSI_PHY2_LPTX_TFALL, DSI_PHY2, 0x7, 28),
[EXR_DSI_PHY3] =
	EXTREG(EXR_DSI_PHY3, DSI_PHY3, 0xFFFFFFFF, 0),
[EXR_DSI_PHY3_EN] =
	EXTREG(EXR_DSI_PHY3_EN, DSI_PHY3, 0x1, 0),
[EXR_DSI_PHY3_LPTX_TRISE] =
	EXTREG(EXR_DSI_PHY3_LPTX_TRISE, DSI_PHY3, 0x7, 1),
[EXR_DSI_PHY3_LPTX_VREF] =
	EXTREG(EXR_DSI_PHY3_LPTX_VREF, DSI_PHY3, 0x1F, 4),
[EXR_DSI_STAT] =
	EXTREG(EXR_DSI_STAT, DSI_STAT, 0xFFFFFFFF, 0),
[EXR_DSI_STAT_DSI_BSY] =
	EXTREG(EXR_DSI_STAT_DSI_STAT, DSI_STAT, 0x1, 0),
[EXR_DSI_STAT_DSI_FULL] =
	EXTREG(EXR_DSI_STAT_DSI_FULL, DSI_STAT, 0x1, 2),
[EXR_DSI_STAT_DSI_DIR] =
	EXTREG(EXR_DSI_STAT_DSI_DIR, DSI_STAT, 0x1, 3),
[EXR_DSI_STAT_DSI_LOCK] =
	EXTREG(EXR_DSI_STAT_DSI_LOCK, DSI_STAT, 0x1, 4),
[EXR_DSI_TXD] =
	EXTREG(EXR_DSI_TXD, DSI_TXD, 0xFFFFFFFF, 0),
[EXR_DSI_RXD] =
	EXTREG(EXR_DSI_RXD, DSI_RXD, 0xFFFFFFFF, 0),
};

int dsi_wait_status(struct xgold_mipi_dsi_device *mipi_dsi, unsigned int reg,
		     unsigned int value, unsigned int mask, unsigned int delay,
		     unsigned int count)
{
	unsigned int read_value;
	int found = 0;

	do {
		read_value = dsi_read_field(mipi_dsi, reg);
		if ((read_value & mask) == value) {
			found = 1;
			break;
		}
		if (delay)
			msleep(delay);
	} while (--count);

	if (!found) {
		DSI_ERR("%s() FAILED reg 0x%x 0x%08x != 0x%08x\n",
				__func__, reg, value, read_value);
		found = -EBUSY;
	} else
		pr_debug("%s() reg 0x%x 0x%08x == 0x%08x\n", __func__,
				reg, value, read_value);

	return found;
}

/**
 * Read DSI register
 */
unsigned int dsi_read_field(struct xgold_mipi_dsi_device *mipi_dsi,
			    unsigned int id)
{
	struct dsi_command *cmd = &dsi_regs[id];

	return (ioread32(mipi_dsi->regbase + cmd->addr) >> cmd->shift) &
		cmd->mask;
}

/**
 * Write DSI register
 */
void dsi_write_field(struct xgold_mipi_dsi_device *mipi_dsi,
		     unsigned int id, u32 val)
{
	u32 regval = 0;
	struct dsi_command *cmd = &dsi_regs[id];

	if (id == EXR_DSI_CFG)
		val |= mipi_dsi->cur_display->dif.dsi.dsi_cfg_reg;

	if (cmd->mask == 0xFFFFFFFF) {
		iowrite32(val, mipi_dsi->regbase + cmd->addr);
	} else {
		val = (val << cmd->shift) & (cmd->mask << cmd->shift);
		regval = ioread32(mipi_dsi->regbase + cmd->addr) &
			~(cmd->mask << cmd->shift);
		iowrite32(val | regval, mipi_dsi->regbase + cmd->addr);
	}
}
