#
# Copyright (C) 2012-2013 Intel Mobile Communications GmbH
#
# This software is licensed under the terms of the GNU General Public
# License version 2, as published by the Free Software Foundation, and
# may be copied, distributed, and modified under those terms.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#

#
# Makefile for the IDI controllers
#

#CFLAGS_imc_controller.o := -DDEBUG

obj-$(CONFIG_IDI_IMC) += imc_controller.o
obj-$(CONFIG_IDI_IMC_PLATFORM) += imc_controller-platform.o
obj-$(CONFIG_IDI_IMC_PCI) += imc_controller-pci.o
