# Copyright (C) 2014 Intel Mobile Communications GmbH
#
# This program is free software; you can redistribute it and/or modify it
# under the terms and conditions of the GNU General Public License,
# version 2, as published by the Free Software Foundation.
#
# This program is distributed in the hope it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.	 See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin St - Fifth Floor, Boston, MA 02110-1301 USA.
#
# Notes:
# Aug 22 2014: IMC: initial version

#-------------------------------------------------------------------------------
#-
#--	 Abstract : Makefile for vvpu vbpipe interface
#--
#-----------------------------------------------------------------------------*/

# define required files
# obj-n: do not build
# obj-y: include in kernel
# obj-m: build as module

obj-$(CONFIG_MOBILEVISOR_VDRIVER_PIPE) += vvpu_vbpipe.o
