#define ERRLOG_0_ID_COREID(_base) ((_base) + 0x0)
#define ERRLOG_0_ID_COREID_CORETYPEID_OFFSET 0x0
#define ERRLOG_0_ID_COREID_CORETYPEID_WIDTH 0x8
#define ERRLOG_0_ID_COREID_CORETYPEID_MASK 0xff
#define ERRLOG_0_ID_COREID_CORETYPEID(_reg) (((_reg) & 0xff) >> 0x0)
#define ERRLOG_0_ID_COREID_CORECHECKSUM_OFFSET 0x8
#define ERRLOG_0_ID_COREID_CORECHECKSUM_WIDTH 0x18
#define ERRLOG_0_ID_COREID_CORECHECKSUM_MASK 0xffffff00
#define ERRLOG_0_ID_COREID_CORECHECKSUM(_reg) (((_reg) & 0xffffff00) >> 0x8)

#define ERRLOG_0_ID_REVISIONID(_base) ((_base) + 0x4)
#define ERRLOG_0_ID_REVISIONID_USERID_OFFSET 0x0
#define ERRLOG_0_ID_REVISIONID_USERID_WIDTH 0x8
#define ERRLOG_0_ID_REVISIONID_USERID_MASK 0xff
#define ERRLOG_0_ID_REVISIONID_USERID(_reg) (((_reg) & 0xff) >> 0x0)
#define ERRLOG_0_ID_REVISIONID_FLEXNOCID_OFFSET 0x8
#define ERRLOG_0_ID_REVISIONID_FLEXNOCID_WIDTH 0x18
#define ERRLOG_0_ID_REVISIONID_FLEXNOCID_MASK 0xffffff00
#define ERRLOG_0_ID_REVISIONID_FLEXNOCID(_reg) (((_reg) & 0xffffff00) >> 0x8)

#define ERRLOG_0_FAULTEN(_base) ((_base) + 0x8)
#define ERRLOG_0_FAULTEN_FAULTEN_OFFSET 0x0
#define ERRLOG_0_FAULTEN_FAULTEN_WIDTH 0x1
#define ERRLOG_0_FAULTEN_FAULTEN_MASK 0x1
#define ERRLOG_0_FAULTEN_FAULTEN(_reg) (((_reg) & 0x1) >> 0x0)

#define ERRLOG_0_ERRVLD(_base) ((_base) + 0xc)
#define ERRLOG_0_ERRVLD_ERRVLD_OFFSET 0x0
#define ERRLOG_0_ERRVLD_ERRVLD_WIDTH 0x1
#define ERRLOG_0_ERRVLD_ERRVLD_MASK 0x1
#define ERRLOG_0_ERRVLD_ERRVLD(_reg) (((_reg) & 0x1) >> 0x0)

#define ERRLOG_0_ERRCLR(_base) ((_base) + 0x10)
#define ERRLOG_0_ERRCLR_ERRCLR_OFFSET 0x0
#define ERRLOG_0_ERRCLR_ERRCLR_WIDTH 0x1
#define ERRLOG_0_ERRCLR_ERRCLR_MASK 0x1
#define ERRLOG_0_ERRCLR_ERRCLR(_reg) (((_reg) & 0x1) >> 0x0)

#define ERRLOG_0_ERRLOG0(_base) ((_base) + 0x14)
#define ERRLOG_0_ERRLOG0_LOCK_OFFSET 0x0
#define ERRLOG_0_ERRLOG0_LOCK_WIDTH 0x1
#define ERRLOG_0_ERRLOG0_LOCK_MASK 0x1
#define ERRLOG_0_ERRLOG0_LOCK(_reg) (((_reg) & 0x1) >> 0x0)
#define ERRLOG_0_ERRLOG0_OPC_OFFSET 0x1
#define ERRLOG_0_ERRLOG0_OPC_WIDTH 0x4
#define ERRLOG_0_ERRLOG0_OPC_MASK 0x1e
#define ERRLOG_0_ERRLOG0_OPC(_reg) (((_reg) & 0x1e) >> 0x1)
#define ERRLOG_0_ERRLOG0_ERRCODE_OFFSET 0x8
#define ERRLOG_0_ERRLOG0_ERRCODE_WIDTH 0x3
#define ERRLOG_0_ERRLOG0_ERRCODE_MASK 0x700
#define ERRLOG_0_ERRLOG0_ERRCODE(_reg) (((_reg) & 0x700) >> 0x8)
#define ERRLOG_0_ERRLOG0_LEN1_OFFSET 0x10
#define ERRLOG_0_ERRLOG0_LEN1_WIDTH 0x7
#define ERRLOG_0_ERRLOG0_LEN1_MASK 0x7f0000
#define ERRLOG_0_ERRLOG0_LEN1(_reg) (((_reg) & 0x7f0000) >> 0x10)
#define ERRLOG_0_ERRLOG0_FORMAT_OFFSET 0x1f
#define ERRLOG_0_ERRLOG0_FORMAT_WIDTH 0x1
#define ERRLOG_0_ERRLOG0_FORMAT_MASK 0x80000000
#define ERRLOG_0_ERRLOG0_FORMAT(_reg) (((_reg) & 0x80000000) >> 0x1f)

#define ERRLOG_0_ERRLOG1(_base) ((_base) + 0x18)
#define ERRLOG_0_ERRLOG1_ERRLOG1_OFFSET 0x0
#define ERRLOG_0_ERRLOG1_ERRLOG1_WIDTH 0x11
#define ERRLOG_0_ERRLOG1_ERRLOG1_MASK 0x1ffff
#define ERRLOG_0_ERRLOG1_ERRLOG1(_reg) (((_reg) & 0x1ffff) >> 0x0)

#define ERRLOG_0_ERRLOG3(_base) ((_base) + 0x20)
#define ERRLOG_0_ERRLOG3_ERRLOG3_OFFSET 0x0
#define ERRLOG_0_ERRLOG3_ERRLOG3_WIDTH 0x20
#define ERRLOG_0_ERRLOG3_ERRLOG3_MASK 0xffffffff
#define ERRLOG_0_ERRLOG3_ERRLOG3(_reg) (((_reg) & 0xffffffff) >> 0x0)

#define ERRLOG_0_ERRLOG5(_base) ((_base) + 0x28)
#define ERRLOG_0_ERRLOG5_ERRLOG5_OFFSET 0x0
#define ERRLOG_0_ERRLOG5_ERRLOG5_WIDTH 0x9
#define ERRLOG_0_ERRLOG5_ERRLOG5_MASK 0x1ff
#define ERRLOG_0_ERRLOG5_ERRLOG5(_reg) (((_reg) & 0x1ff) >> 0x0)

#define ERRLOG_0_ERRLOG7(_base) ((_base) + 0x30)
#define ERRLOG_0_ERRLOG7_ERRLOG7_OFFSET 0x0
#define ERRLOG_0_ERRLOG7_ERRLOG7_WIDTH 0x4
#define ERRLOG_0_ERRLOG7_ERRLOG7_MASK 0xf
#define ERRLOG_0_ERRLOG7_ERRLOG7(_reg) (((_reg) & 0xf) >> 0x0)

#define PROBE_ID_COREID(_base) ((_base) + 0x1000)
#define PROBE_ID_COREID_CORETYPEID_OFFSET 0x0
#define PROBE_ID_COREID_CORETYPEID_WIDTH 0x8
#define PROBE_ID_COREID_CORETYPEID_MASK 0xff
#define PROBE_ID_COREID_CORETYPEID(_reg) (((_reg) & 0xff) >> 0x0)
#define PROBE_ID_COREID_CORECHECKSUM_OFFSET 0x8
#define PROBE_ID_COREID_CORECHECKSUM_WIDTH 0x18
#define PROBE_ID_COREID_CORECHECKSUM_MASK 0xffffff00
#define PROBE_ID_COREID_CORECHECKSUM(_reg) (((_reg) & 0xffffff00) >> 0x8)

#define PROBE_ID_REVISIONID(_base) ((_base) + 0x1004)
#define PROBE_ID_REVISIONID_USERID_OFFSET 0x0
#define PROBE_ID_REVISIONID_USERID_WIDTH 0x8
#define PROBE_ID_REVISIONID_USERID_MASK 0xff
#define PROBE_ID_REVISIONID_USERID(_reg) (((_reg) & 0xff) >> 0x0)
#define PROBE_ID_REVISIONID_FLEXNOCID_OFFSET 0x8
#define PROBE_ID_REVISIONID_FLEXNOCID_WIDTH 0x18
#define PROBE_ID_REVISIONID_FLEXNOCID_MASK 0xffffff00
#define PROBE_ID_REVISIONID_FLEXNOCID(_reg) (((_reg) & 0xffffff00) >> 0x8)

#define PROBE_MAINCTL(_base, _offset, _probe) ((_base) + (_offset) +  \
		(_probe * 0x400) + 8)
#define PROBE_MAINCTL_ERREN_OFFSET 0x0
#define PROBE_MAINCTL_ERREN_WIDTH 0x1
#define PROBE_MAINCTL_ERREN_MASK 0x1
#define PROBE_MAINCTL_ERREN(_reg) (((_reg) & 0x1) >> 0x0)
#define PROBE_MAINCTL_TRACEEN_OFFSET 0x1
#define PROBE_MAINCTL_TRACEEN_WIDTH 0x1
#define PROBE_MAINCTL_TRACEEN_MASK 0x2
#define PROBE_MAINCTL_TRACEEN(_reg) (((_reg) & 0x2) >> 0x1)
#define PROBE_MAINCTL_PAYLOADEN_OFFSET 0x2
#define PROBE_MAINCTL_PAYLOADEN_WIDTH 0x1
#define PROBE_MAINCTL_PAYLOADEN_MASK 0x4
#define PROBE_MAINCTL_PAYLOADEN(_reg) (((_reg) & 0x4) >> 0x2)
#define PROBE_MAINCTL_STATEN_OFFSET 0x3
#define PROBE_MAINCTL_STATEN_WIDTH 0x1
#define PROBE_MAINCTL_STATEN_MASK 0x8
#define PROBE_MAINCTL_STATEN(_reg) (((_reg) & 0x8) >> 0x3)
#define PROBE_MAINCTL_ALARMEN_OFFSET 0x4
#define PROBE_MAINCTL_ALARMEN_WIDTH 0x1
#define PROBE_MAINCTL_ALARMEN_MASK 0x10
#define PROBE_MAINCTL_ALARMEN(_reg) (((_reg) & 0x10) >> 0x4)
#define PROBE_MAINCTL_STATCONDDUMP_OFFSET 0x5
#define PROBE_MAINCTL_STATCONDDUMP_WIDTH 0x1
#define PROBE_MAINCTL_STATCONDDUMP_MASK 0x20
#define PROBE_MAINCTL_STATCONDDUMP(_reg) (((_reg) & 0x20) >> 0x5)
#define PROBE_MAINCTL_INTRUSIVEMODE_OFFSET 0x6
#define PROBE_MAINCTL_INTRUSIVEMODE_WIDTH 0x1
#define PROBE_MAINCTL_INTRUSIVEMODE_MASK 0x40
#define PROBE_MAINCTL_INTRUSIVEMODE(_reg) (((_reg) & 0x40) >> 0x6)

#define PROBE_CFGCTL(_base, _offset, _probe) ((_base) + (_offset) + \
		(_probe * 0x400) + 0xc)
#define PROBE_CFGCTL_GLOBALEN_OFFSET 0x0
#define PROBE_CFGCTL_GLOBALEN_WIDTH 0x1
#define PROBE_CFGCTL_GLOBALEN_MASK 0x1
#define PROBE_CFGCTL_GLOBALEN(_reg) (((_reg) & 0x1) >> 0x0)
#define PROBE_CFGCTL_ACTIVE_OFFSET 0x1
#define PROBE_CFGCTL_ACTIVE_WIDTH 0x1
#define PROBE_CFGCTL_ACTIVE_MASK 0x2
#define PROBE_CFGCTL_ACTIVE(_reg) (((_reg) & 0x2) >> 0x1)

#define PROBE_TRACEPORTSEL(_base, _offset, _probe) \
	((_base) + (_offset) + (_probe * 0x400) + 0x10)
#define PROBE_TRACEPORTSEL_TRACEPORTSEL_OFFSET 0x0
#define PROBE_TRACEPORTSEL_TRACEPORTSEL_WIDTH 0x3
#define PROBE_TRACEPORTSEL_TRACEPORTSEL_MASK 0x7
#define PROBE_TRACEPORTSEL_TRACEPORTSEL(_reg) (((_reg) & 0x7) >> 0x0)

#define PROBE_FILTERLUT(_base, _offset, _probe) \
	((_base) + (_offset) + 0x14)
#define PROBE_FILTERLUT_FILTERLUT_OFFSET 0x0
#define PROBE_FILTERLUT_FILTERLUT_WIDTH 0x10
#define PROBE_FILTERLUT_FILTERLUT_MASK 0xffff
#define PROBE_FILTERLUT_FILTERLUT(_reg) (((_reg) & 0xffff) >> 0x0)

#define PROBE_TRACEALARMEN(_base, _offset, _probe) \
	((_base) + 0x1000 + (_probe * 0x400) + 0x18)
#define PROBE_TRACEALARMEN_TRACEALARMEN_OFFSET 0x0
#define PROBE_TRACEALARMEN_TRACEALARMEN_WIDTH 0x5
#define PROBE_TRACEALARMEN_TRACEALARMEN_MASK 0x1f
#define PROBE_TRACEALARMEN_TRACEALARMEN(_reg) (((_reg) & 0x1f) >> 0x0)

#define PROBE_TRACEALARMSTATUS(_base, _offset, _probe) \
	((_base) + (_offset) + (_probe * 0x400) + 0x1c)
#define PROBE_TRACEALARMSTATUS_TRACEALARMSTATUS_OFFSET 0x0
#define PROBE_TRACEALARMSTATUS_TRACEALARMSTATUS_WIDTH 0x5
#define PROBE_TRACEALARMSTATUS_TRACEALARMSTATUS_MASK 0x1f
#define PROBE_TRACEALARMSTATUS_TRACEALARMSTATUS(_reg) (((_reg) & 0x1f) >> 0x0)

#define PROBE_TRACEALARMCLR(_base, _offset, _probe) \
	((_base) + (_offset) + (_probe * 0x400) + 0x20)
#define PROBE_TRACEALARMCLR_TRACEALARMCLR_OFFSET 0x0
#define PROBE_TRACEALARMCLR_TRACEALARMCLR_WIDTH 0x5
#define PROBE_TRACEALARMCLR_TRACEALARMCLR_MASK 0x1f
#define PROBE_TRACEALARMCLR_TRACEALARMCLR(_reg) (((_reg) & 0x1f) >> 0x0)

#define PROBE_STATPERIOD(_base, _offset, _probe) \
	((_base) + (_offset) + (_probe * 0x400) + 0x24)
#define PROBE_STATPERIOD_STATPERIOD_OFFSET 0x0
#define PROBE_STATPERIOD_STATPERIOD_WIDTH 0x5
#define PROBE_STATPERIOD_STATPERIOD_MASK 0x1f
#define PROBE_STATPERIOD_STATPERIOD(_reg) (((_reg) & 0x1f) >> 0x0)

#define PROBE_STATGO(_base, _offset, _probe) \
	((_base) + (_offset) + (_probe * 0x400) + 0x28)
#define PROBE_STATGO_STATGO_OFFSET 0x0
#define PROBE_STATGO_STATGO_WIDTH 0x1
#define PROBE_STATGO_STATGO_MASK 0x1
#define PROBE_STATGO_STATGO(_reg) (((_reg) & 0x1) >> 0x0)

#define PROBE_STATALARMMIN(_base, _offset, _probe) \
	((_base) + (_offset) + (_probe * 0x400) + 0x2c)
#define PROBE_STATALARMMIN_STATALARMMIN_OFFSET 0x0
#define PROBE_STATALARMMIN_STATALARMMIN_WIDTH 0x20
#define PROBE_STATALARMMIN_STATALARMMIN_MASK 0xffffffff
#define PROBE_STATALARMMIN_STATALARMMIN(_reg) (((_reg) & 0xffffffff) >> 0x0)

#define PROBE_STATALARMMAX(_base, _offset, _probe) \
	((_base) + (_offset) + (_probe * 0x400) + 0x30)
#define PROBE_STATALARMMAX_STATALARMMAX_OFFSET 0x0
#define PROBE_STATALARMMAX_STATALARMMAX_WIDTH 0x20
#define PROBE_STATALARMMAX_STATALARMMAX_MASK 0xffffffff
#define PROBE_STATALARMMAX_STATALARMMAX(_reg) (((_reg) & 0xffffffff) >> 0x0)

#define PROBE_STATALARMSTATUS(_base, _offset, _probe) \
	((_base) + (_offset) + (_probe * 0x400) + 0x34)
#define PROBE_STATALARMSTATUS_STATALARMSTATUS_OFFSET 0x0
#define PROBE_STATALARMSTATUS_STATALARMSTATUS_WIDTH 0x1
#define PROBE_STATALARMSTATUS_STATALARMSTATUS_MASK 0x1
#define PROBE_STATALARMSTATUS_STATALARMSTATUS(_reg) (((_reg) & 0x1) >> 0x0)

#define PROBE_STATALARMCLR(_base, _offset, _probe) \
	((_base) + (_offset) + (_probe * 0x400) + 0x38)
#define PROBE_STATALARMCLR_STATALARMCLR_OFFSET 0x0
#define PROBE_STATALARMCLR_STATALARMCLR_WIDTH 0x1
#define PROBE_STATALARMCLR_STATALARMCLR_MASK 0x1
#define PROBE_STATALARMCLR_STATALARMCLR(_reg) (((_reg) & 0x1) >> 0x0)

#define PROBE_FILTERS_ROUTEIDBASE(_offset, _probe, _filter) \
	((_offset) + (_probe * 0x400) + (_filter * 0x3C) + 0x44)
#define PROBE_FILTERS_ROUTEIDBASE_FILTERS_ROUTEIDBASE_OFFSET 0x0
#define PROBE_FILTERS_ROUTEIDBASE_FILTERS_ROUTEIDBASE_WIDTH 0x11
#define PROBE_FILTERS_ROUTEIDBASE_FILTERS_ROUTEIDBASE_MASK 0x1ffff
#define PROBE_FILTERS_ROUTEIDBASE_FILTERS_ROUTEIDBASE(_reg) \
			(((_reg) & 0x1ffff) >> 0x0)

#define PROBE_FILTERS_ROUTEIDMASK(_offset, _probe, _filter) \
	((_offset) + (_probe * 0x400) + (_filter * 0x3C) + 0x48)
#define PROBE_FILTERS_ROUTEIDMASK_FILTERS_ROUTEIDMASK_OFFSET 0x0
#define PROBE_FILTERS_ROUTEIDMASK_FILTERS_ROUTEIDMASK_WIDTH 0x11
#define PROBE_FILTERS_ROUTEIDMASK_FILTERS_ROUTEIDMASK_MASK 0x1ffff
#define PROBE_FILTERS_ROUTEIDMASK_FILTERS_ROUTEIDMASK(_reg) \
			(((_reg) & 0x1ffff) >> 0x0)

#define PROBE_FILTERS_ADDRBASE_LOW(_offset, _probe, _filter) \
	((_offset) + (_probe * 0x400) + (_filter * 0x3C) + 0x4c)
#define PROBE_FILTERS_ADDRBASE_LOW_FILTERS_ADDRBASE_LOW_OFFSET 0x0
#define PROBE_FILTERS_ADDRBASE_LOW_FILTERS_ADDRBASE_LOW_WIDTH 0x20
#define PROBE_FILTERS_ADDRBASE_LOW_FILTERS_ADDRBASE_LOW_MASK 0xffffffff
#define PROBE_FILTERS_ADDRBASE_LOW_FILTERS_ADDRBASE_LOW(_reg) \
			(((_reg) & 0xffffffff) >> 0x0)

#define PROBE_FILTERS_WINDOWSIZE(_offset, _probe, _filter) \
	((_offset) + (_probe * 0x400) + (_filter * 0x3C) + 0x54)
#define PROBE_FILTERS_WINDOWSIZE_FILTERS_WINDOWSIZE_OFFSET 0x0
#define PROBE_FILTERS_WINDOWSIZE_FILTERS_WINDOWSIZE_WIDTH 0x6
#define PROBE_FILTERS_WINDOWSIZE_FILTERS_WINDOWSIZE_MASK 0x3f
#define PROBE_FILTERS_WINDOWSIZE_FILTERS_WINDOWSIZE(_reg) \
			(((_reg) & 0x3f) >> 0x0)

#define PROBE_FILTERS_SECURITYBASE(_offset, _probe, _filter) \
	((_offset) + (_probe * 0x400) + (_filter * 0x3C) + 0x58)
#define PROBE_FILTERS_SECURITYBASE_FILTERS_SECURITYBASE_OFFSET 0x0
#define PROBE_FILTERS_SECURITYBASE_FILTERS_SECURITYBASE_WIDTH 0x4
#define PROBE_FILTERS_SECURITYBASE_FILTERS_SECURITYBASE_MASK 0xf
#define PROBE_FILTERS_SECURITYBASE_FILTERS_SECURITYBASE(_reg) \
			(((_reg) & 0xf) >> 0x0)

#define PROBE_FILTERS_SECURITYMASK(_offset, _probe, _filter) \
	((_offset) + (_probe * 0x400) + (_filter * 0x3C) + 0x5c)
#define PROBE_FILTERS_SECURITYMASK_FILTERS_SECURITYMASK_OFFSET 0x0
#define PROBE_FILTERS_SECURITYMASK_FILTERS_SECURITYMASK_WIDTH 0x4
#define PROBE_FILTERS_SECURITYMASK_FILTERS_SECURITYMASK_MASK 0xf
#define PROBE_FILTERS_SECURITYMASK_FILTERS_SECURITYMASK(_reg) \
			(((_reg) & 0xf) >> 0x0)

#define PROBE_FILTERS_OPCODE(_offset, _probe, _filter) \
	((_offset) + (_probe * 0x400) + (_filter * 0x3C) + 0x60)
#define PROBE_FILTERS_OPCODE_RDEN_OFFSET 0x0
#define PROBE_FILTERS_OPCODE_RDEN_WIDTH 0x1
#define PROBE_FILTERS_OPCODE_RDEN_MASK 0x1
#define PROBE_FILTERS_OPCODE_RDEN(_reg) (((_reg) & 0x1) >> 0x0)
#define PROBE_FILTERS_OPCODE_WREN_OFFSET 0x1
#define PROBE_FILTERS_OPCODE_WREN_WIDTH 0x1
#define PROBE_FILTERS_OPCODE_WREN_MASK 0x2
#define PROBE_FILTERS_OPCODE_WREN(_reg) (((_reg) & 0x2) >> 0x1)
#define PROBE_FILTERS_OPCODE_LOCKEN_OFFSET 0x2
#define PROBE_FILTERS_OPCODE_LOCKEN_WIDTH 0x1
#define PROBE_FILTERS_OPCODE_LOCKEN_MASK 0x4
#define PROBE_FILTERS_OPCODE_LOCKEN(_reg) (((_reg) & 0x4) >> 0x2)
#define PROBE_FILTERS_OPCODE_URGEN_OFFSET 0x3
#define PROBE_FILTERS_OPCODE_URGEN_WIDTH 0x1
#define PROBE_FILTERS_OPCODE_URGEN_MASK 0x8
#define PROBE_FILTERS_OPCODE_URGEN(_reg) (((_reg) & 0x8) >> 0x3)

#define PROBE_FILTERS_STATUS(_offset, _probe, _filter) \
	((_offset) + (_probe * 0x400) + (_filter * 0x3C) + 0x64)
#define PROBE_FILTERS_STATUS_REQEN_OFFSET 0x0
#define PROBE_FILTERS_STATUS_REQEN_WIDTH 0x1
#define PROBE_FILTERS_STATUS_REQEN_MASK 0x1
#define PROBE_FILTERS_STATUS_REQEN(_reg) (((_reg) & 0x1) >> 0x0)
#define PROBE_FILTERS_STATUS_RSPEN_OFFSET 0x1
#define PROBE_FILTERS_STATUS_RSPEN_WIDTH 0x1
#define PROBE_FILTERS_STATUS_RSPEN_MASK 0x2
#define PROBE_FILTERS_STATUS_RSPEN(_reg) (((_reg) & 0x2) >> 0x1)

#define PROBE_FILTERS_LENGTH(_offset, _probe, _filter) \
	((_offset) + (_probe * 0x400) + (_filter * 0x3C) + 0x68)
#define PROBE_FILTERS_LENGTH_FILTERS_LENGTH_OFFSET 0x0
#define PROBE_FILTERS_LENGTH_FILTERS_LENGTH_WIDTH 0x4
#define PROBE_FILTERS_LENGTH_FILTERS_LENGTH_MASK 0xf
#define PROBE_FILTERS_LENGTH_FILTERS_LENGTH(_reg) (((_reg) & 0xf) >> 0x0)

#define PROBE_FILTERS_URGENCY(_offset, _probe, _filter) \
	((_offset) + (_probe * 0x400) + (_filter * 0x3C) + 0x6c)
#define PROBE_FILTERS_URGENCY_FILTERS_URGENCY_OFFSET 0x0
#define PROBE_FILTERS_URGENCY_FILTERS_URGENCY_WIDTH 0x1
#define PROBE_FILTERS_URGENCY_FILTERS_URGENCY_MASK 0x1
#define PROBE_FILTERS_URGENCY_FILTERS_URGENCY(_reg) (((_reg) & 0x1) >> 0x0)

#define PROBE_COUNTERS_PORTSEL(_offset, _probe, _cnt) \
	((_offset) + (_probe * 0x400) + (_cnt * 0x14) + 0x134)
#define PROBE_COUNTERS_PORTSEL_COUNTERS_PORTSEL_OFFSET 0x0
#define PROBE_COUNTERS_PORTSEL_COUNTERS_PORTSEL_WIDTH 0x3
#define PROBE_COUNTERS_PORTSEL_COUNTERS_PORTSEL_MASK 0x7
#define PROBE_COUNTERS_PORTSEL_COUNTERS_PORTSEL(_reg) (((_reg) & 0x7) >> 0x0)

#define PROBE_COUNTERS_SRC(_offset, _probe, _cnt) \
	((_offset) + (_probe * 0x400) + (_cnt * 0x14) + 0x138)
#define PROBE_COUNTERS_SRC_INTEVENT_OFFSET 0x0
#define PROBE_COUNTERS_SRC_INTEVENT_WIDTH 0x5
#define PROBE_COUNTERS_SRC_INTEVENT_MASK 0x1f
#define PROBE_COUNTERS_SRC_INTEVENT(_reg) (((_reg) & 0x1f) >> 0x0)

#define PROBE_COUNTERS_ALARMMODE(_offset, _probe, _cnt) \
	((_offset) + (_probe * 0x400) + (_cnt * 0x14) + 0x13c)
#define PROBE_COUNTERS_ALARMMODE_COUNTERS_ALARMMODE_OFFSET 0x0
#define PROBE_COUNTERS_ALARMMODE_COUNTERS_ALARMMODE_WIDTH 0x2
#define PROBE_COUNTERS_ALARMMODE_COUNTERS_ALARMMODE_MASK 0x3
#define PROBE_COUNTERS_ALARMMODE_COUNTERS_ALARMMODE(_reg) \
			(((_reg) & 0x3) >> 0x0)

#define PROBE_COUNTERS_VAL(_offset, _probe, _cnt) \
	((_offset) + (_probe * 0x400) + (_cnt * 0x14) + 0x140)
#define PROBE_COUNTERS_VAL_COUNTERS_VAL_OFFSET 0x0
#define PROBE_COUNTERS_VAL_COUNTERS_VAL_WIDTH 0x10
#define PROBE_COUNTERS_VAL_COUNTERS_VAL_MASK 0xffff
#define PROBE_COUNTERS_VAL_COUNTERS_VAL(_reg) (((_reg) & 0xffff) >> 0x0)

#define OBS_L1_ATB_ID_COREID(_base) ((_base) + 0x1c00)
#define OBS_L1_ATB_ID_COREID_CORETYPEID_OFFSET 0x0
#define OBS_L1_ATB_ID_COREID_CORETYPEID_WIDTH 0x8
#define OBS_L1_ATB_ID_COREID_CORETYPEID_MASK 0xff
#define OBS_L1_ATB_ID_COREID_CORETYPEID(_reg) (((_reg) & 0xff) >> 0x0)
#define OBS_L1_ATB_ID_COREID_CORECHECKSUM_OFFSET 0x8
#define OBS_L1_ATB_ID_COREID_CORECHECKSUM_WIDTH 0x18
#define OBS_L1_ATB_ID_COREID_CORECHECKSUM_MASK 0xffffff00
#define OBS_L1_ATB_ID_COREID_CORECHECKSUM(_reg) (((_reg) & 0xffffff00) >> 0x8)

#define OBS_L1_ATB_ID_REVISIONID(_base) ((_base) + 0x1c04)
#define OBS_L1_ATB_ID_REVISIONID_USERID_OFFSET 0x0
#define OBS_L1_ATB_ID_REVISIONID_USERID_WIDTH 0x8
#define OBS_L1_ATB_ID_REVISIONID_USERID_MASK 0xff
#define OBS_L1_ATB_ID_REVISIONID_USERID(_reg) (((_reg) & 0xff) >> 0x0)
#define OBS_L1_ATB_ID_REVISIONID_FLEXNOCID_OFFSET 0x8
#define OBS_L1_ATB_ID_REVISIONID_FLEXNOCID_WIDTH 0x18
#define OBS_L1_ATB_ID_REVISIONID_FLEXNOCID_MASK 0xffffff00
#define OBS_L1_ATB_ID_REVISIONID_FLEXNOCID(_reg) (((_reg) & 0xffffff00) >> 0x8)

#define OBS_L1_ATB_ATBID(_base) ((_base) + 0x1c08)
#define OBS_L1_ATB_ATBID_ATBID_OFFSET 0x0
#define OBS_L1_ATB_ATBID_ATBID_WIDTH 0x7
#define OBS_L1_ATB_ATBID_ATBID_MASK 0x7f
#define OBS_L1_ATB_ATBID_ATBID(_reg) (((_reg) & 0x7f) >> 0x0)

#define OBS_L1_ATB_ATBEN(_base) ((_base) + 0x1c0c)
#define OBS_L1_ATB_ATBEN_ATBEN_OFFSET 0x0
#define OBS_L1_ATB_ATBEN_ATBEN_WIDTH 0x1
#define OBS_L1_ATB_ATBEN_ATBEN_MASK 0x1
#define OBS_L1_ATB_ATBEN_ATBEN(_reg) (((_reg) & 0x1) >> 0x0)

#define OBS_L1_ATB_SYNCPERIOD(_base) ((_base) + 0x1c10)
#define OBS_L1_ATB_SYNCPERIOD_SYNCPERIOD_OFFSET 0x0
#define OBS_L1_ATB_SYNCPERIOD_SYNCPERIOD_WIDTH 0x5
#define OBS_L1_ATB_SYNCPERIOD_SYNCPERIOD_MASK 0x1f
#define OBS_L1_ATB_SYNCPERIOD_SYNCPERIOD(_reg) (((_reg) & 0x1f) >> 0x0)

#define GPU_QOS_GEN_ID_COREID(_base) ((_base) + 0x1d00)
#define GPU_QOS_GEN_ID_COREID_CORETYPEID_OFFSET 0x0
#define GPU_QOS_GEN_ID_COREID_CORETYPEID_WIDTH 0x8
#define GPU_QOS_GEN_ID_COREID_CORETYPEID_MASK 0xff
#define GPU_QOS_GEN_ID_COREID_CORETYPEID(_reg) (((_reg) & 0xff) >> 0x0)
#define GPU_QOS_GEN_ID_COREID_CORECHECKSUM_OFFSET 0x8
#define GPU_QOS_GEN_ID_COREID_CORECHECKSUM_WIDTH 0x18
#define GPU_QOS_GEN_ID_COREID_CORECHECKSUM_MASK 0xffffff00
#define GPU_QOS_GEN_ID_COREID_CORECHECKSUM(_reg) (((_reg) & 0xffffff00) >> 0x8)

#define GPU_QOS_GEN_ID_REVISIONID(_base) ((_base) + 0x1d04)
#define GPU_QOS_GEN_ID_REVISIONID_USERID_OFFSET 0x0
#define GPU_QOS_GEN_ID_REVISIONID_USERID_WIDTH 0x8
#define GPU_QOS_GEN_ID_REVISIONID_USERID_MASK 0xff
#define GPU_QOS_GEN_ID_REVISIONID_USERID(_reg) (((_reg) & 0xff) >> 0x0)
#define GPU_QOS_GEN_ID_REVISIONID_FLEXNOCID_OFFSET 0x8
#define GPU_QOS_GEN_ID_REVISIONID_FLEXNOCID_WIDTH 0x18
#define GPU_QOS_GEN_ID_REVISIONID_FLEXNOCID_MASK 0xffffff00
#define GPU_QOS_GEN_ID_REVISIONID_FLEXNOCID(_reg) (((_reg) & 0xffffff00) >> 0x8)

#define GPU_QOS_GEN_PRIORITY(_base) ((_base) + 0x1d08)
#define GPU_QOS_GEN_PRIORITY_P0_OFFSET 0x0
#define GPU_QOS_GEN_PRIORITY_P0_WIDTH 0x2
#define GPU_QOS_GEN_PRIORITY_P0_MASK 0x3
#define GPU_QOS_GEN_PRIORITY_P0(_reg) (((_reg) & 0x3) >> 0x0)
#define GPU_QOS_GEN_PRIORITY_P1_OFFSET 0x2
#define GPU_QOS_GEN_PRIORITY_P1_WIDTH 0x2
#define GPU_QOS_GEN_PRIORITY_P1_MASK 0xc
#define GPU_QOS_GEN_PRIORITY_P1(_reg) (((_reg) & 0xc) >> 0x2)

#define GPU_QOS_GEN_MODE(_base) ((_base) + 0x1d0c)
#define GPU_QOS_GEN_MODE_MODE_OFFSET 0x0
#define GPU_QOS_GEN_MODE_MODE_WIDTH 0x2
#define GPU_QOS_GEN_MODE_MODE_MASK 0x3
#define GPU_QOS_GEN_MODE_MODE(_reg) (((_reg) & 0x3) >> 0x0)

#define GPU_QOS_GEN_BANDWIDTH(_base) ((_base) + 0x1d10)
#define GPU_QOS_GEN_BANDWIDTH_BANDWIDTH_OFFSET 0x0
#define GPU_QOS_GEN_BANDWIDTH_BANDWIDTH_WIDTH 0xb
#define GPU_QOS_GEN_BANDWIDTH_BANDWIDTH_MASK 0x7ff
#define GPU_QOS_GEN_BANDWIDTH_BANDWIDTH(_reg) (((_reg) & 0x7ff) >> 0x0)

#define GPU_QOS_GEN_SATURATION(_base) ((_base) + 0x1d14)
#define GPU_QOS_GEN_SATURATION_SATURATION_OFFSET 0x0
#define GPU_QOS_GEN_SATURATION_SATURATION_WIDTH 0xa
#define GPU_QOS_GEN_SATURATION_SATURATION_MASK 0x3ff
#define GPU_QOS_GEN_SATURATION_SATURATION(_reg) (((_reg) & 0x3ff) >> 0x0)

#define GPU_QOS_GEN_EXTCONTROL(_base) ((_base) + 0x1d18)
#define GPU_QOS_GEN_EXTCONTROL_SOCKETQOSEN_OFFSET 0x0
#define GPU_QOS_GEN_EXTCONTROL_SOCKETQOSEN_WIDTH 0x1
#define GPU_QOS_GEN_EXTCONTROL_SOCKETQOSEN_MASK 0x1
#define GPU_QOS_GEN_EXTCONTROL_SOCKETQOSEN(_reg) (((_reg) & 0x1) >> 0x0)
#define GPU_QOS_GEN_EXTCONTROL_EXTTHREN_OFFSET 0x1
#define GPU_QOS_GEN_EXTCONTROL_EXTTHREN_WIDTH 0x1
#define GPU_QOS_GEN_EXTCONTROL_EXTTHREN_MASK 0x2
#define GPU_QOS_GEN_EXTCONTROL_EXTTHREN(_reg) (((_reg) & 0x2) >> 0x1)
#define GPU_QOS_GEN_EXTCONTROL_INTCLKEN_OFFSET 0x2
#define GPU_QOS_GEN_EXTCONTROL_INTCLKEN_WIDTH 0x1
#define GPU_QOS_GEN_EXTCONTROL_INTCLKEN_MASK 0x4
#define GPU_QOS_GEN_EXTCONTROL_INTCLKEN(_reg) (((_reg) & 0x4) >> 0x2)

#define VPU_QOS_GEN_ID_COREID(_base) ((_base) + 0x1e00)
#define VPU_QOS_GEN_ID_COREID_CORETYPEID_OFFSET 0x0
#define VPU_QOS_GEN_ID_COREID_CORETYPEID_WIDTH 0x8
#define VPU_QOS_GEN_ID_COREID_CORETYPEID_MASK 0xff
#define VPU_QOS_GEN_ID_COREID_CORETYPEID(_reg) (((_reg) & 0xff) >> 0x0)
#define VPU_QOS_GEN_ID_COREID_CORECHECKSUM_OFFSET 0x8
#define VPU_QOS_GEN_ID_COREID_CORECHECKSUM_WIDTH 0x18
#define VPU_QOS_GEN_ID_COREID_CORECHECKSUM_MASK 0xffffff00
#define VPU_QOS_GEN_ID_COREID_CORECHECKSUM(_reg) (((_reg) & 0xffffff00) >> 0x8)

#define VPU_QOS_GEN_ID_REVISIONID(_base) ((_base) + 0x1e04)
#define VPU_QOS_GEN_ID_REVISIONID_USERID_OFFSET 0x0
#define VPU_QOS_GEN_ID_REVISIONID_USERID_WIDTH 0x8
#define VPU_QOS_GEN_ID_REVISIONID_USERID_MASK 0xff
#define VPU_QOS_GEN_ID_REVISIONID_USERID(_reg) (((_reg) & 0xff) >> 0x0)
#define VPU_QOS_GEN_ID_REVISIONID_FLEXNOCID_OFFSET 0x8
#define VPU_QOS_GEN_ID_REVISIONID_FLEXNOCID_WIDTH 0x18
#define VPU_QOS_GEN_ID_REVISIONID_FLEXNOCID_MASK 0xffffff00
#define VPU_QOS_GEN_ID_REVISIONID_FLEXNOCID(_reg) (((_reg) & 0xffffff00) >> 0x8)

#define VPU_QOS_GEN_PRIORITY(_base) ((_base) + 0x1e08)
#define VPU_QOS_GEN_PRIORITY_P0_OFFSET 0x0
#define VPU_QOS_GEN_PRIORITY_P0_WIDTH 0x2
#define VPU_QOS_GEN_PRIORITY_P0_MASK 0x3
#define VPU_QOS_GEN_PRIORITY_P0(_reg) (((_reg) & 0x3) >> 0x0)
#define VPU_QOS_GEN_PRIORITY_P1_OFFSET 0x2
#define VPU_QOS_GEN_PRIORITY_P1_WIDTH 0x2
#define VPU_QOS_GEN_PRIORITY_P1_MASK 0xc
#define VPU_QOS_GEN_PRIORITY_P1(_reg) (((_reg) & 0xc) >> 0x2)

#define VPU_QOS_GEN_MODE(_base) ((_base) + 0x1e0c)
#define VPU_QOS_GEN_MODE_MODE_OFFSET 0x0
#define VPU_QOS_GEN_MODE_MODE_WIDTH 0x2
#define VPU_QOS_GEN_MODE_MODE_MASK 0x3
#define VPU_QOS_GEN_MODE_MODE(_reg) (((_reg) & 0x3) >> 0x0)

#define VPU_QOS_GEN_BANDWIDTH(_base) ((_base) + 0x1e10)
#define VPU_QOS_GEN_BANDWIDTH_BANDWIDTH_OFFSET 0x0
#define VPU_QOS_GEN_BANDWIDTH_BANDWIDTH_WIDTH 0xb
#define VPU_QOS_GEN_BANDWIDTH_BANDWIDTH_MASK 0x7ff
#define VPU_QOS_GEN_BANDWIDTH_BANDWIDTH(_reg) (((_reg) & 0x7ff) >> 0x0)

#define VPU_QOS_GEN_SATURATION(_base) ((_base) + 0x1e14)
#define VPU_QOS_GEN_SATURATION_SATURATION_OFFSET 0x0
#define VPU_QOS_GEN_SATURATION_SATURATION_WIDTH 0xa
#define VPU_QOS_GEN_SATURATION_SATURATION_MASK 0x3ff
#define VPU_QOS_GEN_SATURATION_SATURATION(_reg) (((_reg) & 0x3ff) >> 0x0)

#define VPU_QOS_GEN_EXTCONTROL(_base) ((_base) + 0x1e18)
#define VPU_QOS_GEN_EXTCONTROL_SOCKETQOSEN_OFFSET 0x0
#define VPU_QOS_GEN_EXTCONTROL_SOCKETQOSEN_WIDTH 0x1
#define VPU_QOS_GEN_EXTCONTROL_SOCKETQOSEN_MASK 0x1
#define VPU_QOS_GEN_EXTCONTROL_SOCKETQOSEN(_reg) (((_reg) & 0x1) >> 0x0)
#define VPU_QOS_GEN_EXTCONTROL_EXTTHREN_OFFSET 0x1
#define VPU_QOS_GEN_EXTCONTROL_EXTTHREN_WIDTH 0x1
#define VPU_QOS_GEN_EXTCONTROL_EXTTHREN_MASK 0x2
#define VPU_QOS_GEN_EXTCONTROL_EXTTHREN(_reg) (((_reg) & 0x2) >> 0x1)
#define VPU_QOS_GEN_EXTCONTROL_INTCLKEN_OFFSET 0x2
#define VPU_QOS_GEN_EXTCONTROL_INTCLKEN_WIDTH 0x1
#define VPU_QOS_GEN_EXTCONTROL_INTCLKEN_MASK 0x4
#define VPU_QOS_GEN_EXTCONTROL_INTCLKEN(_reg) (((_reg) & 0x4) >> 0x2)
