/*
 * Copyright (C) 2012-2013 Intel Mobile Communications GmbH
 *
 * This software is licensed under the terms of the GNU General Public
 * License version 2, as published by the Free Software Foundation, and
 * may be copied, distributed, and modified under those terms.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 */

enum btauif_control_cmd {
	btauif_audio_enable_cmd,
	btauif_audio_disable_cmd
};

enum btauif_aud_state {
	btauif_aud_reset = 0,
	btauif_aud_on,
	btauif_aud_off
};


#define BT_AU_IF_CLC_OFFSET 0x0
#define BT_AU_IF_CLC(_base) ((_base) + BT_AU_IF_CLC_OFFSET)
	#define BT_AU_IF_CLC_RUN_OFFSET 0x0
	#define BT_AU_IF_CLC_RUN_WIDTH 0x2
	#define BT_AU_IF_CLC_RUN_MASK 0x3
	#define BT_AU_IF_CLC_RUN(_reg) (((_reg) & BT_AU_IF_CLC_RUN_MASK) \
			>> BT_AU_IF_CLC_RUN_OFFSET)
	#define BT_AU_IF_CLC_MOD_EN_OFFSET 0x2
	#define BT_AU_IF_CLC_MOD_EN_WIDTH 0x2
	#define BT_AU_IF_CLC_MOD_EN_MASK 0xC
	#define BT_AU_IF_CLC_MOD_EN(_reg) (((_reg) & BT_AU_IF_CLC_MOD_EN_MASK) \
			>> BT_AU_IF_CLC_MOD_EN_OFFSET)

#define BT_AU_IF_CLC_STAT_OFFSET 0x8
#define BT_AU_IF_CLC_STAT(_base) ((_base) + BT_AU_IF_CLC_STAT_OFFSET)
	#define BT_AU_IF_CLC_STAT_RUN_OFFSET 0x0
	#define BT_AU_IF_CLC_STAT_RUN_WIDTH 0x1
	#define BT_AU_IF_CLC_STAT_RUN_MASK 0x1
	#define BT_AU_IF_CLC_STAT_RUN(_reg) \
			(((_reg) & BT_AU_IF_CLC_STAT_RUN_MASK) \
			>> BT_AU_IF_CLC_STAT_RUN_OFFSET)
	#define BT_AU_IF_CLC_STAT_MOD_EN_OFFSET 0x1
	#define BT_AU_IF_CLC_STAT_MOD_EN_WIDTH 0x1
	#define BT_AU_IF_CLC_STAT_MOD_EN_MASK 0x2
	#define BT_AU_IF_CLC_STAT_MOD_EN(_reg) \
			(((_reg) & BT_AU_IF_CLC_STAT_MOD_EN_MASK) \
			>> BT_AU_IF_CLC_STAT_MOD_EN_OFFSET)
	#define BT_AU_IF_CLC_STAT_KID_OFFSET 0x7
	#define BT_AU_IF_CLC_STAT_KID_WIDTH 0x1
	#define BT_AU_IF_CLC_STAT_KID_MASK 0x80
	#define BT_AU_IF_CLC_STAT_KID(_reg) \
			(((_reg) & BT_AU_IF_CLC_STAT_KID_MASK) \
			>> BT_AU_IF_CLC_STAT_KID_OFFSET)
	#define BT_AU_IF_CLC_STAT_FIFOID_OFFSET 0x8
	#define BT_AU_IF_CLC_STAT_FIFOID_WIDTH 0x1
	#define BT_AU_IF_CLC_STAT_FIFOID_MASK 0x100
	#define BT_AU_IF_CLC_STAT_FIFOID(_reg) \
			(((_reg) & BT_AU_IF_CLC_STAT_FIFOID_MASK) \
			>> BT_AU_IF_CLC_STAT_FIFOID_OFFSET)

#define BT_AU_IF_ID_OFFSET 0xc
#define BT_AU_IF_ID(_base) ((_base) + BT_AU_IF_ID_OFFSET)
	#define BT_AU_IF_ID_REV_NUMBER_OFFSET 0x0
	#define BT_AU_IF_ID_REV_NUMBER_WIDTH 0x8
	#define BT_AU_IF_ID_REV_NUMBER_MASK 0xff
	#define BT_AU_IF_ID_REV_NUMBER(_reg) \
			(((_reg) & BT_AU_IF_ID_REV_NUMBER_MASK) \
			>> BT_AU_IF_ID_REV_NUMBER_OFFSET)
	#define BT_AU_IF_ID_RES1_OFFSET 0x8
	#define BT_AU_IF_ID_RES1_WIDTH 0x8
	#define BT_AU_IF_ID_RES1_MASK 0xff00
	#define BT_AU_IF_ID_RES1(_reg) (((_reg) & BT_AU_IF_ID_RES1_MASK) \
			>> BT_AU_IF_ID_RES1_OFFSET)
	#define BT_AU_IF_ID_TS_REV_NR_OFFSET 0x10
	#define BT_AU_IF_ID_TS_REV_NR_WIDTH 0x10
	#define BT_AU_IF_ID_TS_REV_NR_MASK 0xffff0000
	#define BT_AU_IF_ID_TS_REV_NR(_reg) \
			(((_reg) & BT_AU_IF_ID_TS_REV_NR_MASK) \
			>> BT_AU_IF_ID_TS_REV_NR_OFFSET)

#define BT_AU_IF_FIFO_ID_OFFSET 0x10
#define BT_AU_IF_FIFO_ID(_base) ((_base) + BT_AU_IF_FIFO_ID_OFFSET)
	#define BT_AU_IF_FIFO_ID_TX_STAGE_OFFSET 0x0
	#define BT_AU_IF_FIFO_ID_TX_STAGE_WIDTH 0x8
	#define BT_AU_IF_FIFO_ID_TX_STAGE_MASK 0xff
	#define BT_AU_IF_FIFO_ID_TX_STAGE(_reg) \
			(((_reg) & BT_AU_IF_FIFO_ID_TX_STAGE_MASK) \
			>> BT_AU_IF_FIFO_ID_TX_STAGE_OFFSET)
	#define BT_AU_IF_FIFO_ID_RX_STAGE_OFFSET 0x8
	#define BT_AU_IF_FIFO_ID_RX_STAGE_WIDTH 0x8
	#define BT_AU_IF_FIFO_ID_RX_STAGE_MASK 0xff00
	#define BT_AU_IF_FIFO_ID_RX_STAGE(_reg) \
			(((_reg) & BT_AU_IF_FIFO_ID_RX_STAGE_MASK) \
			>> BT_AU_IF_FIFO_ID_RX_STAGE_OFFSET)
	#define BT_AU_IF_FIFO_ID_RPS_STAGE_OFFSET 0x10
	#define BT_AU_IF_FIFO_ID_RPS_STAGE_WIDTH 0x6
	#define BT_AU_IF_FIFO_ID_RPS_STAGE_MASK 0x3f0000
	#define BT_AU_IF_FIFO_ID_RPS_STAGE(_reg) \
			(((_reg) & BT_AU_IF_FIFO_ID_RPS_STAGE_MASK) \
			>> BT_AU_IF_FIFO_ID_RPS_STAGE_OFFSET)

#define BT_AU_IF_FIFO_CFG_OFFSET 0x30
#define BT_AU_IF_FIFO_CFG(_base) ((_base) + BT_AU_IF_FIFO_CFG_OFFSET)
	#define BT_AU_IF_FIFO_CFG_RXBS_OFFSET 0x0
	#define BT_AU_IF_FIFO_CFG_RXBS_WIDTH 0x3
	#define BT_AU_IF_FIFO_CFG_RXBS_MASK 0x7
	#define BT_AU_IF_FIFO_CFG_RXBS(_reg) \
			(((_reg) & BT_AU_IF_FIFO_CFG_RXBS_MASK) \
			>> BT_AU_IF_FIFO_CFG_RXBS_OFFSET)
	#define BT_AU_IF_FIFO_CFG_RXFC_OFFSET 0x3
	#define BT_AU_IF_FIFO_CFG_RXFC_WIDTH 0x1
	#define BT_AU_IF_FIFO_CFG_RXFC_MASK 0x8
	#define BT_AU_IF_FIFO_CFG_RXFC(_reg) \
			(((_reg) & BT_AU_IF_FIFO_CFG_RXFC_MASK) \
			>> BT_AU_IF_FIFO_CFG_RXFC_OFFSET)
	#define BT_AU_IF_FIFO_CFG_TXBS_OFFSET 0x4
	#define BT_AU_IF_FIFO_CFG_TXBS_WIDTH 0x3
	#define BT_AU_IF_FIFO_CFG_TXBS_MASK 0x70
	#define BT_AU_IF_FIFO_CFG_TXBS(_reg) \
			(((_reg) & BT_AU_IF_FIFO_CFG_TXBS_MASK) \
			>> BT_AU_IF_FIFO_CFG_TXBS_OFFSET)
	#define BT_AU_IF_FIFO_CFG_TXFC_OFFSET 0x7
	#define BT_AU_IF_FIFO_CFG_TXFC_WIDTH 0x1
	#define BT_AU_IF_FIFO_CFG_TXFC_MASK 0x80
	#define BT_AU_IF_FIFO_CFG_TXFC(_reg) \
			(((_reg) & BT_AU_IF_FIFO_CFG_TXFC_MASK) \
			>> BT_AU_IF_FIFO_CFG_TXFC_OFFSET)
	#define BT_AU_IF_FIFO_CFG_RXFA_OFFSET 0x8
	#define BT_AU_IF_FIFO_CFG_RXFA_WIDTH 0x3
	#define BT_AU_IF_FIFO_CFG_RXFA_MASK 0x700
	#define BT_AU_IF_FIFO_CFG_RXFA(_reg) \
			(((_reg) & BT_AU_IF_FIFO_CFG_RXFA_MASK) \
			>> BT_AU_IF_FIFO_CFG_RXFA_OFFSET)
	#define BT_AU_IF_FIFO_CFG_RX_SWAP_OFFSET 0xB
	#define BT_AU_IF_FIFO_CFG_RX_SWAP_WIDTH 0x1
	#define BT_AU_IF_FIFO_CFG_RX_SWAP_MASK 0x800
	#define BT_AU_IF_FIFO_CFG_RX_SWAP(_reg) \
			(((_reg) & BT_AU_IF_FIFO_CFG_RX_SWAP_MASK) \
			>> BT_AU_IF_FIFO_CFG_RX_SWAP_OFFSET)
	#define BT_AU_IF_FIFO_CFG_TXFA_OFFSET 0xC
	#define BT_AU_IF_FIFO_CFG_TXFA_WIDTH 0x3
	#define BT_AU_IF_FIFO_CFG_TXFA_MASK 0x7000
	#define BT_AU_IF_FIFO_CFG_TXFA(_reg) \
			(((_reg) & BT_AU_IF_FIFO_CFG_TXFA_MASK) \
			>> BT_AU_IF_FIFO_CFG_TXFA_OFFSET)
	#define BT_AU_IF_FIFO_CFG_TX_SWAP_OFFSET 0xF
	#define BT_AU_IF_FIFO_CFG_TX_SWAP_WIDTH 0x1
	#define BT_AU_IF_FIFO_CFG_TX_SWAP_MASK 0x8000
	#define BT_AU_IF_FIFO_CFG_TX_SWAP(_reg) \
			(((_reg) & BT_AU_IF_FIFO_CFG_TX_SWAP_MASK) \
			>> BT_AU_IF_FIFO_CFG_TX_SWAP_OFFSET)

#define BT_AU_IF_FIFO_CTRL_OFFSET 0x34
#define BT_AU_IF_FIFO_CTRL(_base) ((_base) + BT_AU_IF_FIFO_CTRL_OFFSET)
	#define BT_AU_IF_FIFO_CTRL_TX_START_OFFSET 0x0
	#define BT_AU_IF_FIFO_CTRL_TX_START_WIDTH 0x1
	#define BT_AU_IF_FIFO_CTRL_TX_START_MASK 0x1
	#define BT_AU_IF_FIFO_CTRL_TX_START(_reg) \
			(((_reg) & BT_AU_IF_FIFO_CTRL_TX_START_MASK) \
			>> BT_AU_IF_FIFO_CTRL_TX_START_OFFSET)
	#define BT_AU_IF_FIFO_CTRL_TX_ABORT_OFFSET 0x1
	#define BT_AU_IF_FIFO_CTRL_TX_ABORT_WIDTH 0x1
	#define BT_AU_IF_FIFO_CTRL_TX_ABORT_MASK 0x2
	#define BT_AU_IF_FIFO_CTRL_TX_ABORT(_reg) \
			(((_reg) & BT_AU_IF_FIFO_CTRL_TX_ABORT_MASK) \
			>> BT_AU_IF_FIFO_CTRL_TX_ABORT_OFFSET)
	#define BT_AU_IF_FIFO_CTRL_TX_SETEOP_OFFSET 0x2
	#define BT_AU_IF_FIFO_CTRL_TX_SETEOP_WIDTH 0x1
	#define BT_AU_IF_FIFO_CTRL_TX_SETEOP_MASK 0x4
	#define BT_AU_IF_FIFO_CTRL_TX_SETEOP(_reg) \
			(((_reg) & BT_AU_IF_FIFO_CTRL_TX_SETEOP_MASK) \
			>> BT_AU_IF_FIFO_CTRL_TX_SETEOP_OFFSET)
	#define BT_AU_IF_FIFO_CTRL_RX_START_OFFSET 0x4
	#define BT_AU_IF_FIFO_CTRL_RX_START_WIDTH 0x1
	#define BT_AU_IF_FIFO_CTRL_RX_START_MASK 0x10
	#define BT_AU_IF_FIFO_CTRL_RX_START(_reg) \
			(((_reg) & BT_AU_IF_FIFO_CTRL_RX_START_MASK) \
			>> BT_AU_IF_FIFO_CTRL_RX_START_OFFSET)
	#define BT_AU_IF_FIFO_CTRL_RX_ABORT_OFFSET 0x5
	#define BT_AU_IF_FIFO_CTRL_RX_ABORT_WIDTH 0x1
	#define BT_AU_IF_FIFO_CTRL_RX_ABORT_MASK 0x20
	#define BT_AU_IF_FIFO_CTRL_RX_ABORT(_reg) \
			(((_reg) & BT_AU_IF_FIFO_CTRL_RX_ABORT_MASK) \
			>> BT_AU_IF_FIFO_CTRL_RX_ABORT_OFFSET)
	#define BT_AU_IF_FIFO_CTRL_RX_AR_OFFSET 0x6
	#define BT_AU_IF_FIFO_CTRL_RX_AR_WIDTH 0x2
	#define BT_AU_IF_FIFO_CTRL_RX_AR_MASK 0xC0
	#define BT_AU_IF_FIFO_CTRL_RX_AR(_reg) \
			(((_reg) & BT_AU_IF_FIFO_CTRL_RX_AR_MASK) \
			>> BT_AU_IF_FIFO_CTRL_RX_AR_OFFSET)

#define BT_AU_IF_TPS_CTRL_OFFSET 0x40
#define BT_AU_IF_TPS_CTRL(_base) ((_base) + 0x40)
	#define BT_AU_IF_TPS_CTRL_TPS_OFFSET 0x0
	#define BT_AU_IF_TPS_CTRL_TPS_WIDTH 0x10
	#define BT_AU_IF_TPS_CTRL_TPS_MASK 0xffff
	#define BT_AU_IF_TPS_CTRL_TPS(_reg) (((_reg) & 0xffff) >> 0x0)

#define BT_AU_IF_FIFO_STAT_OFFSET 0x44
#define BT_AU_IF_FIFO_STAT(_base) ((_base) + BT_AU_IF_FIFO_STAT_OFFSET)
	#define BT_AU_IF_FIFO_STAT_RXFFS_OFFSET 0x0
	#define BT_AU_IF_FIFO_STAT_RXFFS_WIDTH 0x8
	#define BT_AU_IF_FIFO_STAT_RXFFS_MASK 0xFF
	#define BT_AU_IF_FIFO_STAT_RXFFS(_reg) \
			(((_reg) & BT_AU_IF_FIFO_STAT_RXFFS_MASK) \
			>> BT_AU_IF_FIFO_STAT_RXFFS_OFFSET)
	#define BT_AU_IF_FIFO_STAT_RX_AR_OFFSET 0xC
	#define BT_AU_IF_FIFO_STAT_RX_AR_WIDTH 0x1
	#define BT_AU_IF_FIFO_STAT_RX_AR_MASK 0x1000
	#define BT_AU_IF_FIFO_STAT_RX_AR(_reg) \
			(((_reg) & BT_AU_IF_FIFO_STAT_RX_AR_MASK) \
			>> BT_AU_IF_FIFO_STAT_RX_AR_OFFSET)
	#define BT_AU_IF_FIFO_STAT_RX_EOP_OFFSET 0xD
	#define BT_AU_IF_FIFO_STAT_RX_EOP_WIDTH 0x1
	#define BT_AU_IF_FIFO_STAT_RX_EOP_MASK 0x2000
	#define BT_AU_IF_FIFO_STAT_RX_EOP(_reg) \
			(((_reg) & BT_AU_IF_FIFO_STAT_RX_EOP_MASK) \
			>> BT_AU_IF_FIFO_STAT_RX_EOP_OFFSET)
	#define BT_AU_IF_FIFO_STAT_MRPS_WE_OFFSET 0xF
	#define BT_AU_IF_FIFO_STAT_MRPS_WE_WIDTH 0x1
	#define BT_AU_IF_FIFO_STAT_MRPS_WE_MASK 0x8000
	#define BT_AU_IF_FIFO_STAT_MRPS_WE(_reg) \
			(((_reg) & BT_AU_IF_FIFO_STAT_MRPS_WE_MASK) \
			>> BT_AU_IF_FIFO_STAT_MRPS_WE_OFFSET)
	#define BT_AU_IF_FIFO_STAT_TXFFS_OFFSET 0x10
	#define BT_AU_IF_FIFO_STAT_TXFFS_WIDTH 0x8
	#define BT_AU_IF_FIFO_STAT_TXFFS_MASK 0xFF0000
	#define BT_AU_IF_FIFO_STAT_TXFFS(_reg) \
			(((_reg) & BT_AU_IF_FIFO_STAT_TXFFS_MASK) \
			>> BT_AU_IF_FIFO_STAT_TXFFS_OFFSET)
	#define BT_AU_IF_FIFO_STAT_TPS_WE_OFFSET 0x1F
	#define BT_AU_IF_FIFO_STAT_TPS_WE_WIDTH 0x1
	#define BT_AU_IF_FIFO_STAT_TPS_WE_MASK 0x80000000
	#define BT_AU_IF_FIFO_STAT_TPS_WE(_reg) \
			(((_reg) & BT_AU_IF_FIFO_STAT_TPS_WE_MASK) \
			>> BT_AU_IF_FIFO_STAT_TPS_WE_OFFSET)

#define BT_AU_IF_CTRL_OFFSET 0x100
#define BT_AU_IF_CTRL(_base) ((_base) + BT_AU_IF_CTRL_OFFSET)
	#define BT_AU_IF_CTRL_AUDIO_CLK_EN_OFFSET 0x0
	#define BT_AU_IF_CTRL_AUDIO_CLK_EN_WIDTH 0x1
	#define BT_AU_IF_CTRL_AUDIO_CLK_EN_MASK 0x1
	#define BT_AU_IF_CTRL_AUDIO_CLK_EN(_reg) \
			(((_reg) & BT_AU_IF_CTRL_AUDIO_CLK_EN_MASK) \
			>> BT_AU_IF_CTRL_AUDIO_CLK_EN_OFFSET)
	#define BT_AU_IF_CTRL_AUDIO_CLK_DEF_OFFSET 0x4
	#define BT_AU_IF_CTRL_AUDIO_CLK_DEF_WIDTH 0x2
	#define BT_AU_IF_CTRL_AUDIO_CLK_DEF_MASK 0x30
	#define BT_AU_IF_CTRL_AUDIO_CLK_DEF(_reg) \
			(((_reg) & BT_AU_IF_CTRL_AUDIO_CLK_DEF_MASK) \
			>> BT_AU_IF_CTRL_AUDIO_CLK_DEF_OFFSET)
	#define BT_AU_IF_CTRL_HANDSHAKE_EN_OFFSET 0x8
	#define BT_AU_IF_CTRL_HANDSHAKE_EN_WIDTH 0x1
	#define BT_AU_IF_CTRL_HANDSHAKE_EN_MASK 0x100
	#define BT_AU_IF_CTRL_HANDSHAKE_EN(_reg) \
			(((_reg) & BT_AU_IF_CTRL_HANDSHAKE_EN_MASK) \
			>> BT_AU_IF_CTRL_HANDSHAKE_EN_OFFSET)

#define BT_AU_IF_MUTE_CTRL_OFFSET 0x104
#define BT_AU_IF_MUTE_CTRL(_base) ((_base) + BT_AU_IF_MUTE_CTRL_OFFSET)
	#define BT_AU_IF_MUTE_CTRL_MUTE_EN_OFFSET 0x0
	#define BT_AU_IF_MUTE_CTRL_MUTE_EN_WIDTH 0x1
	#define BT_AU_IF_MUTE_CTRL_MUTE_EN_MASK 0x1
	#define BT_AU_IF_MUTE_CTRL_MUTE_EN(_reg) \
			(((_reg) & BT_AU_IF_MUTE_CTRL_MUTE_EN_MASK) \
			>> BT_AU_IF_MUTE_CTRL_MUTE_EN_OFFSET)
	#define BT_AU_IF_MUTE_CTRL_MUTE_THRSHLD_OFFSET 0x8
	#define BT_AU_IF_MUTE_CTRL_MUTE_THRSHLD_WIDTH 0x8
	#define BT_AU_IF_MUTE_CTRL_MUTE_THRSHLD_MASK 0xFF00
	#define BT_AU_IF_MUTE_CTRL_MUTE_THRSHLD(_reg) \
			(((_reg) & BT_AU_IF_MUTE_CTRL_MUTE_THRSHLD_MASK) \
			>> BT_AU_IF_MUTE_CTRL_MUTE_THRSHLD_OFFSET)
	#define BT_AU_IF_MUTE_CTRL_MUTE_SAMPLE_OFFSET 0x10
	#define BT_AU_IF_MUTE_CTRL_MUTE_SAMPLE_WIDTH 0x10
	#define BT_AU_IF_MUTE_CTRL_MUTE_SAMPLE_MASK 0xFFFF0000
	#define BT_AU_IF_MUTE_CTRL_MUTE_SAMPLE(_reg) \
			(((_reg) & BT_AU_IF_MUTE_CTRL_MUTE_SAMPLE_MASK) \
			>> BT_AU_IF_MUTE_CTRL_MUTE_SAMPLE_OFFSET)

#define BT_AU_IF_STA_OFFSET 0x108
#define BT_AU_IF_STA(_base) ((_base) + BT_AU_IF_STA_OFFSET)
	#define BT_AU_IF_STA_TX_DATA_CNT_OFFSET 0x0
	#define BT_AU_IF_STA_TX_DATA_CNT_WIDTH 0x8
	#define BT_AU_IF_STA_TX_DATA_CNT_MASK 0xFF
	#define BT_AU_IF_STA_TX_DATA_CNT(_reg) \
			(((_reg) & BT_AU_IF_STA_TX_DATA_CNT_MASK) \
			>> BT_AU_IF_STA_TX_DATA_CNT_OFFSET)
	#define BT_AU_IF_STA_RX_SPACE_CNT_OFFSET 0x8
	#define BT_AU_IF_STA_RX_SPACE_CNT_WIDTH 0x8
	#define BT_AU_IF_STA_RX_SPACE_CNT_MASK 0xFF00
	#define BT_AU_IF_STA_RX_SPACE_CNT(_reg) \
			(((_reg) & BT_AU_IF_STA_RX_SPACE_CNT_MASK) \
			>> BT_AU_IF_STA_RX_SPACE_CNT_OFFSET)
	#define BT_AU_IF_STA_AUD_OUT_CODE_OFFSET 0x10
	#define BT_AU_IF_STA_AUD_OUT_CODE_WIDTH 0x3
	#define BT_AU_IF_STA_AUD_OUT_CODE_MASK 0x70000
	#define BT_AU_IF_STA_AUD_OUT_CODE(_reg) \
			(((_reg) & BT_AU_IF_STA_AUD_OUT_CODE_MASK) \
			>> BT_AU_IF_STA_AUD_OUT_CODE_OFFSET)
	#define BT_AU_IF_STA_AUD_IN_CODE_OFFSET 0x18
	#define BT_AU_IF_STA_AUD_IN_CODE_WIDTH 0x3
	#define BT_AU_IF_STA_AUD_IN_CODE_MASK 0x7000000
	#define BT_AU_IF_STA_AUD_IN_CODE(_reg) \
			(((_reg) & BT_AU_IF_STA_AUD_IN_CODE_MASK) \
			>> BT_AU_IF_STA_AUD_IN_CODE_OFFSET)

