/*
 ****************************************************************
 *
 *  Component: DCC driver
 *
 *  Copyright (C) 2011, Intel Mobile Communications GmbH.
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License Version 2
 *  as published by the Free Software Foundation.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 *  You should have received a copy of the GNU General Public License Version 2
 *  along with this program. If not, see <http://www.gnu.org/licenses/>.
 *
 ****************************************************************
 */
#include <linux/types.h>
#include <linux/io.h>
#include <linux/types.h>
#include <linux/time.h>

/*completion*/
#include <linux/hrtimer.h>
#include <linux/completion.h>

#include "dcc-core.h"
#include "dcc-hwregs.h"

/*#define DCC_HW_STUB*/

#define CMD_MAX_WORDS	(17)
#define CMDHEADER(_iten_, _opcode_) \
			(((!!_iten_)<<7) | (_opcode_&0x1F))
#define COORDINATES(_y_, _x_)	\
	(((_y_&0x7FF) << 20) | ((_x_&0x7FF) << 8))
#define COLORRGB(_r_, _g_, _b_)	\
	(((_r_&0xFF) << 24) | ((_g_&0xFF) << 16) | ((_b_&0xFF) << 8))
#define COLORARGB(_a_, _r_, _g_, _b_)	\
	(((_a_&0xFF) << 24) \
	 | ((_r_&0xFF) << 16) | ((_g_&0xFF) << 8) | (_b_&0xFF))
#define TWO16BITS(_a_, _b_)		\
	(((_a_&0xFFFF) << 16) | (_b_&0xFFFF))

#define CMD_TYPE_INTREG 1
#define CMD_TYPE_EXTREG 2

#define EXTREG(_id_, _addr_, _mask_, _shift_) \
	{#_id_, CMD_TYPE_EXTREG, _addr_, _mask_, _shift_}

#define INTREG(_id_, _addr_, _mask_, _shift_) \
	{#_id_, CMD_TYPE_INTREG, _addr_, _mask_, _shift_}

/*external registers*/
struct gra_command gra_regs[] = {
	/*-------------------------------------------------------*/
	/*      EXTERNAL REGISTERS                                   */
	/*-------------------------------------------------------*/
/* DIF Clock Control Register */
[EXR_DIF_CLC] =
	EXTREG(EXR_DIF_CLC, GRA_DIF_CLC, 0xFFFFFFFF, 0),
[EXR_DIF_CLC_DISR] =
	EXTREG(EXR_DIF_CLC_DISR, GRA_DIF_CLC, 0x1, 0),
[EXR_DIF_CLC_DISS] =
	EXTREG(EXR_DIF_CLC_DISS, GRA_DIF_CLC, 0x1, 1),
[EXR_DIF_CLC_SPEN] =
	EXTREG(EXR_DIF_CLC_SPEN, GRA_DIF_CLC, 0x1, 2),
[EXR_DIF_CLC_EDIS] =
	EXTREG(EXR_DIF_CLC_EDIS, GRA_DIF_CLC, 0x1, 3),
[EXR_DIF_CLC_SBWE] =
	EXTREG(EXR_DIF_CLC_SBWE, GRA_DIF_CLC, 0x1, 4),
[EXR_DIF_CLC_FSOE] =
	EXTREG(EXR_DIF_CLC_FSOE, GRA_DIF_CLC, 0x1, 5),
[EXR_DIF_CLC_RMC] =
	EXTREG(EXR_DIF_CLC_RMC, GRA_DIF_CLC, 0xFF, 8),
[EXR_DIF_CLC_ORMC] =
	EXTREG(EXR_DIF_CLC_ORMC, GRA_DIF_CLC, 0xFF, 16),
/* DIF Identification Register */
[EXR_DIF_ID_NUMBER] =
	EXTREG(EXR_DIF_ID_NUMBER, GRA_DIF_ID, 0xFFFF, 0),
[EXR_DIF_ID_CONFIG] =
	EXTREG(EXR_DIF_ID_CONFIG, GRA_DIF_ID, 0xFFFF, 16),
/* DIF Status Register (0x38) */
[EXR_DIF_STAT] =
	EXTREG(EXR_DIF_STAT, GRA_DIF_STAT, 0xFFFFFFFF, 0),
[EXR_DIF_STAT_BSY] =
	EXTREG(EXR_DIF_STAT_BSY, GRA_DIF_STAT, 0x1, 0),
[EXR_DIF_STAT_GRABSY] =
	EXTREG(EXR_DIF_STAT_GRABSY, GRA_DIF_STAT, 0x1, 1),
[EXR_DIF_STAT_DSIFULL] =
	EXTREG(EXR_DIF_STAT_DSIFULL, GRA_DIF_STAT, 0x1, 2),
[EXR_DIF_STAT_DSIDIR] =
	EXTREG(EXR_DIF_STAT_DSIDIR, GRA_DIF_STAT, 0x1, 3),
[EXR_DIF_STAT_DSILOCK] =
	EXTREG(EXR_DIF_STAT_DSILOCK, GRA_DIF_STAT, 0x1, 4),
/* DIF Run Control Register (0x10) */
[EXR_DIF_RUNCTRL] =
	EXTREG(EXR_DIF_RUNCTRL, GRA_DIF_RUNCTRL, 0x1, 0),
/* DIF Control Register (0x20) */
[EXR_DIF_CON] =
	EXTREG(EXR_DIF_CON, GRA_DIF_CON, 0xFFFFFFFF, 0),
[EXR_DIF_CON_TRI] =
	EXTREG(EXR_DIF_CON_TRI, GRA_DIF_CON, 0x3, 0),
[EXR_DIF_CON_HB] =
	EXTREG(EXR_DIF_CON_HB, GRA_DIF_CON, 0x1, 4),
[EXR_DIF_CON_PH] =
	EXTREG(EXR_DIF_CON_PH, GRA_DIF_CON, 0x1, 5),
[EXR_DIF_CON_PO] =
	EXTREG(EXR_DIF_CON_PO, GRA_DIF_CON, 0x1, 6),
[EXR_DIF_CON_LB] =
	EXTREG(EXR_DIF_CON_LB, GRA_DIF_CON, 0x1, 7),
[EXR_DIF_CON_BM] =
	EXTREG(EXR_DIF_CON_BM, GRA_DIF_CON, 0x1F, 16),
/* DIF Peripheral Function Register (0x24) */
[EXR_DIF_PERREG] =
	EXTREG(EXR_DIF_PERREG, GRA_DIF_PERREG, 0xFFFFFFFF, 0),
[EXR_DIF_PERREG_DIFPERMODE] =
	EXTREG(EXR_DIF_PERREG_DIFPERMODE, GRA_DIF_PERREG, 0x1, 0),
[EXR_DIF_PERREG_INBAND] =
	EXTREG(EXR_DIF_PERREG_INBAND, GRA_DIF_PERREG, 0x1, 1),
[EXR_DIF_PERREG_CS1POL] =
	EXTREG(EXR_DIF_PERREG_CS1POL, GRA_DIF_PERREG, 0x1, 2),
[EXR_DIF_PERREG_CS2POL] =
	EXTREG(EXR_DIF_PERREG_CS2POL, GRA_DIF_PERREG, 0x1, 3),
[EXR_DIF_PERREG_RDPOL] =
	EXTREG(EXR_DIF_PERREG_RDPOL, GRA_DIF_PERREG, 0x1, 4),
[EXR_DIF_PERREG_WRPOL] =
	EXTREG(EXR_DIF_PERREG_WRPOL, GRA_DIF_PERREG, 0x1, 5),
[EXR_DIF_PERREG_CDPOL] =
	EXTREG(EXR_DIF_PERREG_CDPOL, GRA_DIF_PERREG, 0x1, 6),
[EXR_DIF_PERREG_CS3POL] =
	EXTREG(EXR_DIF_PERREG_CS3POL, GRA_DIF_PERREG, 0x1, 7),
[EXR_DIF_PERREG_MIPIEN] =
	EXTREG(EXR_DIF_PERREG_MIPIEN, GRA_DIF_PERREG, 0x1, 14),
/* DIF Chip Select and Data Configuration Register (0x28)  */
[EXR_DIF_CSREG] =
	EXTREG(EXR_DIF_CSREG, GRA_DIF_CSREG, 0xFFFFFFFF, 0),
[EXR_DIF_CSREG_CD] =
	EXTREG(EXR_DIF_CSREG_CD, GRA_DIF_CSREG, 0x1, 0),
[EXR_DIF_CSREG_CS1] =
	EXTREG(EXR_DIF_CSREG_CS1, GRA_DIF_CSREG, 0x1, 1),
[EXR_DIF_CSREG_CS2] =
	EXTREG(EXR_DIF_CSREG_CS2, GRA_DIF_CSREG, 0x1, 2),
[EXR_DIF_CSREG_CS3] =
	EXTREG(EXR_DIF_CSREG_CS3, GRA_DIF_CSREG, 0x1, 3),
[EXR_DIF_CSREG_BSCONF] =
	EXTREG(EXR_DIF_CSREG_BSCONF, GRA_DIF_CSREG, 0x7, 4),
[EXR_DIF_CSREG_GRACMD] =
	EXTREG(EXR_DIF_CSREG_GRACMD, GRA_DIF_CSREG, 0x1, 7),
/* DIF LCD Timing Register 1 (0x2C)  */
[EXR_DIF_LCDTIM1] =
	EXTREG(EXR_DIF_LCDTIM1, GRA_DIF_LCDTIM1, 0xFFFFFFFF, 0),
[EXR_DIF_LCDTIM1_ADDRDELAY] =
	EXTREG(EXR_DIF_LCDTIM1_ADDRDELAY, GRA_DIF_LCDTIM1, 0x7F, 0),
[EXR_DIF_LCDTIM1_ACCESSCYCLE] =
	EXTREG(EXR_DIF_LCDTIM1_ACCESSCYCLE, GRA_DIF_LCDTIM1, 0x7F, 8),
[EXR_DIF_LCDTIM1_DATADELAY] =
	EXTREG(EXR_DIF_LCDTIM1_DATADELAY, GRA_DIF_LCDTIM1, 0x7F, 16),
/* DIF LCD Timing Register 2 (0x30)  */
[EXR_DIF_LCDTIM2] =
	EXTREG(EXR_DIF_LCDTIM2, GRA_DIF_LCDTIM2, 0xFFFFFFFF, 0),
[EXR_DIF_LCDTIM2_CSACT] =
	EXTREG(EXR_DIF_LCDTIM2_CSACT, GRA_DIF_LCDTIM2, 0x7F, 0),
[EXR_DIF_LCDTIM2_CSDEACT] =
	EXTREG(EXR_DIF_LCDTIM2_CSDEACT, GRA_DIF_LCDTIM2, 0x7F, 8),
[EXR_DIF_LCDTIM2_WRRDACT] =
	EXTREG(EXR_DIF_LCDTIM2_WRRDACT, GRA_DIF_LCDTIM2, 0x7F, 16),
[EXR_DIF_LCDTIM2_WRRDDEACT] =
	EXTREG(EXR_DIF_LCDTIM2_WRRDDEACT, GRA_DIF_LCDTIM2, 0x7F, 24),
/* DIF Start LCD Read Register (0x34)  */
[EXR_DIF_STARTLCDRD_STARTREAD] =
	EXTREG(EXR_DIF_STARTLCDRD_STARTREAD, GRA_DIF_STARTLCDRD, 0x1, 0),
[EXR_DIF_STARTLCDRD_READBYTES] =
	EXTREG(EXR_DIF_STARTLCDRD_READBYTES, GRA_DIF_STARTLCDRD, 0x7FFF, 1),
[EXR_DIF_COEFF_REG1] =
	EXTREG(EXR_DIF_COEFF_REG1, GRA_DIF_COEFF_REG1, 0xFFFFFFFF, 0),
[EXR_DIF_COEFF_REG2] =
	EXTREG(EXR_DIF_COEFF_REG2, GRA_DIF_COEFF_REG2, 0xFFFFFFFF, 0),
[EXR_DIF_COEFF_REG3] =
	EXTREG(EXR_DIF_COEFF_REG3, GRA_DIF_COEFF_REG3, 0xFFFFFFFF, 0),
[EXR_DIF_OFFSET_REG] =
	EXTREG(EXR_DIF_OFFSET_REG, GRA_DIF_OFFSET_REG, 0xFFFFFFFF, 0),

/* DIF Pixel-Bit Conversion Register (0x4C)  */
[EXR_DIF_PBBCONV_MODE] =
	EXTREG(EXR_DIF_PBBCONV_MODE, GRA_DIF_PBCCON, 0x1, 0),
/* DIF Bit Multiplex Configuration Register 0 (0x50) */
[EXR_DIF_BMREG0] =
	EXTREG(EXR_DIF_BMREG0, GRA_DIF_BMREG0, 0xFFFFFFFF, 0),
[EXR_DIF_BMREGx_1] =
	EXTREG(EXR_DIF_BMREG0, GRA_DIF_BMREG0, 0x1F, 0),
[EXR_DIF_BMREGx_2] =
	EXTREG(EXR_DIF_BMREG0, GRA_DIF_BMREG0, 0x1F, 5),
[EXR_DIF_BMREGx_3] =
	EXTREG(EXR_DIF_BMREG0, GRA_DIF_BMREG0, 0x1F, 10),
[EXR_DIF_BMREGx_4] =
	EXTREG(EXR_DIF_BMREG0, GRA_DIF_BMREG0, 0x1F, 16),
[EXR_DIF_BMREGx_5] =
	EXTREG(EXR_DIF_BMREG0, GRA_DIF_BMREG0, 0x1F, 21),
[EXR_DIF_BMREGx_6] =
	EXTREG(EXR_DIF_BMREG0, GRA_DIF_BMREG0, 0x1F, 26),
/* DIF Bit Multiplex Configuration Register 1 (0x54) */
[EXR_DIF_BMREG1] =
	EXTREG(EXR_DIF_BMREG1, GRA_DIF_BMREG1, 0xFFFFFFFF, 0),
/* DIF Bit Multiplex Configuration Register 2 (0x58) */
[EXR_DIF_BMREG2] =
	EXTREG(EXR_DIF_BMREG2, GRA_DIF_BMREG2, 0xFFFFFFFF, 0),
/* DIF Bit Multiplex Configuration Register 3 (0x5C) */
[EXR_DIF_BMREG3] =
	EXTREG(EXR_DIF_BMREG3, GRA_DIF_BMREG3, 0xFFFFFFFF, 0),
/* DIF Bit Multiplex Configuration Register 4 (0x60) */
[EXR_DIF_BMREG4] =
	EXTREG(EXR_DIF_BMREG4, GRA_DIF_BMREG4, 0xFFFFFFFF, 0),
/* DIF Bit Multiplex Configuration Register 5 (0x64) */
[EXR_DIF_BMREG5] =
	EXTREG(EXR_DIF_BMREG5, GRA_DIF_BMREG5, 0xFFFFFFFF, 0),
/* DIF Bit Control Register 0 (0x68) */
[EXR_DIF_BCSEL0] =
	EXTREG(EXR_DIF_BCSEL0, GRA_DIF_BCSEL0, 0xFFFFFFFF, 0),
/* DIF Bit Control Register 1 (0x6C) */
[EXR_DIF_BCSEL1] =
	EXTREG(EXR_DIF_BCSEL1, GRA_DIF_BCSEL1, 0xFFFFFFFF, 0),
/* DIF Bit Clamp Value Register (0x70) */
[EXR_DIF_BCREG] =
	EXTREG(EXR_DIF_BCREG, GRA_DIF_BCREG, 0xFFFFFFFF, 0),
/* DIF Bit Inversion Register (0x74) */
[EXR_DIF_INVERT_BIT] =
	EXTREG(EXR_DIF_INVERT_BIT, GRA_DIF_INVERT, 0xFFFFFFFF, 0),
/* DIF Transfer Synchronization Configuration Register (0x78) */
[EXR_DIF_SYNCCONFIG] =
	EXTREG(EXR_DIF_SYNCCONFIG, GRA_DIF_SYNC_CONFIG, 0xFFFFFFFF, 0),
[EXR_DIF_SYNCCONFIG_SYNCEN] =
	EXTREG(EXR_DIF_SYNCCONFIG_SYNCEN, GRA_DIF_SYNC_CONFIG, 0x1, 0),
[EXR_DIF_SYNCCONFIG_HDPOL] =
	EXTREG(EXR_DIF_SYNCCONFIG_HDPOL, GRA_DIF_SYNC_CONFIG, 0x1, 1),
[EXR_DIF_SYNCCONFIG_VDPOL] =
	EXTREG(EXR_DIF_SYNCCONFIG_VDPOL, GRA_DIF_SYNC_CONFIG, 0x1, 2),
[EXR_DIF_SYNCCONFIG_SYNCCD] =
	EXTREG(EXR_DIF_SYNCCONFIG_SYNCCD, GRA_DIF_SYNC_CONFIG, 0x1, 3),
[EXR_DIF_SYNCCONFIG_SYNCCS1] =
	EXTREG(EXR_DIF_SYNCCONFIG_SYNCCS1, GRA_DIF_SYNC_CONFIG, 0x1, 4),
[EXR_DIF_SYNCCONFIG_SYNCCS2] =
	EXTREG(EXR_DIF_SYNCCONFIG_SYNCCS2, GRA_DIF_SYNC_CONFIG, 0x1, 5),
[EXR_DIF_SYNCCONFIG_SYNCCS3] =
	EXTREG(EXR_DIF_SYNCCONFIG_SYNCCS3, GRA_DIF_SYNC_CONFIG, 0x1, 6),
[EXR_DIF_SYNCCONFIG_EXTSTART] =
	EXTREG(EXR_DIF_SYNCCONFIG_EXTSTART, GRA_DIF_SYNC_CONFIG, 0x3, 8),
[EXR_DIF_SYNCCONFIG_EXTBYTES] =
	EXTREG(EXR_DIF_SYNCCONFIG_EXTBYTES, GRA_DIF_SYNC_CONFIG, 0x3, 10),
[EXR_DIF_SYNCCONFIG_EXTROWS] =
	EXTREG(EXR_DIF_SYNCCONFIG_EXTROWS, GRA_DIF_SYNC_CONFIG, 0x3, 12),
[EXR_DIF_SYNCCONFIG_COMP] =
	EXTREG(EXR_DIF_SYNCCONFIG_COMP, GRA_DIF_SYNC_CONFIG, 0xFF, 16),
/* DIF Transfer Synchronization Count Register (0x7C) */
[EXR_DIF_SYNCCOUNT] =
	EXTREG(EXR_DIF_SYNCCOUNT, GRA_DIF_SYNC_COUNT, 0xFFFFFFFF, 0),
[EXR_DIF_SYNCCOUNT_NUMROWS] =
	EXTREG(EXR_DIF_SYNCCOUNT_NUMROWS, GRA_DIF_SYNC_COUNT, 0x3FF, 22),
[EXR_DIF_SYNCCOUNT_NUMBYTES] =
	EXTREG(EXR_DIF_SYNCCOUNT_NUMBYTES, GRA_DIF_SYNC_COUNT, 0xFFF, 10),
[EXR_DIF_SYNCCOUNT_HDSTART] =
	EXTREG(EXR_DIF_SYNCCOUNT_HDSTART, GRA_DIF_SYNC_COUNT, 0x3FF, 0),
/* DIF Baud Rate Timer Reload Register (0x80) */
[EXR_DIF_BR] =
	EXTREG(EXR_DIF_BR, GRA_DIF_BR, 0xFFFF, 0),
/* DIF Baud Rate Timer Fractional Register (0x84) */
[EXR_DIF_FDIV] =
	EXTREG(EXR_DIF_FDIV, GRA_DIF_FDIV, 0x1FF, 0),
[EXR_DIF_RXFIFOCFG] =
	EXTREG(EXR_DIF_RXFIFOCFG, GRA_DIF_RXFIFO_CFG, 0xFFFFFFFF, 0),
[EXR_DIF_RXFIFOCFG_RXBS] =
	EXTREG(EXR_DIF_RXFIFOCFG_RXBS, GRA_DIF_RXFIFO_CFG, 0x7, 0),
[EXR_DIF_RXFIFOCFG_RXFA] =
	EXTREG(EXR_DIF_RXFIFOCFG_RXFA, GRA_DIF_RXFIFO_CFG, 0x3, 8),
[EXR_DIF_RXFIFOCFG_RXFC] =
	EXTREG(EXR_DIF_RXFIFOCFG_RXFC, GRA_DIF_RXFIFO_CFG, 0x1, 16),
/* DIF_RPS_CTRL (0x94) */
[EXR_DIF_MRPS_CTRL] =
	EXTREG(EXR_DIF_MRPS_CTRL, GRA_DIF_MRPS_CTRL, 0xFFFFFFFF, 0),
/* DIF_RXRPS_STAT (0x98) */
[EXR_DIF_RPS_STAT] =
	EXTREG(EXR_DIF_RPS_STAT, GRA_DIF_RPS_STAT, 0xFFFFFFFF, 0),
/* DIF_RXFFS_STAT (0x9C) */
[EXR_DIF_RXFFS_STAT] =
	EXTREG(EXR_DIF_RXFFS_STAT, GRA_DIF_RXFFS_STAT, 0xFFFFFFFF, 0),
/* DIF_RXD (0xC000) */
[EXR_DIF_RXD] =
	EXTREG(EXR_DIF_RXD, GRA_DIF_RXD, 0xFFFFFFFF, 0),
/* DIF Tx FIFO Configuration Register (0x00A0) */
[EXR_DIF_TXFIFOCFG] =
	EXTREG(EXR_DIF_TXFIFOCFG, GRA_DIF_TXFIFO_CFG, 0xFFFFFFFF, 0),
[EXR_DIF_TXFIFOCFG_TXBS] =
	EXTREG(EXR_DIF_TXFIFOCFG_TXBS, GRA_DIF_TXFIFO_CFG, 0x7, 0),
[EXR_DIF_TXFIFOCFG_TXFA] =
	EXTREG(EXR_DIF_TXFIFOCFG_TXFA, GRA_DIF_TXFIFO_CFG, 0x3, 8),
[EXR_DIF_TXFIFOCFG_TXFC] =
	EXTREG(EXR_DIF_TXFIFOCFG_TXFC, GRA_DIF_TXFIFO_CFG, 0x1, 16),
/* DIF Transmit Packet Size Register (0x00A4) */
[EXR_DIF_TPS_CTRL] =
	EXTREG(EXR_DIF_TPS_CTRL, GRA_DIF_TPS_CTRL, 0x3FFF, 0),
/* DIF Tx Filled FIFO Stages Status Register (0x00A8) */
[EXR_DIF_TXFFS_STAT] =
	EXTREG(EXR_DIF_TXFFS_STAT, GRA_DIF_TXFFS_STAT, 0xFFFFFFFF, 0),
/* DIF Error Interrupt Source Mask Register (0x00B0) */
[EXR_DIF_ERRIRQSM] =
	EXTREG(EXR_DIF_ERRIRQSM, GRA_DIF_ERR_IRQSM, 0xFFFFFFFF, 0),
/*Register (0x00B4) */
[EXR_DIF_ERRIRQSS] =
	EXTREG(EXR_DIF_ERRIRQSS, GRA_DIF_ERR_IRQSS, 0xFFFFFFFF, 0),
/*Register (0x00B8) */
[EXR_DIF_ERRIRQSC] =
	EXTREG(EXR_DIF_ERRIRQSC, GRA_DIF_ERR_IRQSC, 0xFFFFFFFF, 0),
/* DIF Transmission Data Register (0x8000) */
[EXR_DIF_TXD] =
	EXTREG(EXR_DIF_TXD, GRA_DIF_TXD, 0xFFFFFFFF, 0),
/* DIF Register (0x00C0) */
[EXR_DIF_RIS] =
	EXTREG(EXR_DIF_RIS, GRA_DIF_RIS, 0xFFFFFFFF, 0),
/* DIF Interrupt Mask Control Register (0x00C4) */
[EXR_DIF_IMSC] =
	EXTREG(EXR_DIF_IMSC, GRA_DIF_IMSC, 0xFFFFFFFF, 0),
[EXR_DIF_IMSC_RXLSREQ] =
	EXTREG(EXR_DIF_IMSC_RXLSREQ, GRA_DIF_IMSC, 0x1, 0),
[EXR_DIF_IMSC_RXSREQ] =
	EXTREG(EXR_DIF_IMSC_RXSREQ, GRA_DIF_IMSC, 0x1, 1),
[EXR_DIF_IMSC_RXLBREQ] =
	EXTREG(EXR_DIF_IMSC_RXLBREQ, GRA_DIF_IMSC, 0x1, 2),
[EXR_DIF_IMSC_RXBREQ] =
	EXTREG(EXR_DIF_IMSC_RXBREQ, GRA_DIF_IMSC, 0x1, 3),
[EXR_DIF_IMSC_TXLSREQ] =
	EXTREG(EXR_DIF_IMSC_TXLSREQ, GRA_DIF_IMSC, 0x1, 4),
[EXR_DIF_IMSC_TXSREQ] =
	EXTREG(EXR_DIF_IMSC_TXSREQ, GRA_DIF_IMSC, 0x1, 5),
[EXR_DIF_IMSC_TXLBREQ] =
	EXTREG(EXR_DIF_IMSC_TXLBREQ, GRA_DIF_IMSC, 0x1, 6),
[EXR_DIF_IMSC_TXBREQ] =
	EXTREG(EXR_DIF_IMSC_TXBREQ, GRA_DIF_IMSC, 0x1, 7),
[EXR_DIF_IMSC_ERR] =
	EXTREG(EXR_DIF_IMSC_ERR, GRA_DIF_IMSC, 0x1, 8),
[EXR_DIF_IMSC_CMD] =
	EXTREG(EXR_DIF_IMSC_CMD, GRA_DIF_IMSC, 0x1, 9),
[EXR_DIF_IMSC_FRAME] =
	EXTREG(EXR_DIF_IMSC_FRAME, GRA_DIF_IMSC, 0x1, 10),
/*Register (0x00CC) */
[EXR_DIF_ICR] =
	EXTREG(EXR_DIF_ICR, GRA_DIF_ICR, 0xFFFFFFFF, 0),

/* DIF Transmission Data Register (0x008C) */
[EXR_DIF_DEBUG] =
	EXTREG(EXR_DIF_DEBUG, GRA_DIF_DEBUG_REG, 0xFFFFFFFF, 0),

/*-------------------------------------------------------*/
/*      INTERNAL REGISTERS                               */
/*-------------------------------------------------------*/
/* DIF Configuration Register (0x00) */
[INR_DIF_CONF] =
	INTREG(INR_DIF_CONF, GRA_DIF_CONF, 0xFFFFFFFF, 0),
[INR_DIF_CONF_CLIP] =
	INTREG(INR_DIF_CONF_CLIP, GRA_DIF_CONF, 0x1, 0),
[INR_DIF_CONF_SPR] =
	INTREG(INR_DIF_CONF_SPR, GRA_DIF_CONF, 0x1, 1),
[INR_DIF_CONF_TRANS] =
	INTREG(INR_DIF_CONF_TRANS, GRA_DIF_CONF, 0x1, 2),
[INR_DIF_CONF_MASK] =
	INTREG(INR_DIF_CONF_MASK, GRA_DIF_CONF, 0x1, 3),
[INR_DIF_CONF_BLEND] =
	INTREG(INR_DIF_CONF_BLEND, GRA_DIF_CONF, 0x1, 4),
[INR_DIF_CONF_DEST] =
	INTREG(INR_DIF_CONF_DEST, GRA_DIF_CONF, 0x1, 5),
[INR_DIF_CONF_PIXEL] =
	INTREG(INR_DIF_CONF_PIXEL, GRA_DIF_CONF, 0x7, 6),
[INR_DIF_CONF_ALPHA] =
	INTREG(INR_DIF_CONF_ALPHA, GRA_DIF_CONF, 0x3, 9),
[INR_DIF_CONF_POWER] =
	INTREG(INR_DIF_CONF_POWER, GRA_DIF_CONF, 0x1, 11),
[INR_DIF_CONF_GLOBAL] =
	INTREG(INR_DIF_CONF_GLOBAL, GRA_DIF_CONF, 0x1, 17),
[INR_DIF_CONF_BGR] =
	INTREG(INR_DIF_CONF_BGR, GRA_DIF_CONF, 0x1, 18),
[INR_DIF_CONF_STENCIL] =
	INTREG(INR_DIF_CONF_STENCIL, GRA_DIF_CONF, 0x3, 19),
[INR_DIF_CONF_AUTO] =
	INTREG(INR_DIF_CONF_AUTO, GRA_DIF_CONF, 0x1, 21),
[INR_DIF_CONF_LOCK] =
	INTREG(INR_DIF_CONF_LOCK, GRA_DIF_CONF, 0x1, 22),
[INR_DIF_CONF_ALPHA_SRC] =
	INTREG(INR_DIF_CONF_ALPHA_SRC, GRA_DIF_CONF, 0x3, 23),
[INR_DIF_CONF_BLEND_DRAW] =
	INTREG(INR_DIF_CONF_BLEND_DRAW, GRA_DIF_CONF, 0x7, 25),
[INR_DIF_CONF_BLEND_OVER] =
	INTREG(INR_DIF_CONF_BLEND_OVER, GRA_DIF_CONF, 0x7, 28),
[INR_DIF_CONF_BACK] =
	INTREG(INR_DIF_CONF_BACK, GRA_DIF_CONF, 0x1, 31),
/* DIF Frame Buffer Cache Base Register (0x01) */
[INR_DIF_VIDEOBASE] =
	INTREG(INR_DIF_VIDEOBASE, GRA_GRA_VIDEO_BASE, 0xFFFFFFFF, 0),
/* DIF Frame Buffer Cache Size Register (0x02) */
[INR_DIF_VIDEOSIZE] =
	INTREG(INR_DIF_VIDEOSIZE, GRA_GRA_VIDEO_SIZE, 0xFFFFFFFF, 0),
[INR_DIF_VIDEOSIZE_XRES] =
	INTREG(INR_DIF_VIDEOSIZE_XRES, GRA_GRA_VIDEO_SIZE, 0x7FF, 0),
/* DIF Clipping Rectangle Topleft (0x03) */
[INR_DIF_CLIPPING_TL] =
	INTREG(INR_DIF_CLIPPING_TL, GRA_GRA_CLIPPINGRECT_TL, 0xFFFFFFFF, 0),
[INR_DIF_CLIPPING_TL_XCOORD] =
	INTREG(INR_DIF_CLIPPING_TL_XCOORD, GRA_GRA_CLIPPINGRECT_TL, 0x7FF, 0),
[INR_DIF_CLIPPING_TL_YCOORD] =
	INTREG(INR_DIF_CLIPPING_TL_YCOORD, GRA_GRA_CLIPPINGRECT_TL, 0x7FF, 16),
/* DIF Clipping rectangle Bottomright (0x04) */
[INR_DIF_CLIPPING_BR] =
	INTREG(INR_DIF_CLIPPING_BR, GRA_GRA_CLIPPINGRECT_BR, 0xFFFFFFFF, 0),
[INR_DIF_CLIPPING_BR_XCOORD] =
	INTREG(INR_DIF_CLIPPING_BR_XCOORD, GRA_GRA_CLIPPINGRECT_BR, 0x7FF, 0),
[INR_DIF_CLIPPING_BR_YCOORD] =
	INTREG(INR_DIF_CLIPPING_BR_YCOORD, GRA_GRA_CLIPPINGRECT_BR, 0x7FF, 16),
/* To Be Continued ..... */

/* DIF Image Source Register (0x05) */
[INR_DIF_IMG_SRC] =
	INTREG(INR_DIF_IMG_SRC, GRA_GRA_IMAGE_SRC, 0xFFFFFFFF, 0),
[INR_DIF_IMG_SRC_COL_EN] =
	INTREG(INR_DIF_IMG_SRC_COL_EN, GRA_GRA_IMAGE_SRC, 0x1, 0),
[INR_DIF_IMG_SRC_FORMAT] =
	INTREG(INR_DIF_IMG_SRC_FORMAT, GRA_GRA_IMAGE_SRC, 0x3, 1),
[INR_DIF_IMG_SRC_Y1_POS] =
	INTREG(INR_DIF_IMG_SRC_Y1_POS, GRA_GRA_IMAGE_SRC, 0x3, 3),
[INR_DIF_IMG_SRC_Y2_POS] =
	INTREG(INR_DIF_IMG_SRC_Y2_POS, GRA_GRA_IMAGE_SRC, 0x3, 5),
[INR_DIF_IMG_SRC_U_POS] =
	INTREG(INR_DIF_IMG_SRC_U_POS, GRA_GRA_IMAGE_SRC, 0x3, 7),
[INR_DIF_IMG_SRC_V_POS] =
	INTREG(INR_DIF_IMG_SRC_V_POS, GRA_GRA_IMAGE_SRC, 0x3, 9),
[INR_DIF_IMG_SRC_ROT] =
	INTREG(INR_DIF_IMG_SRC_ROT, GRA_GRA_IMAGE_SRC, 0x3, 11),
[INR_DIF_IMG_SRC_MIRROR] =
	INTREG(INR_DIF_IMG_SRC_MIRROR, GRA_GRA_IMAGE_SRC, 0x1, 13),
[INR_DIF_IMG_SRC_Y] =
	INTREG(INR_DIF_IMG_SRC_Y, GRA_GRA_IMAGE_SRC, 0xFF, 16),
[INR_DIF_IMG_SRC_INLINE] =
	INTREG(INR_DIF_IMG_SRC_INLINE, GRA_GRA_IMAGE_SRC, 0x3, 24),
[INR_DIF_IMG_SRC_SEMI] =
	INTREG(INR_DIF_IMG_SRC_SEMI, GRA_GRA_IMAGE_SRC, 0x1, 26),
/* DIF_IMAGE_SIZE (0x06) */
[INR_DIF_IMG_SIZE] =
	INTREG(INR_DIF_IMG_SIZE, GRA_GRA_IMAGE_SIZE, 0xFFFFFFFF, 0),
[INR_DIF_IMG_SIZE_XRES] =
	INTREG(INR_DIF_IMG_SIZE_XRES, GRA_GRA_IMAGE_SIZE, 0xFFF, 0),
[INR_DIF_IMG_SIZE_YRES] =
	INTREG(INR_DIF_IMG_SIZE_YRES, GRA_GRA_IMAGE_SIZE, 0xFFF, 16),
/* DIF_IMAGE_U_OFFSET (0x07) */
[INR_DIF_IMG_UOFFSET] =
	INTREG(INR_DIF_IMG_UOFFSET, GRA_GRA_IMAGE_U_OFFSET, 0xFFFFFFFF, 0),
/* DIF_IMAGE_V_OFFSET (0x08) */
[INR_DIF_IMG_VOFFSET] =
	INTREG(INR_DIF_IMG_VOFFSET, GRA_GRA_IMAGE_V_OFFSET, 0xFFFFFFFF, 0),
/* DIF_IMAGE_U_OFFSET2 (0x1D) */
[INR_DIF_IMG_UOFFSET2] =
	INTREG(INR_DIF_IMG_UOFFSET2, GRA_GRA_IMAGE_U_OFFSET2, 0xFFFFFFFF, 0),
/* DIF_IMAGE_V_OFFSET2 (0x1E) */
[INR_DIF_IMG_VOFFSET2] =
	INTREG(INR_DIF_IMG_VOFFSET2, GRA_GRA_IMAGE_V_OFFSET2, 0xFFFFFFFF, 0),
/* DIF_IMAGE_WINDOW_TL (0x09) */
[INR_DIF_IMG_WINTL] =
	INTREG(INR_DIF_IMG_WINTL, GRA_GRA_IMAGE_WINDOW_TL, 0xFFFFFFFF, 0),
[INR_DIF_IMG_WINTL_X1] =
	INTREG(INR_DIF_IMG_WINTL_X1, GRA_GRA_IMAGE_WINDOW_TL, 0xFFF, 0),
[INR_DIF_IMG_WINTL_Y1] =
	INTREG(INR_DIF_IMG_WINTL_Y1, GRA_GRA_IMAGE_WINDOW_TL, 0xFFF, 16),
/* DIF_IMAGE_WINDOW_BR (0x0A) */
[INR_DIF_IMG_WINBR] =
	INTREG(INR_DIF_IMG_WINBR, GRA_GRA_IMAGE_WINDOW_BR, 0xFFFFFFFF, 0),
[INR_DIF_IMG_WINBR_X2] =
	INTREG(INR_DIF_IMG_WINBR_X2, GRA_GRA_IMAGE_WINDOW_BR, 0xFFF, 0),
[INR_DIF_IMG_WINBR_Y2] =
	INTREG(INR_DIF_IMG_WINBR_Y2, GRA_GRA_IMAGE_WINDOW_BR, 0xFFF, 16),
/* DIF_IMAGE_SCALE (0x0B) */
[INR_DIF_IMG_SCALE] =
	INTREG(INR_DIF_IMG_SCALE, GRA_GRA_IMAGE_SCALE, 0xFFFFFFFF, 0),
[INR_DIF_IMG_SCALE_SCALEX] =
	INTREG(INR_DIF_IMG_SCALE_SCALEX, GRA_GRA_IMAGE_SCALE, 0xFFFF, 0),
[INR_DIF_IMG_SCALE_SCALEY] =
	INTREG(INR_DIF_IMG_SCALE_SCALEY, GRA_GRA_IMAGE_SCALE, 0xFFFF, 16),
/* DIF_SPRITE_CONF0 (0x0D) */
[INR_DIF_SPRITE_CONF0] =
	INTREG(INR_DIF_SPRITE_CONF0, GRA_GRA_SPRITE_CONF0, 0xFFFFFFFF, 0),
[INR_DIF_SPRITE_CONF0_TRI] =
	INTREG(INR_DIF_SPRITE_CONF0_TRI, GRA_GRA_SPRITE_CONF0, 0x1, 3),
[INR_DIF_SPRITE_CONF0_BGR] =
	INTREG(INR_DIF_SPRITE_CONF0_BGR, GRA_GRA_SPRITE_CONF0, 0x1, 4),
[INR_DIF_SPRITE_CONF0_ACT] =
	INTREG(INR_DIF_SPRITE_CONF0_ACT, GRA_GRA_SPRITE_CONF0, 0x1, 5),
[INR_DIF_SPRITE_CONF0_TYP] =
	INTREG(INR_DIF_SPRITE_CONF0_TYP, GRA_GRA_SPRITE_CONF0, 0x7, 6),
[INR_DIF_SPRITE_CONF0_XPOS] =
	INTREG(INR_DIF_SPRITE_CONF0_XPOS, GRA_GRA_SPRITE_CONF0, 0x7FF, 10),
[INR_DIF_SPRITE_CONF0_YPOS] =
	INTREG(INR_DIF_SPRITE_CONF0_YPOS, GRA_GRA_SPRITE_CONF0, 0x7FF, 21),
/* DIF_SPRITE_CONF1 (0x0E) */
[INR_DIF_SPRITE_CONF1] =
	INTREG(INR_DIF_SPRITE_CONF1, GRA_GRA_SPRITE_CONF1, 0xFFFFFFFF, 0),
[INR_DIF_SPRITE_CONF1_TRI] =
	INTREG(INR_DIF_SPRITE_CONF1_TRI, GRA_GRA_SPRITE_CONF0, 0x1, 3),
[INR_DIF_SPRITE_CONF1_BGR] =
	INTREG(INR_DIF_SPRITE_CONF1_BGR, GRA_GRA_SPRITE_CONF0, 0x1, 4),
[INR_DIF_SPRITE_CONF1_ACT] =
	INTREG(INR_DIF_SPRITE_CONF1_ACT, GRA_GRA_SPRITE_CONF1, 0x1, 5),
[INR_DIF_SPRITE_CONF1_TYP] =
	INTREG(INR_DIF_SPRITE_CONF1_TYP, GRA_GRA_SPRITE_CONF1, 0x7, 6),
[INR_DIF_SPRITE_CONF1_XPOS] =
	INTREG(INR_DIF_SPRITE_CONF1_XPOS, GRA_GRA_SPRITE_CONF1, 0x7FF, 10),
[INR_DIF_SPRITE_CONF1_YPOS] =
	INTREG(INR_DIF_SPRITE_CONF1_YPOS, GRA_GRA_SPRITE_CONF1, 0x7FF, 21),
/* DIF_SPRITE_CONF2 (0x0F) */
[INR_DIF_SPRITE_CONF2] =
	INTREG(INR_DIF_SPRITE_CONF2, GRA_GRA_SPRITE_CONF2, 0xFFFFFFFF, 0),
[INR_DIF_SPRITE_CONF2_TRI] =
	INTREG(INR_DIF_SPRITE_CONF2_TRI, GRA_GRA_SPRITE_CONF0, 0x1, 3),
[INR_DIF_SPRITE_CONF2_BGR] =
	INTREG(INR_DIF_SPRITE_CONF2_BGR, GRA_GRA_SPRITE_CONF0, 0x1, 4),
[INR_DIF_SPRITE_CONF2_ACT] =
	INTREG(INR_DIF_SPRITE_CONF2_ACT, GRA_GRA_SPRITE_CONF2, 0x1, 5),
[INR_DIF_SPRITE_CONF2_TYP] =
	INTREG(INR_DIF_SPRITE_CONF2_TYP, GRA_GRA_SPRITE_CONF2, 0x7, 6),
[INR_DIF_SPRITE_CONF2_BLEND] =
	INTREG(INR_DIF_SPRITE_CONF2_BLEND, GRA_GRA_SPRITE_CONF2, 0x1, 9),
[INR_DIF_SPRITE_CONF2_CHROMA] =
	INTREG(INR_DIF_SPRITE_CONF2_CHROMA, GRA_GRA_SPRITE_CONF2, 0xFFFF, 16),
/* DIF_SPRITE_CONF3 (0x10) */
[INR_DIF_SPRITE_CONF3] =
	INTREG(INR_DIF_SPRITE_CONF3, GRA_GRA_SPRITE_CONF3, 0xFFFFFFFF, 0),
[INR_DIF_SPRITE_CONF3_TRI] =
	INTREG(INR_DIF_SPRITE_CONF3_TRI, GRA_GRA_SPRITE_CONF0, 0x1, 3),
[INR_DIF_SPRITE_CONF3_BGR] =
	INTREG(INR_DIF_SPRITE_CONF3_BGR, GRA_GRA_SPRITE_CONF0, 0x1, 4),
[INR_DIF_SPRITE_CONF3_ACT] =
	INTREG(INR_DIF_SPRITE_CONF3_ACT, GRA_GRA_SPRITE_CONF3, 0x1, 5),
[INR_DIF_SPRITE_CONF3_TYP] =
	INTREG(INR_DIF_SPRITE_CONF3_TYP, GRA_GRA_SPRITE_CONF3, 0x7, 6),
[INR_DIF_SPRITE_CONF3_XPOS] =
	INTREG(INR_DIF_SPRITE_CONF3_XPOS, GRA_GRA_SPRITE_CONF3, 0x7FF, 10),
[INR_DIF_SPRITE_CONF3_YPOS] =
	INTREG(INR_DIF_SPRITE_CONF3_YPOS, GRA_GRA_SPRITE_CONF3, 0x7FF, 21),
/* DIF_SPRITE_BASE0 (0x16) */
[INR_DIF_SPRITE_BASEx0] =
	INTREG(INR_DIF_SPRITE_BASEx0, GRA_GRA_SPRITE_BASEx0, 0xFFFFFFFF, 0),
/* DIF_SPRITE_BASE1 (0x17) */
[INR_DIF_SPRITE_BASEx1] =
	INTREG(INR_DIF_SPRITE_BASEx1, GRA_GRA_SPRITE_BASEx1, 0xFFFFFFFF, 0),
/* DIF_SPRITE_BASE2 (0x0C) */
[INR_DIF_SPRITE_BASEx2] =
	INTREG(INR_DIF_SPRITE_BASEx2, GRA_GRA_SPRITE_BASEx2, 0xFFFFFFFF, 0),
/* DIF_SPRITE_BASE3 (0x18) */
[INR_DIF_SPRITE_BASEx3] =
	INTREG(INR_DIF_SPRITE_BASEx3, GRA_GRA_SPRITE_BASEx3, 0xFFFFFFFF, 0),
/* DIF_SPRITE_SIZE0 (0x19) */
[INR_DIF_SPRITE_SIZE0] =
	INTREG(INR_DIF_SPRITE_SIZE0, GRA_GRA_SPRITE_SIZE0, 0xFFFFFFFF, 0),
[INR_DIF_SPRITE_SIZE0_WIDTH] =
	INTREG(INR_DIF_SPRITE_SIZE0_WIDTH, GRA_GRA_SPRITE_SIZE0, 0x3FF, 0),
[INR_DIF_SPRITE_SIZE0_HEIGHT] =
	INTREG(INR_DIF_SPRITE_SIZE0_HEIGHT, GRA_GRA_SPRITE_SIZE0, 0x7FF, 10),
[INR_DIF_SPRITE_SIZE0_WIDTHMSB] =
	INTREG(INR_DIF_SPRITE_SIZE0_WIDTHMSB, GRA_GRA_SPRITE_SIZE0, 0x1, 22),
[INR_DIF_SPRITE_SIZE0_ALPHA] =
	INTREG(INR_DIF_SPRITE_SIZE0_ALPHA, GRA_GRA_SPRITE_SIZE0, 0xFF, 23),
[INR_DIF_SPRITE_SIZE0_GLOBAL] =
	INTREG(INR_DIF_SPRITE_SIZE0_GLOBAL, GRA_GRA_SPRITE_SIZE0, 0x1, 31),
/* DIF_SPRITE_SIZE1 (0x1A) */
[INR_DIF_SPRITE_SIZE1] =
	INTREG(INR_DIF_SPRITE_SIZE1, GRA_GRA_SPRITE_SIZE1, 0xFFFFFFFF, 0),
[INR_DIF_SPRITE_SIZE1_WIDTH] =
	INTREG(INR_DIF_SPRITE_SIZE1_WIDTH, GRA_GRA_SPRITE_SIZE1, 0x3FF, 0),
[INR_DIF_SPRITE_SIZE1_HEIGHT] =
	INTREG(INR_DIF_SPRITE_SIZE1_HEIGHT, GRA_GRA_SPRITE_SIZE1, 0x7FF, 10),
[INR_DIF_SPRITE_SIZE1_WIDTHMSB] =
	INTREG(INR_DIF_SPRITE_SIZE1_WIDTHMSB, GRA_GRA_SPRITE_SIZE1, 0x1, 22),
[INR_DIF_SPRITE_SIZE1_ALPHA] =
	INTREG(INR_DIF_SPRITE_SIZE1_ALPHA, GRA_GRA_SPRITE_SIZE1, 0xFF, 23),
[INR_DIF_SPRITE_SIZE1_GLOBAL] =
	INTREG(INR_DIF_SPRITE_SIZE1_GLOBAL, GRA_GRA_SPRITE_SIZE1, 0x1, 31),
/* DIF_SPRITE_SIZE2 (0x1B) */
[INR_DIF_SPRITE_SIZE2] =
	INTREG(INR_DIF_SPRITE_SIZE2, GRA_GRA_SPRITE_SIZE2, 0xFFFFFFFF, 0),
[INR_DIF_SPRITE_SIZE2_WIDTH] =
	INTREG(INR_DIF_SPRITE_SIZE2_WIDTH, GRA_GRA_SPRITE_SIZE2, 0x3FF, 0),
[INR_DIF_SPRITE_SIZE2_HEIGHT] =
	INTREG(INR_DIF_SPRITE_SIZE2_HEIGHT, GRA_GRA_SPRITE_SIZE2, 0x7FF, 10),
[INR_DIF_SPRITE_SIZE2_WIDTHMSB] =
	INTREG(INR_DIF_SPRITE_SIZE2_WIDTHMSB, GRA_GRA_SPRITE_SIZE2, 0x1, 22),
[INR_DIF_SPRITE_SIZE2_ALPHA] =
	INTREG(INR_DIF_SPRITE_SIZE2_ALPHA, GRA_GRA_SPRITE_SIZE2, 0xFF, 23),
[INR_DIF_SPRITE_SIZE2_GLOBAL] =
	INTREG(INR_DIF_SPRITE_SIZE2_GLOBAL, GRA_GRA_SPRITE_SIZE2, 0x1, 31),
/* DIF_SPRITE_SIZE3 (0x1C) */
[INR_DIF_SPRITE_SIZE3] =
	INTREG(INR_DIF_SPRITE_SIZE3, GRA_GRA_SPRITE_SIZE3, 0xFFFFFFFF, 0),
[INR_DIF_SPRITE_SIZE3_WIDTH] =
	INTREG(INR_DIF_SPRITE_SIZE3_WIDTH, GRA_GRA_SPRITE_SIZE3, 0x3FF, 0),
[INR_DIF_SPRITE_SIZE3_HEIGHT] =
	INTREG(INR_DIF_SPRITE_SIZE3_HEIGHT, GRA_GRA_SPRITE_SIZE3, 0x7FF, 10),
[INR_DIF_SPRITE_SIZE3_WIDTHMSB] =
	INTREG(INR_DIF_SPRITE_SIZE3_WIDTHMSB, GRA_GRA_SPRITE_SIZE3, 0x1, 22),
[INR_DIF_SPRITE_SIZE3_ALPHA] =
	INTREG(INR_DIF_SPRITE_SIZE3_ALPHA, GRA_GRA_SPRITE_SIZE3, 0xFF, 23),
[INR_DIF_SPRITE_SIZE3_GLOBAL] =
	INTREG(INR_DIF_SPRITE_SIZE3_GLOBAL, GRA_GRA_SPRITE_SIZE3, 0x1, 31),

/* DIF Stencil Buffer Base Register (0x33) */
[INR_GRA_STENCILBASE] =
	INTREG(INR_GRA_STENCILBASE, GRA_GRA_STENCIL_BASE, 0xFFFFFFFF, 0),

/* DIF DSI Configuration Register (0x27) */
[INR_DIF_DSICFG] =
	INTREG(INR_DIF_DSICFG, GRA_DIF_DSI_CFG, 0xFFFFFFFF, 0),
[INR_DIF_DSICFG_CRC] =
	INTREG(INR_DIF_DSICFG_CRC, GRA_DIF_DSI_CFG, 0x1, 0),
[INR_DIF_DSICFG_ECC] =
	INTREG(INR_DIF_DSICFG_ECC, GRA_DIF_DSI_CFG, 0x1, 1),
[INR_DIF_DSICFG_GATE] =
	INTREG(INR_DIF_DSICFG_GATE, GRA_DIF_DSI_CFG, 0x1, 2),
[INR_DIF_DSICFG_TX] =
	INTREG(INR_DIF_DSICFG_TX, GRA_DIF_DSI_CFG, 0x1, 3),
[INR_DIF_DSICFG_LP] =
	INTREG(INR_DIF_DSICFG_LP, GRA_DIF_DSI_CFG, 0x1, 4),
[INR_DIF_DSICFG_MODE] =
	INTREG(INR_DIF_DSICFG_MODE, GRA_DIF_DSI_CFG, 0x1, 5),
[INR_DIF_DSICFG_EOT] =
	INTREG(INR_DIF_DSICFG_EOT, GRA_DIF_DSI_CFG, 0x1, 6),
[INR_DIF_DSICFG_TURN] =
	INTREG(INR_DIF_DSICFG_TURN, GRA_DIF_DSI_CFG, 0x1, 7),
[INR_DIF_DSICFG_VALID] =
	INTREG(INR_DIF_DSICFG_VALID, GRA_DIF_DSI_CFG, 0x1, 8),
[INR_DIF_DSICFG_DATA] =
	INTREG(INR_DIF_DSICFG_DATA, GRA_DIF_DSI_CFG, 0x1, 9),
[INR_DIF_DSICFG_STP] =
	INTREG(INR_DIF_DSICFG_STP, GRA_DIF_DSI_CFG, 0x1, 10),
[INR_DIF_DSICFG_ULPS] =
	INTREG(INR_DIF_DSICFG_ULPS, GRA_DIF_DSI_CFG, 0x1, 11),
[INR_DIF_DSICFG_EN] =
	INTREG(INR_DIF_DSICFG_EN,	GRA_DIF_DSI_CFG, 0x1, 12),
[INR_DIF_DSICFG_LANES] =
	INTREG(INR_DIF_DSICFG_LANES, GRA_DIF_DSI_CFG, 0x3, 13),
[INR_DIF_DSICFG_ID] =
	INTREG(INR_DIF_DSICFG_ID,	GRA_DIF_DSI_CFG, 0x3, 15),
[INR_DIF_DSICFG_TXS] =
	INTREG(INR_DIF_DSICFG_TXS,	GRA_DIF_DSI_CFG, 0x1, 17),
[INR_DIF_DSICFG_TE] =
	INTREG(INR_DIF_DSICFG_TE,	GRA_DIF_DSI_CFG, 0x1, 18),
[INR_DIF_DSICFG_FIN] =
	INTREG(INR_DIF_DSICFG_FIN,	GRA_DIF_DSI_CFG, 0x1, 19),

/* DIF DSI Clock Register (0x28) */
[INR_DIF_DSICLK] =
	INTREG(INR_DIF_DSICLK, GRA_DIF_DSI_CLK, 0xFFFFFFFF, 0),
[INR_DIF_DSICLK_SETUP] =
	INTREG(INR_DIF_DSICLK_SETUP, GRA_DIF_DSI_CLK, 0xF, 0),
[INR_DIF_DSICLK_HOLD] =
	INTREG(INR_DIF_DSICLK_HOLD, GRA_DIF_DSI_CLK, 0xF, 4),

/* DIF DSI Header Register (0x29) */
[INR_DIF_DSIHEAD] =
	INTREG(INR_DIF_DSIHEAD, GRA_DIF_DSI_HEAD, 0xFFFFFFFF, 0),
[INR_DIF_DSIHEAD_HEADER] =
	INTREG(INR_DIF_DSIHEAD_HEADER, GRA_DIF_DSI_HEAD, 0xFF, 0),
[INR_DIF_DSIHEAD_WCNT] =
	INTREG(INR_DIF_DSIHEAD_WCNT, GRA_DIF_DSI_HEAD, 0xFFFF, 8),
[INR_DIF_DSIHEAD_CMD] =
	INTREG(INR_DIF_DSIHEAD_CMD, GRA_DIF_DSI_HEAD, 0xFF, 24),

/* DIF DSI Timeout 0 Register (0x2A) */
[INR_DIF_DSITO0] =
	INTREG(INR_DIF_DSITO0, GRA_DIF_DSI_TO0, 0xFFFFFFFF, 0),
[INR_DIF_DSITO0_LPTX] =
	INTREG(INR_DIF_DSITO0_LPTX, GRA_DIF_DSI_TO0, 0xFFFF, 0),
[INR_DIF_DSITO0_HSTX] =
	INTREG(INR_DIF_DSITO0_HSTX, GRA_DIF_DSI_TO0, 0xFFFF, 16),

/* DIF DSI Timeout 1 Register (0x2B) */
[INR_DIF_DSITO1] =
	INTREG(INR_DIF_DSITO1, GRA_DIF_DSI_TO1, 0xFFFFFFFF, 0),
[INR_DIF_DSITO1_LPRX] =
	INTREG(INR_DIF_DSITO1_LPRX, GRA_DIF_DSI_TO1, 0xFFFF, 0),
[INR_DIF_DSITO1_BASE] =
	INTREG(INR_DIF_DSITO1_BASE, GRA_DIF_DSI_TO1, 0xFFFF, 16),

/* DIF DSI Video 0 Register (0x2C) */
[INR_DIF_DSIVID0] =
	INTREG(INR_DIF_DSIVID0,	GRA_DIF_DSI_VID0, 0xFFFFFFFF, 0),
[INR_DIF_DSIVID0_HFPBYTES] =
	INTREG(INR_DIF_DSIVID0_HFPBYTES, GRA_DIF_DSI_VID0, 0xFF, 0),
[INR_DIF_DSIVID0_HBPBYTES] =
	INTREG(INR_DIF_DSIVID0_HBPBYTES, GRA_DIF_DSI_VID0, 0xFF, 8),
[INR_DIF_DSIVID0_HSABYTES] =
	INTREG(INR_DIF_DSIVID0_HSABYTES, GRA_DIF_DSI_VID0, 0xFF, 16),
[INR_DIF_DSIVID0_HFP] =
	INTREG(INR_DIF_DSIVID0_HFP, GRA_DIF_DSI_VID0, 0x1, 24),
[INR_DIF_DSIVID0_HBP] =
	INTREG(INR_DIF_DSIVID0_HBP, GRA_DIF_DSI_VID0, 0x1, 25),
[INR_DIF_DSIVID0_HSA] =
	INTREG(INR_DIF_DSIVID0_HSA, GRA_DIF_DSI_VID0, 0x1, 26),
[INR_DIF_DSIVID0_HFPLP] =
	INTREG(INR_DIF_DSIVID0_HFPLP, GRA_DIF_DSI_VID0, 0x1, 27),
[INR_DIF_DSIVID0_HBPLP] =
	INTREG(INR_DIF_DSIVID0_HBPLP, GRA_DIF_DSI_VID0, 0x1, 28),
[INR_DIF_DSIVID0_HSALP] =
	INTREG(INR_DIF_DSIVID0_HSALP, GRA_DIF_DSI_VID0, 0x1, 29),

/* DIF DSI Video 1 Register (0x2D) */
[INR_DIF_DSIVID1] =
	INTREG(INR_DIF_DSIVID1,	GRA_DIF_DSI_VID1, 0xFFFFFFFF, 0),
[INR_DIF_DSIVID1_VACT] =
	INTREG(INR_DIF_DSIVID1_VACT, GRA_DIF_DSI_VID1, 0xFFF, 0),
[INR_DIF_DSIVID1_MODE] =
	INTREG(INR_DIF_DSIVID1_MODE, GRA_DIF_DSI_VID1, 0x3,  12),
[INR_DIF_DSIVID1_ID] =
	INTREG(INR_DIF_DSIVID1_ID, GRA_DIF_DSI_VID1, 0x3,  14),
[INR_DIF_DSIVID1_PIXEL] =
	INTREG(INR_DIF_DSIVID1_PIXEL, GRA_DIF_DSI_VID1, 0x3,  16),
[INR_DIF_DSIVID1_TOFILL] =
	INTREG(INR_DIF_DSIVID1_TOFILL, GRA_DIF_DSI_VID1, 0x3FF, 18),
[INR_DIF_DSIVID1_LASTCS] =
	INTREG(INR_DIF_DSIVID1_LASTCS, GRA_DIF_DSI_VID1, 0xF, 28),

/* DIF DSI Video 2 Register (0x2E) */
[INR_DIF_DSIVID2] =
	INTREG(INR_DIF_DSIVID2, GRA_DIF_DSI_VID2, 0xFFFFFFFF, 0),
[INR_DIF_DSIVID2_VFP] =
	INTREG(INR_DIF_DSIVID2_VFP, GRA_DIF_DSI_VID2, 0xFF, 0),
[INR_DIF_DSIVID2_VBP] =
	INTREG(INR_DIF_DSIVID2_VBP, GRA_DIF_DSI_VID2, 0xFF, 8),
[INR_DIF_DSIVID2_VSA] =
	INTREG(INR_DIF_DSIVID2_VSA, GRA_DIF_DSI_VID2, 0xFF, 16),

/* DIF DSI Video 3 Register (0x2F) */
[INR_DIF_DSIVID3] =
	INTREG(INR_DIF_DSIVID3,	GRA_DIF_DSI_VID3, 0xFFFFFFFF, 0),
[INR_DIF_DSIVID3_PIXELPACKETS] =
	INTREG(INR_DIF_DSIVID3_PIXELPACKETS, GRA_DIF_DSI_VID3, 0xFFFF, 0),
[INR_DIF_DSIVID3_PIXELBYTES] =
	INTREG(INR_DIF_DSIVID3_PIXELBYTES, GRA_DIF_DSI_VID3, 0xFFFF, 16),

/* DIF DSI Video 4 Register (0x30) */
[INR_DIF_DSIVID4] =
	INTREG(INR_DIF_DSIVID4,	GRA_DIF_DSI_VID4, 0xFFFFFFFF, 0),
[INR_DIF_DSIVID4_BLANKPACKETS] =
	INTREG(INR_DIF_DSIVID4_BLANKPACKETS, GRA_DIF_DSI_VID4, 0xFFFF, 0),
[INR_DIF_DSIVID4_BLANKBYTES] =
	INTREG(INR_DIF_DSIVID4_BLANKBYTES, GRA_DIF_DSI_VID4, 0xFFFF, 16),

/* DIF DSI Video 5 Register (0x31) */
[INR_DIF_DSIVID5] =
	INTREG(INR_DIF_DSIVID5,	GRA_DIF_DSI_VID5, 0xFFFFFFFF, 0),
[INR_DIF_DSIVID5_LINE] =
	INTREG(INR_DIF_DSIVID5_LINE, GRA_DIF_DSI_VID5, 0xFFFF, 0),
[INR_DIF_DSIVID5_BLLP] =
	INTREG(INR_DIF_DSIVID5_BLLP, GRA_DIF_DSI_VID5, 0xFFFF, 16),

/* DIF DSI Video 6 Register (0x32) */
[INR_DIF_DSIVID6] =
	INTREG(INR_DIF_DSIVID6, GRA_DIF_DSI_VID6, 0xFFFFFFFF, 0),
[INR_DIF_DSIVID6_LASTBLANK] =
	INTREG(INR_DIF_DSIVID6_LASTBLANK, GRA_DIF_DSI_VID6, 0xFFFF, 0),
[INR_DIF_DSIVID6_LASTPIXEL] =
	INTREG(INR_DIF_DSIVID6_LASTPIXEL, GRA_DIF_DSI_VID6, 0xFFFF, 16),

/* DIF DSI PHY 0 Register (0x34) */
[INR_DIF_DSIPHY0] =
	INTREG(INR_DIF_DSIPHY0,	GRA_DIF_DSI_PHY0, 0xFFFFFFFF, 0),
[INR_DIF_DSIPHY0_SHARE] =
	INTREG(INR_DIF_DSIPHY0_SHARE, GRA_DIF_DSI_PHY0, 0x1,  0),
[INR_DIF_DSIPHY0_M] =
	INTREG(INR_DIF_DSIPHY0_M, GRA_DIF_DSI_PHY0, 0xF,  1),
[INR_DIF_DSIPHY0_N] =
	INTREG(INR_DIF_DSIPHY0_N, GRA_DIF_DSI_PHY0, 0xFF, 5),
[INR_DIF_DSIPHY0_PWUP] =
	INTREG(INR_DIF_DSIPHY0_PWUP, GRA_DIF_DSI_PHY0, 0x3F, 13),
[INR_DIF_DSIPHY0_CALIB] =
	INTREG(INR_DIF_DSIPHY0_CALIB, GRA_DIF_DSI_PHY0, 0x3F, 19),
[INR_DIF_DSIPHY0_TOREQ] =
	INTREG(INR_DIF_DSIPHY0_TOREQ, GRA_DIF_DSI_PHY0, 0x3F, 25),

/* DIF DSI PHY 1 Register (0x35) */
[INR_DIF_DSIPHY1] =
	INTREG(INR_DIF_DSIPHY1,	GRA_DIF_DSI_PHY1, 0xFFFFFFFF, 0),
[INR_DIF_DSIPHY1_TOLPHSDIS] =
	INTREG(INR_DIF_DSIPHY1_TOLPHSDIS, GRA_DIF_DSI_PHY1, 0x3F, 0),
[INR_DIF_DSIPHY1_TOLPHSEOT] =
	INTREG(INR_DIF_DSIPHY1_TOLPHSEOT, GRA_DIF_DSI_PHY1, 0x3F, 6),
[INR_DIF_DSIPHY1_TOHSZERO] =
	INTREG(INR_DIF_DSIPHY1_TOHSZERO, GRA_DIF_DSI_PHY1, 0x3F, 12),
[INR_DIF_DSIPHY1_TOHSFLIP] =
	INTREG(INR_DIF_DSIPHY1_TOHSFLIP, GRA_DIF_DSI_PHY1, 0x3F, 18),
[INR_DIF_DSIPHY1_LPCLKDIV] =
	INTREG(INR_DIF_DSIPHY1_LPCLKDIV, GRA_DIF_DSI_PHY1, 0x3F, 24),

/* DIF DSI PHY 2 Register (0x36) */
[INR_DIF_DSIPHY2] =
	INTREG(INR_DIF_DSIPHY2,	GRA_DIF_DSI_PHY2, 0xFFFFFFFF, 0),
[INR_DIF_DSIPHY2_HSCLKPRE] =
	INTREG(INR_DIF_DSIPHY2_HSCLKPRE, GRA_DIF_DSI_PHY2, 0x3FF, 0),
[INR_DIF_DSIPHY2_HSCLKPOST] =
	INTREG(INR_DIF_DSIPHY2_HSCLKPOST, GRA_DIF_DSI_PHY2, 0x3FF, 10),
[INR_DIF_DSIPHY2_DATDELAY] =
	INTREG(INR_DIF_DSIPHY2_DATDELAY, GRA_DIF_DSI_PHY2, 0xF,  20),
[INR_DIF_DSIPHY2_CLKDELAY] =
	INTREG(INR_DIF_DSIPHY2_CLKDELAY, GRA_DIF_DSI_PHY2, 0xF,  24),
[INR_DIF_DSIPHY2_LPTX_TFALL] =
	INTREG(INR_DIF_DSIPHY2_LPTX_TFALL, GRA_DIF_DSI_PHY2, 0x7,  28),

/* DIF DSI PHY 3 Register (0x37) */
[INR_DIF_DSIPHY3] =
	INTREG(INR_DIF_DSIPHY3,	GRA_DIF_DSI_PHY3, 0xFFFFFFFF, 0),
[INR_DIF_DSIPHY3_EN] =
	INTREG(INR_DIF_DSIPHY3_EN, GRA_DIF_DSI_PHY3, 0x1,  0),
[INR_DIF_DSIPHY3_LPTX_TRISE] =
	INTREG(INR_DIF_DSIPHY3_LPTX_TRISE, GRA_DIF_DSI_PHY3, 0x7,  1),
[INR_DIF_DSIPHY3_LPTX_VREF] =
	INTREG(INR_DIF_DSIPHY3_LPTX_VREF, GRA_DIF_DSI_PHY3, 0x1F, 4),

};

/**
 * Wait for a specific value of a register
 */
DECLARE_COMPLETION(comp);
static enum hrtimer_restart complete_timer_func(struct hrtimer *timer)
{
	complete(&comp);
	return HRTIMER_NORESTART;
}

int gra_waitfor_external(void *base, unsigned int field, unsigned int value)
{
	unsigned int fieldval = value - 1;	/* just to invalid first test */
	int ret = 0;
	struct gra_command *cmd = &(gra_regs[field]);

	fieldval = ioread32(base + cmd->addr);
	if (fieldval != value) {
		struct hrtimer timer;
		hrtimer_init(&timer, CLOCK_MONOTONIC, HRTIMER_MODE_REL);
		timer.function = complete_timer_func;
		while (fieldval != value) {
			hrtimer_start(&timer, ktime_set(0, 700 * 1000),
				      HRTIMER_MODE_REL);
			wait_for_completion(&comp);
			fieldval = ioread32(base + cmd->addr);
		}
		hrtimer_cancel(&timer);
	}

	return ret;
}

/**
 * Reads GRA external register field value
 */
static unsigned int gra_rdextfield(void *regbase, unsigned int id)
{
	unsigned int retval = 0, regval = 0;
	struct gra_command *cmd = &(gra_regs[id]);

	if (regbase) {
		regval = ioread32(regbase + cmd->addr);
	} else {
		dcc_err("%s, mmio base address is null\n", __func__);
		return -1;
	}

	retval = (regval >> cmd->shift) & cmd->mask;

	return retval;
}

/**
 * Write GRA external register field value
 */
static int gra_wrextfield(void *regbase, unsigned int id, unsigned int val)
{
	unsigned int regval = 0;
	struct gra_command *cmd = &(gra_regs[id]);

	if (regbase) {
		if (cmd->mask == 0xFFFFFFFF) {
			iowrite32(val, regbase + cmd->addr);
		} else {
			val = (val << cmd->shift) & (cmd->mask << cmd->shift);
			regval =
			    ioread32(regbase + cmd->addr)
					& ~(cmd->mask << cmd->shift);
			DCC_DBG4("wr 0x%08x | 0x%08x = 0x%08x -> @0x%04x %s\n",
				val, regval, val|regval, cmd->addr, cmd->name);
			iowrite32(val | regval, regbase + cmd->addr);
		}
	} else {
		dcc_err("%s, mmio base address is null\n", __func__);
		return -1;
	}

	return 0;
}

/**
 * Reads GRA internal register field value
 */
static unsigned int gra_rdintreg(struct dcc_drvdata *p, unsigned int id)
{
	unsigned int regval;
	unsigned int dif_gracmd;
	unsigned int getregister;
	struct gra_command *cmd = &(gra_regs[id]);

	dif_gracmd = gra_rdextfield(p->reg.vbase, EXR_DIF_CSREG_GRACMD);

	/* check that it's possible to read into GRA internal registers */
	if (!(dif_gracmd)) {
		dcc_err("%s: %s: Read not allowed\n",
		     __func__, cmd->name);
		regval = -1;
		goto exit;
	}

	getregister = cmd->addr;
	gra_sendcmd(p, GRACMD_GET_REGISTER, 0, &getregister, 1);
	/* get the internal register value from the DEBUG register */
	gra_waitfor_external(p->reg.vbase, EXR_DIF_TXFFS_STAT, 0);

	regval = gra_rdextfield(p->reg.vbase, EXR_DIF_DEBUG);

exit:
	return regval;
}

/**
 * Reads GRA internal register field value
 */
/*mirror register for DIF_CONF because it's often used*/
static unsigned int inr_dif_conf = 0x700;

static unsigned int gra_rdintfield(struct dcc_drvdata *p, unsigned int id)
{
	unsigned int ret;
	unsigned int regval;
	unsigned int dif_gracmd;
	unsigned int getregister;
	struct gra_command *cmd = &(gra_regs[id]);

	dif_gracmd = gra_rdextfield(p->reg.vbase, EXR_DIF_CSREG_GRACMD);

	/* check that it's possible to read into GRA internal registers */
	if (!(dif_gracmd)) {
		dcc_err("%s: %s: Read not allowed\n",
		     __func__, cmd->name);
		ret = -1;
		goto exit;
	}

	getregister = cmd->addr;
	gra_sendcmd(p, GRACMD_GET_REGISTER, 0, &getregister, 1);
	/* get the internal register value from the DEBUG register */
	gra_waitfor_external(p->reg.vbase, EXR_DIF_TXFFS_STAT, 0);
	regval = gra_rdextfield(p->reg.vbase, EXR_DIF_DEBUG);

	ret = (regval >> cmd->shift) & cmd->mask;

exit:
	return ret;
}

/**
 * Writes GRA internal registers
 */
static unsigned int gra_wrintfield(struct dcc_drvdata *p,
		unsigned int id,
		unsigned int value)
{
	int ret;
	unsigned int regval;
	unsigned int dif_gracmd;
	unsigned int setregister[2];
	struct gra_command *cmd = &(gra_regs[id]);

	dif_gracmd = gra_rdextfield(p->reg.vbase, EXR_DIF_CSREG_GRACMD);
	if (!dif_gracmd) {
		dcc_err("%s: Writing register(%s) not allowed\n",
		     __func__, cmd->name);
		ret = -1;
		goto exit;
	}

	setregister[0] = cmd->addr;
	if (cmd->mask != 0xFFFFFFFF) {
		if (cmd->addr == GRA_DIF_CONF) {
			regval = inr_dif_conf;
		} else {
			dcc_err("READ INTERNAL FIELD: %s\n", cmd->name);
			regval = gra_rdintreg(p, id);
		}

		setregister[1] =
		    ((value & cmd->
		      mask) << cmd->shift) | (regval & (~(cmd->mask << cmd->
							  shift)));
	} else {
		setregister[1] = value;
	}

	if (cmd->addr == GRA_DIF_CONF)
		inr_dif_conf = setregister[1];

	ret = gra_sendcmd(p, GRACMD_SET_REGISTER, 0, setregister, 2);
exit:
	return ret;
}

/**
 * Read GRA register
 */
int gra_read_field(struct dcc_drvdata *p,
		unsigned int id, unsigned int *reg_value)
{
	unsigned int retval = 0xDEADDEAD;
	struct gra_command *cmd = &(gra_regs[id]);

	if (cmd->type == CMD_TYPE_EXTREG) {
		retval = gra_rdextfield(p->reg.vbase, id);
	} else if (cmd->type == CMD_TYPE_INTREG) {
		retval = gra_rdintfield(p, id);
	} else {
		dcc_warn("%s, unknown register type (id=%x, type=%d\n",
			 __func__, id, cmd->type);
		goto error;
	}

	*reg_value = retval;
	return 0;
error:
	return -1;
}

/**
 * Write GRA register
 */
int gra_write_field(struct dcc_drvdata *p,
		unsigned int id,
		unsigned int val)
{
	int ret = 0;
	struct gra_command *cmd = &(gra_regs[id]);

	if ((id == EXR_DIF_ICR) ||
		(id == EXR_DIF_ERRIRQSC)) {
		DCC_DBG4("wr 0x%08x -> @0x%04x %s\n",
				val, cmd->addr, cmd->name);
	} else {
		DCC_DBG3("wr 0x%08x -> @0x%04x %s\n",
				val, cmd->addr, cmd->name);
	}

	if (cmd->type == CMD_TYPE_EXTREG) {
		ret = gra_wrextfield(p->reg.vbase, id, val);
	} else if (cmd->type == CMD_TYPE_INTREG) {
		ret = gra_wrintfield(p, id, val);
	} else {
		dcc_warn("%s, unknown register type (id=%x, type=%d\n",
			 __func__, id, cmd->type);
	}

	return ret;
}

/**
 * @brief Directly writes to hw (without using fifo)
 * @param data 32 bit data to write to hwfifo
 */
static inline void grac_wr_to_hwfifo(struct dcc_drvdata *pdata,
		unsigned int data)
{
	gra_wrextfield(pdata->reg.vbase, EXR_DIF_TXD, data);
}

#define CMD_INTERRUPT_ENABLE(_c_) (1)
unsigned long dccflags;
/**
 * Writes GRA internal registers
 *
 * Parameters must be serialized in *params from LSB to MSB,
 * and from first word to last word.
 */
int gra_sendcmd(struct dcc_drvdata *p, unsigned int opcode,
		bool iten, unsigned int *params, int nbparams)
{
	int ret = 0;
	int cmdbufwords = 0, i;
	unsigned int cmdbuf[CMD_MAX_WORDS];

	iten = 1;

	switch (opcode) {
	case GRACMD_RECT:	/* Draw rectangle */
		cmdbuf[0] =
		    COORDINATES(params[1], params[0]) | CMDHEADER(iten, opcode);
		cmdbuf[1] = COORDINATES(params[3], params[2]);
		cmdbufwords = 2;
		break;

	case GRACMD_LINE_TO:	/* Line to command opcode */
	case GRACMD_LINE_REL:	/* Line rel command opcode */
	case GRACMD_MOVE_TO:	/* Move to command opcode */
	case GRACMD_MOVE_REL:	/* Move rel command opcode */
	case GRACMD_SETPIXEL:	/* Set pixel command opcode */
		cmdbuf[0] =
		    COORDINATES(params[1], params[0]) | CMDHEADER(iten, opcode);
		cmdbufwords = 1;
		break;

	case GRACMD_BITBLT:	/* BitBlt command opcode */
		cmdbuf[0] =
		    COORDINATES(params[1], params[0]) | CMDHEADER(iten, opcode);
		cmdbuf[1] = COORDINATES(params[3], params[2]);
		cmdbuf[2] = (params[4] & 0x7);
		cmdbuf[3] = params[5];
		cmdbufwords = 4;
		break;

	case GRACMD_SCROLL_MOVE: /* Scroll move command opcode */
		cmdbuf[0] =
		    COORDINATES(params[1], params[0]) | CMDHEADER(iten, opcode);
		cmdbuf[1] = COORDINATES(params[3], params[2]);
		cmdbuf[2] = COORDINATES(params[5], params[4]);
		cmdbufwords = 3;
		break;

	case GRACMD_SET_BK_COLOR: /* Set background color command opcode */
	case GRACMD_SET_COLOR:	/* Set foreground color command opcode */
		cmdbuf[0] =
		    COLORRGB(params[2], params[1], params[0])
		    | CMDHEADER(iten, opcode);
		cmdbufwords = 1;
		break;

	case GRACMD_SET_LINESTYLE: /* Set line style command command opcode */
		cmdbuf[0] =
		    ((params[1] & 0x7FF) << 20) | ((params[0] & 0x3) << 8) |
		    CMDHEADER(iten, opcode);
		cmdbufwords = 1;
		break;

	case GRACMD_SET_ALPHA:	/* Set alpha channel command opcode */
		cmdbuf[0] = ((params[0] & 0xFF) << 8) | CMDHEADER(iten, opcode);
		cmdbufwords = 1;
		break;

	case GRACMD_SET_DRAWMODE:	/* Set draw mode command opcode */
		cmdbuf[0] = ((params[0] & 0x3) << 8) | CMDHEADER(iten, opcode);
		cmdbufwords = 1;
		break;

	case GRACMD_TRIANGLE:	/* Triangle command opcode */
		cmdbuf[0] = ((params[0] & 0x1) << 8)
		    | ((params[1] & 0x1) << 9)
		    | ((params[2] & 0x1) << 10)
		    | ((params[3] & 0x1) << 11)
		    | ((params[4] & 0x1) << 12)
		    | ((params[5] & 0x1) << 13)
		    | ((params[6] & 0x1) << 14)
		    | ((params[7] & 0x1) << 15)
		    | CMDHEADER(iten, opcode);
		cmdbuf[1] = TWO16BITS(params[9], params[8]);
		cmdbuf[2] = TWO16BITS(params[11], params[10]);
		cmdbuf[3] = TWO16BITS(params[13], params[12]);
		cmdbuf[4] =
		    COLORARGB(params[17], params[16], params[15], params[14]);
		cmdbuf[5] =
		    COLORARGB(params[21], params[20], params[19], params[18]);
		cmdbuf[6] =
		    COLORARGB(params[25], params[24], params[23], params[22]);
		cmdbuf[7] = TWO16BITS(params[27], params[26]);
		cmdbuf[8] = TWO16BITS(params[29], params[28]);
		cmdbuf[9] = TWO16BITS(params[31], params[30]);
		cmdbuf[10] =
		    ((params[34] & 0x1F) << 26) | ((params[33] & 0x3F) << 20) |
		    (params[32] & 0x7FFFF);
		cmdbuf[11] =
		    ((params[36] & 0xFF) << 20) | (params[35] & 0x7FFFF);
		cmdbuf[12] =
		    ((params[38] & 0xFF) << 20) | (params[37] & 0x7FFFF);
		cmdbuf[13] =
		    ((params[40] & 0xFF) << 20) | (params[39] & 0x7FFFF);
		cmdbuf[14] =
		    ((params[42] & 0xFF) << 20) | (params[41] & 0x7FFFF);
		cmdbuf[15] = (params[43] & 0x7FFFF);
		cmdbuf[16] = (params[44] /*&0x1FFFFFFF */);
		cmdbufwords = 17;
		break;

	case GRACMD_BITBLT2: /* BitBlt2 command opcode */
		cmdbuf[0] =
		    COORDINATES(params[1], params[0]) | CMDHEADER(iten, opcode);
		cmdbuf[1] = COORDINATES(params[3], params[2]);
		cmdbuf[2] = (params[4] & 0x1)
		    | ((params[5] & 0x1) << 1)
		    | ((params[6] & 0x1) << 2)
		    | ((params[7] & 0x3FF) << 8);
		cmdbuf[3] = (params[8] /*&0x7FFFFFFF */);
		cmdbufwords = 4;
		break;

	case GRACMD_UPDATE: /* Update command opcode */
	case GRACMD_START_UPDATE: /* Start update command opcode */
		cmdbuf[0] = ((params[0] & 0xFF) << 8) | CMDHEADER(iten, opcode);
		cmdbuf[1] = COORDINATES(params[2], params[1]);
		cmdbuf[2] = COORDINATES(params[4], params[3]);
		cmdbufwords = 3;
		break;

	case GRACMD_ROTATE_IMAGE: /* Rotate image command opcode */
		cmdbuf[0] = CMDHEADER(iten, opcode);
		cmdbuf[1] = (params[0] /*&0x7FFFFFFF */);
		cmdbuf[2] = (params[1] /*&0x7FFFFFFF */);
		cmdbufwords = 3;
		break;

	case GRACMD_DRAW_IMAGE:	/* Draw image command opcode */
		cmdbuf[0] = ((params[0] & 0xFF) << 8) | CMDHEADER(iten, opcode);
		cmdbuf[1] = COORDINATES(params[2], params[1]);
		cmdbuf[2] = COORDINATES(params[4], params[3]);
		cmdbuf[3] = (params[5] /*&0x7FFFFFFF */);
		cmdbufwords = 4;
		break;

	case GRACMD_INTERRUPT: /* Command interrupt command opcode */
		cmdbuf[0] = (opcode & 0xF);
		cmdbufwords = 1;
		break;

	case GRACMD_SCHEDULE_UPDATE: /* Schedule update command opcode */
		cmdbuf[0] =
		    ((!!params[6]) << 19) |
		    ((params[1] & 0x7) << 16) |
		    ((params[0] & 0xFF) << 8) |
		    CMDHEADER(iten, opcode);
		cmdbuf[1] = COORDINATES(params[3], params[2]);
		cmdbuf[2] = COORDINATES(params[5], params[4]);
		if (params[6]) {
			cmdbuf[3] = params[6];
			cmdbufwords = 4;
		} else
			cmdbufwords = 3;
		break;

	case GRACMD_SWITCH_UPDATE: /* Switch update command opcode */
		cmdbuf[0] =
		    ((params[1] & 0x7) << 16) | ((params[0] & 0xFF) << 8) |
		    CMDHEADER(iten, opcode);
		cmdbufwords = 1;
		break;

	case GRACMD_GET_REGISTER: /* Get internal register command opcode */
		cmdbuf[0] = ((params[0] & 0x3F) << 8) | CMDHEADER(iten, opcode);
		cmdbufwords = 1;
		break;

	case GRACMD_SET_REGISTER: /* Set internal register command opcode */
		iten = 0;
		cmdbuf[0] = ((params[0] & 0x3F) << 8) | CMDHEADER(iten, opcode);
		cmdbuf[1] = params[1];
		cmdbufwords = 2;
		break;

	default:
		dcc_err("%s: unknown command 0x%x\n", __func__, opcode);
		ret = -1;
		return ret;
	}

	{
		struct timeval begin;
		long long diffus = 0;
		unsigned txffs, tries = 0xFFFFFF;
		measdelay_start(&begin);
		gra_read_field(p, EXR_DIF_TXFFS_STAT, &txffs);

		while (txffs && tries) {
			DCC_DBG3("wait empty fifo (%d)\n", txffs);
			gra_read_field(p, EXR_DIF_TXFFS_STAT, &txffs);
			tries--;
		}
		if (!tries) {
			diffus = measdelay_stop(NULL, &begin);
			DCC_DBG1("fifo stucked for %lli usec (%d stages)\n",
					diffus, txffs);
			BUG();
		}
	}

	if ((opcode != GRACMD_SET_REGISTER)
		&& (opcode != GRACMD_GET_REGISTER))
		DCC_DBG3("send cmd : 0x%08x\n", cmdbuf[0])
	else
		DCC_DBG4("send cmd : 0x%08x\n", cmdbuf[0]);

	grac_wr_to_hwfifo(p, cmdbuf[0]);

	for (i = 1; i < cmdbufwords; i++) {
		if ((opcode != GRACMD_SET_REGISTER)
		    && (opcode != GRACMD_GET_REGISTER)) {
			DCC_DBG3("           0x%08x\n", cmdbuf[i]);
		} else {
		DCC_DBG4("           0x%08x\n", cmdbuf[i]);
		}

		grac_wr_to_hwfifo(p, cmdbuf[i]);
	}

#ifndef DCC_HW_STUB
	if (iten) {
		DCC_DBG4("wait for cmd 0x%x irq\n", opcode);
		ret = dcc_completion_timeout_ms(&p->sync.eoc,
				p->sync.eoc_to);
		if (!ret) {
			unsigned int stat, txffs;
			gra_read_field(p, EXR_DIF_STAT, &stat);
			gra_read_field(p, EXR_DIF_TXFFS_STAT, &txffs);
			dcc_warn("cmd 0x%x irq timedout %dms STAT:0x%08x TXFFS:0x%08x\n",
				opcode, p->sync.eoc_to, stat, txffs);
			if (opcode == 0x10) {
				dcc_warn("SOFT RESET\n");
				gra_write_field(p, EXR_DIF_RUNCTRL,
						DCC_MODE_CONF);
				udelay(100);
				gra_write_field(p, EXR_DIF_RUNCTRL,
						DCC_MODE_RUN);
			}
		} else {
			DCC_DBG4("cmd irq received\n");
		}
	}
#endif

	return ret;
}

#ifdef DCC_HW_STUB
unsigned int dcc_reg_stub[(GRA_DIF_RXD>>2)];
#endif


