obj-$(CONFIG_X86_INTEL_SOFIA) += vmm_pmic.o vmm_pmic-ext.o
obj-$(CONFIG_X86_INTEL_SOFIA) += mv_hypercalls.o
obj-$(CONFIG_X86_INTEL_SOFIA) += mv_svc_hypercalls.o
obj-$(CONFIG_X86_INTEL_SOFIA) += mv_gal.o
obj-$(CONFIG_X86_INTEL_SOFIA) += mv_ipc.o
obj-$(CONFIG_X86_INTEL_SOFIA) += reboot.o
obj-$(CONFIG_X86_INTEL_SOFIA) += cpu.o
