obj-$(CONFIG_X86_INTEL_SOFIA) += vmm_guest_api.o
obj-$(CONFIG_X86_INTEL_SOFIA) += vmm_al.o
obj-$(CONFIG_X86_INTEL_SOFIA) += vmm_pmic.o vmm_pmic-ext.o
obj-$(CONFIG_X86_INTEL_SOFIA) += nk_sofia_bridge.o
obj-$(CONFIG_X86_INTEL_SOFIA) += reboot.o
obj-$(CONFIG_X86_INTEL_SOFIA) += pal_platform_service.o
