#ifndef I2C_XGOLD
#define I2C_XGOLD


#define i2c_warn(fmt, arg...)  \
	pr_warn("I2C: " fmt, ##arg);

#define i2c_debug(data, fmt, arg...) \
{ \
	if (data->debug) \
		pr_debug("I2C: " fmt, ##arg); \
}

#define i2c_info(fmt, arg...) \
	pr_info("I2C: " fmt, ##arg);

#define i2c_err(fmt, arg...) \
	pr_err("I2C: " fmt, ##arg);

/* FIXME hardcoded FDIV values */
#define XGOLD_I2C_FDIV_B100		0x20020
#define XGOLD_I2C_FDIV_B400		0x20008

/* Interrupts masks */
#define XGOLD_I2C_IMSC_LSREQ_BIT	0x01
#define XGOLD_I2C_IMSC_SREQ_BIT		0x02
#define XGOLD_I2C_IMSC_LBREQ_BIT	0x04
#define XGOLD_I2C_IMSC_BREQ_BIT		0x08
#define XGOLD_I2C_IMSC_ERR_BIT		0x10
#define XGOLD_I2C_IMSC_P_BIT		0x20
#define XGOLD_I2C_IMSC_MASK		0x3F

/* Error interrupts maks */
#define XGOLD_I2C_ERR_MASK		0x0F

/* Protocol interrupts masks */
#define XGOLD_I2C_P_AM_BIT		0x1
#define XGOLD_I2C_P_GC_BIT		0x2
#define XGOLD_I2C_P_MC_BIT		0x4
#define XGOLD_I2C_P_AL_BIT		0x8
#define XGOLD_I2C_P_NACK_BIT		0x10
#define XGOLD_I2C_P_TX_END_BIT		0x20
#define XGOLD_I2C_P_RX_BIT		0x40

#define XGOLD_I2C_P_MASK		0x3F
#define XGOLD_I2C_P_MASK_ALL		(XGOLD_I2C_P_MASK)


/* Unsefull mask */
#define XGOLD_I2C_DMAE_DISABLE			0x0
#define XGOLD_I2C_DMAE_ENABLE			0xF
#define XGOLD_I2C_FDIV_HIGH_CFG_DISABLE		0x0

/* FIFO depth */
#define XGOLD_I2C_FIFO_DEPTH		8

/* change default baud rate of i2c bus */
#define I2C_XGOLD_BAUD        0x0730

/* set baud rate of i2c bus to be used for this client only. */
#define I2C_XGOLD_BAUD_CLIENT 0x0731

/* set clients priority */
#define I2C_XGOLD_PRIORITY    0x0732

/* xgold i2c flags */
#define XGOLD_I2C_M_NORESTART	0x20	/* don't send RESTART between xfers */
#define XGOLD_I2C_M_B100	0x40	/* baud rate 100kHz (400kHz dafault) */
#define XGOLD_I2C_M_DMA_TX	0x2	/* client requires a dma I2C TX xfer */
#define XGOLD_I2C_M_DMA_RX	0x4	/* client requires a dma I2C RX xfer */

#define I2C_MSG_NORESTART(_f_)	(0 != (_f_ & XGOLD_I2C_M_NORESTART))
#define I2C_MSG_B400(_f_)	(0 == (_f_ & XGOLD_I2C_M_B100))
#define I2C_MSG_B100(_f_)	(XGOLD_I2C_M_B100 == \
					(_f_ & XGOLD_I2C_M_B100))
#define I2C_MSG_DMA_WR(_f_)	(XGOLD_I2C_M_DMA_TX == \
					(_f_ & XGOLD_I2C_M_DMA_TX))
#define I2C_MSG_DMA_RD(_f_)	(XGOLD_I2C_M_DMA_RX == \
					(_f_ & XGOLD_I2C_M_DMA_RX))

enum xgold_i2c_bus_state {
	XGOLD_I2C_BUS_FREE = 0,
	XGOLD_I2C_BUS_BUSY,
	XGOLD_I2C_BUS_BUSY_MASTER,
	XGOLD_I2C_BUS_BUSY_SLAVE,
};

enum xgold_i2c_baud {
	I2C_XGOLD_B100 = 0,
	I2C_XGOLD_B400,
};

struct xgold_i2c_ops {
	int (*probe)(struct device *);
	int (*remove)(struct device *);
};

struct xgold_i2c_dev;

struct xgold_i2c_algo_data {
	void __iomem *regs;
	struct i2c_msg *msg;
	int state;
	wait_queue_head_t cmd_wait;
	unsigned char addr_sent;
	struct completion cmd_complete;
	int cmd_err;
	int timeout;
	unsigned int default_baud;
	unsigned int current_baud;
	spinlock_t lock;
	struct xgold_i2c_dev *i2c_dev;
	struct platform_device *platform_dev;
	/* local parameters */
	u8 *buf;
	int buf_len;
	u16 addr;
	unsigned flags;
	bool debug;
	/* DMA */
	dma_addr_t regs_phys;
	bool dma_mode;
	struct dma_chan *dmach;
	unsigned char *dma_buf;
	int dma_buf_len;
	struct scatterlist sg_io;
	dma_cookie_t dma_cookie;
};

struct xgold_i2c_dev {
	struct device *dev;
	struct i2c_adapter adapter;
	struct xgold_i2c_algo_data algo_data;
	struct xgold_i2c_ops *core_ops;
	const struct dev_pm_ops *pm_ops;
};

struct xgold_i2c_dev *xgold_i2c_init_driver(struct device *);

/* --------------------------------------------------------
		I2C Register definitions
---------------------------------------------------------*/

/* Registers definition */
#define I2C_CLC_OFFSET	  0x0
	#define I2C_CLC_ORMC_OFFSET 0x10
	#define I2C_CLC_ORMC_WIDTH 0x8
	#define I2C_CLC_ORMC_MASK 0xff0000
	#define I2C_CLC_RMC_OFFSET 0x8
	#define I2C_CLC_RMC_WIDTH 0x8
	#define I2C_CLC_RMC_MASK 0xff00
	#define I2C_CLC_FSOE_OFFSET 0x5
	#define I2C_CLC_FSOE_WIDTH 0x1
	#define I2C_CLC_FSOE_MASK 0x20
		#define I2C_CLC_FSOE (1 << I2C_CLC_FSOE_OFFSET)
		#define I2C_CLC_FSOE_FSOE_DIS (0x0 << I2C_CLC_FSOE_OFFSET)
		#define I2C_CLC_FSOE_FSOE_EN (0x1 << I2C_CLC_FSOE_OFFSET)
	#define I2C_CLC_SBWE_OFFSET 0x4
	#define I2C_CLC_SBWE_WIDTH 0x1
	#define I2C_CLC_SBWE_MASK 0x10
		#define I2C_CLC_SBWE (1 << I2C_CLC_SBWE_OFFSET)
		#define I2C_CLC_SBWE_SBWE_DIS (0x0 << I2C_CLC_SBWE_OFFSET)
		#define I2C_CLC_SBWE_SBWE_EN (0x1 << I2C_CLC_SBWE_OFFSET)
	#define I2C_CLC_EDIS_OFFSET 0x3
	#define I2C_CLC_EDIS_WIDTH 0x1
	#define I2C_CLC_EDIS_MASK 0x8
		#define I2C_CLC_EDIS (1 << I2C_CLC_EDIS_OFFSET)
		#define I2C_CLC_EDIS_EDIS_EN (0x0 << I2C_CLC_EDIS_OFFSET)
		#define I2C_CLC_EDIS_EDIS_DIS (0x1 << I2C_CLC_EDIS_OFFSET)
	#define I2C_CLC_SPEN_OFFSET 0x2
	#define I2C_CLC_SPEN_WIDTH 0x1
	#define I2C_CLC_SPEN_MASK 0x4
		#define I2C_CLC_SPEN (1 << I2C_CLC_SPEN_OFFSET)
		#define I2C_CLC_SPEN_SPEN_DIS (0x0 << I2C_CLC_SPEN_OFFSET)
		#define I2C_CLC_SPEN_SPEN_EN (0x1 << I2C_CLC_SPEN_OFFSET)
	#define I2C_CLC_DISS_OFFSET 0x1
	#define I2C_CLC_DISS_WIDTH 0x1
	#define I2C_CLC_DISS_MASK 0x2
		#define I2C_CLC_DISS (1 << I2C_CLC_DISS_OFFSET)
		#define I2C_CLC_DISS_DISS_EN (0x0 << I2C_CLC_DISS_OFFSET)
		#define I2C_CLC_DISS_DISS_DIS (0x1 << I2C_CLC_DISS_OFFSET)
	#define I2C_CLC_DISR_OFFSET 0x0
	#define I2C_CLC_DISR_WIDTH 0x1
	#define I2C_CLC_DISR_MASK 0x1
		#define I2C_CLC_DISR (1 << I2C_CLC_DISR_OFFSET)
		#define I2C_CLC_DISR_DISR_OFF (0x0 << I2C_CLC_DISR_OFFSET)
		#define I2C_CLC_DISR_DISR_ON (0x1 << I2C_CLC_DISR_OFFSET)

#define I2C_ID_OFFSET	  0x8
	#define I2C_ID_MOD_ID_OFFSET 0x8
	#define I2C_ID_MOD_ID_WIDTH 0x8
	#define I2C_ID_MOD_ID_MASK 0xff00
	#define I2C_ID_REV_ID_OFFSET 0x0
	#define I2C_ID_REV_ID_WIDTH 0x8
	#define I2C_ID_REV_ID_MASK 0xff

#define I2C_RUN_CTRL_OFFSET	  0x10
	#define I2C_RUN_CTRL_RUN_OFFSET 0x0
	#define I2C_RUN_CTRL_RUN_WIDTH 0x1
	#define I2C_RUN_CTRL_RUN_MASK 0x1
		#define I2C_RUN_CTRL_RUN (1 << I2C_RUN_CTRL_RUN_OFFSET)
		#define I2C_RUN_CTRL_RUN_DIS (0x0 << I2C_RUN_CTRL_RUN_OFFSET)
		#define I2C_RUN_CTRL_RUN_EN (0x1 << I2C_RUN_CTRL_RUN_OFFSET)

#define I2C_ENDD_CTRL_OFFSET	  0x14
	#define I2C_ENDD_CTRL_SETEND_OFFSET 0x1
	#define I2C_ENDD_CTRL_SETEND_WIDTH 0x1
	#define I2C_ENDD_CTRL_SETEND_MASK 0x2
		#define I2C_ENDD_CTRL_SETEND (1 << I2C_ENDD_CTRL_SETEND_OFFSET)
		#define I2C_ENDD_CTRL_SETEND_SET \
			(0x1 << I2C_ENDD_CTRL_SETEND_OFFSET)
		#define I2C_ENDD_CTRL_SETEND_UNSET \
			(0x0 << I2C_ENDD_CTRL_SETEND_OFFSET)
	#define I2C_ENDD_CTRL_SETRSC_OFFSET 0x0
	#define I2C_ENDD_CTRL_SETRSC_WIDTH 0x1
	#define I2C_ENDD_CTRL_SETRSC_MASK 0x1
		#define I2C_ENDD_CTRL_SETRSC (1 << I2C_ENDD_CTRL_SETRSC_OFFSET)
		#define I2C_ENDD_CTRL_SETRSC_RSC \
			(0x1 << I2C_ENDD_CTRL_SETRSC_OFFSET)
		#define I2C_ENDD_CTRL_SETRSC_NORSC \
			(0x0 << I2C_ENDD_CTRL_SETRSC_OFFSET)

#define I2C_FDIV_CFG_OFFSET	  0x18
	#define I2C_FDIV_CFG_INC_OFFSET 0x10
	#define I2C_FDIV_CFG_INC_WIDTH 0x8
	#define I2C_FDIV_CFG_INC_MASK 0xff0000
	#define I2C_FDIV_CFG_DEC_OFFSET 0x0
	#define I2C_FDIV_CFG_DEC_WIDTH 0xb
	#define I2C_FDIV_CFG_DEC_MASK 0x7ff

#define I2C_FDIV_HIGH_CFG_OFFSET	  0x1c
	#define I2C_FDIV_HIGH_CFG_RES_DIS_SCL_SYN_OFFSET 0x1f
	#define I2C_FDIV_HIGH_CFG_RES_DIS_SCL_SYN_WIDTH 0x1
	#define I2C_FDIV_HIGH_CFG_RES_DIS_SCL_SYN_MASK 0x80000000
		#define I2C_FDIV_HIGH_CFG_RES_DIS_SCL_SYN \
			(1 << I2C_FDIV_HIGH_CFG_RES_DIS_SCL_SYN_OFFSET)
	#define I2C_FDIV_HIGH_CFG_INC_OFFSET 0x10
	#define I2C_FDIV_HIGH_CFG_INC_WIDTH 0x8
	#define I2C_FDIV_HIGH_CFG_INC_MASK 0xff0000
	#define I2C_FDIV_HIGH_CFG_DEC_OFFSET 0x0
	#define I2C_FDIV_HIGH_CFG_DEC_WIDTH 0xb
	#define I2C_FDIV_HIGH_CFG_DEC_MASK 0x7ff

#define I2C_ADDR_CFG_OFFSET	  0x20
	#define I2C_ADDR_CFG_SOPE_OFFSET 0x15
	#define I2C_ADDR_CFG_SOPE_WIDTH 0x1
	#define I2C_ADDR_CFG_SOPE_MASK 0x200000
		#define I2C_ADDR_CFG_SOPE (1 << I2C_ADDR_CFG_SOPE_OFFSET)
		#define I2C_ADDR_CFG_SOPE_DIS \
			(0x0 << I2C_ADDR_CFG_SOPE_OFFSET)
		#define I2C_ADDR_CFG_SOPE_EN \
			(0x1 << I2C_ADDR_CFG_SOPE_OFFSET)
	#define I2C_ADDR_CFG_SONA_OFFSET 0x14
	#define I2C_ADDR_CFG_SONA_WIDTH 0x1
	#define I2C_ADDR_CFG_SONA_MASK 0x100000
		#define I2C_ADDR_CFG_SONA (1 << I2C_ADDR_CFG_SONA_OFFSET)
		#define I2C_ADDR_CFG_SONA_DIS \
			(0x0 << I2C_ADDR_CFG_SONA_OFFSET)
		#define I2C_ADDR_CFG_SONA_EN \
			(0x1 << I2C_ADDR_CFG_SONA_OFFSET)
	#define I2C_ADDR_CFG_MNS_OFFSET 0x13
	#define I2C_ADDR_CFG_MNS_WIDTH 0x1
	#define I2C_ADDR_CFG_MNS_MASK 0x80000
		#define I2C_ADDR_CFG_MNS (1 << I2C_ADDR_CFG_MNS_OFFSET)
		#define I2C_ADDR_CFG_MNS_DIS (0x0 << I2C_ADDR_CFG_MNS_OFFSET)
		#define I2C_ADDR_CFG_MNS_EN (0x1 << I2C_ADDR_CFG_MNS_OFFSET)
	#define I2C_ADDR_CFG_MCE_OFFSET 0x12
	#define I2C_ADDR_CFG_MCE_WIDTH 0x1
	#define I2C_ADDR_CFG_MCE_MASK 0x40000
		#define I2C_ADDR_CFG_MCE (1 << I2C_ADDR_CFG_MCE_OFFSET)
		#define I2C_ADDR_CFG_MCE_DIS (0x0 << I2C_ADDR_CFG_MCE_OFFSET)
		#define I2C_ADDR_CFG_MCE_EN (0x1 << I2C_ADDR_CFG_MCE_OFFSET)
	#define I2C_ADDR_CFG_GCE_OFFSET 0x11
	#define I2C_ADDR_CFG_GCE_WIDTH 0x1
	#define I2C_ADDR_CFG_GCE_MASK 0x20000
		#define I2C_ADDR_CFG_GCE (1 << I2C_ADDR_CFG_GCE_OFFSET)
		#define I2C_ADDR_CFG_GCE_DIS (0x0 << I2C_ADDR_CFG_GCE_OFFSET)
		#define I2C_ADDR_CFG_GCE_EN (0x1 << I2C_ADDR_CFG_GCE_OFFSET)
	#define I2C_ADDR_CFG_TBAM_OFFSET 0x10
	#define I2C_ADDR_CFG_TBAM_WIDTH 0x1
	#define I2C_ADDR_CFG_TBAM_MASK 0x10000
		#define I2C_ADDR_CFG_TBAM (1 << I2C_ADDR_CFG_TBAM_OFFSET)
		#define I2C_ADDR_CFG_TBAM_AM7 \
			(0x0 << I2C_ADDR_CFG_TBAM_OFFSET)
		#define I2C_ADDR_CFG_TBAM_AM10 \
			(0x1 << I2C_ADDR_CFG_TBAM_OFFSET)
	#define I2C_ADDR_CFG_ADR_OFFSET 0x0
	#define I2C_ADDR_CFG_ADR_WIDTH 0xa
	#define I2C_ADDR_CFG_ADR_MASK 0x3ff

#define I2C_BUS_STAT_OFFSET	  0x24
	#define I2C_BUS_STAT_RNW_OFFSET 0x2
	#define I2C_BUS_STAT_RNW_WIDTH 0x1
	#define I2C_BUS_STAT_RNW_MASK 0x4
		#define I2C_BUS_STAT_RNW (1 << I2C_BUS_STAT_RNW_OFFSET)
		#define I2C_BUS_STAT_RNW_WRITE \
			(0x0 << I2C_BUS_STAT_RNW_OFFSET)
		#define I2C_BUS_STAT_RNW_READ \
			(0x1 << I2C_BUS_STAT_RNW_OFFSET)
	#define I2C_BUS_STAT_BS_OFFSET 0x0
	#define I2C_BUS_STAT_BS_WIDTH 0x2
	#define I2C_BUS_STAT_BS_MASK 0x3

#define I2C_TIM_CFG_OFFSET	  0x40
	#define I2C_TIM_CFG_HS_SDA_DEL_OFFSET 0x10
	#define I2C_TIM_CFG_HS_SDA_DEL_WIDTH 0x3
	#define I2C_TIM_CFG_HS_SDA_DEL_MASK 0x70000
		#define I2C_TIM_CFG_HS_SDA_DEL_D3 \
			(0x0 << I2C_TIM_CFG_HS_SDA_DEL_OFFSET)
		#define I2C_TIM_CFG_HS_SDA_DEL_D4 \
			(0x1 << I2C_TIM_CFG_HS_SDA_DEL_OFFSET)
		#define I2C_TIM_CFG_HS_SDA_DEL_D10 \
			(0x7 << I2C_TIM_CFG_HS_SDA_DEL_OFFSET)
	#define I2C_TIM_CFG_FS_SCL_LOW_OFFSET 0xf
	#define I2C_TIM_CFG_FS_SCL_LOW_WIDTH 0x1
	#define I2C_TIM_CFG_FS_SCL_LOW_MASK 0x8000
		#define I2C_TIM_CFG_FS_SCL_LOW \
			(1 << I2C_TIM_CFG_FS_SCL_LOW_OFFSET)
		#define I2C_TIM_CFG_FS_SCL_LOW_DIS \
			(0x0 << I2C_TIM_CFG_FS_SCL_LOW_OFFSET)
		#define I2C_TIM_CFG_FS_SCL_LOW_EN \
			(0x1 << I2C_TIM_CFG_FS_SCL_LOW_OFFSET)
	#define I2C_TIM_CFG_SCL_DEL_HD_STA_OFFSET 0x9
	#define I2C_TIM_CFG_SCL_DEL_HD_STA_WIDTH 0x3
	#define I2C_TIM_CFG_SCL_DEL_HD_STA_MASK 0xe00
		#define I2C_TIM_CFG_SCL_DEL_HD_STA_D2 \
			(0x0 << I2C_TIM_CFG_SCL_DEL_HD_STA_OFFSET)
		#define I2C_TIM_CFG_SCL_DEL_HD_STA_D3 \
			(0x1 << I2C_TIM_CFG_SCL_DEL_HD_STA_OFFSET)
		#define I2C_TIM_CFG_SCL_DEL_HD_STA_D9 \
			(0x7 << I2C_TIM_CFG_SCL_DEL_HD_STA_OFFSET)
	#define I2C_TIM_CFG_HS_SDA_DEL_HD_DAT_OFFSET 0x6
	#define I2C_TIM_CFG_HS_SDA_DEL_HD_DAT_WIDTH 0x3
	#define I2C_TIM_CFG_HS_SDA_DEL_HD_DAT_MASK 0x1c0
		#define I2C_TIM_CFG_HS_SDA_DEL_HD_DAT_D3 \
			(0x0 << I2C_TIM_CFG_HS_SDA_DEL_HD_DAT_OFFSET)
		#define I2C_TIM_CFG_HS_SDA_DEL_HD_DAT_D4 \
			(0x1 << I2C_TIM_CFG_HS_SDA_DEL_HD_DAT_OFFSET)
		#define I2C_TIM_CFG_HS_SDA_DEL_HD_DAT_D10 \
			(0x7 << I2C_TIM_CFG_HS_SDA_DEL_HD_DAT_OFFSET)
	#define I2C_TIM_CFG_SDA_DEL_HD_DAT_OFFSET 0x0
	#define I2C_TIM_CFG_SDA_DEL_HD_DAT_WIDTH 0x6
	#define I2C_TIM_CFG_SDA_DEL_HD_DAT_MASK 0x3f
		#define I2C_TIM_CFG_SDA_DEL_HD_DAT_D3 \
			(0x0 << I2C_TIM_CFG_SDA_DEL_HD_DAT_OFFSET)
		#define I2C_TIM_CFG_SDA_DEL_HD_DAT_D4 \
			(0x1 << I2C_TIM_CFG_SDA_DEL_HD_DAT_OFFSET)
		#define I2C_TIM_CFG_SDA_DEL_HD_DAT_D66 \
			(0x3f << I2C_TIM_CFG_SDA_DEL_HD_DAT_OFFSET)

#define I2C_FIFO_CFG_OFFSET	  0x28
	#define I2C_FIFO_CFG_TXFC_OFFSET 0x11
	#define I2C_FIFO_CFG_TXFC_WIDTH 0x1
	#define I2C_FIFO_CFG_TXFC_MASK 0x20000
		#define I2C_FIFO_CFG_TXFC \
			(1 << I2C_FIFO_CFG_TXFC_OFFSET)
		#define I2C_FIFO_CFG_TXFC_TXNFC \
			(0x0 << I2C_FIFO_CFG_TXFC_OFFSET)
		#define I2C_FIFO_CFG_TXFC_TXFC \
			(0x1 << I2C_FIFO_CFG_TXFC_OFFSET)
	#define I2C_FIFO_CFG_RXFC_OFFSET 0x10
	#define I2C_FIFO_CFG_RXFC_WIDTH 0x1
	#define I2C_FIFO_CFG_RXFC_MASK 0x10000
		#define I2C_FIFO_CFG_RXFC (1 << I2C_FIFO_CFG_RXFC_OFFSET)
		#define I2C_FIFO_CFG_RXFC_RXNFC \
			(0x0 << I2C_FIFO_CFG_RXFC_OFFSET)
		#define I2C_FIFO_CFG_RXFC_RXFC \
			(0x1 << I2C_FIFO_CFG_RXFC_OFFSET)
	#define I2C_FIFO_CFG_TXFA_OFFSET 0xc
	#define I2C_FIFO_CFG_TXFA_WIDTH 0x2
	#define I2C_FIFO_CFG_TXFA_MASK 0x3000
		#define I2C_FIFO_CFG_TXFA_TXFA1 \
			(0x0 << I2C_FIFO_CFG_TXFA_OFFSET)
		#define I2C_FIFO_CFG_TXFA_TXFA2 \
			(0x1 << I2C_FIFO_CFG_TXFA_OFFSET)
		#define I2C_FIFO_CFG_TXFA_TXFA4 \
			(0x2 << I2C_FIFO_CFG_TXFA_OFFSET)
		#define I2C_FIFO_CFG_TXFA_TXFA8 \
			(0x3 << I2C_FIFO_CFG_TXFA_OFFSET)
	#define I2C_FIFO_CFG_RXFA_OFFSET 0x8
	#define I2C_FIFO_CFG_RXFA_WIDTH 0x2
	#define I2C_FIFO_CFG_RXFA_MASK 0x300
		#define I2C_FIFO_CFG_RXFA_RXFA1 \
			(0x0 << I2C_FIFO_CFG_RXFA_OFFSET)
		#define I2C_FIFO_CFG_RXFA_RXFA2 \
			(0x1 << I2C_FIFO_CFG_RXFA_OFFSET)
		#define I2C_FIFO_CFG_RXFA_RXFA4 \
			(0x2 << I2C_FIFO_CFG_RXFA_OFFSET)
		#define I2C_FIFO_CFG_RXFA_RXFA8 \
			(0x3 << I2C_FIFO_CFG_RXFA_OFFSET)
	#define I2C_FIFO_CFG_TXBS_OFFSET 0x4
	#define I2C_FIFO_CFG_TXBS_WIDTH 0x2
	#define I2C_FIFO_CFG_TXBS_MASK 0x30
		#define I2C_FIFO_CFG_TXBS_TXBS1 \
			(0x0 << I2C_FIFO_CFG_TXBS_OFFSET)
		#define I2C_FIFO_CFG_TXBS_TXBS2 \
			(0x1 << I2C_FIFO_CFG_TXBS_OFFSET)
		#define I2C_FIFO_CFG_TXBS_TXBS4 \
			(0x2 << I2C_FIFO_CFG_TXBS_OFFSET)
		#define I2C_FIFO_CFG_TXBS_TXBS8 \
			(0x3 << I2C_FIFO_CFG_TXBS_OFFSET)
	#define I2C_FIFO_CFG_RXBS_OFFSET 0x0
	#define I2C_FIFO_CFG_RXBS_WIDTH 0x2
	#define I2C_FIFO_CFG_RXBS_MASK 0x3
		#define I2C_FIFO_CFG_RXBS_RXBS1 \
			(0x0 << I2C_FIFO_CFG_RXBS_OFFSET)
		#define I2C_FIFO_CFG_RXBS_RXBS2 \
			(0x1 << I2C_FIFO_CFG_RXBS_OFFSET)
		#define I2C_FIFO_CFG_RXBS_RXBS4 \
			(0x2 << I2C_FIFO_CFG_RXBS_OFFSET)
		#define I2C_FIFO_CFG_RXBS_RXBS8 \
			(0x3 << I2C_FIFO_CFG_RXBS_OFFSET)

#define I2C_MRPS_CTRL_OFFSET	  0x2c
	#define I2C_MRPS_CTRL_MRPS_OFFSET 0x0
	#define I2C_MRPS_CTRL_MRPS_WIDTH 0xe
	#define I2C_MRPS_CTRL_MRPS_MASK 0x3fff

#define I2C_RPS_STAT_OFFSET	  0x30
	#define I2C_RPS_STAT_RPS_OFFSET 0x0
	#define I2C_RPS_STAT_RPS_WIDTH 0xe
	#define I2C_RPS_STAT_RPS_MASK 0x3fff

#define I2C_TPS_CTRL_OFFSET	  0x34
	#define I2C_TPS_CTRL_TPS_OFFSET 0x0
	#define I2C_TPS_CTRL_TPS_WIDTH 0xe
	#define I2C_TPS_CTRL_TPS_MASK 0x3fff

#define I2C_FFS_STAT_OFFSET	  0x38
	#define I2C_FFS_STAT_FFS_OFFSET 0x0
	#define I2C_FFS_STAT_FFS_WIDTH 0x4
	#define I2C_FFS_STAT_FFS_MASK 0xf

#define I2C_TXD_OFFSET	  0x8000
	#define I2C_TXD_TXD_OFFSET 0x0
	#define I2C_TXD_TXD_WIDTH 0x20
	#define I2C_TXD_TXD_MASK 0xffffffff

#define I2C_RXD_OFFSET	  0xc000
	#define I2C_RXD_RXD_OFFSET 0x0
	#define I2C_RXD_RXD_WIDTH 0x20
	#define I2C_RXD_RXD_MASK 0xffffffff

#define I2C_RIS_OFFSET	  0x80
	#define I2C_RIS_I2C_P_INT_OFFSET 0x5
	#define I2C_RIS_I2C_P_INT_WIDTH 0x1
	#define I2C_RIS_I2C_P_INT_MASK 0x20
		#define I2C_RIS_I2C_P_INT (1 << I2C_RIS_I2C_P_INT_OFFSET)
		#define I2C_RIS_I2C_P_INT_NO_INT \
			(0x0 << I2C_RIS_I2C_P_INT_OFFSET)
		#define I2C_RIS_I2C_P_INT_INT_PEND \
			(0x1 << I2C_RIS_I2C_P_INT_OFFSET)
	#define I2C_RIS_I2C_ERR_INT_OFFSET 0x4
	#define I2C_RIS_I2C_ERR_INT_WIDTH 0x1
	#define I2C_RIS_I2C_ERR_INT_MASK 0x10
		#define I2C_RIS_I2C_ERR_INT (1 << I2C_RIS_I2C_ERR_INT_OFFSET)
		#define I2C_RIS_I2C_ERR_INT_NO_INT \
			(0x0 << I2C_RIS_I2C_ERR_INT_OFFSET)
		#define I2C_RIS_I2C_ERR_INT_INT_PEND \
			(0x1 << I2C_RIS_I2C_ERR_INT_OFFSET)
	#define I2C_RIS_BREQ_INT_OFFSET 0x3
	#define I2C_RIS_BREQ_INT_WIDTH 0x1
	#define I2C_RIS_BREQ_INT_MASK 0x8
		#define I2C_RIS_BREQ_INT (1 << I2C_RIS_BREQ_INT_OFFSET)
		#define I2C_RIS_BREQ_INT_NO_INT \
			(0x0 << I2C_RIS_BREQ_INT_OFFSET)
		#define I2C_RIS_BREQ_INT_INT_PEND \
			(0x1 << I2C_RIS_BREQ_INT_OFFSET)
	#define I2C_RIS_LBREQ_INT_OFFSET 0x2
	#define I2C_RIS_LBREQ_INT_WIDTH 0x1
	#define I2C_RIS_LBREQ_INT_MASK 0x4
		#define I2C_RIS_LBREQ_INT (1 << I2C_RIS_LBREQ_INT_OFFSET)
		#define I2C_RIS_LBREQ_INT_NO_INT \
			(0x0 << I2C_RIS_LBREQ_INT_OFFSET)
		#define I2C_RIS_LBREQ_INT_INT_PEND \
			(0x1 << I2C_RIS_LBREQ_INT_OFFSET)
	#define I2C_RIS_SREQ_INT_OFFSET 0x1
	#define I2C_RIS_SREQ_INT_WIDTH 0x1
	#define I2C_RIS_SREQ_INT_MASK 0x2
		#define I2C_RIS_SREQ_INT (1 << I2C_RIS_SREQ_INT_OFFSET)
		#define I2C_RIS_SREQ_INT_NO_INT \
			(0x0 << I2C_RIS_SREQ_INT_OFFSET)
		#define I2C_RIS_SREQ_INT_INT_PEND \
			(0x1 << I2C_RIS_SREQ_INT_OFFSET)
	#define I2C_RIS_LSREQ_INT_OFFSET 0x0
	#define I2C_RIS_LSREQ_INT_WIDTH 0x1
	#define I2C_RIS_LSREQ_INT_MASK 0x1
		#define I2C_RIS_LSREQ_INT (1 << I2C_RIS_LSREQ_INT_OFFSET)
		#define I2C_RIS_LSREQ_INT_NO_INT \
			(0x0 << I2C_RIS_LSREQ_INT_OFFSET)
		#define I2C_RIS_LSREQ_INT_INT_PEND \
			(0x1 << I2C_RIS_LSREQ_INT_OFFSET)

#define I2C_IMSC_OFFSET	  0x84
	#define I2C_IMSC_I2C_P_INT_OFFSET 0x5
	#define I2C_IMSC_I2C_P_INT_WIDTH 0x1
	#define I2C_IMSC_I2C_P_INT_MASK 0x20
		#define I2C_IMSC_I2C_P_INT (1 << I2C_IMSC_I2C_P_INT_OFFSET)
		#define I2C_IMSC_I2C_P_INT_INT_DIS \
			(0x0 << I2C_IMSC_I2C_P_INT_OFFSET)
		#define I2C_IMSC_I2C_P_INT_INT_EN \
			(0x1 << I2C_IMSC_I2C_P_INT_OFFSET)
	#define I2C_IMSC_I2C_ERR_INT_OFFSET 0x4
	#define I2C_IMSC_I2C_ERR_INT_WIDTH 0x1
	#define I2C_IMSC_I2C_ERR_INT_MASK 0x10
		#define I2C_IMSC_I2C_ERR_INT (1 << I2C_IMSC_I2C_ERR_INT_OFFSET)
		#define I2C_IMSC_I2C_ERR_INT_INT_DIS \
			(0x0 << I2C_IMSC_I2C_ERR_INT_OFFSET)
		#define I2C_IMSC_I2C_ERR_INT_INT_EN \
			(0x1 << I2C_IMSC_I2C_ERR_INT_OFFSET)
	#define I2C_IMSC_BREQ_INT_OFFSET 0x3
	#define I2C_IMSC_BREQ_INT_WIDTH 0x1
	#define I2C_IMSC_BREQ_INT_MASK 0x8
		#define I2C_IMSC_BREQ_INT (1 << I2C_IMSC_BREQ_INT_OFFSET)
		#define I2C_IMSC_BREQ_INT_INT_DIS \
			(0x0 << I2C_IMSC_BREQ_INT_OFFSET)
		#define I2C_IMSC_BREQ_INT_INT_EN \
			(0x1 << I2C_IMSC_BREQ_INT_OFFSET)
	#define I2C_IMSC_LBREQ_INT_OFFSET 0x2
	#define I2C_IMSC_LBREQ_INT_WIDTH 0x1
	#define I2C_IMSC_LBREQ_INT_MASK 0x4
		#define I2C_IMSC_LBREQ_INT (1 << I2C_IMSC_LBREQ_INT_OFFSET)
		#define I2C_IMSC_LBREQ_INT_INT_DIS \
			(0x0 << I2C_IMSC_LBREQ_INT_OFFSET)
		#define I2C_IMSC_LBREQ_INT_INT_EN \
			(0x1 << I2C_IMSC_LBREQ_INT_OFFSET)
	#define I2C_IMSC_SREQ_INT_OFFSET 0x1
	#define I2C_IMSC_SREQ_INT_WIDTH 0x1
	#define I2C_IMSC_SREQ_INT_MASK 0x2
		#define I2C_IMSC_SREQ_INT (1 << I2C_IMSC_SREQ_INT_OFFSET)
		#define I2C_IMSC_SREQ_INT_INT_DIS \
			(0x0 << I2C_IMSC_SREQ_INT_OFFSET)
		#define I2C_IMSC_SREQ_INT_INT_EN \
			(0x1 << I2C_IMSC_SREQ_INT_OFFSET)
	#define I2C_IMSC_LSREQ_INT_OFFSET 0x0
	#define I2C_IMSC_LSREQ_INT_WIDTH 0x1
	#define I2C_IMSC_LSREQ_INT_MASK 0x1
		#define I2C_IMSC_LSREQ_INT (1 << I2C_IMSC_LSREQ_INT_OFFSET)
		#define I2C_IMSC_LSREQ_INT_INT_DIS \
			(0x0 << I2C_IMSC_LSREQ_INT_OFFSET)
		#define I2C_IMSC_LSREQ_INT_INT_EN \
			(0x1 << I2C_IMSC_LSREQ_INT_OFFSET)

#define I2C_MIS_OFFSET	  0x88
	#define I2C_MIS_I2C_P_INT_OFFSET 0x5
	#define I2C_MIS_I2C_P_INT_WIDTH 0x1
	#define I2C_MIS_I2C_P_INT_MASK 0x20
		#define I2C_MIS_I2C_P_INT (1 << I2C_MIS_I2C_P_INT_OFFSET)
		#define I2C_MIS_I2C_P_INT_NO_INT \
			(0x0 << I2C_MIS_I2C_P_INT_OFFSET)
		#define I2C_MIS_I2C_P_INT_INT_PEND \
			(0x1 << I2C_MIS_I2C_P_INT_OFFSET)
	#define I2C_MIS_I2C_ERR_INT_OFFSET 0x4
	#define I2C_MIS_I2C_ERR_INT_WIDTH 0x1
	#define I2C_MIS_I2C_ERR_INT_MASK 0x10
		#define I2C_MIS_I2C_ERR_INT (1 << I2C_MIS_I2C_ERR_INT_OFFSET)
		#define I2C_MIS_I2C_ERR_INT_NO_INT \
			(0x0 << I2C_MIS_I2C_ERR_INT_OFFSET)
		#define I2C_MIS_I2C_ERR_INT_INT_PEND \
			(0x1 << I2C_MIS_I2C_ERR_INT_OFFSET)
	#define I2C_MIS_BREQ_INT_OFFSET 0x3
	#define I2C_MIS_BREQ_INT_WIDTH 0x1
	#define I2C_MIS_BREQ_INT_MASK 0x8
		#define I2C_MIS_BREQ_INT (1 << I2C_MIS_BREQ_INT_OFFSET)
		#define I2C_MIS_BREQ_INT_NO_INT \
			(0x0 << I2C_MIS_BREQ_INT_OFFSET)
		#define I2C_MIS_BREQ_INT_INT_PEND \
			(0x1 << I2C_MIS_BREQ_INT_OFFSET)
	#define I2C_MIS_LBREQ_INT_OFFSET 0x2
	#define I2C_MIS_LBREQ_INT_WIDTH 0x1
	#define I2C_MIS_LBREQ_INT_MASK 0x4
		#define I2C_MIS_LBREQ_INT (1 << I2C_MIS_LBREQ_INT_OFFSET)
		#define I2C_MIS_LBREQ_INT_NO_INT \
			(0x0 << I2C_MIS_LBREQ_INT_OFFSET)
		#define I2C_MIS_LBREQ_INT_INT_PEND \
			(0x1 << I2C_MIS_LBREQ_INT_OFFSET)
	#define I2C_MIS_SREQ_INT_OFFSET 0x1
	#define I2C_MIS_SREQ_INT_WIDTH 0x1
	#define I2C_MIS_SREQ_INT_MASK 0x2
		#define I2C_MIS_SREQ_INT (1 << I2C_MIS_SREQ_INT_OFFSET)
		#define I2C_MIS_SREQ_INT_NO_INT \
			(0x0 << I2C_MIS_SREQ_INT_OFFSET)
		#define I2C_MIS_SREQ_INT_INT_PEND \
			(0x1 << I2C_MIS_SREQ_INT_OFFSET)
	#define I2C_MIS_LSREQ_INT_OFFSET 0x0
	#define I2C_MIS_LSREQ_INT_WIDTH 0x1
	#define I2C_MIS_LSREQ_INT_MASK 0x1
		#define I2C_MIS_LSREQ_INT (1 << I2C_MIS_LSREQ_INT_OFFSET)
		#define I2C_MIS_LSREQ_INT_NO_INT \
			(0x0 << I2C_MIS_LSREQ_INT_OFFSET)
		#define I2C_MIS_LSREQ_INT_INT_PEND \
			(0x1 << I2C_MIS_LSREQ_INT_OFFSET)

#define I2C_MIS_NO_INT_PEND	0x0


#define I2C_ICR_OFFSET	  0x8c
	#define I2C_ICR_I2C_P_INT_OFFSET 0x5
	#define I2C_ICR_I2C_P_INT_WIDTH 0x1
	#define I2C_ICR_I2C_P_INT_MASK 0x20
		#define I2C_ICR_I2C_P_INT (1 << I2C_ICR_I2C_P_INT_OFFSET)
		#define I2C_ICR_I2C_P_INT_NO_CHANGE \
			(0x0 << I2C_ICR_I2C_P_INT_OFFSET)
		#define I2C_ICR_I2C_P_INT_CLR_INT \
			(0x1 << I2C_ICR_I2C_P_INT_OFFSET)
	#define I2C_ICR_I2C_ERR_INT_OFFSET 0x4
	#define I2C_ICR_I2C_ERR_INT_WIDTH 0x1
	#define I2C_ICR_I2C_ERR_INT_MASK 0x10
		#define I2C_ICR_I2C_ERR_INT (1 << I2C_ICR_I2C_ERR_INT_OFFSET)
		#define I2C_ICR_I2C_ERR_INT_NO_CHANGE \
			(0x0 << I2C_ICR_I2C_ERR_INT_OFFSET)
		#define I2C_ICR_I2C_ERR_INT_CLR_INT \
			(0x1 << I2C_ICR_I2C_ERR_INT_OFFSET)
	#define I2C_ICR_BREQ_INT_OFFSET 0x3
	#define I2C_ICR_BREQ_INT_WIDTH 0x1
	#define I2C_ICR_BREQ_INT_MASK 0x8
		#define I2C_ICR_BREQ_INT (1 << I2C_ICR_BREQ_INT_OFFSET)
		#define I2C_ICR_BREQ_INT_NO_CHANGE \
			(0x0 << I2C_ICR_BREQ_INT_OFFSET)
		#define I2C_ICR_BREQ_INT_CLR_INT \
			(0x1 << I2C_ICR_BREQ_INT_OFFSET)
	#define I2C_ICR_LBREQ_INT_OFFSET 0x2
	#define I2C_ICR_LBREQ_INT_WIDTH 0x1
	#define I2C_ICR_LBREQ_INT_MASK 0x4
		#define I2C_ICR_LBREQ_INT (1 << I2C_ICR_LBREQ_INT_OFFSET)
		#define I2C_ICR_LBREQ_INT_NO_CHANGE \
			(0x0 << I2C_ICR_LBREQ_INT_OFFSET)
		#define I2C_ICR_LBREQ_INT_CLR_INT \
			(0x1 << I2C_ICR_LBREQ_INT_OFFSET)
	#define I2C_ICR_SREQ_INT_OFFSET 0x1
	#define I2C_ICR_SREQ_INT_WIDTH 0x1
	#define I2C_ICR_SREQ_INT_MASK 0x2
		#define I2C_ICR_SREQ_INT (1 << I2C_ICR_SREQ_INT_OFFSET)
		#define I2C_ICR_SREQ_INT_NO_CHANGE \
			(0x0 << I2C_ICR_SREQ_INT_OFFSET)
		#define I2C_ICR_SREQ_INT_CLR_INT \
			(0x1 << I2C_ICR_SREQ_INT_OFFSET)
	#define I2C_ICR_LSREQ_INT_OFFSET 0x0
	#define I2C_ICR_LSREQ_INT_WIDTH 0x1
	#define I2C_ICR_LSREQ_INT_MASK 0x1
		#define I2C_ICR_LSREQ_INT (1 << I2C_ICR_LSREQ_INT_OFFSET)
		#define I2C_ICR_LSREQ_INT_NO_CHANGE \
			(0x0 << I2C_ICR_LSREQ_INT_OFFSET)
		#define I2C_ICR_LSREQ_INT_CLR_INT \
			(0x1 << I2C_ICR_LSREQ_INT_OFFSET)

#define I2C_ISR_OFFSET	  0x90
	#define I2C_ISR_I2C_P_INT_OFFSET 0x5
	#define I2C_ISR_I2C_P_INT_WIDTH 0x1
	#define I2C_ISR_I2C_P_INT_MASK 0x20
		#define I2C_ISR_I2C_P_INT (1 << I2C_ISR_I2C_P_INT_OFFSET)
		#define I2C_ISR_I2C_P_INT_NO_CHANGE \
			(0x0 << I2C_ISR_I2C_P_INT_OFFSET)
		#define I2C_ISR_I2C_P_INT_SET_INT \
			(0x1 << I2C_ISR_I2C_P_INT_OFFSET)
	#define I2C_ISR_I2C_ERR_INT_OFFSET 0x4
	#define I2C_ISR_I2C_ERR_INT_WIDTH 0x1
	#define I2C_ISR_I2C_ERR_INT_MASK 0x10
		#define I2C_ISR_I2C_ERR_INT (1 << I2C_ISR_I2C_ERR_INT_OFFSET)
		#define I2C_ISR_I2C_ERR_INT_NO_CHANGE \
			(0x0 << I2C_ISR_I2C_ERR_INT_OFFSET)
		#define I2C_ISR_I2C_ERR_INT_SET_INT \
			(0x1 << I2C_ISR_I2C_ERR_INT_OFFSET)
	#define I2C_ISR_BREQ_INT_OFFSET 0x3
	#define I2C_ISR_BREQ_INT_WIDTH 0x1
	#define I2C_ISR_BREQ_INT_MASK 0x8
		#define I2C_ISR_BREQ_INT (1 << I2C_ISR_BREQ_INT_OFFSET)
		#define I2C_ISR_BREQ_INT_NO_CHANGE \
			(0x0 << I2C_ISR_BREQ_INT_OFFSET)
		#define I2C_ISR_BREQ_INT_SET_INT \
			(0x1 << I2C_ISR_BREQ_INT_OFFSET)
	#define I2C_ISR_LBREQ_INT_OFFSET 0x2
	#define I2C_ISR_LBREQ_INT_WIDTH 0x1
	#define I2C_ISR_LBREQ_INT_MASK 0x4
		#define I2C_ISR_LBREQ_INT (1 << I2C_ISR_LBREQ_INT_OFFSET)
		#define I2C_ISR_LBREQ_INT_NO_CHANGE \
			(0x0 << I2C_ISR_LBREQ_INT_OFFSET)
		#define I2C_ISR_LBREQ_INT_SET_INT \
			(0x1 << I2C_ISR_LBREQ_INT_OFFSET)
	#define I2C_ISR_SREQ_INT_OFFSET 0x1
	#define I2C_ISR_SREQ_INT_WIDTH 0x1
	#define I2C_ISR_SREQ_INT_MASK 0x2
		#define I2C_ISR_SREQ_INT (1 << I2C_ISR_SREQ_INT_OFFSET)
		#define I2C_ISR_SREQ_INT_NO_CHANGE \
			(0x0 << I2C_ISR_SREQ_INT_OFFSET)
		#define I2C_ISR_SREQ_INT_SET_INT \
			(0x1 << I2C_ISR_SREQ_INT_OFFSET)
	#define I2C_ISR_LSREQ_INT_OFFSET 0x0
	#define I2C_ISR_LSREQ_INT_WIDTH 0x1
	#define I2C_ISR_LSREQ_INT_MASK 0x1
		#define I2C_ISR_LSREQ_INT (1 << I2C_ISR_LSREQ_INT_OFFSET)
		#define I2C_ISR_LSREQ_INT_NO_CHANGE \
			(0x0 << I2C_ISR_LSREQ_INT_OFFSET)
		#define I2C_ISR_LSREQ_INT_SET_INT \
			(0x1 << I2C_ISR_LSREQ_INT_OFFSET)

#define I2C_DMAE_OFFSET	  0x94
	#define I2C_DMAE_BREQ_INT_OFFSET 0x3
	#define I2C_DMAE_BREQ_INT_WIDTH 0x1
	#define I2C_DMAE_BREQ_INT_MASK 0x8
		#define I2C_DMAE_BREQ_INT (1 << I2C_DMAE_BREQ_INT_OFFSET)
	#define I2C_DMAE_LBREQ_INT_OFFSET 0x2
	#define I2C_DMAE_LBREQ_INT_WIDTH 0x1
	#define I2C_DMAE_LBREQ_INT_MASK 0x4
		#define I2C_DMAE_LBREQ_INT (1 << I2C_DMAE_LBREQ_INT_OFFSET)
	#define I2C_DMAE_SREQ_INT_OFFSET 0x1
	#define I2C_DMAE_SREQ_INT_WIDTH 0x1
	#define I2C_DMAE_SREQ_INT_MASK 0x2
		#define I2C_DMAE_SREQ_INT (1 << I2C_DMAE_SREQ_INT_OFFSET)
	#define I2C_DMAE_LSREQ_INT_OFFSET 0x0
	#define I2C_DMAE_LSREQ_INT_WIDTH 0x1
	#define I2C_DMAE_LSREQ_INT_MASK 0x1
		#define I2C_DMAE_LSREQ_INT (1 << I2C_DMAE_LSREQ_INT_OFFSET)

#define I2C_ERR_IRQSM_OFFSET	  0x60
	#define I2C_ERR_IRQSM_TXF_OFL_OFFSET 0x3
	#define I2C_ERR_IRQSM_TXF_OFL_WIDTH 0x1
	#define I2C_ERR_IRQSM_TXF_OFL_MASK 0x8
		#define I2C_ERR_IRQSM_TXF_OFL \
			(1 << I2C_ERR_IRQSM_TXF_OFL_OFFSET)
		#define I2C_ERR_IRQSM_TXF_OFL_INTRS_DIS \
			(0x0 << I2C_ERR_IRQSM_TXF_OFL_OFFSET)
		#define I2C_ERR_IRQSM_TXF_OFL_INTRS_EN \
			(0x1 << I2C_ERR_IRQSM_TXF_OFL_OFFSET)
	#define I2C_ERR_IRQSM_TXF_UFL_OFFSET 0x2
	#define I2C_ERR_IRQSM_TXF_UFL_WIDTH 0x1
	#define I2C_ERR_IRQSM_TXF_UFL_MASK 0x4
		#define I2C_ERR_IRQSM_TXF_UFL \
			(1 << I2C_ERR_IRQSM_TXF_UFL_OFFSET)
		#define I2C_ERR_IRQSM_TXF_UFL_INTRS_DIS \
			(0x0 << I2C_ERR_IRQSM_TXF_UFL_OFFSET)
		#define I2C_ERR_IRQSM_TXF_UFL_INTRS_EN \
			(0x1 << I2C_ERR_IRQSM_TXF_UFL_OFFSET)
	#define I2C_ERR_IRQSM_RXF_OFL_OFFSET 0x1
	#define I2C_ERR_IRQSM_RXF_OFL_WIDTH 0x1
	#define I2C_ERR_IRQSM_RXF_OFL_MASK 0x2
		#define I2C_ERR_IRQSM_RXF_OFL \
			(1 << I2C_ERR_IRQSM_RXF_OFL_OFFSET)
		#define I2C_ERR_IRQSM_RXF_OFL_INTRS_DIS \
			(0x0 << I2C_ERR_IRQSM_RXF_OFL_OFFSET)
		#define I2C_ERR_IRQSM_RXF_OFL_INTRS_EN \
			(0x1 << I2C_ERR_IRQSM_RXF_OFL_OFFSET)
	#define I2C_ERR_IRQSM_RXF_UFL_OFFSET 0x0
	#define I2C_ERR_IRQSM_RXF_UFL_WIDTH 0x1
	#define I2C_ERR_IRQSM_RXF_UFL_MASK 0x1
		#define I2C_ERR_IRQSM_RXF_UFL \
			(1 << I2C_ERR_IRQSM_RXF_UFL_OFFSET)
		#define I2C_ERR_IRQSM_RXF_UFL_INTRS_DIS \
			(0x0 << I2C_ERR_IRQSM_RXF_UFL_OFFSET)
		#define I2C_ERR_IRQSM_RXF_UFL_INTRS_EN \
			(0x1 << I2C_ERR_IRQSM_RXF_UFL_OFFSET)

#define I2C_ERR_IRQSS_OFFSET	  0x64
	#define I2C_ERR_IRQSS_TXF_OFL_OFFSET 0x3
	#define I2C_ERR_IRQSS_TXF_OFL_WIDTH 0x1
	#define I2C_ERR_IRQSS_TXF_OFL_MASK 0x8
		#define I2C_ERR_IRQSS_TXF_OFL \
			(1 << I2C_ERR_IRQSS_TXF_OFL_OFFSET)
		#define I2C_ERR_IRQSS_TXF_OFL_NO_INTRS \
			(0x0 << I2C_ERR_IRQSS_TXF_OFL_OFFSET)
		#define I2C_ERR_IRQSS_TXF_OFL_INTRS_PEND \
			(0x1 << I2C_ERR_IRQSS_TXF_OFL_OFFSET)
	#define I2C_ERR_IRQSS_TXF_UFL_OFFSET 0x2
	#define I2C_ERR_IRQSS_TXF_UFL_WIDTH 0x1
	#define I2C_ERR_IRQSS_TXF_UFL_MASK 0x4
		#define I2C_ERR_IRQSS_TXF_UFL \
			(1 << I2C_ERR_IRQSS_TXF_UFL_OFFSET)
		#define I2C_ERR_IRQSS_TXF_UFL_NO_INTRS \
			(0x0 << I2C_ERR_IRQSS_TXF_UFL_OFFSET)
		#define I2C_ERR_IRQSS_TXF_UFL_INTRS_PEND \
			(0x1 << I2C_ERR_IRQSS_TXF_UFL_OFFSET)
	#define I2C_ERR_IRQSS_RXF_OFL_OFFSET 0x1
	#define I2C_ERR_IRQSS_RXF_OFL_WIDTH 0x1
	#define I2C_ERR_IRQSS_RXF_OFL_MASK 0x2
		#define I2C_ERR_IRQSS_RXF_OFL \
			(1 << I2C_ERR_IRQSS_RXF_OFL_OFFSET)
		#define I2C_ERR_IRQSS_RXF_OFL_NO_INTRS \
			(0x0 << I2C_ERR_IRQSS_RXF_OFL_OFFSET)
		#define I2C_ERR_IRQSS_RXF_OFL_INTRS_PEND \
			(0x1 << I2C_ERR_IRQSS_RXF_OFL_OFFSET)
	#define I2C_ERR_IRQSS_RXF_UFL_OFFSET 0x0
	#define I2C_ERR_IRQSS_RXF_UFL_WIDTH 0x1
	#define I2C_ERR_IRQSS_RXF_UFL_MASK 0x1
		#define I2C_ERR_IRQSS_RXF_UFL \
			(1 << I2C_ERR_IRQSS_RXF_UFL_OFFSET)
		#define I2C_ERR_IRQSS_RXF_UFL_NO_INTRS \
			(0x0 << I2C_ERR_IRQSS_RXF_UFL_OFFSET)
		#define I2C_ERR_IRQSS_RXF_UFL_INTRS_PEND \
			(0x1 << I2C_ERR_IRQSS_RXF_UFL_OFFSET)

#define I2C_ERR_IRQSC_OFFSET	  0x68
	#define I2C_ERR_IRQSC_TXF_OFL_OFFSET 0x3
	#define I2C_ERR_IRQSC_TXF_OFL_WIDTH 0x1
	#define I2C_ERR_IRQSC_TXF_OFL_MASK 0x8
		#define I2C_ERR_IRQSC_TXF_OFL \
			(1 << I2C_ERR_IRQSC_TXF_OFL_OFFSET)
		#define I2C_ERR_IRQSC_TXF_OFL_NOP \
			(0x0 << I2C_ERR_IRQSC_TXF_OFL_OFFSET)
		#define I2C_ERR_IRQSC_TXF_OFL_INTRS_CLR \
			(0x1 << I2C_ERR_IRQSC_TXF_OFL_OFFSET)
	#define I2C_ERR_IRQSC_TXF_UFL_OFFSET 0x2
	#define I2C_ERR_IRQSC_TXF_UFL_WIDTH 0x1
	#define I2C_ERR_IRQSC_TXF_UFL_MASK 0x4
		#define I2C_ERR_IRQSC_TXF_UFL \
			(1 << I2C_ERR_IRQSC_TXF_UFL_OFFSET)
		#define I2C_ERR_IRQSC_TXF_UFL_NOP \
			(0x0 << I2C_ERR_IRQSC_TXF_UFL_OFFSET)
		#define I2C_ERR_IRQSC_TXF_UFL_INTRS_CLR \
			(0x1 << I2C_ERR_IRQSC_TXF_UFL_OFFSET)
	#define I2C_ERR_IRQSC_RXF_OFL_OFFSET 0x1
	#define I2C_ERR_IRQSC_RXF_OFL_WIDTH 0x1
	#define I2C_ERR_IRQSC_RXF_OFL_MASK 0x2
		#define I2C_ERR_IRQSC_RXF_OFL \
			(1 << I2C_ERR_IRQSC_RXF_OFL_OFFSET)
		#define I2C_ERR_IRQSC_RXF_OFL_NOP \
			(0x0 << I2C_ERR_IRQSC_RXF_OFL_OFFSET)
		#define I2C_ERR_IRQSC_RXF_OFL_INTRS_CLR \
			(0x1 << I2C_ERR_IRQSC_RXF_OFL_OFFSET)
	#define I2C_ERR_IRQSC_RXF_UFL_OFFSET 0x0
	#define I2C_ERR_IRQSC_RXF_UFL_WIDTH 0x1
	#define I2C_ERR_IRQSC_RXF_UFL_MASK 0x1
		#define I2C_ERR_IRQSC_RXF_UFL \
			(1 << I2C_ERR_IRQSC_RXF_UFL_OFFSET)
		#define I2C_ERR_IRQSC_RXF_UFL_NOP \
			(0x0 << I2C_ERR_IRQSC_RXF_UFL_OFFSET)
		#define I2C_ERR_IRQSC_RXF_UFL_INTRS_CLR \
			(0x1 << I2C_ERR_IRQSC_RXF_UFL_OFFSET)

#define I2C_P_IRQSM_OFFSET	  0x70
	#define I2C_P_IRQSM_RX_OFFSET 0x6
	#define I2C_P_IRQSM_RX_WIDTH 0x1
	#define I2C_P_IRQSM_RX_MASK 0x40
		#define I2C_P_IRQSM_RX (1 << I2C_P_IRQSM_RX_OFFSET)
		#define I2C_P_IRQSM_RX_INTRS_DIS (0x0 << I2C_P_IRQSM_RX_OFFSET)
		#define I2C_P_IRQSM_RX_INTRS_EN (0x1 << I2C_P_IRQSM_RX_OFFSET)
	#define I2C_P_IRQSM_TX_END_OFFSET 0x5
	#define I2C_P_IRQSM_TX_END_WIDTH 0x1
	#define I2C_P_IRQSM_TX_END_MASK 0x20
		#define I2C_P_IRQSM_TX_END (1 << I2C_P_IRQSM_TX_END_OFFSET)
		#define I2C_P_IRQSM_TX_END_INTRS_DIS \
			(0x0 << I2C_P_IRQSM_TX_END_OFFSET)
		#define I2C_P_IRQSM_TX_END_INTRS_EN \
			(0x1 << I2C_P_IRQSM_TX_END_OFFSET)
	#define I2C_P_IRQSM_NACK_OFFSET 0x4
	#define I2C_P_IRQSM_NACK_WIDTH 0x1
	#define I2C_P_IRQSM_NACK_MASK 0x10
		#define I2C_P_IRQSM_NACK (1 << I2C_P_IRQSM_NACK_OFFSET)
		#define I2C_P_IRQSM_NACK_INTRS_DIS \
			(0x0 << I2C_P_IRQSM_NACK_OFFSET)
		#define I2C_P_IRQSM_NACK_INTRS_EN \
			(0x1 << I2C_P_IRQSM_NACK_OFFSET)
	#define I2C_P_IRQSM_AL_OFFSET 0x3
	#define I2C_P_IRQSM_AL_WIDTH 0x1
	#define I2C_P_IRQSM_AL_MASK 0x8
		#define I2C_P_IRQSM_AL (1 << I2C_P_IRQSM_AL_OFFSET)
		#define I2C_P_IRQSM_AL_INTRS_DIS (0x0 << I2C_P_IRQSM_AL_OFFSET)
		#define I2C_P_IRQSM_AL_INTRS_EN (0x1 << I2C_P_IRQSM_AL_OFFSET)
	#define I2C_P_IRQSM_MC_OFFSET 0x2
	#define I2C_P_IRQSM_MC_WIDTH 0x1
	#define I2C_P_IRQSM_MC_MASK 0x4
		#define I2C_P_IRQSM_MC (1 << I2C_P_IRQSM_MC_OFFSET)
		#define I2C_P_IRQSM_MC_INTRS_DIS (0x0 << I2C_P_IRQSM_MC_OFFSET)
		#define I2C_P_IRQSM_MC_INTRS_EN (0x1 << I2C_P_IRQSM_MC_OFFSET)
	#define I2C_P_IRQSM_GC_OFFSET 0x1
	#define I2C_P_IRQSM_GC_WIDTH 0x1
	#define I2C_P_IRQSM_GC_MASK 0x2
		#define I2C_P_IRQSM_GC (1 << I2C_P_IRQSM_GC_OFFSET)
		#define I2C_P_IRQSM_GC_INTRS_DIS (0x0 << I2C_P_IRQSM_GC_OFFSET)
		#define I2C_P_IRQSM_GC_INTRS_EN (0x1 << I2C_P_IRQSM_GC_OFFSET)
	#define I2C_P_IRQSM_AM_OFFSET 0x0
	#define I2C_P_IRQSM_AM_WIDTH 0x1
	#define I2C_P_IRQSM_AM_MASK 0x1
		#define I2C_P_IRQSM_AM (1 << I2C_P_IRQSM_AM_OFFSET)
		#define I2C_P_IRQSM_AM_INTRS_DIS (0x0 << I2C_P_IRQSM_AM_OFFSET)
		#define I2C_P_IRQSM_AM_INTRS_EN (0x1 << I2C_P_IRQSM_AM_OFFSET)

#define I2C_P_IRQSS_OFFSET	  0x74
	#define I2C_P_IRQSS_RX_OFFSET 0x6
	#define I2C_P_IRQSS_RX_WIDTH 0x1
	#define I2C_P_IRQSS_RX_MASK 0x40
		#define I2C_P_IRQSS_RX (1 << I2C_P_IRQSS_RX_OFFSET)
		#define I2C_P_IRQSS_RX_NO_INTRS (0x0 << I2C_P_IRQSS_RX_OFFSET)
		#define I2C_P_IRQSS_RX_INTRS_PEND (0x1 << I2C_P_IRQSS_RX_OFFSET)
	#define I2C_P_IRQSS_TX_END_OFFSET 0x5
	#define I2C_P_IRQSS_TX_END_WIDTH 0x1
	#define I2C_P_IRQSS_TX_END_MASK 0x20
		#define I2C_P_IRQSS_TX_END (1 << I2C_P_IRQSS_TX_END_OFFSET)
		#define I2C_P_IRQSS_TX_END_NO_INTRS \
			(0x0 << I2C_P_IRQSS_TX_END_OFFSET)
		#define I2C_P_IRQSS_TX_END_INTRS_PEND \
			(0x1 << I2C_P_IRQSS_TX_END_OFFSET)
	#define I2C_P_IRQSS_NACK_OFFSET 0x4
	#define I2C_P_IRQSS_NACK_WIDTH 0x1
	#define I2C_P_IRQSS_NACK_MASK 0x10
		#define I2C_P_IRQSS_NACK (1 << I2C_P_IRQSS_NACK_OFFSET)
		#define I2C_P_IRQSS_NACK_NO_INTRS \
			(0x0 << I2C_P_IRQSS_NACK_OFFSET)
		#define I2C_P_IRQSS_NACK_INTRS_PEND \
			(0x1 << I2C_P_IRQSS_NACK_OFFSET)
	#define I2C_P_IRQSS_AL_OFFSET 0x3
	#define I2C_P_IRQSS_AL_WIDTH 0x1
	#define I2C_P_IRQSS_AL_MASK 0x8
		#define I2C_P_IRQSS_AL (1 << I2C_P_IRQSS_AL_OFFSET)
		#define I2C_P_IRQSS_AL_NO_INTRS (0x0 << I2C_P_IRQSS_AL_OFFSET)
		#define I2C_P_IRQSS_AL_INTRS_PEND (0x1 << I2C_P_IRQSS_AL_OFFSET)
	#define I2C_P_IRQSS_MC_OFFSET 0x2
	#define I2C_P_IRQSS_MC_WIDTH 0x1
	#define I2C_P_IRQSS_MC_MASK 0x4
		#define I2C_P_IRQSS_MC (1 << I2C_P_IRQSS_MC_OFFSET)
		#define I2C_P_IRQSS_MC_NO_INTRS (0x0 << I2C_P_IRQSS_MC_OFFSET)
		#define I2C_P_IRQSS_MC_INTRS_PEND (0x1 << I2C_P_IRQSS_MC_OFFSET)
	#define I2C_P_IRQSS_GC_OFFSET 0x1
	#define I2C_P_IRQSS_GC_WIDTH 0x1
	#define I2C_P_IRQSS_GC_MASK 0x2
		#define I2C_P_IRQSS_GC (1 << I2C_P_IRQSS_GC_OFFSET)
		#define I2C_P_IRQSS_GC_NO_INTRS (0x0 << I2C_P_IRQSS_GC_OFFSET)
		#define I2C_P_IRQSS_GC_INTRS_PEND (0x1 << I2C_P_IRQSS_GC_OFFSET)
	#define I2C_P_IRQSS_AM_OFFSET 0x0
	#define I2C_P_IRQSS_AM_WIDTH 0x1
	#define I2C_P_IRQSS_AM_MASK 0x1
		#define I2C_P_IRQSS_AM (1 << I2C_P_IRQSS_AM_OFFSET)
		#define I2C_P_IRQSS_AM_NO_INTRS (0x0 << I2C_P_IRQSS_AM_OFFSET)
		#define I2C_P_IRQSS_AM_INTRS_PEND (0x1 << I2C_P_IRQSS_AM_OFFSET)

#define I2C_P_IRQSC_OFFSET	  0x78
	#define I2C_P_IRQSC_RX_OFFSET 0x6
	#define I2C_P_IRQSC_RX_WIDTH 0x1
	#define I2C_P_IRQSC_RX_MASK 0x40
		#define I2C_P_IRQSC_RX (1 << I2C_P_IRQSC_RX_OFFSET)
		#define I2C_P_IRQSC_RX_NOP (0x0 << I2C_P_IRQSC_RX_OFFSET)
		#define I2C_P_IRQSC_RX_INTRS_CLR (0x1 << I2C_P_IRQSC_RX_OFFSET)
	#define I2C_P_IRQSC_TX_END_OFFSET 0x5
	#define I2C_P_IRQSC_TX_END_WIDTH 0x1
	#define I2C_P_IRQSC_TX_END_MASK 0x20
		#define I2C_P_IRQSC_TX_END (1 << I2C_P_IRQSC_TX_END_OFFSET)
		#define I2C_P_IRQSC_TX_END_NOP \
			(0x0 << I2C_P_IRQSC_TX_END_OFFSET)
		#define I2C_P_IRQSC_TX_END_INTRS_CLR \
			(0x1 << I2C_P_IRQSC_TX_END_OFFSET)
	#define I2C_P_IRQSC_NACK_OFFSET 0x4
	#define I2C_P_IRQSC_NACK_WIDTH 0x1
	#define I2C_P_IRQSC_NACK_MASK 0x10
		#define I2C_P_IRQSC_NACK (1 << I2C_P_IRQSC_NACK_OFFSET)
	#define I2C_P_IRQSC_AL_OFFSET 0x3
	#define I2C_P_IRQSC_AL_WIDTH 0x1
	#define I2C_P_IRQSC_AL_MASK 0x8
		#define I2C_P_IRQSC_AL (1 << I2C_P_IRQSC_AL_OFFSET)
		#define I2C_P_IRQSC_AL_NOP (0x0 << I2C_P_IRQSC_AL_OFFSET)
		#define I2C_P_IRQSC_AL_INTRS_CLR (0x1 << I2C_P_IRQSC_AL_OFFSET)
	#define I2C_P_IRQSC_MC_OFFSET 0x2
	#define I2C_P_IRQSC_MC_WIDTH 0x1
	#define I2C_P_IRQSC_MC_MASK 0x4
		#define I2C_P_IRQSC_MC (1 << I2C_P_IRQSC_MC_OFFSET)
		#define I2C_P_IRQSC_MC_NOP (0x0 << I2C_P_IRQSC_MC_OFFSET)
		#define I2C_P_IRQSC_MC_INTRS_CLR (0x1 << I2C_P_IRQSC_MC_OFFSET)
	#define I2C_P_IRQSC_GC_OFFSET 0x1
	#define I2C_P_IRQSC_GC_WIDTH 0x1
	#define I2C_P_IRQSC_GC_MASK 0x2
		#define I2C_P_IRQSC_GC (1 << I2C_P_IRQSC_GC_OFFSET)
		#define I2C_P_IRQSC_GC_NOP (0x0 << I2C_P_IRQSC_GC_OFFSET)
		#define I2C_P_IRQSC_GC_INTRS_CLR (0x1 << I2C_P_IRQSC_GC_OFFSET)
	#define I2C_P_IRQSC_AM_OFFSET 0x0
	#define I2C_P_IRQSC_AM_WIDTH 0x1
	#define I2C_P_IRQSC_AM_MASK 0x1
		#define I2C_P_IRQSC_AM (1 << I2C_P_IRQSC_AM_OFFSET)
		#define I2C_P_IRQSC_AM_NOP (0x0 << I2C_P_IRQSC_AM_OFFSET)
		#define I2C_P_IRQSC_AM_INTRS_CLR (0x1 << I2C_P_IRQSC_AM_OFFSET)

#endif
