/*
 * Copyright (C) 2014 Intel Mobile Communications GmbH
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 */

#ifndef _PMIC_REG_ACCESS_H
#define _PMIC_REG_ACCESS_H


/*DEV1 Registers */
#define BASE_ADDRESS_DEV1 (0x4E)
#define BASE_ADDRESS_DEV1_VMM (BASE_ADDRESS_DEV1 << 24)

#define PBIRQ_REG (BASE_ADDRESS_DEV1_VMM | 0x3)
#define THRMIRQ0_REG (BASE_ADDRESS_DEV1_VMM | 0x4)
#define THRMIRQ1_REG (BASE_ADDRESS_DEV1_VMM | 0x5)
#define THRMIRQ2_REG (BASE_ADDRESS_DEV1_VMM | 0x6)
#define BCUIRQ_REG (BASE_ADDRESS_DEV1_VMM | 0x7)
#define ADCIRQ_REG (BASE_ADDRESS_DEV1_VMM | 0x8)
#define CHGRIRQ0_REG (BASE_ADDRESS_DEV1_VMM | 0x9)
#define CHGRIRQ1_REG (BASE_ADDRESS_DEV1_VMM | 0xA)
#define GPIOIRQ0_REG (BASE_ADDRESS_DEV1_VMM | 0xB)
#define GPIOIRQ1_REG (BASE_ADDRESS_DEV1_VMM | 0xC)
#define CRITIRQ_REG (BASE_ADDRESS_DEV1_VMM | 0xD)

#define RESETSRC0_REG (BASE_ADDRESS_DEV1_VMM | 0x2C)
#define RESETSRC1_REG (BASE_ADDRESS_DEV1_VMM | 0x2D)

#define WAKESRC_REG (BASE_ADDRESS_DEV1_VMM | 0x31)

#define MODEMCTRL_REG (BASE_ADDRESS_DEV1_VMM | 0x36)
#define SOCCTRL_REG (BASE_ADDRESS_DEV1_VMM | 0x37)

#define GPIO0CTLO_REG (BASE_ADDRESS_DEV1_VMM | 0x44)
#define GPIO1CTLO_REG (BASE_ADDRESS_DEV1_VMM | 0x45)
#define GPIO2CTLO_REG (BASE_ADDRESS_DEV1_VMM | 0x46)
#define GPIO3CTLO_REG (BASE_ADDRESS_DEV1_VMM | 0x47)
#define GPIO4CTLO_REG (BASE_ADDRESS_DEV1_VMM | 0x48)
#define GPIO5CTLO_REG (BASE_ADDRESS_DEV1_VMM | 0x49)
#define GPIO6CTLO_REG (BASE_ADDRESS_DEV1_VMM | 0x4A)
#define GPIO7CTLO_REG (BASE_ADDRESS_DEV1_VMM | 0x4B)
#define GPIO8CTLO_REG (BASE_ADDRESS_DEV1_VMM | 0x4C)

#define S_BCUCTRL_REG (BASE_ADDRESS_DEV1_VMM | 0x8C)

/*DEV2 Registers */
#define BASE_ADDRESS_DEV2 (0x4F)
#define BASE_ADDRESS_DEV2_VMM (BASE_ADDRESS_DEV2 << 24)

#define VRTCCTRL_REG (BASE_ADDRESS_DEV2_VMM | 0xB5)
#define TMUIRQ_REG (BASE_ADDRESS_DEV2_VMM | 0xB6)

/*DEV3 Registers */
#define BASE_ADDRESS_DEV3 (0x5E)
#define BASE_ADDRESS_DEV3_VMM (BASE_ADDRESS_DEV3 << 24)

#define USBIDDETTYPE_REG (BASE_ADDRESS_DEV3_VMM | 0x7)
#define USBPHYCTRL_REG (BASE_ADDRESS_DEV3_VMM | 0x8)

#define CHGRCTRL0_REG (BASE_ADDRESS_DEV3_VMM | 0x16)
#define CHGRSTATUS_REG (BASE_ADDRESS_DEV3_VMM | 0x19)

#define VBUSDETCTRL_REG (BASE_ADDRESS_DEV3_VMM | 0x1D)
#define VDCINDETCTRL_REG (BASE_ADDRESS_DEV3_VMM | 0x1E)

#define CHRTTADDR_REG (BASE_ADDRESS_DEV3_VMM | 0x22)

#define CHGDISCTRL_REG (BASE_ADDRESS_DEV3_VMM | 0x2F)

#define TLP1CTRL_REG (BASE_ADDRESS_DEV3_VMM | 0x30)
#define TLP1EVSTATUS0_REG (BASE_ADDRESS_DEV3_VMM | 0x31)
#define TLP1EVSTATUS1_REG (BASE_ADDRESS_DEV3_VMM | 0x32)
#define TLP1EVSTATUS2_REG (BASE_ADDRESS_DEV3_VMM | 0x33)
#define TLP1EVSTATUS3_REG (BASE_ADDRESS_DEV3_VMM | 0x34)

#define TLP1INSTMEMADDRH_REG (BASE_ADDRESS_DEV3_VMM | 0x38)
#define TLP1INSTMEMADDRL_REG (BASE_ADDRESS_DEV3_VMM | 0x39)

#define TLP2CTRL_REG (BASE_ADDRESS_DEV3_VMM | 0x61)
#define TLP2EVSTATUS_REG (BASE_ADDRESS_DEV3_VMM | 0x62)

#define TLP2INSTMEMADDR_REG (BASE_ADDRESS_DEV3_VMM | 0x64)


/*DEV4 Registers */
#define BASE_ADDRESS_DEV4 (0x5F)
#define BASE_ADDRESS_DEV4_VMM (BASE_ADDRESS_DEV4 << 24)

#define VENDCTL0_REG (BASE_ADDRESS_DEV4_VMM | 0x36)
#define VENDCTL1_REG (BASE_ADDRESS_DEV4_VMM | 0x37)
#define VENDCTL2_REG (BASE_ADDRESS_DEV4_VMM | 0x38)

#define NVM_MB_ADDRH_REG (BASE_ADDRESS_DEV4_VMM | 0x3A)
#define NVM_MB_ADDRL_REG (BASE_ADDRESS_DEV4_VMM | 0x3B)

#define CODSRC_REG (BASE_ADDRESS_DEV4_VMM | 0x6C)
#define ISOCTRL_REG (BASE_ADDRESS_DEV4_VMM | 0x6D)

#define NVMVIRQ_REG (BASE_ADDRESS_DEV4_VMM | 0x78)
#define ADCTLP2VIRQ_REG (BASE_ADDRESS_DEV4_VMM | 0x79)

#define I2CSIFVIRQ_REG (BASE_ADDRESS_DEV4_VMM | 0x7A)
#define REGBUSVIRQ_REG (BASE_ADDRESS_DEV4_VMM | 0x7B)
#define CHGRVIRQ_REG (BASE_ADDRESS_DEV4_VMM | 0x7C)
#define TLP1VIRQ_REG (BASE_ADDRESS_DEV4_VMM | 0x7D)
#define DCDCVIRQ0_REG (BASE_ADDRESS_DEV4_VMM | 0x7E)

#define VROCIRQ0_REG (BASE_ADDRESS_DEV4_VMM | 0x80)

#define VROCIRQ2_REG (BASE_ADDRESS_DEV4_VMM | 0x82)

#define GPADC_TEST0_REG (BASE_ADDRESS_DEV4_VMM | 0xAF)

#define GPADC_PKTST_REG (BASE_ADDRESS_DEV4_VMM | 0xB1)

#define COMPTEST1_REG (BASE_ADDRESS_DEV4_VMM | 0xB3)

#define PMICSPARE05_REG (BASE_ADDRESS_DEV4_VMM | 0xC4)
#define PMICSPARE06_REG (BASE_ADDRESS_DEV4_VMM | 0xC5)
#define PMICSPARE07_REG (BASE_ADDRESS_DEV4_VMM | 0xC6)
#define PMICSPARE08_REG (BASE_ADDRESS_DEV4_VMM | 0xC7)
#define PMICSPARE09_REG (BASE_ADDRESS_DEV4_VMM | 0xC8)
#define PMICSPARE10_REG (BASE_ADDRESS_DEV4_VMM | 0xC9)
#define PMICSPARE11_REG (BASE_ADDRESS_DEV4_VMM | 0xCA)
#define PMICSPARE12_REG (BASE_ADDRESS_DEV4_VMM | 0xCB)
#define I2C_HS_TIMING_REG (BASE_ADDRESS_DEV4_VMM | 0xCC)

#define AFE_SPARE1_REG (BASE_ADDRESS_DEV4_VMM | 0xF0)
#define AFE_SPARE2_REG (BASE_ADDRESS_DEV4_VMM | 0xF1)
#define AFE_SPARE3_REG (BASE_ADDRESS_DEV4_VMM | 0xF2)

/*DEV5 Registers */
#define BASE_ADDRESS_DEV5 (0x6D)
#define BASE_ADDRESS_DEV5_VMM (BASE_ADDRESS_DEV5 << 24)

#define AFE_AUDOUTCTRL1A_REG (BASE_ADDRESS_DEV5_VMM | 0x48)
#define AFE_AUDOUTCTRL1B_REG (BASE_ADDRESS_DEV5_VMM | 0x49)
#define AFE_AUDOUTCTRL1C_REG (BASE_ADDRESS_DEV5_VMM | 0x4A)
#define AFE_AUDOUTCTRL1D_REG (BASE_ADDRESS_DEV5_VMM | 0x4B)

#define AFE_AUDOUTCTRL3A_REG (BASE_ADDRESS_DEV5_VMM | 0x50)
#define AFE_AUDOUTCTRL3B_REG (BASE_ADDRESS_DEV5_VMM | 0x51)
#define AFE_AUDOUTCTRL3C_REG (BASE_ADDRESS_DEV5_VMM | 0x52)
#define AFE_AUDOUTCTRL3D_REG (BASE_ADDRESS_DEV5_VMM | 0x53)

#define AFE_AUDIOINCTRL3_REG (BASE_ADDRESS_DEV5_VMM | 0x56)

#define AFE_GAIN_IN3_REG (BASE_ADDRESS_DEV5_VMM | 0x72)
#define AFE_GAIN_IN4_REG (BASE_ADDRESS_DEV5_VMM | 0x73)

#define AFE_DIGMICCTRL_REG (BASE_ADDRESS_DEV5_VMM | 0x80)

#define I2S_CTRL_LOW_REG (BASE_ADDRESS_DEV5_VMM | 0x90)


#endif /* _PMIC_REG_ACCESS_H */
