/*
 * Copyright (C) 2014 Intel Mobile Communications GmbH
 *
 * This software is licensed under the terms of the GNU General Public
 * License version 2, as published by the Free Software Foundation, and
 * may be copied, distributed, and modified under those terms.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

#ifndef _XGOLD_USIF_H
#define _XGOLD_USIF_H

#define USIF_ID_OFFSET	  0xc
#define USIF_ID(_base) ((_base) + 0xc)
#define USIF_ID_TS_REV_NR_OFFSET 0x10
#define USIF_ID_TS_REV_NR_WIDTH 0x10
#define USIF_ID_TS_REV_NR_MASK 0xffff0000
#define USIF_ID_TS_REV_NR(_reg) (((_reg) & 0xffff0000) >> 0x10)
#define USIF_ID_MOD_ID_OFFSET 0x8
#define USIF_ID_MOD_ID_WIDTH 0x8
#define USIF_ID_MOD_ID_MASK 0xff00
#define USIF_ID_MOD_ID(_reg) (((_reg) & 0xff00) >> 0x8)
#define USIF_ID_REV_NUMBER_OFFSET 0x0
#define USIF_ID_REV_NUMBER_WIDTH 0x8
#define USIF_ID_REV_NUMBER_MASK 0xff
#define USIF_ID_REV_NUMBER(_reg) (((_reg) & 0xff) >> 0x0)

#define USIF_FIFO_ID_OFFSET	  0x10
#define USIF_FIFO_ID(_base) ((_base) + 0x10)
#define USIF_FIFO_ID_RPS_STAGE_OFFSET 0x10
#define USIF_FIFO_ID_RPS_STAGE_WIDTH 0x6
#define USIF_FIFO_ID_RPS_STAGE_MASK 0x3f0000
#define USIF_FIFO_ID_RPS_STAGE(_reg) (((_reg) & 0x3f0000) >> 0x10)
#define USIF_FIFO_ID_RPS_STAGE_NFF (0x0 << USIF_FIFO_ID_RPS_STAGE_OFFSET)
#define USIF_FIFO_ID_RPS_STAGE_FS01 (0x1 << USIF_FIFO_ID_RPS_STAGE_OFFSET)
#define USIF_FIFO_ID_RPS_STAGE_FS02 (0x2 << USIF_FIFO_ID_RPS_STAGE_OFFSET)
#define USIF_FIFO_ID_RPS_STAGE_FS3F (0x3f << USIF_FIFO_ID_RPS_STAGE_OFFSET)
#define USIF_FIFO_ID_RX_STAGE_OFFSET 0x8
#define USIF_FIFO_ID_RX_STAGE_WIDTH 0x8
#define USIF_FIFO_ID_RX_STAGE_MASK 0xff00
#define USIF_FIFO_ID_RX_STAGE(_reg) (((_reg) & 0xff00) >> 0x8)
#define USIF_FIFO_ID_RX_STAGE_NFF (0x0 << USIF_FIFO_ID_RX_STAGE_OFFSET)
#define USIF_FIFO_ID_RX_STAGE_FS01 (0x1 << USIF_FIFO_ID_RX_STAGE_OFFSET)
#define USIF_FIFO_ID_RX_STAGE_FSFF (0xff << USIF_FIFO_ID_RX_STAGE_OFFSET)
#define USIF_FIFO_ID_TX_STAGE_OFFSET 0x0
#define USIF_FIFO_ID_TX_STAGE_WIDTH 0x8
#define USIF_FIFO_ID_TX_STAGE_MASK 0xff
#define USIF_FIFO_ID_TX_STAGE(_reg) (((_reg) & 0xff) >> 0x0)
#define USIF_FIFO_ID_TX_STAGE_NFF (0x0 << USIF_FIFO_ID_TX_STAGE_OFFSET)
#define USIF_FIFO_ID_TX_STAGE_FS01 (0x1 << USIF_FIFO_ID_TX_STAGE_OFFSET)
#define USIF_FIFO_ID_TX_STAGE_FSFF (0xff << USIF_FIFO_ID_TX_STAGE_OFFSET)

#define USIF_SRB_MSCONF_ID_OFFSET	  0x14
#define USIF_SRB_MSCONF_ID(_base) ((_base) + 0x14)
#define USIF_SRB_MSCONF_ID_SEL_MULTISRC_IRQ_OFFSET 0x0
#define USIF_SRB_MSCONF_ID_SEL_MULTISRC_IRQ_WIDTH 0x20
#define USIF_SRB_MSCONF_ID_SEL_MULTISRC_IRQ_MASK 0xffffffff
#define USIF_SRB_MSCONF_ID_SEL_MULTISRC_IRQ(_reg) (((_reg) & 0xffffffff) >> 0x0)

#define USIF_SRB_ERRCONF_ID_OFFSET	  0x18
#define USIF_SRB_ERRCONF_ID(_base) ((_base) + 0x18)
#define USIF_SRB_ERRCONF_ID_SEL_ERR_IRQ_OFFSET 0x0
#define USIF_SRB_ERRCONF_ID_SEL_ERR_IRQ_WIDTH 0x20
#define USIF_SRB_ERRCONF_ID_SEL_ERR_IRQ_MASK 0xffffffff
#define USIF_SRB_ERRCONF_ID_SEL_ERR_IRQ(_reg) (((_reg) & 0xffffffff) >> 0x0)

#define USIF_SWCID_OFFSET	  0x1c
#define USIF_SWCID(_base) ((_base) + 0x1c)
#define USIF_SWCID_SWCID_OFFSET 0xf
#define USIF_SWCID_SWCID_WIDTH 0x11
#define USIF_SWCID_SWCID_MASK 0xffff8000
#define USIF_SWCID_SWCID(_reg) (((_reg) & 0xffff8000) >> 0xf)
#define USIF_SWCID_CRCPL_OFFSET 0xe
#define USIF_SWCID_CRCPL_WIDTH 0x1
#define USIF_SWCID_CRCPL_MASK 0x4000
#define USIF_SWCID_CRCPL(_reg) (((_reg) & 0x4000) >> 0xe)
#define USIF_SWCID_CRCPL_CRC16 (0x0 << USIF_SWCID_CRCPL_OFFSET)
#define USIF_SWCID_CRCPL_CRC32 (0x1 << USIF_SWCID_CRCPL_OFFSET)
#define USIF_SWCID_DMA_OFFSET 0xd
#define USIF_SWCID_DMA_WIDTH 0x1
#define USIF_SWCID_DMA_MASK 0x2000
#define USIF_SWCID_DMA(_reg) (((_reg) & 0x2000) >> 0xd)
#define USIF_SWCID_DMA_ARM (0x0 << USIF_SWCID_DMA_OFFSET)
#define USIF_SWCID_DMA_DPLUS (0x1 << USIF_SWCID_DMA_OFFSET)
#define USIF_SWCID_ACS_OFFSET 0xb
#define USIF_SWCID_ACS_WIDTH 0x2
#define USIF_SWCID_ACS_MASK 0x1800
#define USIF_SWCID_ACS(_reg) (((_reg) & 0x1800) >> 0xb)
#define USIF_SWCID_ACS_DIS (0x0 << USIF_SWCID_ACS_OFFSET)
#define USIF_SWCID_ACS_EN_ONE (0x1 << USIF_SWCID_ACS_OFFSET)
#define USIF_SWCID_ACS_EN_ALL (0x2 << USIF_SWCID_ACS_OFFSET)
#define USIF_SWCID_ACS_RES (0x3 << USIF_SWCID_ACS_OFFSET)
#define USIF_SWCID_SSC_OFFSET 0xa
#define USIF_SWCID_SSC_WIDTH 0x1
#define USIF_SWCID_SSC_MASK 0x400
#define USIF_SWCID_SSC(_reg) (((_reg) & 0x400) >> 0xa)
#define USIF_SWCID_SSC_DIS (0x0 << USIF_SWCID_SSC_OFFSET)
#define USIF_SWCID_SSC_EN (0x1 << USIF_SWCID_SSC_OFFSET)
#define USIF_SWCID_ABD_OFFSET 0x9
#define USIF_SWCID_ABD_WIDTH 0x1
#define USIF_SWCID_ABD_MASK 0x200
#define USIF_SWCID_ABD(_reg) (((_reg) & 0x200) >> 0x9)
#define USIF_SWCID_ABD_DIS (0x0 << USIF_SWCID_ABD_OFFSET)
#define USIF_SWCID_ABD_EN (0x1 << USIF_SWCID_ABD_OFFSET)
#define USIF_SWCID_SLIP_OFFSET 0x8
#define USIF_SWCID_SLIP_WIDTH 0x1
#define USIF_SWCID_SLIP_MASK 0x100
#define USIF_SWCID_SLIP(_reg) (((_reg) & 0x100) >> 0x8)
#define USIF_SWCID_SLIP_DIS (0x0 << USIF_SWCID_SLIP_OFFSET)
#define USIF_SWCID_SLIP_EN (0x1 << USIF_SWCID_SLIP_OFFSET)
#define USIF_SWCID_CRC_OFFSET 0x7
#define USIF_SWCID_CRC_WIDTH 0x1
#define USIF_SWCID_CRC_MASK 0x80
#define USIF_SWCID_CRC(_reg) (((_reg) & 0x80) >> 0x7)
#define USIF_SWCID_CRC_DIS (0x0 << USIF_SWCID_CRC_OFFSET)
#define USIF_SWCID_CRC_EN (0x1 << USIF_SWCID_CRC_OFFSET)
#define USIF_SWCID_MSS_OFFSET 0x6
#define USIF_SWCID_MSS_WIDTH 0x1
#define USIF_SWCID_MSS_MASK 0x40
#define USIF_SWCID_MSS(_reg) (((_reg) & 0x40) >> 0x6)
#define USIF_SWCID_MSS_DIS (0x0 << USIF_SWCID_MSS_OFFSET)
#define USIF_SWCID_MSS_EN (0x1 << USIF_SWCID_MSS_OFFSET)
#define USIF_SWCID_FM_OFFSET 0x5
#define USIF_SWCID_FM_WIDTH 0x1
#define USIF_SWCID_FM_MASK 0x20
#define USIF_SWCID_FM(_reg) (((_reg) & 0x20) >> 0x5)
#define USIF_SWCID_FM_DIS (0x0 << USIF_SWCID_FM_OFFSET)
#define USIF_SWCID_FM_EN (0x1 << USIF_SWCID_FM_OFFSET)
#define USIF_SWCID_DADW_OFFSET 0x0
#define USIF_SWCID_DADW_WIDTH 0x5
#define USIF_SWCID_DADW_MASK 0x1f
#define USIF_SWCID_DADW(_reg) (((_reg) & 0x1f) >> 0x0)

#define USIF_CLC_OFFSET		  0x0
#define USIF_CLC(_base) ((_base) + 0x0)
#define USIF_CLC_IDREN_OFFSET 0xa
#define USIF_CLC_IDREN_WIDTH 0x2
#define USIF_CLC_IDREN_MASK 0xc00
#define USIF_CLC_IDREN(_reg) (((_reg) & 0xc00) >> 0xa)
#define USIF_CLC_IDREN_IDRDIS (0x2 << USIF_CLC_IDREN_OFFSET)
#define USIF_CLC_IDREN_IDREN (0x1 << USIF_CLC_IDREN_OFFSET)
#define USIF_CLC_EDREN_OFFSET 0x8
#define USIF_CLC_EDREN_WIDTH 0x2
#define USIF_CLC_EDREN_MASK 0x300
#define USIF_CLC_EDREN(_reg) (((_reg) & 0x300) >> 0x8)
#define USIF_CLC_EDREN_EDRDIS (0x2 << USIF_CLC_EDREN_OFFSET)
#define USIF_CLC_EDREN_EDREN (0x1 << USIF_CLC_EDREN_OFFSET)
#define USIF_CLC_FSOE_OFFSET 0x6
#define USIF_CLC_FSOE_WIDTH 0x2
#define USIF_CLC_FSOE_MASK 0xc0
#define USIF_CLC_FSOE(_reg) (((_reg) & 0xc0) >> 0x6)
#define USIF_CLC_FSOE_FSODIS (0x2 << USIF_CLC_FSOE_OFFSET)
#define USIF_CLC_FSOE_FSOEN (0x1 << USIF_CLC_FSOE_OFFSET)
#define USIF_CLC_SPEN_OFFSET 0x4
#define USIF_CLC_SPEN_WIDTH 0x2
#define USIF_CLC_SPEN_MASK 0x30
#define USIF_CLC_SPEN(_reg) (((_reg) & 0x30) >> 0x4)
#define USIF_CLC_SPEN_SPDIS (0x2 << USIF_CLC_SPEN_OFFSET)
#define USIF_CLC_SPEN_SPEN (0x1 << USIF_CLC_SPEN_OFFSET)
#define USIF_CLC_MOD_EN_OFFSET 0x2
#define USIF_CLC_MOD_EN_WIDTH 0x2
#define USIF_CLC_MOD_EN_MASK 0xc
#define USIF_CLC_MOD_EN(_reg) (((_reg) & 0xc) >> 0x2)
#define USIF_CLC_MOD_EN_DIS_REQ (0x2 << USIF_CLC_MOD_EN_OFFSET)
#define USIF_CLC_MOD_EN_EN_REQ (0x1 << USIF_CLC_MOD_EN_OFFSET)
#define USIF_CLC_RUN_OFFSET 0x0
#define USIF_CLC_RUN_WIDTH 0x2
#define USIF_CLC_RUN_MASK 0x3
#define USIF_CLC_RUN(_reg) (((_reg) & 0x3) >> 0x0)
#define USIF_CLC_RUN_STOP (0x2 << USIF_CLC_RUN_OFFSET)
#define USIF_CLC_RUN_RUN (0x1 << USIF_CLC_RUN_OFFSET)

#define USIF_CLC_CNT_OFFSET	  0x4
#define USIF_CLC_CNT(_base) ((_base) + 0x4)
#define USIF_CLC_CNT_ORMCSMC_OFFSET 0x8
#define USIF_CLC_CNT_ORMCSMC_WIDTH 0x8
#define USIF_CLC_CNT_ORMCSMC_MASK 0xff00
#define USIF_CLC_CNT_ORMCSMC(_reg) (((_reg) & 0xff00) >> 0x8)
#define USIF_CLC_CNT_RMC_OFFSET 0x0
#define USIF_CLC_CNT_RMC_WIDTH 0x8
#define USIF_CLC_CNT_RMC_MASK 0xff
#define USIF_CLC_CNT_RMC(_reg) (((_reg) & 0xff) >> 0x0)

#define USIF_CLC_STAT_OFFSET	  0x8
#define USIF_CLC_STAT(_base) ((_base) + 0x8)
#define USIF_CLC_STAT_FIFOID_OFFSET 0x8
#define USIF_CLC_STAT_FIFOID_WIDTH 0x1
#define USIF_CLC_STAT_FIFOID_MASK 0x100
#define USIF_CLC_STAT_FIFOID(_reg) (((_reg) & 0x100) >> 0x8)
#define USIF_CLC_STAT_FIFOID_FIFOACT (0x0 << USIF_CLC_STAT_FIFOID_OFFSET)
#define USIF_CLC_STAT_FIFOID_FIFOIDLE (0x1 << USIF_CLC_STAT_FIFOID_OFFSET)
#define USIF_CLC_STAT_KID_OFFSET 0x7
#define USIF_CLC_STAT_KID_WIDTH 0x1
#define USIF_CLC_STAT_KID_MASK 0x80
#define USIF_CLC_STAT_KID(_reg) (((_reg) & 0x80) >> 0x7)
#define USIF_CLC_STAT_KID_KEACT (0x0 << USIF_CLC_STAT_KID_OFFSET)
#define USIF_CLC_STAT_KID_KEIDLE (0x1 << USIF_CLC_STAT_KID_OFFSET)
#define USIF_CLC_STAT_CUOK_OFFSET 0x6
#define USIF_CLC_STAT_CUOK_WIDTH 0x1
#define USIF_CLC_STAT_CUOK_MASK 0x40
#define USIF_CLC_STAT_CUOK(_reg) (((_reg) & 0x40) >> 0x6)
#define USIF_CLC_STAT_CUOK_CUACT (0x0 << USIF_CLC_STAT_CUOK_OFFSET)
#define USIF_CLC_STAT_CUOK_CUOK (0x1 << USIF_CLC_STAT_CUOK_OFFSET)
#define USIF_CLC_STAT_IDRE_OFFSET 0x5
#define USIF_CLC_STAT_IDRE_WIDTH 0x1
#define USIF_CLC_STAT_IDRE_MASK 0x20
#define USIF_CLC_STAT_IDRE(_reg) (((_reg) & 0x20) >> 0x5)
#define USIF_CLC_STAT_IDRE_IDRE (0x0 << USIF_CLC_STAT_IDRE_OFFSET)
#define USIF_CLC_STAT_IDRE_IDRD (0x1 << USIF_CLC_STAT_IDRE_OFFSET)
#define USIF_CLC_STAT_EDRE_OFFSET 0x4
#define USIF_CLC_STAT_EDRE_WIDTH 0x1
#define USIF_CLC_STAT_EDRE_MASK 0x10
#define USIF_CLC_STAT_EDRE(_reg) (((_reg) & 0x10) >> 0x4)
#define USIF_CLC_STAT_EDRE_EDREENABLED (0x0 << USIF_CLC_STAT_EDRE_OFFSET)
#define USIF_CLC_STAT_EDRE_EDRDDISABLED (0x1 << USIF_CLC_STAT_EDRE_OFFSET)
#define USIF_CLC_STAT_FSOE_OFFSET 0x3
#define USIF_CLC_STAT_FSOE_WIDTH 0x1
#define USIF_CLC_STAT_FSOE_MASK 0x8
#define USIF_CLC_STAT_FSOE(_reg) (((_reg) & 0x8) >> 0x3)
#define USIF_CLC_STAT_FSOE_FSODDISABLED (0x0 << USIF_CLC_STAT_FSOE_OFFSET)
#define USIF_CLC_STAT_FSOE_FSOEENABLED (0x1 << USIF_CLC_STAT_FSOE_OFFSET)
#define USIF_CLC_STAT_SPEN_OFFSET 0x2
#define USIF_CLC_STAT_SPEN_WIDTH 0x1
#define USIF_CLC_STAT_SPEN_MASK 0x4
#define USIF_CLC_STAT_SPEN(_reg) (((_reg) & 0x4) >> 0x2)
#define USIF_CLC_STAT_SPEN_SPEN (0x0 << USIF_CLC_STAT_SPEN_OFFSET)
#define USIF_CLC_STAT_SPEN_SPDIS (0x1 << USIF_CLC_STAT_SPEN_OFFSET)
#define USIF_CLC_STAT_MODEN_OFFSET 0x1
#define USIF_CLC_STAT_MODEN_WIDTH 0x1
#define USIF_CLC_STAT_MODEN_MASK 0x2
#define USIF_CLC_STAT_MODEN(_reg) (((_reg) & 0x2) >> 0x1)
#define USIF_CLC_STAT_MODEN_VAL(_reg) ((_reg) & 0x2)
#define USIF_CLC_STAT_MODEN_MOD_DIS (0x0 << USIF_CLC_STAT_MODEN_OFFSET)
#define USIF_CLC_STAT_MODEN_MOD_EN (0x1 << USIF_CLC_STAT_MODEN_OFFSET)
#define USIF_CLC_STAT_RUN_OFFSET 0x0
#define USIF_CLC_STAT_RUN_WIDTH 0x1
#define USIF_CLC_STAT_RUN_MASK 0x1
#define USIF_CLC_STAT_RUN(_reg) (((_reg) & 0x1) >> 0x0)
#define USIF_CLC_STAT_RUN_CFG (0x0 << USIF_CLC_STAT_RUN_OFFSET)
#define USIF_CLC_STAT_RUN_RUN (0x1 << USIF_CLC_STAT_RUN_OFFSET)

#define USIF_MSS_SET_OFFSET	  0x100
#define USIF_MSS_SET(_base) ((_base) + 0x100)
#define USIF_MSS_SET_RISET_OFFSET 0x5
#define USIF_MSS_SET_RISET_WIDTH 0x1
#define USIF_MSS_SET_RISET_MASK 0x20
#define USIF_MSS_SET_RISET(_reg) (((_reg) & 0x20) >> 0x5)
#define USIF_MSS_SET_RISET_NE (0x0 << USIF_MSS_SET_RISET_OFFSET)
#define USIF_MSS_SET_RISET_RI (0x1 << USIF_MSS_SET_RISET_OFFSET)
#define USIF_MSS_SET_DCDSET_OFFSET 0x4
#define USIF_MSS_SET_DCDSET_WIDTH 0x1
#define USIF_MSS_SET_DCDSET_MASK 0x10
#define USIF_MSS_SET_DCDSET(_reg) (((_reg) & 0x10) >> 0x4)
#define USIF_MSS_SET_DCDSET_NE (0x0 << USIF_MSS_SET_DCDSET_OFFSET)
#define USIF_MSS_SET_DCDSET_DCD (0x1 << USIF_MSS_SET_DCDSET_OFFSET)
#define USIF_MSS_SET_DSRSET_OFFSET 0x3
#define USIF_MSS_SET_DSRSET_WIDTH 0x1
#define USIF_MSS_SET_DSRSET_MASK 0x8
#define USIF_MSS_SET_DSRSET(_reg) (((_reg) & 0x8) >> 0x3)
#define USIF_MSS_SET_DSRSET_NE (0x0 << USIF_MSS_SET_DSRSET_OFFSET)
#define USIF_MSS_SET_DSRSET_DSR (0x1 << USIF_MSS_SET_DSRSET_OFFSET)
#define USIF_MSS_SET_DTRSET_OFFSET 0x2
#define USIF_MSS_SET_DTRSET_WIDTH 0x1
#define USIF_MSS_SET_DTRSET_MASK 0x4
#define USIF_MSS_SET_DTRSET(_reg) (((_reg) & 0x4) >> 0x2)
#define USIF_MSS_SET_DTRSET_NE (0x0 << USIF_MSS_SET_DTRSET_OFFSET)
#define USIF_MSS_SET_DTRSET_DTR (0x1 << USIF_MSS_SET_DTRSET_OFFSET)
#define USIF_MSS_SET_FCOSET_OFFSET 0x0
#define USIF_MSS_SET_FCOSET_WIDTH 0x1
#define USIF_MSS_SET_FCOSET_MASK 0x1
#define USIF_MSS_SET_FCOSET(_reg) (((_reg) & 0x1) >> 0x0)
#define USIF_MSS_SET_FCOSET_NE (0x0 << USIF_MSS_SET_FCOSET_OFFSET)
#define USIF_MSS_SET_FCOSET_FCO (0x1 << USIF_MSS_SET_FCOSET_OFFSET)

#define USIF_MSS_CLR_OFFSET	  0x104
#define USIF_MSS_CLR(_base) ((_base) + 0x104)
#define USIF_MSS_CLR_RICLR_OFFSET 0x5
#define USIF_MSS_CLR_RICLR_WIDTH 0x1
#define USIF_MSS_CLR_RICLR_MASK 0x20
#define USIF_MSS_CLR_RICLR(_reg) (((_reg) & 0x20) >> 0x5)
#define USIF_MSS_CLR_RICLR_NE (0x0 << USIF_MSS_CLR_RICLR_OFFSET)
#define USIF_MSS_CLR_RICLR_RI (0x1 << USIF_MSS_CLR_RICLR_OFFSET)
#define USIF_MSS_CLR_DCDCLR_OFFSET 0x4
#define USIF_MSS_CLR_DCDCLR_WIDTH 0x1
#define USIF_MSS_CLR_DCDCLR_MASK 0x10
#define USIF_MSS_CLR_DCDCLR(_reg) (((_reg) & 0x10) >> 0x4)
#define USIF_MSS_CLR_DCDCLR_NE (0x0 << USIF_MSS_CLR_DCDCLR_OFFSET)
#define USIF_MSS_CLR_DCDCLR_DCD (0x1 << USIF_MSS_CLR_DCDCLR_OFFSET)
#define USIF_MSS_CLR_DSRCLR_OFFSET 0x3
#define USIF_MSS_CLR_DSRCLR_WIDTH 0x1
#define USIF_MSS_CLR_DSRCLR_MASK 0x8
#define USIF_MSS_CLR_DSRCLR(_reg) (((_reg) & 0x8) >> 0x3)
#define USIF_MSS_CLR_DSRCLR_NE (0x0 << USIF_MSS_CLR_DSRCLR_OFFSET)
#define USIF_MSS_CLR_DSRCLR_DSR (0x1 << USIF_MSS_CLR_DSRCLR_OFFSET)
#define USIF_MSS_CLR_DTRCLR_OFFSET 0x2
#define USIF_MSS_CLR_DTRCLR_WIDTH 0x1
#define USIF_MSS_CLR_DTRCLR_MASK 0x4
#define USIF_MSS_CLR_DTRCLR(_reg) (((_reg) & 0x4) >> 0x2)
#define USIF_MSS_CLR_DTRCLR_NE (0x0 << USIF_MSS_CLR_DTRCLR_OFFSET)
#define USIF_MSS_CLR_DTRCLR_DTR (0x1 << USIF_MSS_CLR_DTRCLR_OFFSET)
#define USIF_MSS_CLR_FCOCLR_OFFSET 0x0
#define USIF_MSS_CLR_FCOCLR_WIDTH 0x1
#define USIF_MSS_CLR_FCOCLR_MASK 0x1
#define USIF_MSS_CLR_FCOCLR(_reg) (((_reg) & 0x1) >> 0x0)
#define USIF_MSS_CLR_FCOCLR_NE (0x0 << USIF_MSS_CLR_FCOCLR_OFFSET)
#define USIF_MSS_CLR_FCOCLR_FCO (0x1 << USIF_MSS_CLR_FCOCLR_OFFSET)

#define USIF_MSS_STAT_OFFSET	  0x108
#define USIF_MSS_STAT(_base) ((_base) + 0x108)
#define USIF_MSS_STAT_RI_OFFSET 0x5
#define USIF_MSS_STAT_RI_WIDTH 0x1
#define USIF_MSS_STAT_RI_MASK 0x20
#define USIF_MSS_STAT_RI(_reg) (((_reg) & 0x20) >> 0x5)
#define USIF_MSS_STAT_RI_INACT (0x0 << USIF_MSS_STAT_RI_OFFSET)
#define USIF_MSS_STAT_RI_ACT (0x1 << USIF_MSS_STAT_RI_OFFSET)
#define USIF_MSS_STAT_DCD_OFFSET 0x4
#define USIF_MSS_STAT_DCD_WIDTH 0x1
#define USIF_MSS_STAT_DCD_MASK 0x10
#define USIF_MSS_STAT_DCD(_reg) (((_reg) & 0x10) >> 0x4)
#define USIF_MSS_STAT_DCD_INACT (0x0 << USIF_MSS_STAT_DCD_OFFSET)
#define USIF_MSS_STAT_DCD_ACT (0x1 << USIF_MSS_STAT_DCD_OFFSET)
#define USIF_MSS_STAT_DSR_OFFSET 0x3
#define USIF_MSS_STAT_DSR_WIDTH 0x1
#define USIF_MSS_STAT_DSR_MASK 0x8
#define USIF_MSS_STAT_DSR(_reg) (((_reg) & 0x8) >> 0x3)
#define USIF_MSS_STAT_DSR_INACT (0x0 << USIF_MSS_STAT_DSR_OFFSET)
#define USIF_MSS_STAT_DSR_ACT (0x1 << USIF_MSS_STAT_DSR_OFFSET)
#define USIF_MSS_STAT_DTR_OFFSET 0x2
#define USIF_MSS_STAT_DTR_WIDTH 0x1
#define USIF_MSS_STAT_DTR_MASK 0x4
#define USIF_MSS_STAT_DTR(_reg) (((_reg) & 0x4) >> 0x2)
#define USIF_MSS_STAT_DTR_INACT (0x0 << USIF_MSS_STAT_DTR_OFFSET)
#define USIF_MSS_STAT_DTR_ACT (0x1 << USIF_MSS_STAT_DTR_OFFSET)
#define USIF_MSS_STAT_FCI_OFFSET 0x1
#define USIF_MSS_STAT_FCI_WIDTH 0x1
#define USIF_MSS_STAT_FCI_MASK 0x2
#define USIF_MSS_STAT_FCI(_reg) (((_reg) & 0x2) >> 0x1)
#define USIF_MSS_STAT_FCI_INACT (0x0 << USIF_MSS_STAT_FCI_OFFSET)
#define USIF_MSS_STAT_FCI_ACT (0x1 << USIF_MSS_STAT_FCI_OFFSET)
#define USIF_MSS_STAT_FCO_OFFSET 0x0
#define USIF_MSS_STAT_FCO_WIDTH 0x1
#define USIF_MSS_STAT_FCO_MASK 0x1
#define USIF_MSS_STAT_FCO(_reg) (((_reg) & 0x1) >> 0x0)
#define USIF_MSS_STAT_FCO_INACT (0x0 << USIF_MSS_STAT_FCO_OFFSET)
#define USIF_MSS_STAT_FCO_ACT (0x1 << USIF_MSS_STAT_FCO_OFFSET)

#define USIF_MSS_CTRL_OFFSET	  0x10c
#define USIF_MSS_CTRL(_base) ((_base) + 0x10c)
#define USIF_MSS_CTRL_FCOEN_OFFSET 0x1
#define USIF_MSS_CTRL_FCOEN_WIDTH 0x1
#define USIF_MSS_CTRL_FCOEN_MASK 0x2
#define USIF_MSS_CTRL_FCOEN(_reg) (((_reg) & 0x2) >> 0x1)
#define USIF_MSS_CTRL_FCOEN_FCODIS (0x0 << USIF_MSS_CTRL_FCOEN_OFFSET)
#define USIF_MSS_CTRL_FCOEN_FCOEN (0x1 << USIF_MSS_CTRL_FCOEN_OFFSET)
#define USIF_MSS_CTRL_FCIEN_OFFSET 0x0
#define USIF_MSS_CTRL_FCIEN_WIDTH 0x1
#define USIF_MSS_CTRL_FCIEN_MASK 0x1
#define USIF_MSS_CTRL_FCIEN(_reg) (((_reg) & 0x1) >> 0x0)
#define USIF_MSS_CTRL_FCIEN_FCIDIS (0x0 << USIF_MSS_CTRL_FCIEN_OFFSET)
#define USIF_MSS_CTRL_FCIEN_FCIEN (0x1 << USIF_MSS_CTRL_FCIEN_OFFSET)

#define USIF_MODE_CFG_OFFSET	  0x110
#define USIF_MODE_CFG(_base) ((_base) + 0x110)
#define USIF_MODE_CFG_TXEN_OFFSET 0x10
#define USIF_MODE_CFG_TXEN_WIDTH 0x1
#define USIF_MODE_CFG_TXEN_MASK 0x10000
#define USIF_MODE_CFG_TXEN(_reg) (((_reg) & 0x10000) >> 0x10)
#define USIF_MODE_CFG_TXEN_DIS (0x0 << USIF_MODE_CFG_TXEN_OFFSET)
#define USIF_MODE_CFG_TXEN_EN (0x1 << USIF_MODE_CFG_TXEN_OFFSET)
#define USIF_MODE_CFG_HDEN_OFFSET 0xf
#define USIF_MODE_CFG_HDEN_WIDTH 0x1
#define USIF_MODE_CFG_HDEN_MASK 0x8000
#define USIF_MODE_CFG_HDEN(_reg) (((_reg) & 0x8000) >> 0xf)
#define USIF_MODE_CFG_HDEN_DIS (0x0 << USIF_MODE_CFG_HDEN_OFFSET)
#define USIF_MODE_CFG_HDEN_EN (0x1 << USIF_MODE_CFG_HDEN_OFFSET)
#define USIF_MODE_CFG_EQU_OFFSET 0xe
#define USIF_MODE_CFG_EQU_WIDTH 0x1
#define USIF_MODE_CFG_EQU_MASK 0x4000
#define USIF_MODE_CFG_EQU(_reg) (((_reg) & 0x4000) >> 0xe)
#define USIF_MODE_CFG_EQU_DTE (0x0 << USIF_MODE_CFG_EQU_OFFSET)
#define USIF_MODE_CFG_EQU_DCE (0x1 << USIF_MODE_CFG_EQU_OFFSET)
#define USIF_MODE_CFG_ECEN_OFFSET 0xd
#define USIF_MODE_CFG_ECEN_WIDTH 0x1
#define USIF_MODE_CFG_ECEN_MASK 0x2000
#define USIF_MODE_CFG_ECEN(_reg) (((_reg) & 0x2000) >> 0xd)
#define USIF_MODE_CFG_ECEN_DIS (0x0 << USIF_MODE_CFG_ECEN_OFFSET)
#define USIF_MODE_CFG_ECEN_EN (0x1 << USIF_MODE_CFG_ECEN_OFFSET)
#define USIF_MODE_CFG_ABEN_OFFSET 0xc
#define USIF_MODE_CFG_ABEN_WIDTH 0x1
#define USIF_MODE_CFG_ABEN_MASK 0x1000
#define USIF_MODE_CFG_ABEN(_reg) (((_reg) & 0x1000) >> 0xc)
#define USIF_MODE_CFG_TX_IDLE_OFFSET 0xb
#define USIF_MODE_CFG_TX_IDLE_WIDTH 0x1
#define USIF_MODE_CFG_TX_IDLE_MASK 0x800
#define USIF_MODE_CFG_TX_IDLE(_reg) (((_reg) & 0x800) >> 0xb)
#define USIF_MODE_CFG_TX_IDLE_LOW (0x0 << USIF_MODE_CFG_TX_IDLE_OFFSET)
#define USIF_MODE_CFG_TX_IDLE_HIGH (0x1 << USIF_MODE_CFG_TX_IDLE_OFFSET)
#define USIF_MODE_CFG_SCPH_OFFSET 0xa
#define USIF_MODE_CFG_SCPH_WIDTH 0x1
#define USIF_MODE_CFG_SCPH_MASK 0x400
#define USIF_MODE_CFG_SCPH(_reg) (((_reg) & 0x400) >> 0xa)
#define USIF_MODE_CFG_SCPH_LEAD (0x0 << USIF_MODE_CFG_SCPH_OFFSET)
#define USIF_MODE_CFG_SCPH_TRAIL (0x1 << USIF_MODE_CFG_SCPH_OFFSET)
#define USIF_MODE_CFG_SCPOL_OFFSET 0x9
#define USIF_MODE_CFG_SCPOL_WIDTH 0x1
#define USIF_MODE_CFG_SCPOL_MASK 0x200
#define USIF_MODE_CFG_SCPOL(_reg) (((_reg) & 0x200) >> 0x9)
#define USIF_MODE_CFG_SCPOL_LOW (0x0 << USIF_MODE_CFG_SCPOL_OFFSET)
#define USIF_MODE_CFG_SCPOL_HIGH (0x1 << USIF_MODE_CFG_SCPOL_OFFSET)
#define USIF_MODE_CFG_SCFRC_OFFSET 0x8
#define USIF_MODE_CFG_SCFRC_WIDTH 0x1
#define USIF_MODE_CFG_SCFRC_MASK 0x100
#define USIF_MODE_CFG_SCFRC(_reg) (((_reg) & 0x100) >> 0x8)
#define USIF_MODE_CFG_SCFRC_NORM (0x0 << USIF_MODE_CFG_SCFRC_OFFSET)
#define USIF_MODE_CFG_SCFRC_FORCED (0x1 << USIF_MODE_CFG_SCFRC_OFFSET)
#define USIF_MODE_CFG_RXINV_OFFSET 0x7
#define USIF_MODE_CFG_RXINV_WIDTH 0x1
#define USIF_MODE_CFG_RXINV_MASK 0x80
#define USIF_MODE_CFG_RXINV(_reg) (((_reg) & 0x80) >> 0x7)
#define USIF_MODE_CFG_RXINV_NO (0x0 << USIF_MODE_CFG_RXINV_OFFSET)
#define USIF_MODE_CFG_RXINV_INV (0x1 << USIF_MODE_CFG_RXINV_OFFSET)
#define USIF_MODE_CFG_TXINV_OFFSET 0x6
#define USIF_MODE_CFG_TXINV_WIDTH 0x1
#define USIF_MODE_CFG_TXINV_MASK 0x40
#define USIF_MODE_CFG_TXINV(_reg) (((_reg) & 0x40) >> 0x6)
#define USIF_MODE_CFG_TXINV_NO (0x0 << USIF_MODE_CFG_TXINV_OFFSET)
#define USIF_MODE_CFG_TXINV_INC (0x1 << USIF_MODE_CFG_TXINV_OFFSET)
#define USIF_MODE_CFG_ECH_OFFSET 0x5
#define USIF_MODE_CFG_ECH_WIDTH 0x1
#define USIF_MODE_CFG_ECH_MASK 0x20
#define USIF_MODE_CFG_ECH(_reg) (((_reg) & 0x20) >> 0x5)
#define USIF_MODE_CFG_ECH_DIS (0x0 << USIF_MODE_CFG_ECH_OFFSET)
#define USIF_MODE_CFG_ECH_ECHO (0x1 << USIF_MODE_CFG_ECH_OFFSET)
#define USIF_MODE_CFG_LB_OFFSET 0x4
#define USIF_MODE_CFG_LB_WIDTH 0x1
#define USIF_MODE_CFG_LB_MASK 0x10
#define USIF_MODE_CFG_LB(_reg) (((_reg) & 0x10) >> 0x4)
#define USIF_MODE_CFG_LB_DIS (0x0 << USIF_MODE_CFG_LB_OFFSET)
#define USIF_MODE_CFG_LB_LOOP (0x1 << USIF_MODE_CFG_LB_OFFSET)
#define USIF_MODE_CFG_FCEN_OFFSET 0x3
#define USIF_MODE_CFG_FCEN_WIDTH 0x1
#define USIF_MODE_CFG_FCEN_MASK 0x8
#define USIF_MODE_CFG_FCEN(_reg) (((_reg) & 0x8) >> 0x3)
#define USIF_MODE_CFG_FCEN_DIS (0x0 << USIF_MODE_CFG_FCEN_OFFSET)
#define USIF_MODE_CFG_FCEN_EN (0x1 << USIF_MODE_CFG_FCEN_OFFSET)
#define USIF_MODE_CFG_RXEN_OFFSET 0x2
#define USIF_MODE_CFG_RXEN_WIDTH 0x1
#define USIF_MODE_CFG_RXEN_MASK 0x4
#define USIF_MODE_CFG_RXEN(_reg) (((_reg) & 0x4) >> 0x2)
#define USIF_MODE_CFG_RXEN_DIS (0x0 << USIF_MODE_CFG_RXEN_OFFSET)
#define USIF_MODE_CFG_RXEN_EN (0x1 << USIF_MODE_CFG_RXEN_OFFSET)
#define USIF_MODE_CFG_MA_OFFSET 0x1
#define USIF_MODE_CFG_MA_WIDTH 0x1
#define USIF_MODE_CFG_MA_MASK 0x2
#define USIF_MODE_CFG_MA(_reg) (((_reg) & 0x2) >> 0x1)
#define USIF_MODE_CFG_MA_SLAVE (0x0 << USIF_MODE_CFG_MA_OFFSET)
#define USIF_MODE_CFG_MA_MASTER (0x1 << USIF_MODE_CFG_MA_OFFSET)
#define USIF_MODE_CFG_SYNC_OFFSET 0x0
#define USIF_MODE_CFG_SYNC_WIDTH 0x1
#define USIF_MODE_CFG_SYNC_MASK 0x1
#define USIF_MODE_CFG_SYNC(_reg) (((_reg) & 0x1) >> 0x0)
#define USIF_MODE_CFG_SYNC_ASYN (0x0 << USIF_MODE_CFG_SYNC_OFFSET)
#define USIF_MODE_CFG_SYNC_SYN (0x1 << USIF_MODE_CFG_SYNC_OFFSET)

#define USIF_PRTC_CFG_OFFSET	  0x114
#define USIF_PRTC_CFG(_base) ((_base) + 0x114)
#define USIF_PRTC_CFG_HDLC_OFFSET 0x1e
#define USIF_PRTC_CFG_HDLC_WIDTH 0x1
#define USIF_PRTC_CFG_HDLC_MASK 0x40000000
#define USIF_PRTC_CFG_HDLC(_reg) (((_reg) & 0x40000000) >> 0x1e)
#define USIF_PRTC_CFG_HDLC_SR1055 (0x0 << USIF_PRTC_CFG_HDLC_OFFSET)
#define USIF_PRTC_CFG_HDLC_HR1662 (0x1 << USIF_PRTC_CFG_HDLC_OFFSET)
#define USIF_PRTC_CFG_SLIPEXT_OFFSET 0x1d
#define USIF_PRTC_CFG_SLIPEXT_WIDTH 0x1
#define USIF_PRTC_CFG_SLIPEXT_MASK 0x20000000
#define USIF_PRTC_CFG_SLIPEXT(_reg) (((_reg) & 0x20000000) >> 0x1d)
#define USIF_PRTC_CFG_SLIPEXT_STD (0x0 << USIF_PRTC_CFG_SLIPEXT_OFFSET)
#define USIF_PRTC_CFG_SLIPEXT_EXT (0x1 << USIF_PRTC_CFG_SLIPEXT_OFFSET)
#define USIF_PRTC_CFG_SLIPEN_OFFSET 0x1c
#define USIF_PRTC_CFG_SLIPEN_WIDTH 0x1
#define USIF_PRTC_CFG_SLIPEN_MASK 0x10000000
#define USIF_PRTC_CFG_SLIPEN(_reg) (((_reg) & 0x10000000) >> 0x1c)
#define USIF_PRTC_CFG_FCOTL_OFFSET 0x14
#define USIF_PRTC_CFG_FCOTL_WIDTH 0x6
#define USIF_PRTC_CFG_FCOTL_MASK 0x3f00000
#define USIF_PRTC_CFG_FCOTL(_reg) (((_reg) & 0x3f00000) >> 0x14)
#define USIF_PRTC_CFG_FC_S_ICTO_OFFSET 0x13
#define USIF_PRTC_CFG_FC_S_ICTO_WIDTH 0x1
#define USIF_PRTC_CFG_FC_S_ICTO_MASK 0x80000
#define USIF_PRTC_CFG_FC_S_ICTO(_reg) (((_reg) & 0x80000) >> 0x13)
#define USIF_PRTC_CFG_FC_S_ICTO_CONT (0x0 << USIF_PRTC_CFG_FC_S_ICTO_OFFSET)
#define USIF_PRTC_CFG_FC_S_ICTO_STOP (0x1 << USIF_PRTC_CFG_FC_S_ICTO_OFFSET)
#define USIF_PRTC_CFG_FCSINV_OFFSET 0x12
#define USIF_PRTC_CFG_FCSINV_WIDTH 0x1
#define USIF_PRTC_CFG_FCSINV_MASK 0x40000
#define USIF_PRTC_CFG_FCSINV(_reg) (((_reg) & 0x40000) >> 0x12)
#define USIF_PRTC_CFG_STP2_OFFSET 0xc
#define USIF_PRTC_CFG_STP2_WIDTH 0x1
#define USIF_PRTC_CFG_STP2_MASK 0x1000
#define USIF_PRTC_CFG_STP2(_reg) (((_reg) & 0x1000) >> 0xc)
#define USIF_PRTC_CFG_ERRFE_OFFSET 0xa
#define USIF_PRTC_CFG_ERRFE_WIDTH 0x1
#define USIF_PRTC_CFG_ERRFE_MASK 0x400
#define USIF_PRTC_CFG_ERRFE(_reg) (((_reg) & 0x400) >> 0xa)
#define USIF_PRTC_CFG_ERRFE_NOT (0x0 << USIF_PRTC_CFG_ERRFE_OFFSET)
#define USIF_PRTC_CFG_ERRFE_STO (0x1 << USIF_PRTC_CFG_ERRFE_OFFSET)
#define USIF_PRTC_CFG_ODD_OFFSET 0x9
#define USIF_PRTC_CFG_ODD_WIDTH 0x1
#define USIF_PRTC_CFG_ODD_MASK 0x200
#define USIF_PRTC_CFG_ODD(_reg) (((_reg) & 0x200) >> 0x9)
#define USIF_PRTC_CFG_ODD_EVEN (0x0 << USIF_PRTC_CFG_ODD_OFFSET)
#define USIF_PRTC_CFG_ODD_ODD (0x1 << USIF_PRTC_CFG_ODD_OFFSET)
#define USIF_PRTC_CFG_PAR_OFFSET 0x8
#define USIF_PRTC_CFG_PAR_WIDTH 0x1
#define USIF_PRTC_CFG_PAR_MASK 0x100
#define USIF_PRTC_CFG_PAR(_reg) (((_reg) & 0x100) >> 0x8)
#define USIF_PRTC_CFG_HD_OFFSET 0x7
#define USIF_PRTC_CFG_HD_WIDTH 0x1
#define USIF_PRTC_CFG_HD_MASK 0x80
#define USIF_PRTC_CFG_HD(_reg) (((_reg) & 0x80) >> 0x7)
#define USIF_PRTC_CFG_HD_LSB (0x0 << USIF_PRTC_CFG_HD_OFFSET)
#define USIF_PRTC_CFG_HD_MSB (0x1 << USIF_PRTC_CFG_HD_OFFSET)
#define USIF_PRTC_CFG_CLEN_OFFSET 0x0
#define USIF_PRTC_CFG_CLEN_WIDTH 0x5
#define USIF_PRTC_CFG_CLEN_MASK 0x1f
#define USIF_PRTC_CFG_CLEN(_reg) (((_reg) & 0x1f) >> 0x0)
#define USIF_PRTC_CFG_CLEN_N1 (0x1 << USIF_PRTC_CFG_CLEN_OFFSET)
#define USIF_PRTC_CFG_CLEN_N4 (0x4 << USIF_PRTC_CFG_CLEN_OFFSET)
#define USIF_PRTC_CFG_CLEN_N5 (0x5 << USIF_PRTC_CFG_CLEN_OFFSET)
#define USIF_PRTC_CFG_CLEN_N8 (0x8 << USIF_PRTC_CFG_CLEN_OFFSET)
#define USIF_PRTC_CFG_CLEN_N31 (0x1f << USIF_PRTC_CFG_CLEN_OFFSET)
#define USIF_PRTC_CFG_CLEN_N32 (0x0 << USIF_PRTC_CFG_CLEN_OFFSET)

#define USIF_PRTC_STAT_OFFSET	  0x118
#define USIF_PRTC_STAT(_base) ((_base) + 0x118)
#define USIF_PRTC_STAT_TXACT_OFFSET 0x1f
#define USIF_PRTC_STAT_TXACT_WIDTH 0x1
#define USIF_PRTC_STAT_TXACT_MASK 0x80000000
#define USIF_PRTC_STAT_TXACT(_reg) (((_reg) & 0x80000000) >> 0x1f)
#define USIF_PRTC_STAT_TXACT_IDLE (0x0 << USIF_PRTC_STAT_TXACT_OFFSET)
#define USIF_PRTC_STAT_TXACT_BSY (0x1 << USIF_PRTC_STAT_TXACT_OFFSET)
#define USIF_PRTC_STAT_BCRV_OFFSET 0x10
#define USIF_PRTC_STAT_BCRV_WIDTH 0xd
#define USIF_PRTC_STAT_BCRV_MASK 0x1fff0000
#define USIF_PRTC_STAT_BCRV(_reg) (((_reg) & 0x1fff0000) >> 0x10)
#define USIF_PRTC_STAT_AB_DONE_OFFSET 0xf
#define USIF_PRTC_STAT_AB_DONE_WIDTH 0x1
#define USIF_PRTC_STAT_AB_DONE_MASK 0x8000
#define USIF_PRTC_STAT_AB_DONE(_reg) (((_reg) & 0x8000) >> 0xf)
#define USIF_PRTC_STAT_AB_DONE_ZERO (0x0 << USIF_PRTC_STAT_AB_DONE_OFFSET)
#define USIF_PRTC_STAT_AB_DONE_DONE (0x1 << USIF_PRTC_STAT_AB_DONE_OFFSET)
#define USIF_PRTC_STAT_ODD_OFFSET 0x9
#define USIF_PRTC_STAT_ODD_WIDTH 0x1
#define USIF_PRTC_STAT_ODD_MASK 0x200
#define USIF_PRTC_STAT_ODD(_reg) (((_reg) & 0x200) >> 0x9)
#define USIF_PRTC_STAT_ODD_EVEN (0x0 << USIF_PRTC_STAT_ODD_OFFSET)
#define USIF_PRTC_STAT_ODD_ODD (0x1 << USIF_PRTC_STAT_ODD_OFFSET)
#define USIF_PRTC_STAT_PAR_OFFSET 0x8
#define USIF_PRTC_STAT_PAR_WIDTH 0x1
#define USIF_PRTC_STAT_PAR_MASK 0x100
#define USIF_PRTC_STAT_PAR(_reg) (((_reg) & 0x100) >> 0x8)
#define USIF_PRTC_STAT_CLEN_OFFSET 0x0
#define USIF_PRTC_STAT_CLEN_WIDTH 0x5
#define USIF_PRTC_STAT_CLEN_MASK 0x1f
#define USIF_PRTC_STAT_CLEN(_reg) (((_reg) & 0x1f) >> 0x0)
#define USIF_PRTC_STAT_CLEN_N1 (0x1 << USIF_PRTC_STAT_CLEN_OFFSET)
#define USIF_PRTC_STAT_CLEN_N4 (0x4 << USIF_PRTC_STAT_CLEN_OFFSET)
#define USIF_PRTC_STAT_CLEN_N5 (0x5 << USIF_PRTC_STAT_CLEN_OFFSET)
#define USIF_PRTC_STAT_CLEN_N8 (0x8 << USIF_PRTC_STAT_CLEN_OFFSET)
#define USIF_PRTC_STAT_CLEN_N31 (0x1f << USIF_PRTC_STAT_CLEN_OFFSET)
#define USIF_PRTC_STAT_CLEN_N32 (0x0 << USIF_PRTC_STAT_CLEN_OFFSET)

#define USIF_FRM_CTRL_OFFSET	  0x11c
#define USIF_FRM_CTRL(_base) ((_base) + 0x11c)
#define USIF_FRM_CTRL_PLEN_OFFSET 0x16
#define USIF_FRM_CTRL_PLEN_WIDTH 0xa
#define USIF_FRM_CTRL_PLEN_MASK 0xffc00000
#define USIF_FRM_CTRL_PLEN(_reg) (((_reg) & 0xffc00000) >> 0x16)
#define USIF_FRM_CTRL_STOP_OFFSET 0x14
#define USIF_FRM_CTRL_STOP_WIDTH 0x1
#define USIF_FRM_CTRL_STOP_MASK 0x100000
#define USIF_FRM_CTRL_STOP(_reg) (((_reg) & 0x100000) >> 0x14)
#define USIF_FRM_CTRL_STOP_OFF (0x0 << USIF_FRM_CTRL_STOP_OFFSET)
#define USIF_FRM_CTRL_STOP_ON (0x1 << USIF_FRM_CTRL_STOP_OFFSET)
#define USIF_FRM_CTRL_DLEN_OFFSET 0x4
#define USIF_FRM_CTRL_DLEN_WIDTH 0xc
#define USIF_FRM_CTRL_DLEN_MASK 0xfff0
#define USIF_FRM_CTRL_DLEN(_reg) (((_reg) & 0xfff0) >> 0x4)
#define USIF_FRM_CTRL_IAEN_OFFSET 0x3
#define USIF_FRM_CTRL_IAEN_WIDTH 0x1
#define USIF_FRM_CTRL_IAEN_MASK 0x8
#define USIF_FRM_CTRL_IAEN(_reg) (((_reg) & 0x8) >> 0x3)
#define USIF_FRM_CTRL_IAEN_OFF (0x0 << USIF_FRM_CTRL_IAEN_OFFSET)
#define USIF_FRM_CTRL_IAEN_EN (0x1 << USIF_FRM_CTRL_IAEN_OFFSET)
#define USIF_FRM_CTRL_IBEN_OFFSET 0x2
#define USIF_FRM_CTRL_IBEN_WIDTH 0x1
#define USIF_FRM_CTRL_IBEN_MASK 0x4
#define USIF_FRM_CTRL_IBEN(_reg) (((_reg) & 0x4) >> 0x2)
#define USIF_FRM_CTRL_IBEN_OFF (0x0 << USIF_FRM_CTRL_IBEN_OFFSET)
#define USIF_FRM_CTRL_IBEN_EN (0x1 << USIF_FRM_CTRL_IBEN_OFFSET)
#define USIF_FRM_CTRL_SFEN_OFFSET 0x0
#define USIF_FRM_CTRL_SFEN_WIDTH 0x1
#define USIF_FRM_CTRL_SFEN_MASK 0x1
#define USIF_FRM_CTRL_SFEN(_reg) (((_reg) & 0x1) >> 0x0)
#define USIF_FRM_CTRL_SFEN_OFF (0x0 << USIF_FRM_CTRL_SFEN_OFFSET)
#define USIF_FRM_CTRL_SFEN_ON (0x1 << USIF_FRM_CTRL_SFEN_OFFSET)

#define USIF_FRM_STAT_OFFSET	  0x120
#define USIF_FRM_STAT(_base) ((_base) + 0x120)
#define USIF_FRM_STAT_PCNT_OFFSET 0x16
#define USIF_FRM_STAT_PCNT_WIDTH 0xa
#define USIF_FRM_STAT_PCNT_MASK 0xffc00000
#define USIF_FRM_STAT_PCNT(_reg) (((_reg) & 0xffc00000) >> 0x16)
#define USIF_FRM_STAT_DCNT_OFFSET 0x4
#define USIF_FRM_STAT_DCNT_WIDTH 0xc
#define USIF_FRM_STAT_DCNT_MASK 0xfff0
#define USIF_FRM_STAT_DCNT(_reg) (((_reg) & 0xfff0) >> 0x4)
#define USIF_FRM_STAT_PBSY_OFFSET 0x2
#define USIF_FRM_STAT_PBSY_WIDTH 0x1
#define USIF_FRM_STAT_PBSY_MASK 0x4
#define USIF_FRM_STAT_PBSY(_reg) (((_reg) & 0x4) >> 0x2)
#define USIF_FRM_STAT_PBSY_NO (0x0 << USIF_FRM_STAT_PBSY_OFFSET)
#define USIF_FRM_STAT_PBSY_YES (0x1 << USIF_FRM_STAT_PBSY_OFFSET)
#define USIF_FRM_STAT_DBSY_OFFSET 0x1
#define USIF_FRM_STAT_DBSY_WIDTH 0x1
#define USIF_FRM_STAT_DBSY_MASK 0x2
#define USIF_FRM_STAT_DBSY(_reg) (((_reg) & 0x2) >> 0x1)
#define USIF_FRM_STAT_DBSY_NO (0x0 << USIF_FRM_STAT_DBSY_OFFSET)
#define USIF_FRM_STAT_DBSY_YES (0x1 << USIF_FRM_STAT_DBSY_OFFSET)
#define USIF_FRM_STAT_SFEN_OFFSET 0x0
#define USIF_FRM_STAT_SFEN_WIDTH 0x1
#define USIF_FRM_STAT_SFEN_MASK 0x1
#define USIF_FRM_STAT_SFEN(_reg) (((_reg) & 0x1) >> 0x0)
#define USIF_FRM_STAT_SFEN_OFF (0x0 << USIF_FRM_STAT_SFEN_OFFSET)
#define USIF_FRM_STAT_SFEN_ON (0x1 << USIF_FRM_STAT_SFEN_OFFSET)

#define USIF_CRC_CFG_OFFSET	  0x124
#define USIF_CRC_CFG(_base) ((_base) + 0x124)
#define USIF_CRC_CFG_ENDIAN_OFFSET 0xc
#define USIF_CRC_CFG_ENDIAN_WIDTH 0x1
#define USIF_CRC_CFG_ENDIAN_MASK 0x1000
#define USIF_CRC_CFG_ENDIAN(_reg) (((_reg) & 0x1000) >> 0xc)
#define USIF_CRC_CFG_ENDIAN_BIG (0x0 << USIF_CRC_CFG_ENDIAN_OFFSET)
#define USIF_CRC_CFG_ENDIAN_LITTLE (0x1 << USIF_CRC_CFG_ENDIAN_OFFSET)
#define USIF_CRC_CFG_FIN_XOR_OFFSET 0xb
#define USIF_CRC_CFG_FIN_XOR_WIDTH 0x1
#define USIF_CRC_CFG_FIN_XOR_MASK 0x800
#define USIF_CRC_CFG_FIN_XOR(_reg) (((_reg) & 0x800) >> 0xb)
#define USIF_CRC_CFG_FIN_XOR_NOINV (0x0 << USIF_CRC_CFG_FIN_XOR_OFFSET)
#define USIF_CRC_CFG_FIN_XOR_INV (0x1 << USIF_CRC_CFG_FIN_XOR_OFFSET)
#define USIF_CRC_CFG_REFO_OFFSET 0xa
#define USIF_CRC_CFG_REFO_WIDTH 0x1
#define USIF_CRC_CFG_REFO_MASK 0x400
#define USIF_CRC_CFG_REFO(_reg) (((_reg) & 0x400) >> 0xa)
#define USIF_CRC_CFG_REFO_NOT (0x0 << USIF_CRC_CFG_REFO_OFFSET)
#define USIF_CRC_CFG_REFO_BITREF (0x1 << USIF_CRC_CFG_REFO_OFFSET)
#define USIF_CRC_CFG_CRC_HD_OFFSET 0x9
#define USIF_CRC_CFG_CRC_HD_WIDTH 0x1
#define USIF_CRC_CFG_CRC_HD_MASK 0x200
#define USIF_CRC_CFG_CRC_HD(_reg) (((_reg) & 0x200) >> 0x9)
#define USIF_CRC_CFG_CRC_HD_LSB (0x0 << USIF_CRC_CFG_CRC_HD_OFFSET)
#define USIF_CRC_CFG_CRC_HD_MSB (0x1 << USIF_CRC_CFG_CRC_HD_OFFSET)
#define USIF_CRC_CFG_INIT_OFFSET 0x8
#define USIF_CRC_CFG_INIT_WIDTH 0x1
#define USIF_CRC_CFG_INIT_MASK 0x100
#define USIF_CRC_CFG_INIT(_reg) (((_reg) & 0x100) >> 0x8)
#define USIF_CRC_CFG_INIT_ZEROS (0x0 << USIF_CRC_CFG_INIT_OFFSET)
#define USIF_CRC_CFG_INIT_ONES (0x1 << USIF_CRC_CFG_INIT_OFFSET)
#define USIF_CRC_CFG_PLEN_OFFSET 0x0
#define USIF_CRC_CFG_PLEN_WIDTH 0x5
#define USIF_CRC_CFG_PLEN_MASK 0x1f
#define USIF_CRC_CFG_PLEN(_reg) (((_reg) & 0x1f) >> 0x0)
#define USIF_CRC_CFG_PLEN_G8 (0x8 << USIF_CRC_CFG_PLEN_OFFSET)
#define USIF_CRC_CFG_PLEN_G16 (0x10 << USIF_CRC_CFG_PLEN_OFFSET)
#define USIF_CRC_CFG_PLEN_G32 (0x0 << USIF_CRC_CFG_PLEN_OFFSET)
#define USIF_CRC_CFG_PLEN_RES (0x1 << USIF_CRC_CFG_PLEN_OFFSET)

#define USIF_CRCPOLY_CFG_OFFSET		  0x128
#define USIF_CRCPOLY_CFG(_base) ((_base) + 0x128)
#define USIF_CRCPOLY_CFG_POLY_OFFSET 0x0
#define USIF_CRCPOLY_CFG_POLY_WIDTH 0x20
#define USIF_CRCPOLY_CFG_POLY_MASK 0xffffffff
#define USIF_CRCPOLY_CFG_POLY(_reg) (((_reg) & 0xffffffff) >> 0x0)

#define USIF_CRC_CTRL_OFFSET	  0x12c
#define USIF_CRC_CTRL(_base) ((_base) + 0x12c)
#define USIF_CRC_CTRL_CRCTX_OFFSET 0x1
#define USIF_CRC_CTRL_CRCTX_WIDTH 0x1
#define USIF_CRC_CTRL_CRCTX_MASK 0x2
#define USIF_CRC_CTRL_CRCTX(_reg) (((_reg) & 0x2) >> 0x1)
#define USIF_CRC_CTRL_CRCTX_CRCTX_DIS (0x0 << USIF_CRC_CTRL_CRCTX_OFFSET)
#define USIF_CRC_CTRL_CRCTX_CRCTX_EN (0x1 << USIF_CRC_CTRL_CRCTX_OFFSET)
#define USIF_CRC_CTRL_CRCRX_OFFSET 0x0
#define USIF_CRC_CTRL_CRCRX_WIDTH 0x1
#define USIF_CRC_CTRL_CRCRX_MASK 0x1
#define USIF_CRC_CTRL_CRCRX(_reg) (((_reg) & 0x1) >> 0x0)
#define USIF_CRC_CTRL_CRCRX_CRCRX_DIS (0x0 << USIF_CRC_CTRL_CRCRX_OFFSET)
#define USIF_CRC_CTRL_CRCRX_CRCRX_EN (0x1 << USIF_CRC_CTRL_CRCRX_OFFSET)

#define USIF_CS_CFG_OFFSET	  0x130
#define USIF_CS_CFG(_base) ((_base) + 0x130)
#define USIF_CS_CFG_CSOINV_OFFSET 0x18
#define USIF_CS_CFG_CSOINV_WIDTH 0x8
#define USIF_CS_CFG_CSOINV_MASK 0xff000000
#define USIF_CS_CFG_CSOINV(_reg) (((_reg) & 0xff000000) >> 0x18)
#define USIF_CS_CFG_CSOINV_LOW (0x0 << USIF_CS_CFG_CSOINV_OFFSET)
#define USIF_CS_CFG_CSOINV_HIGH (0x1 << USIF_CS_CFG_CSOINV_OFFSET)
#define USIF_CS_CFG_CSOFRM_OFFSET 0x14
#define USIF_CS_CFG_CSOFRM_WIDTH 0x4
#define USIF_CS_CFG_CSOFRM_MASK 0xf00000
#define USIF_CS_CFG_CSOFRM(_reg) (((_reg) & 0xf00000) >> 0x14)
#define USIF_CS_CFG_CSOFRM_NO (0x0 << USIF_CS_CFG_CSOFRM_OFFSET)
#define USIF_CS_CFG_CSOFRM_CSO0 (0x1 << USIF_CS_CFG_CSOFRM_OFFSET)
#define USIF_CS_CFG_CSOFRM_CSO1 (0x2 << USIF_CS_CFG_CSOFRM_OFFSET)
#define USIF_CS_CFG_CSOFRM_CSO2 (0x3 << USIF_CS_CFG_CSOFRM_OFFSET)
#define USIF_CS_CFG_CSOFRM_CSO3 (0x4 << USIF_CS_CFG_CSOFRM_OFFSET)
#define USIF_CS_CFG_CSOFRM_CSO4 (0x5 << USIF_CS_CFG_CSOFRM_OFFSET)
#define USIF_CS_CFG_CSOFRM_CSO5 (0x6 << USIF_CS_CFG_CSOFRM_OFFSET)
#define USIF_CS_CFG_CSOFRM_CSO6 (0x7 << USIF_CS_CFG_CSOFRM_OFFSET)
#define USIF_CS_CFG_CSOFRM_CSO7 (0x8 << USIF_CS_CFG_CSOFRM_OFFSET)
#define USIF_CS_CFG_CSOCLK_OFFSET 0x10
#define USIF_CS_CFG_CSOCLK_WIDTH 0x4
#define USIF_CS_CFG_CSOCLK_MASK 0xf0000
#define USIF_CS_CFG_CSOCLK(_reg) (((_reg) & 0xf0000) >> 0x10)
#define USIF_CS_CFG_CSOCLK_NO (0x0 << USIF_CS_CFG_CSOCLK_OFFSET)
#define USIF_CS_CFG_CSOCLK_CSO0 (0x1 << USIF_CS_CFG_CSOCLK_OFFSET)
#define USIF_CS_CFG_CSOCLK_CSO1 (0x2 << USIF_CS_CFG_CSOCLK_OFFSET)
#define USIF_CS_CFG_CSOCLK_CSO2 (0x3 << USIF_CS_CFG_CSOCLK_OFFSET)
#define USIF_CS_CFG_CSOCLK_CSO3 (0x4 << USIF_CS_CFG_CSOCLK_OFFSET)
#define USIF_CS_CFG_CSOCLK_CSO4 (0x5 << USIF_CS_CFG_CSOCLK_OFFSET)
#define USIF_CS_CFG_CSOCLK_CSO5 (0x6 << USIF_CS_CFG_CSOCLK_OFFSET)
#define USIF_CS_CFG_CSOCLK_CSO6 (0x7 << USIF_CS_CFG_CSOCLK_OFFSET)
#define USIF_CS_CFG_CSOCLK_CSO7 (0x8 << USIF_CS_CFG_CSOCLK_OFFSET)
#define USIF_CS_CFG_CSO_OFFSET 0x8
#define USIF_CS_CFG_CSO_WIDTH 0x8
#define USIF_CS_CFG_CSO_MASK 0xff00
#define USIF_CS_CFG_CSO(_reg) (((_reg) & 0xff00) >> 0x8)
#define USIF_CS_CFG_CSO_LOW (0x0 << USIF_CS_CFG_CSO_OFFSET)
#define USIF_CS_CFG_CSO_HIGH (0x1 << USIF_CS_CFG_CSO_OFFSET)
#define USIF_CS_CFG_CSIINV_OFFSET 0x4
#define USIF_CS_CFG_CSIINV_WIDTH 0x1
#define USIF_CS_CFG_CSIINV_MASK 0x10
#define USIF_CS_CFG_CSIINV(_reg) (((_reg) & 0x10) >> 0x4)
#define USIF_CS_CFG_CSIINV_NO (0x0 << USIF_CS_CFG_CSIINV_OFFSET)
#define USIF_CS_CFG_CSIINV_INV (0x1 << USIF_CS_CFG_CSIINV_OFFSET)
#define USIF_CS_CFG_EACS_OFFSET 0x1
#define USIF_CS_CFG_EACS_WIDTH 0x1
#define USIF_CS_CFG_EACS_MASK 0x2
#define USIF_CS_CFG_EACS(_reg) (((_reg) & 0x2) >> 0x1)
#define USIF_CS_CFG_EACS_DIS (0x0 << USIF_CS_CFG_EACS_OFFSET)
#define USIF_CS_CFG_EACS_EN (0x1 << USIF_CS_CFG_EACS_OFFSET)
#define USIF_CS_CFG_CSEN_OFFSET 0x0
#define USIF_CS_CFG_CSEN_WIDTH 0x1
#define USIF_CS_CFG_CSEN_MASK 0x1
#define USIF_CS_CFG_CSEN(_reg) (((_reg) & 0x1) >> 0x0)
#define USIF_CS_CFG_CSEN_DIS (0x0 << USIF_CS_CFG_CSEN_OFFSET)
#define USIF_CS_CFG_CSEN_EN (0x1 << USIF_CS_CFG_CSEN_OFFSET)

#define USIF_FDIV_CFG_OFFSET	  0x140
#define USIF_FDIV_CFG(_base) ((_base) + 0x140)
#define USIF_FDIV_CFG_DEC_OFFSET 0x10
#define USIF_FDIV_CFG_DEC_WIDTH 0x10
#define USIF_FDIV_CFG_DEC_MASK 0xffff0000
#define USIF_FDIV_CFG_DEC(_reg) (((_reg) & 0xffff0000) >> 0x10)
#define USIF_FDIV_CFG_INC_OFFSET 0x0
#define USIF_FDIV_CFG_INC_WIDTH 0x9
#define USIF_FDIV_CFG_INC_MASK 0x1ff
#define USIF_FDIV_CFG_INC(_reg) (((_reg) & 0x1ff) >> 0x0)

#define USIF_BC_CFG_OFFSET	  0x144
#define USIF_BC_CFG(_base) ((_base) + 0x144)
#define USIF_BC_CFG_SCDEL_OFFSET 0x1c
#define USIF_BC_CFG_SCDEL_WIDTH 0x4
#define USIF_BC_CFG_SCDEL_MASK 0xf0000000
#define USIF_BC_CFG_SCDEL(_reg) (((_reg) & 0xf0000000) >> 0x1c)
#define USIF_BC_CFG_SCDEL_FBC (0x0 << USIF_BC_CFG_SCDEL_OFFSET)
#define USIF_BC_CFG_SCDEL_DEL1 (0x1 << USIF_BC_CFG_SCDEL_OFFSET)
#define USIF_BC_CFG_SCDEL_DEL15 (0xf << USIF_BC_CFG_SCDEL_OFFSET)
#define USIF_BC_CFG_SCDIV_OFFSET 0x18
#define USIF_BC_CFG_SCDIV_WIDTH 0x1
#define USIF_BC_CFG_SCDIV_MASK 0x1000000
#define USIF_BC_CFG_SCDIV(_reg) (((_reg) & 0x1000000) >> 0x18)
#define USIF_BC_CFG_SCDIV_QUART (0x0 << USIF_BC_CFG_SCDIV_OFFSET)
#define USIF_BC_CFG_SCDIV_HALF (0x1 << USIF_BC_CFG_SCDIV_OFFSET)
#define USIF_BC_CFG_BCRV_OFFSET 0x0
#define USIF_BC_CFG_BCRV_WIDTH 0xd
#define USIF_BC_CFG_BCRV_MASK 0x1fff
#define USIF_BC_CFG_BCRV(_reg) (((_reg) & 0x1fff) >> 0x0)

#define USIF_ICTMO_CFG_OFFSET	  0x148
#define USIF_ICTMO_CFG(_base) ((_base) + 0x148)
#define USIF_ICTMO_CFG_TMO_OFFSET 0x0
#define USIF_ICTMO_CFG_TMO_WIDTH 0x10
#define USIF_ICTMO_CFG_TMO_MASK 0xffff
#define USIF_ICTMO_CFG_TMO(_reg) (((_reg) & 0xffff) >> 0x0)
#define USIF_ICTMO_CFG_TMO_DIS (0x0 << USIF_ICTMO_CFG_TMO_OFFSET)
#define USIF_ICTMO_CFG_TMO_EN (0x1 << USIF_ICTMO_CFG_TMO_OFFSET)

#define USIF_ICTM_CFG_OFFSET	  0x14c
#define USIF_ICTM_CFG(_base) ((_base) + 0x14c)
#define USIF_ICTM_CFG_TM_OFFSET 0x0
#define USIF_ICTM_CFG_TM_WIDTH 0xe
#define USIF_ICTM_CFG_TM_MASK 0x3fff
#define USIF_ICTM_CFG_TM(_reg) (((_reg) & 0x3fff) >> 0x0)
#define USIF_ICTM_CFG_TM_DIS (0x0 << USIF_ICTM_CFG_TM_OFFSET)
#define USIF_ICTM_CFG_TM_EN (0x1 << USIF_ICTM_CFG_TM_OFFSET)

#define USIF_ECTM_CFG_OFFSET	  0x150
#define USIF_ECTM_CFG(_base) ((_base) + 0x150)
#define USIF_ECTM_CFG_ECTM_OFFSET 0x0
#define USIF_ECTM_CFG_ECTM_WIDTH 0xe
#define USIF_ECTM_CFG_ECTM_MASK 0x3fff
#define USIF_ECTM_CFG_ECTM(_reg) (((_reg) & 0x3fff) >> 0x0)
#define USIF_ECTM_CFG_ECTM_DIS (0x0 << USIF_ECTM_CFG_ECTM_OFFSET)
#define USIF_ECTM_CFG_ECTM_EN (0x1 << USIF_ECTM_CFG_ECTM_OFFSET)

#define USIF_CS_TIM0_CFG_OFFSET		  0x154
#define USIF_CS_TIM0_CFG(_base) ((_base) + 0x154)
#define USIF_CS_TIM0_CFG_SETUP_OFFSET 0x10
#define USIF_CS_TIM0_CFG_SETUP_WIDTH 0x8
#define USIF_CS_TIM0_CFG_SETUP_MASK 0xff0000
#define USIF_CS_TIM0_CFG_SETUP(_reg) (((_reg) & 0xff0000) >> 0x10)
#define USIF_CS_TIM0_CFG_HOLD_OFFSET 0x8
#define USIF_CS_TIM0_CFG_HOLD_WIDTH 0x8
#define USIF_CS_TIM0_CFG_HOLD_MASK 0xff00
#define USIF_CS_TIM0_CFG_HOLD(_reg) (((_reg) & 0xff00) >> 0x8)
#define USIF_CS_TIM0_CFG_IDLE_OFFSET 0x0
#define USIF_CS_TIM0_CFG_IDLE_WIDTH 0x8
#define USIF_CS_TIM0_CFG_IDLE_MASK 0xff
#define USIF_CS_TIM0_CFG_IDLE(_reg) (((_reg) & 0xff) >> 0x0)

#define USIF_DPLUS_CTRL_OFFSET	  0x2c
#define USIF_DPLUS_CTRL(_base) ((_base) + 0x2c)
#define USIF_DPLUS_CTRL_TX_INTL_EN_OFFSET 0x18
#define USIF_DPLUS_CTRL_TX_INTL_EN_WIDTH 0x2
#define USIF_DPLUS_CTRL_TX_INTL_EN_MASK 0x3000000
#define USIF_DPLUS_CTRL_TX_INTL_EN(_reg) (((_reg) & 0x3000000) >> 0x18)
#define USIF_DPLUS_CTRL_TX_INTL_EN_TX_INTL_DIS \
			(0x2 << USIF_DPLUS_CTRL_TX_INTL_EN_OFFSET)
#define USIF_DPLUS_CTRL_TX_INTL_EN_TX_INTL_EN \
			(0x1 << USIF_DPLUS_CTRL_TX_INTL_EN_OFFSET)
#define USIF_DPLUS_CTRL_DPLUS_TXEN_OFFSET 0x16
#define USIF_DPLUS_CTRL_DPLUS_TXEN_WIDTH 0x2
#define USIF_DPLUS_CTRL_DPLUS_TXEN_MASK 0xc00000
#define USIF_DPLUS_CTRL_DPLUS_TXEN(_reg) (((_reg) & 0xc00000) >> 0x16)
#define USIF_DPLUS_CTRL_DPLUS_TXEN_DPLUS_TX_DIS \
			(0x2 << USIF_DPLUS_CTRL_DPLUS_TXEN_OFFSET)
#define USIF_DPLUS_CTRL_DPLUS_TXEN_DPLUS_TX_EN \
			(0x1 << USIF_DPLUS_CTRL_DPLUS_TXEN_OFFSET)
#define USIF_DPLUS_CTRL_RX_MASK_OFFSET 0x8
#define USIF_DPLUS_CTRL_RX_MASK_WIDTH 0x8
#define USIF_DPLUS_CTRL_RX_MASK_MASK 0xff00
#define USIF_DPLUS_CTRL_RX_MASK(_reg) (((_reg) & 0xff00) >> 0x8)
#define USIF_DPLUS_CTRL_RX_MASK_COMPC0 (0x1 << USIF_DPLUS_CTRL_RX_MASK_OFFSET)
#define USIF_DPLUS_CTRL_RX_MASK_COMPC1 (0x2 << USIF_DPLUS_CTRL_RX_MASK_OFFSET)
#define USIF_DPLUS_CTRL_RX_MASK_COMPC2 (0x4 << USIF_DPLUS_CTRL_RX_MASK_OFFSET)
#define USIF_DPLUS_CTRL_RX_MASK_COMPC3 (0x8 << USIF_DPLUS_CTRL_RX_MASK_OFFSET)
#define USIF_DPLUS_CTRL_RX_MASK_COMPC4 (0x10 << USIF_DPLUS_CTRL_RX_MASK_OFFSET)
#define USIF_DPLUS_CTRL_RX_MASK_COMPC5 (0x20 << USIF_DPLUS_CTRL_RX_MASK_OFFSET)
#define USIF_DPLUS_CTRL_RX_MASK_COMPC6 (0x40 << USIF_DPLUS_CTRL_RX_MASK_OFFSET)
#define USIF_DPLUS_CTRL_RX_MASK_COMPC7 (0x80 << USIF_DPLUS_CTRL_RX_MASK_OFFSET)
#define USIF_DPLUS_CTRL_SETMASK_OFFSET 0x7
#define USIF_DPLUS_CTRL_SETMASK_WIDTH 0x1
#define USIF_DPLUS_CTRL_SETMASK_MASK 0x80
#define USIF_DPLUS_CTRL_SETMASK(_reg) (((_reg) & 0x80) >> 0x7)
#define USIF_DPLUS_CTRL_SETMASK_SETRXMASK \
			(0x1 << USIF_DPLUS_CTRL_SETMASK_OFFSET)
#define USIF_DPLUS_CTRL_SETMASK_NO_UPD \
			(0x0 << USIF_DPLUS_CTRL_SETMASK_OFFSET)

#define USIF_FIFO_CFG_OFFSET	  0x30
#define USIF_FIFO_CFG(_base) ((_base) + 0x30)
#define USIF_FIFO_CFG_TX_SWAP_OFFSET 0xf
#define USIF_FIFO_CFG_TX_SWAP_WIDTH 0x1
#define USIF_FIFO_CFG_TX_SWAP_MASK 0x8000
#define USIF_FIFO_CFG_TX_SWAP(_reg) (((_reg) & 0x8000) >> 0xf)
#define USIF_FIFO_CFG_TX_SWAP_NO_TXSWAP (0x0 << USIF_FIFO_CFG_TX_SWAP_OFFSET)
#define USIF_FIFO_CFG_TX_SWAP_TXWSWAP (0x1 << USIF_FIFO_CFG_TX_SWAP_OFFSET)
#define USIF_FIFO_CFG_TXFA_OFFSET 0xc
#define USIF_FIFO_CFG_TXFA_WIDTH 0x3
#define USIF_FIFO_CFG_TXFA_MASK 0x7000
#define USIF_FIFO_CFG_TXFA(_reg) (((_reg) & 0x7000) >> 0xc)
#define USIF_FIFO_CFG_TXFA_TXFA1 (0x0 << USIF_FIFO_CFG_TXFA_OFFSET)
#define USIF_FIFO_CFG_TXFA_TXFA2 (0x1 << USIF_FIFO_CFG_TXFA_OFFSET)
#define USIF_FIFO_CFG_TXFA_TXFA4 (0x2 << USIF_FIFO_CFG_TXFA_OFFSET)
#define USIF_FIFO_CFG_TXFA_TXFA8 (0x3 << USIF_FIFO_CFG_TXFA_OFFSET)
#define USIF_FIFO_CFG_TXFA_RES (0x4 << USIF_FIFO_CFG_TXFA_OFFSET)
#define USIF_FIFO_CFG_RX_SWAP_OFFSET 0xb
#define USIF_FIFO_CFG_RX_SWAP_WIDTH 0x1
#define USIF_FIFO_CFG_RX_SWAP_MASK 0x800
#define USIF_FIFO_CFG_RX_SWAP(_reg) (((_reg) & 0x800) >> 0xb)
#define USIF_FIFO_CFG_RX_SWAP_NO_RXSWAP (0x0 << USIF_FIFO_CFG_RX_SWAP_OFFSET)
#define USIF_FIFO_CFG_RX_SWAP_RXWSWAP (0x1 << USIF_FIFO_CFG_RX_SWAP_OFFSET)
#define USIF_FIFO_CFG_RXFA_OFFSET 0x8
#define USIF_FIFO_CFG_RXFA_WIDTH 0x3
#define USIF_FIFO_CFG_RXFA_MASK 0x700
#define USIF_FIFO_CFG_RXFA(_reg) (((_reg) & 0x700) >> 0x8)
#define USIF_FIFO_CFG_RXFA_RXFA1 (0x0 << USIF_FIFO_CFG_RXFA_OFFSET)
#define USIF_FIFO_CFG_RXFA_RXFA2 (0x1 << USIF_FIFO_CFG_RXFA_OFFSET)
#define USIF_FIFO_CFG_RXFA_RXFA4 (0x2 << USIF_FIFO_CFG_RXFA_OFFSET)
#define USIF_FIFO_CFG_RXFA_RXFA8 (0x3 << USIF_FIFO_CFG_RXFA_OFFSET)
#define USIF_FIFO_CFG_RXFA_RES (0x4 << USIF_FIFO_CFG_RXFA_OFFSET)
#define USIF_FIFO_CFG_TXFC_OFFSET 0x7
#define USIF_FIFO_CFG_TXFC_WIDTH 0x1
#define USIF_FIFO_CFG_TXFC_MASK 0x80
#define USIF_FIFO_CFG_TXFC(_reg) (((_reg) & 0x80) >> 0x7)
#define USIF_FIFO_CFG_TXFC_TXNFC (0x0 << USIF_FIFO_CFG_TXFC_OFFSET)
#define USIF_FIFO_CFG_TXFC_TXFC (0x1 << USIF_FIFO_CFG_TXFC_OFFSET)
#define USIF_FIFO_CFG_TXBS_OFFSET 0x4
#define USIF_FIFO_CFG_TXBS_WIDTH 0x3
#define USIF_FIFO_CFG_TXBS_MASK 0x70
#define USIF_FIFO_CFG_TXBS(_reg) (((_reg) & 0x70) >> 0x4)
#define USIF_FIFO_CFG_TXBS_TXBS1 (0x0 << USIF_FIFO_CFG_TXBS_OFFSET)
#define USIF_FIFO_CFG_TXBS_TXBS2 (0x1 << USIF_FIFO_CFG_TXBS_OFFSET)
#define USIF_FIFO_CFG_TXBS_TXBS4 (0x2 << USIF_FIFO_CFG_TXBS_OFFSET)
#define USIF_FIFO_CFG_TXBS_TXBS8 (0x3 << USIF_FIFO_CFG_TXBS_OFFSET)
#define USIF_FIFO_CFG_TXBS_TXBS16 (0x4 << USIF_FIFO_CFG_TXBS_OFFSET)
#define USIF_FIFO_CFG_TXBS_RES (0x5 << USIF_FIFO_CFG_TXBS_OFFSET)
#define USIF_FIFO_CFG_RXFC_OFFSET 0x3
#define USIF_FIFO_CFG_RXFC_WIDTH 0x1
#define USIF_FIFO_CFG_RXFC_MASK 0x8
#define USIF_FIFO_CFG_RXFC(_reg) (((_reg) & 0x8) >> 0x3)
#define USIF_FIFO_CFG_RXFC_RXNFC (0x0 << USIF_FIFO_CFG_RXFC_OFFSET)
#define USIF_FIFO_CFG_RXFC_RXFC (0x1 << USIF_FIFO_CFG_RXFC_OFFSET)
#define USIF_FIFO_CFG_RXBS_OFFSET 0x0
#define USIF_FIFO_CFG_RXBS_WIDTH 0x3
#define USIF_FIFO_CFG_RXBS_MASK 0x7
#define USIF_FIFO_CFG_RXBS(_reg) (((_reg) & 0x7) >> 0x0)
#define USIF_FIFO_CFG_RXBS_RXBS1 (0x0 << USIF_FIFO_CFG_RXBS_OFFSET)
#define USIF_FIFO_CFG_RXBS_RXBS2 (0x1 << USIF_FIFO_CFG_RXBS_OFFSET)
#define USIF_FIFO_CFG_RXBS_RXBS4 (0x2 << USIF_FIFO_CFG_RXBS_OFFSET)
#define USIF_FIFO_CFG_RXBS_RXBS8 (0x3 << USIF_FIFO_CFG_RXBS_OFFSET)
#define USIF_FIFO_CFG_RXBS_RXBS16 (0x4 << USIF_FIFO_CFG_RXBS_OFFSET)
#define USIF_FIFO_CFG_RXBS_RES (0x5 << USIF_FIFO_CFG_RXBS_OFFSET)

#define USIF_FIFO_CTRL_OFFSET	  0x34
#define USIF_FIFO_CTRL(_base) ((_base) + 0x34)
#define USIF_FIFO_CTRL_RX_AR_OFFSET 0x6
#define USIF_FIFO_CTRL_RX_AR_WIDTH 0x2
#define USIF_FIFO_CTRL_RX_AR_MASK 0xc0
#define USIF_FIFO_CTRL_RX_AR(_reg) (((_reg) & 0xc0) >> 0x6)
#define USIF_FIFO_CTRL_RX_AR_AR_OFF (0x2 << USIF_FIFO_CTRL_RX_AR_OFFSET)
#define USIF_FIFO_CTRL_RX_AR_AR_ON (0x1 << USIF_FIFO_CTRL_RX_AR_OFFSET)
#define USIF_FIFO_CTRL_RX_ABORT_OFFSET 0x5
#define USIF_FIFO_CTRL_RX_ABORT_WIDTH 0x1
#define USIF_FIFO_CTRL_RX_ABORT_MASK 0x20
#define USIF_FIFO_CTRL_RX_ABORT(_reg) (((_reg) & 0x20) >> 0x5)
#define USIF_FIFO_CTRL_RX_START_OFFSET 0x4
#define USIF_FIFO_CTRL_RX_START_WIDTH 0x1
#define USIF_FIFO_CTRL_RX_START_MASK 0x10
#define USIF_FIFO_CTRL_RX_START(_reg) (((_reg) & 0x10) >> 0x4)
#define USIF_FIFO_CTRL_TX_SETEOP_OFFSET 0x2
#define USIF_FIFO_CTRL_TX_SETEOP_WIDTH 0x1
#define USIF_FIFO_CTRL_TX_SETEOP_MASK 0x4
#define USIF_FIFO_CTRL_TX_SETEOP(_reg) (((_reg) & 0x4) >> 0x2)
#define USIF_FIFO_CTRL_TX_ABORT_OFFSET 0x1
#define USIF_FIFO_CTRL_TX_ABORT_WIDTH 0x1
#define USIF_FIFO_CTRL_TX_ABORT_MASK 0x2
#define USIF_FIFO_CTRL_TX_ABORT(_reg) (((_reg) & 0x2) >> 0x1)
#define USIF_FIFO_CTRL_TX_START_OFFSET 0x0
#define USIF_FIFO_CTRL_TX_START_WIDTH 0x1
#define USIF_FIFO_CTRL_TX_START_MASK 0x1
#define USIF_FIFO_CTRL_TX_START(_reg) (((_reg) & 0x1) >> 0x0)

#define USIF_MRPS_CTRL_OFFSET	  0x38
#define USIF_MRPS_CTRL(_base) ((_base) + 0x38)
#define USIF_MRPS_CTRL_MRPS_OFFSET 0x0
#define USIF_MRPS_CTRL_MRPS_WIDTH 0x13
#define USIF_MRPS_CTRL_MRPS_MASK 0x7ffff
#define USIF_MRPS_CTRL_MRPS(_reg) (((_reg) & 0x7ffff) >> 0x0)
#define USIF_MRPS_CTRL_MRPS_UNDEF (0x0 << USIF_MRPS_CTRL_MRPS_OFFSET)
#define USIF_MRPS_CTRL_MRPS_MRPS (0x1 << USIF_MRPS_CTRL_MRPS_OFFSET)
#define USIF_MRPS_CTRL_MRPS_RES (0x40001 << USIF_MRPS_CTRL_MRPS_OFFSET)

#define USIF_RPS_STAT_OFFSET	  0x3c
#define USIF_RPS_STAT(_base) ((_base) + 0x3c)
#define USIF_RPS_STAT_MRPS_STOP_IND_OFFSET 0x1f
#define USIF_RPS_STAT_MRPS_STOP_IND_WIDTH 0x1
#define USIF_RPS_STAT_MRPS_STOP_IND_MASK 0x80000000
#define USIF_RPS_STAT_MRPS_STOP_IND(_reg) (((_reg) & 0x80000000) >> 0x1f)
#define USIF_RPS_STAT_MRPS_STOP_IND_CONST_0B1 \
			(0x1 << USIF_RPS_STAT_MRPS_STOP_IND_OFFSET)
#define USIF_RPS_STAT_FIFO_FULL_IND_OFFSET 0x1e
#define USIF_RPS_STAT_FIFO_FULL_IND_WIDTH 0x1
#define USIF_RPS_STAT_FIFO_FULL_IND_MASK 0x40000000
#define USIF_RPS_STAT_FIFO_FULL_IND(_reg) (((_reg) & 0x40000000) >> 0x1e)
#define USIF_RPS_STAT_FIFO_FULL_IND_CONST_0B1 \
			(0x1 << USIF_RPS_STAT_FIFO_FULL_IND_OFFSET)
#define USIF_RPS_STAT_RPS_OFFSET 0x0
#define USIF_RPS_STAT_RPS_WIDTH 0x13
#define USIF_RPS_STAT_RPS_MASK 0x7ffff
#define USIF_RPS_STAT_RPS(_reg) (((_reg) & 0x7ffff) >> 0x0)

#define USIF_TPS_CTRL_OFFSET	  0x40
#define USIF_TPS_CTRL(_base) ((_base) + 0x40)
#define USIF_TPS_CTRL_TPS_OFFSET 0x0
#define USIF_TPS_CTRL_TPS_WIDTH 0x13
#define USIF_TPS_CTRL_TPS_MASK 0x7ffff
#define USIF_TPS_CTRL_TPS(_reg) (((_reg) & 0x7ffff) >> 0x0)
#define USIF_TPS_CTRL_TPS_NOTPS (0x0 << USIF_TPS_CTRL_TPS_OFFSET)
#define USIF_TPS_CTRL_TPS_TPS (0x1 << USIF_TPS_CTRL_TPS_OFFSET)
#define USIF_TPS_CTRL_TPS_RES (0x40001 << USIF_TPS_CTRL_TPS_OFFSET)

#define USIF_FIFO_STAT_OFFSET	  0x44
#define USIF_FIFO_STAT(_base) ((_base) + 0x44)
#define USIF_FIFO_STAT_TPS_WE_OFFSET 0x1f
#define USIF_FIFO_STAT_TPS_WE_WIDTH 0x1
#define USIF_FIFO_STAT_TPS_WE_MASK 0x80000000
#define USIF_FIFO_STAT_TPS_WE(_reg) (((_reg) & 0x80000000) >> 0x1f)
#define USIF_FIFO_STAT_TPS_WE_TPS_BUSY (0x0 << USIF_FIFO_STAT_TPS_WE_OFFSET)
#define USIF_FIFO_STAT_TPS_WE_TPS_READY (0x1 << USIF_FIFO_STAT_TPS_WE_OFFSET)
#define USIF_FIFO_STAT_TXFFS_OFFSET 0x10
#define USIF_FIFO_STAT_TXFFS_WIDTH 0x8
#define USIF_FIFO_STAT_TXFFS_MASK 0xff0000
#define USIF_FIFO_STAT_TXFFS(_reg) (((_reg) & 0xff0000) >> 0x10)
#define USIF_FIFO_STAT_MRPS_WE_OFFSET 0xf
#define USIF_FIFO_STAT_MRPS_WE_WIDTH 0x1
#define USIF_FIFO_STAT_MRPS_WE_MASK 0x8000
#define USIF_FIFO_STAT_MRPS_WE(_reg) (((_reg) & 0x8000) >> 0xf)
#define USIF_FIFO_STAT_MRPS_WE_MRPS_BUSY (0x0 << USIF_FIFO_STAT_MRPS_WE_OFFSET)
#define USIF_FIFO_STAT_MRPS_WE_MRPS_READY (0x1 << USIF_FIFO_STAT_MRPS_WE_OFFSET)
#define USIF_FIFO_STAT_RX_EOP_OFFSET 0xd
#define USIF_FIFO_STAT_RX_EOP_WIDTH 0x1
#define USIF_FIFO_STAT_RX_EOP_MASK 0x2000
#define USIF_FIFO_STAT_RX_EOP(_reg) (((_reg) & 0x2000) >> 0xd)
#define USIF_FIFO_STAT_RX_EOP_RX_EOP (0x1 << USIF_FIFO_STAT_RX_EOP_OFFSET)
#define USIF_FIFO_STAT_RX_EOP_RX_NOEOP (0x0 << USIF_FIFO_STAT_RX_EOP_OFFSET)
#define USIF_FIFO_STAT_RX_AR_OFFSET 0xc
#define USIF_FIFO_STAT_RX_AR_WIDTH 0x1
#define USIF_FIFO_STAT_RX_AR_MASK 0x1000
#define USIF_FIFO_STAT_RX_AR(_reg) (((_reg) & 0x1000) >> 0xc)
#define USIF_FIFO_STAT_RX_AR_AR_OFF (0x0 << USIF_FIFO_STAT_RX_AR_OFFSET)
#define USIF_FIFO_STAT_RX_AR_AR_ON (0x1 << USIF_FIFO_STAT_RX_AR_OFFSET)
#define USIF_FIFO_STAT_RXFFS_OFFSET 0x0
#define USIF_FIFO_STAT_RXFFS_WIDTH 0x8
#define USIF_FIFO_STAT_RXFFS_MASK 0xff
#define USIF_FIFO_STAT_RXFFS(_reg) (((_reg) & 0xff) >> 0x0)

#define USIF_TXD_SB_OFFSET	  0x48
#define USIF_TXD_SB(_base) ((_base) + 0x48)
#define USIF_TXD_SB_XME_OFFSET 0x7
#define USIF_TXD_SB_XME_WIDTH 0x1
#define USIF_TXD_SB_XME_MASK 0x80
#define USIF_TXD_SB_XME(_reg) (((_reg) & 0x80) >> 0x7)
#define USIF_TXD_SB_TX_BE_OFFSET 0x4
#define USIF_TXD_SB_TX_BE_WIDTH 0x2
#define USIF_TXD_SB_TX_BE_MASK 0x30
#define USIF_TXD_SB_TX_BE(_reg) (((_reg) & 0x30) >> 0x4)
#define USIF_TXD_SB_TX_BE_CH4 (0x0 << USIF_TXD_SB_TX_BE_OFFSET)
#define USIF_TXD_SB_TX_BE_CH1 (0x1 << USIF_TXD_SB_TX_BE_OFFSET)
#define USIF_TXD_SB_TX_BE_CH2 (0x2 << USIF_TXD_SB_TX_BE_OFFSET)
#define USIF_TXD_SB_TX_BE_CH3 (0x3 << USIF_TXD_SB_TX_BE_OFFSET)
#define USIF_TXD_SB_TX_CLASS_OFFSET 0x0
#define USIF_TXD_SB_TX_CLASS_WIDTH 0x3
#define USIF_TXD_SB_TX_CLASS_MASK 0x7
#define USIF_TXD_SB_TX_CLASS(_reg) (((_reg) & 0x7) >> 0x0)

#define USIF_DPLUS_STAT_OFFSET	  0x4c
#define USIF_DPLUS_STAT(_base) ((_base) + 0x4c)
#define USIF_DPLUS_STAT_RX_FIFO_EMPTY_OFFSET 0x1f
#define USIF_DPLUS_STAT_RX_FIFO_EMPTY_WIDTH 0x1
#define USIF_DPLUS_STAT_RX_FIFO_EMPTY_MASK 0x80000000
#define USIF_DPLUS_STAT_RX_FIFO_EMPTY(_reg) (((_reg) & 0x80000000) >> 0x1f)
#define USIF_DPLUS_STAT_TX_INTL_EN_OFFSET 0x18
#define USIF_DPLUS_STAT_TX_INTL_EN_WIDTH 0x1
#define USIF_DPLUS_STAT_TX_INTL_EN_MASK 0x1000000
#define USIF_DPLUS_STAT_TX_INTL_EN(_reg) (((_reg) & 0x1000000) >> 0x18)
#define USIF_DPLUS_STAT_DPLUS_TX_ACT_OFFSET 0x17
#define USIF_DPLUS_STAT_DPLUS_TX_ACT_WIDTH 0x1
#define USIF_DPLUS_STAT_DPLUS_TX_ACT_MASK 0x800000
#define USIF_DPLUS_STAT_DPLUS_TX_ACT(_reg) (((_reg) & 0x800000) >> 0x17)
#define USIF_DPLUS_STAT_RX_MASK_OFFSET 0x8
#define USIF_DPLUS_STAT_RX_MASK_WIDTH 0x8
#define USIF_DPLUS_STAT_RX_MASK_MASK 0xff00
#define USIF_DPLUS_STAT_RX_MASK(_reg) (((_reg) & 0xff00) >> 0x8)
#define USIF_DPLUS_STAT_RME_OFFSET 0x7
#define USIF_DPLUS_STAT_RME_WIDTH 0x1
#define USIF_DPLUS_STAT_RME_MASK 0x80
#define USIF_DPLUS_STAT_RME(_reg) (((_reg) & 0x80) >> 0x7)
#define USIF_DPLUS_STAT_RX_BE_OFFSET 0x4
#define USIF_DPLUS_STAT_RX_BE_WIDTH 0x2
#define USIF_DPLUS_STAT_RX_BE_MASK 0x30
#define USIF_DPLUS_STAT_RX_BE(_reg) (((_reg) & 0x30) >> 0x4)
#define USIF_DPLUS_STAT_RX_BE_CH4 (0x0 << USIF_DPLUS_STAT_RX_BE_OFFSET)
#define USIF_DPLUS_STAT_RX_BE_CH1 (0x1 << USIF_DPLUS_STAT_RX_BE_OFFSET)
#define USIF_DPLUS_STAT_RX_BE_CH2 (0x2 << USIF_DPLUS_STAT_RX_BE_OFFSET)
#define USIF_DPLUS_STAT_RX_BE_CH3 (0x3 << USIF_DPLUS_STAT_RX_BE_OFFSET)
#define USIF_DPLUS_STAT_RX_CLASS_OFFSET 0x0
#define USIF_DPLUS_STAT_RX_CLASS_WIDTH 0x3
#define USIF_DPLUS_STAT_RX_CLASS_MASK 0x7
#define USIF_DPLUS_STAT_RX_CLASS(_reg) (((_reg) & 0x7) >> 0x0)

#define USIF_TXD_OFFSET		  0x40000
#define USIF_TXD(_base) ((_base) + 0x40000)
#define USIF_TXD_TXD_OFFSET 0x0
#define USIF_TXD_TXD_WIDTH 0x20
#define USIF_TXD_TXD_MASK 0xffffffff
#define USIF_TXD_TXD(_reg) (((_reg) & 0xffffffff) >> 0x0)

#define USIF_RXD_OFFSET		  0x80000
#define USIF_RXD(_base) ((_base) + 0x80000)
#define USIF_RXD_RXD_OFFSET 0x0
#define USIF_RXD_RXD_WIDTH 0x20
#define USIF_RXD_RXD_MASK 0xffffffff
#define USIF_RXD_RXD(_reg) (((_reg) & 0xffffffff) >> 0x0)

#define USIF_RIS_OFFSET		  0x80
#define USIF_RIS(_base) ((_base) + 0x80)
#define USIF_RIS_TMO_OFFSET 0x1f
#define USIF_RIS_TMO_WIDTH 0x1
#define USIF_RIS_TMO_MASK 0x80000000
#define USIF_RIS_TMO(_reg) (((_reg) & 0x80000000) >> 0x1f)
#define USIF_RIS_TMO_NO_INT (0x0 << USIF_RIS_TMO_OFFSET)
#define USIF_RIS_TMO_INT_PEND (0x1 << USIF_RIS_TMO_OFFSET)
#define USIF_RIS_FRM_PAUSE_OFFSET 0x1e
#define USIF_RIS_FRM_PAUSE_WIDTH 0x1
#define USIF_RIS_FRM_PAUSE_MASK 0x40000000
#define USIF_RIS_FRM_PAUSE(_reg) (((_reg) & 0x40000000) >> 0x1e)
#define USIF_RIS_FRM_PAUSE_NO_INT (0x0 << USIF_RIS_FRM_PAUSE_OFFSET)
#define USIF_RIS_FRM_PAUSE_INT_PEND (0x1 << USIF_RIS_FRM_PAUSE_OFFSET)
#define USIF_RIS_TX_FIN_OFFSET 0x1d
#define USIF_RIS_TX_FIN_WIDTH 0x1
#define USIF_RIS_TX_FIN_MASK 0x20000000
#define USIF_RIS_TX_FIN(_reg) (((_reg) & 0x20000000) >> 0x1d)
#define USIF_RIS_TX_FIN_NO_INT (0x0 << USIF_RIS_TX_FIN_OFFSET)
#define USIF_RIS_TX_FIN_INT_PEND (0x1 << USIF_RIS_TX_FIN_OFFSET)
#define USIF_RIS_RI_OFFSET 0x1c
#define USIF_RIS_RI_WIDTH 0x1
#define USIF_RIS_RI_MASK 0x10000000
#define USIF_RIS_RI(_reg) (((_reg) & 0x10000000) >> 0x1c)
#define USIF_RIS_RI_NO_INT (0x0 << USIF_RIS_RI_OFFSET)
#define USIF_RIS_RI_INT_PEND (0x1 << USIF_RIS_RI_OFFSET)
#define USIF_RIS_DCD_OFFSET 0x1b
#define USIF_RIS_DCD_WIDTH 0x1
#define USIF_RIS_DCD_MASK 0x8000000
#define USIF_RIS_DCD(_reg) (((_reg) & 0x8000000) >> 0x1b)
#define USIF_RIS_DCD_NO_INT (0x0 << USIF_RIS_DCD_OFFSET)
#define USIF_RIS_DCD_INT_PEND (0x1 << USIF_RIS_DCD_OFFSET)
#define USIF_RIS_DSR_OFFSET 0x1a
#define USIF_RIS_DSR_WIDTH 0x1
#define USIF_RIS_DSR_MASK 0x4000000
#define USIF_RIS_DSR(_reg) (((_reg) & 0x4000000) >> 0x1a)
#define USIF_RIS_DSR_NO_INT (0x0 << USIF_RIS_DSR_OFFSET)
#define USIF_RIS_DSR_INT_PEND (0x1 << USIF_RIS_DSR_OFFSET)
#define USIF_RIS_DTR_OFFSET 0x19
#define USIF_RIS_DTR_WIDTH 0x1
#define USIF_RIS_DTR_MASK 0x2000000
#define USIF_RIS_DTR(_reg) (((_reg) & 0x2000000) >> 0x19)
#define USIF_RIS_DTR_NO_INT (0x0 << USIF_RIS_DTR_OFFSET)
#define USIF_RIS_DTR_INT_PEND (0x1 << USIF_RIS_DTR_OFFSET)
#define USIF_RIS_FCI_OFFSET 0x18
#define USIF_RIS_FCI_WIDTH 0x1
#define USIF_RIS_FCI_MASK 0x1000000
#define USIF_RIS_FCI(_reg) (((_reg) & 0x1000000) >> 0x18)
#define USIF_RIS_FCI_NO_INT (0x0 << USIF_RIS_FCI_OFFSET)
#define USIF_RIS_FCI_INT_PEND (0x1 << USIF_RIS_FCI_OFFSET)
#define USIF_RIS_FCO_OFFSET 0x17
#define USIF_RIS_FCO_WIDTH 0x1
#define USIF_RIS_FCO_MASK 0x800000
#define USIF_RIS_FCO(_reg) (((_reg) & 0x800000) >> 0x17)
#define USIF_RIS_FCO_NO_INT (0x0 << USIF_RIS_FCO_OFFSET)
#define USIF_RIS_FCO_INT_PEND (0x1 << USIF_RIS_FCO_OFFSET)
#define USIF_RIS_MC_OFFSET 0x15
#define USIF_RIS_MC_WIDTH 0x1
#define USIF_RIS_MC_MASK 0x200000
#define USIF_RIS_MC(_reg) (((_reg) & 0x200000) >> 0x15)
#define USIF_RIS_MC_NO_INT (0x0 << USIF_RIS_MC_OFFSET)
#define USIF_RIS_MC_INT_PEND (0x1 << USIF_RIS_MC_OFFSET)
#define USIF_RIS_SLIP_OFFSET 0x14
#define USIF_RIS_SLIP_WIDTH 0x1
#define USIF_RIS_SLIP_MASK 0x100000
#define USIF_RIS_SLIP(_reg) (((_reg) & 0x100000) >> 0x14)
#define USIF_RIS_SLIP_NO_INT (0x0 << USIF_RIS_SLIP_OFFSET)
#define USIF_RIS_SLIP_INT_PEND (0x1 << USIF_RIS_SLIP_OFFSET)
#define USIF_RIS_CRC_OFFSET 0x13
#define USIF_RIS_CRC_WIDTH 0x1
#define USIF_RIS_CRC_MASK 0x80000
#define USIF_RIS_CRC(_reg) (((_reg) & 0x80000) >> 0x13)
#define USIF_RIS_CRC_NO_INT (0x0 << USIF_RIS_CRC_OFFSET)
#define USIF_RIS_CRC_INT_PEND (0x1 << USIF_RIS_CRC_OFFSET)
#define USIF_RIS_PHE_OFFSET 0x11
#define USIF_RIS_PHE_WIDTH 0x1
#define USIF_RIS_PHE_MASK 0x20000
#define USIF_RIS_PHE(_reg) (((_reg) & 0x20000) >> 0x11)
#define USIF_RIS_PHE_NO_INT (0x0 << USIF_RIS_PHE_OFFSET)
#define USIF_RIS_PHE_INT_PEND (0x1 << USIF_RIS_PHE_OFFSET)
#define USIF_RIS_FE_OFFSET 0x10
#define USIF_RIS_FE_WIDTH 0x1
#define USIF_RIS_FE_MASK 0x10000
#define USIF_RIS_FE(_reg) (((_reg) & 0x10000) >> 0x10)
#define USIF_RIS_FE_NO_INT (0x0 << USIF_RIS_FE_OFFSET)
#define USIF_RIS_FE_INT_PEND (0x1 << USIF_RIS_FE_OFFSET)
#define USIF_RIS_PE_OFFSET 0xf
#define USIF_RIS_PE_WIDTH 0x1
#define USIF_RIS_PE_MASK 0x8000
#define USIF_RIS_PE(_reg) (((_reg) & 0x8000) >> 0xf)
#define USIF_RIS_PE_NO_INT (0x0 << USIF_RIS_PE_OFFSET)
#define USIF_RIS_PE_INT_PEND (0x1 << USIF_RIS_PE_OFFSET)
#define USIF_RIS_TXOF_OFFSET 0xe
#define USIF_RIS_TXOF_WIDTH 0x1
#define USIF_RIS_TXOF_MASK 0x4000
#define USIF_RIS_TXOF(_reg) (((_reg) & 0x4000) >> 0xe)
#define USIF_RIS_TXOF_NO_INT (0x0 << USIF_RIS_TXOF_OFFSET)
#define USIF_RIS_TXOF_INT_PEND (0x1 << USIF_RIS_TXOF_OFFSET)
#define USIF_RIS_TXUR_OFFSET 0xd
#define USIF_RIS_TXUR_WIDTH 0x1
#define USIF_RIS_TXUR_MASK 0x2000
#define USIF_RIS_TXUR(_reg) (((_reg) & 0x2000) >> 0xd)
#define USIF_RIS_TXUR_NO_INT (0x0 << USIF_RIS_TXUR_OFFSET)
#define USIF_RIS_TXUR_INT_PEND (0x1 << USIF_RIS_TXUR_OFFSET)
#define USIF_RIS_RXOF_OFFSET 0xc
#define USIF_RIS_RXOF_WIDTH 0x1
#define USIF_RIS_RXOF_MASK 0x1000
#define USIF_RIS_RXOF(_reg) (((_reg) & 0x1000) >> 0xc)
#define USIF_RIS_RXOF_NO_INT (0x0 << USIF_RIS_RXOF_OFFSET)
#define USIF_RIS_RXOF_INT_PEND (0x1 << USIF_RIS_RXOF_OFFSET)
#define USIF_RIS_RXUR_OFFSET 0xb
#define USIF_RIS_RXUR_WIDTH 0x1
#define USIF_RIS_RXUR_MASK 0x800
#define USIF_RIS_RXUR(_reg) (((_reg) & 0x800) >> 0xb)
#define USIF_RIS_RXUR_NO_INT (0x0 << USIF_RIS_RXUR_OFFSET)
#define USIF_RIS_RXUR_INT_PEND (0x1 << USIF_RIS_RXUR_OFFSET)
#define USIF_RIS_WKP_OFFSET 0x9
#define USIF_RIS_WKP_WIDTH 0x1
#define USIF_RIS_WKP_MASK 0x200
#define USIF_RIS_WKP(_reg) (((_reg) & 0x200) >> 0x9)
#define USIF_RIS_WKP_NO_INT (0x0 << USIF_RIS_WKP_OFFSET)
#define USIF_RIS_WKP_INT_PEND (0x1 << USIF_RIS_WKP_OFFSET)
#define USIF_RIS_AB_OFFSET 0x8
#define USIF_RIS_AB_WIDTH 0x1
#define USIF_RIS_AB_MASK 0x100
#define USIF_RIS_AB(_reg) (((_reg) & 0x100) >> 0x8)
#define USIF_RIS_AB_NO_INT (0x0 << USIF_RIS_AB_OFFSET)
#define USIF_RIS_AB_INT_PEND (0x1 << USIF_RIS_AB_OFFSET)
#define USIF_RIS_TX_BREQ_OFFSET 0x7
#define USIF_RIS_TX_BREQ_WIDTH 0x1
#define USIF_RIS_TX_BREQ_MASK 0x80
#define USIF_RIS_TX_BREQ(_reg) (((_reg) & 0x80) >> 0x7)
#define USIF_RIS_TX_BREQ_NO_INT (0x0 << USIF_RIS_TX_BREQ_OFFSET)
#define USIF_RIS_TX_BREQ_INT_PEND (0x1 << USIF_RIS_TX_BREQ_OFFSET)
#define USIF_RIS_TX_LBREQ_OFFSET 0x6
#define USIF_RIS_TX_LBREQ_WIDTH 0x1
#define USIF_RIS_TX_LBREQ_MASK 0x40
#define USIF_RIS_TX_LBREQ(_reg) (((_reg) & 0x40) >> 0x6)
#define USIF_RIS_TX_LBREQ_NO_INT (0x0 << USIF_RIS_TX_LBREQ_OFFSET)
#define USIF_RIS_TX_LBREQ_INT_PEND (0x1 << USIF_RIS_TX_LBREQ_OFFSET)
#define USIF_RIS_TX_SREQ_OFFSET 0x5
#define USIF_RIS_TX_SREQ_WIDTH 0x1
#define USIF_RIS_TX_SREQ_MASK 0x20
#define USIF_RIS_TX_SREQ(_reg) (((_reg) & 0x20) >> 0x5)
#define USIF_RIS_TX_SREQ_NO_INT (0x0 << USIF_RIS_TX_SREQ_OFFSET)
#define USIF_RIS_TX_SREQ_INT_PEND (0x1 << USIF_RIS_TX_SREQ_OFFSET)
#define USIF_RIS_TX_LSREQ_OFFSET 0x4
#define USIF_RIS_TX_LSREQ_WIDTH 0x1
#define USIF_RIS_TX_LSREQ_MASK 0x10
#define USIF_RIS_TX_LSREQ(_reg) (((_reg) & 0x10) >> 0x4)
#define USIF_RIS_TX_LSREQ_NO_INT (0x0 << USIF_RIS_TX_LSREQ_OFFSET)
#define USIF_RIS_TX_LSREQ_INT_PEND (0x1 << USIF_RIS_TX_LSREQ_OFFSET)
#define USIF_RIS_RX_BREQ_OFFSET 0x3
#define USIF_RIS_RX_BREQ_WIDTH 0x1
#define USIF_RIS_RX_BREQ_MASK 0x8
#define USIF_RIS_RX_BREQ(_reg) (((_reg) & 0x8) >> 0x3)
#define USIF_RIS_RX_BREQ_NO_INT (0x0 << USIF_RIS_RX_BREQ_OFFSET)
#define USIF_RIS_RX_BREQ_INT_PEND (0x1 << USIF_RIS_RX_BREQ_OFFSET)
#define USIF_RIS_RX_LBREQ_OFFSET 0x2
#define USIF_RIS_RX_LBREQ_WIDTH 0x1
#define USIF_RIS_RX_LBREQ_MASK 0x4
#define USIF_RIS_RX_LBREQ(_reg) (((_reg) & 0x4) >> 0x2)
#define USIF_RIS_RX_LBREQ_NO_INT (0x0 << USIF_RIS_RX_LBREQ_OFFSET)
#define USIF_RIS_RX_LBREQ_INT_PEND (0x1 << USIF_RIS_RX_LBREQ_OFFSET)
#define USIF_RIS_RX_SREQ_OFFSET 0x1
#define USIF_RIS_RX_SREQ_WIDTH 0x1
#define USIF_RIS_RX_SREQ_MASK 0x2
#define USIF_RIS_RX_SREQ(_reg) (((_reg) & 0x2) >> 0x1)
#define USIF_RIS_RX_SREQ_NO_INT (0x0 << USIF_RIS_RX_SREQ_OFFSET)
#define USIF_RIS_RX_SREQ_INT_PEND (0x1 << USIF_RIS_RX_SREQ_OFFSET)
#define USIF_RIS_RX_LSREQ_OFFSET 0x0
#define USIF_RIS_RX_LSREQ_WIDTH 0x1
#define USIF_RIS_RX_LSREQ_MASK 0x1
#define USIF_RIS_RX_LSREQ(_reg) (((_reg) & 0x1) >> 0x0)
#define USIF_RIS_RX_LSREQ_NO_INT (0x0 << USIF_RIS_RX_LSREQ_OFFSET)
#define USIF_RIS_RX_LSREQ_INT_PEND (0x1 << USIF_RIS_RX_LSREQ_OFFSET)

#define USIF_IMSC_OFFSET	  0x84
#define USIF_IMSC(_base) ((_base) + 0x84)
#define USIF_IMSC_TMO_OFFSET 0x1f
#define USIF_IMSC_TMO_WIDTH 0x1
#define USIF_IMSC_TMO_MASK 0x80000000
#define USIF_IMSC_TMO(_reg) (((_reg) & 0x80000000) >> 0x1f)
#define USIF_IMSC_TMO_INT_DIS (0x0 << USIF_IMSC_TMO_OFFSET)
#define USIF_IMSC_TMO_INT_EN (0x1 << USIF_IMSC_TMO_OFFSET)
#define USIF_IMSC_FRM_PAUSE_OFFSET 0x1e
#define USIF_IMSC_FRM_PAUSE_WIDTH 0x1
#define USIF_IMSC_FRM_PAUSE_MASK 0x40000000
#define USIF_IMSC_FRM_PAUSE(_reg) (((_reg) & 0x40000000) >> 0x1e)
#define USIF_IMSC_FRM_PAUSE_INT_DIS (0x0 << USIF_IMSC_FRM_PAUSE_OFFSET)
#define USIF_IMSC_FRM_PAUSE_INT_EN (0x1 << USIF_IMSC_FRM_PAUSE_OFFSET)
#define USIF_IMSC_TX_FIN_OFFSET 0x1d
#define USIF_IMSC_TX_FIN_WIDTH 0x1
#define USIF_IMSC_TX_FIN_MASK 0x20000000
#define USIF_IMSC_TX_FIN(_reg) (((_reg) & 0x20000000) >> 0x1d)
#define USIF_IMSC_TX_FIN_INT_DIS (0x0 << USIF_IMSC_TX_FIN_OFFSET)
#define USIF_IMSC_TX_FIN_INT_EN (0x1 << USIF_IMSC_TX_FIN_OFFSET)
#define USIF_IMSC_RI_OFFSET 0x1c
#define USIF_IMSC_RI_WIDTH 0x1
#define USIF_IMSC_RI_MASK 0x10000000
#define USIF_IMSC_RI(_reg) (((_reg) & 0x10000000) >> 0x1c)
#define USIF_IMSC_RI_INT_DIS (0x0 << USIF_IMSC_RI_OFFSET)
#define USIF_IMSC_RI_INT_EN (0x1 << USIF_IMSC_RI_OFFSET)
#define USIF_IMSC_DCD_OFFSET 0x1b
#define USIF_IMSC_DCD_WIDTH 0x1
#define USIF_IMSC_DCD_MASK 0x8000000
#define USIF_IMSC_DCD(_reg) (((_reg) & 0x8000000) >> 0x1b)
#define USIF_IMSC_DCD_INT_DIS (0x0 << USIF_IMSC_DCD_OFFSET)
#define USIF_IMSC_DCD_INT_EN (0x1 << USIF_IMSC_DCD_OFFSET)
#define USIF_IMSC_DSR_OFFSET 0x1a
#define USIF_IMSC_DSR_WIDTH 0x1
#define USIF_IMSC_DSR_MASK 0x4000000
#define USIF_IMSC_DSR(_reg) (((_reg) & 0x4000000) >> 0x1a)
#define USIF_IMSC_DSR_INT_DIS (0x0 << USIF_IMSC_DSR_OFFSET)
#define USIF_IMSC_DSR_INT_EN (0x1 << USIF_IMSC_DSR_OFFSET)
#define USIF_IMSC_DTR_OFFSET 0x19
#define USIF_IMSC_DTR_WIDTH 0x1
#define USIF_IMSC_DTR_MASK 0x2000000
#define USIF_IMSC_DTR(_reg) (((_reg) & 0x2000000) >> 0x19)
#define USIF_IMSC_DTR_INT_DIS (0x0 << USIF_IMSC_DTR_OFFSET)
#define USIF_IMSC_DTR_INT_EN (0x1 << USIF_IMSC_DTR_OFFSET)
#define USIF_IMSC_FCI_OFFSET 0x18
#define USIF_IMSC_FCI_WIDTH 0x1
#define USIF_IMSC_FCI_MASK 0x1000000
#define USIF_IMSC_FCI(_reg) (((_reg) & 0x1000000) >> 0x18)
#define USIF_IMSC_FCI_INT_DIS (0x0 << USIF_IMSC_FCI_OFFSET)
#define USIF_IMSC_FCI_INT_EN (0x1 << USIF_IMSC_FCI_OFFSET)
#define USIF_IMSC_FCO_OFFSET 0x17
#define USIF_IMSC_FCO_WIDTH 0x1
#define USIF_IMSC_FCO_MASK 0x800000
#define USIF_IMSC_FCO(_reg) (((_reg) & 0x800000) >> 0x17)
#define USIF_IMSC_FCO_INT_DIS (0x0 << USIF_IMSC_FCO_OFFSET)
#define USIF_IMSC_FCO_INT_EN (0x1 << USIF_IMSC_FCO_OFFSET)
#define USIF_IMSC_MC_OFFSET 0x15
#define USIF_IMSC_MC_WIDTH 0x1
#define USIF_IMSC_MC_MASK 0x200000
#define USIF_IMSC_MC(_reg) (((_reg) & 0x200000) >> 0x15)
#define USIF_IMSC_MC_INT_DIS (0x0 << USIF_IMSC_MC_OFFSET)
#define USIF_IMSC_MC_INT_EN (0x1 << USIF_IMSC_MC_OFFSET)
#define USIF_IMSC_SLIP_OFFSET 0x14
#define USIF_IMSC_SLIP_WIDTH 0x1
#define USIF_IMSC_SLIP_MASK 0x100000
#define USIF_IMSC_SLIP(_reg) (((_reg) & 0x100000) >> 0x14)
#define USIF_IMSC_SLIP_INT_DIS (0x0 << USIF_IMSC_SLIP_OFFSET)
#define USIF_IMSC_SLIP_INT_EN (0x1 << USIF_IMSC_SLIP_OFFSET)
#define USIF_IMSC_CRC_OFFSET 0x13
#define USIF_IMSC_CRC_WIDTH 0x1
#define USIF_IMSC_CRC_MASK 0x80000
#define USIF_IMSC_CRC(_reg) (((_reg) & 0x80000) >> 0x13)
#define USIF_IMSC_CRC_INT_DIS (0x0 << USIF_IMSC_CRC_OFFSET)
#define USIF_IMSC_CRC_INT_EN (0x1 << USIF_IMSC_CRC_OFFSET)
#define USIF_IMSC_PHE_OFFSET 0x11
#define USIF_IMSC_PHE_WIDTH 0x1
#define USIF_IMSC_PHE_MASK 0x20000
#define USIF_IMSC_PHE(_reg) (((_reg) & 0x20000) >> 0x11)
#define USIF_IMSC_PHE_INT_DIS (0x0 << USIF_IMSC_PHE_OFFSET)
#define USIF_IMSC_PHE_INT_EN (0x1 << USIF_IMSC_PHE_OFFSET)
#define USIF_IMSC_FE_OFFSET 0x10
#define USIF_IMSC_FE_WIDTH 0x1
#define USIF_IMSC_FE_MASK 0x10000
#define USIF_IMSC_FE(_reg) (((_reg) & 0x10000) >> 0x10)
#define USIF_IMSC_FE_INT_DIS (0x0 << USIF_IMSC_FE_OFFSET)
#define USIF_IMSC_FE_INT_EN (0x1 << USIF_IMSC_FE_OFFSET)
#define USIF_IMSC_PE_OFFSET 0xf
#define USIF_IMSC_PE_WIDTH 0x1
#define USIF_IMSC_PE_MASK 0x8000
#define USIF_IMSC_PE(_reg) (((_reg) & 0x8000) >> 0xf)
#define USIF_IMSC_PE_INT_DIS (0x0 << USIF_IMSC_PE_OFFSET)
#define USIF_IMSC_PE_INT_EN (0x1 << USIF_IMSC_PE_OFFSET)
#define USIF_IMSC_TXOF_OFFSET 0xe
#define USIF_IMSC_TXOF_WIDTH 0x1
#define USIF_IMSC_TXOF_MASK 0x4000
#define USIF_IMSC_TXOF(_reg) (((_reg) & 0x4000) >> 0xe)
#define USIF_IMSC_TXOF_INT_DIS (0x0 << USIF_IMSC_TXOF_OFFSET)
#define USIF_IMSC_TXOF_INT_EN (0x1 << USIF_IMSC_TXOF_OFFSET)
#define USIF_IMSC_TXUR_OFFSET 0xd
#define USIF_IMSC_TXUR_WIDTH 0x1
#define USIF_IMSC_TXUR_MASK 0x2000
#define USIF_IMSC_TXUR(_reg) (((_reg) & 0x2000) >> 0xd)
#define USIF_IMSC_TXUR_INT_DIS (0x0 << USIF_IMSC_TXUR_OFFSET)
#define USIF_IMSC_TXUR_INT_EN (0x1 << USIF_IMSC_TXUR_OFFSET)
#define USIF_IMSC_RXOF_OFFSET 0xc
#define USIF_IMSC_RXOF_WIDTH 0x1
#define USIF_IMSC_RXOF_MASK 0x1000
#define USIF_IMSC_RXOF(_reg) (((_reg) & 0x1000) >> 0xc)
#define USIF_IMSC_RXOF_INT_DIS (0x0 << USIF_IMSC_RXOF_OFFSET)
#define USIF_IMSC_RXOF_INT_EN (0x1 << USIF_IMSC_RXOF_OFFSET)
#define USIF_IMSC_RXUR_OFFSET 0xb
#define USIF_IMSC_RXUR_WIDTH 0x1
#define USIF_IMSC_RXUR_MASK 0x800
#define USIF_IMSC_RXUR(_reg) (((_reg) & 0x800) >> 0xb)
#define USIF_IMSC_RXUR_INT_DIS (0x0 << USIF_IMSC_RXUR_OFFSET)
#define USIF_IMSC_RXUR_INT_EN (0x1 << USIF_IMSC_RXUR_OFFSET)
#define USIF_IMSC_WKP_OFFSET 0x9
#define USIF_IMSC_WKP_WIDTH 0x1
#define USIF_IMSC_WKP_MASK 0x200
#define USIF_IMSC_WKP(_reg) (((_reg) & 0x200) >> 0x9)
#define USIF_IMSC_WKP_INT_DIS (0x0 << USIF_IMSC_WKP_OFFSET)
#define USIF_IMSC_WKP_INT_EN (0x1 << USIF_IMSC_WKP_OFFSET)
#define USIF_IMSC_AB_OFFSET 0x8
#define USIF_IMSC_AB_WIDTH 0x1
#define USIF_IMSC_AB_MASK 0x100
#define USIF_IMSC_AB(_reg) (((_reg) & 0x100) >> 0x8)
#define USIF_IMSC_AB_INT_DIS (0x0 << USIF_IMSC_AB_OFFSET)
#define USIF_IMSC_AB_INT_EN (0x1 << USIF_IMSC_AB_OFFSET)
#define USIF_IMSC_TX_BREQ_OFFSET 0x7
#define USIF_IMSC_TX_BREQ_WIDTH 0x1
#define USIF_IMSC_TX_BREQ_MASK 0x80
#define USIF_IMSC_TX_BREQ(_reg) (((_reg) & 0x80) >> 0x7)
#define USIF_IMSC_TX_BREQ_INT_DIS (0x0 << USIF_IMSC_TX_BREQ_OFFSET)
#define USIF_IMSC_TX_BREQ_INT_EN (0x1 << USIF_IMSC_TX_BREQ_OFFSET)
#define USIF_IMSC_TX_LBREQ_OFFSET 0x6
#define USIF_IMSC_TX_LBREQ_WIDTH 0x1
#define USIF_IMSC_TX_LBREQ_MASK 0x40
#define USIF_IMSC_TX_LBREQ(_reg) (((_reg) & 0x40) >> 0x6)
#define USIF_IMSC_TX_LBREQ_INT_DIS (0x0 << USIF_IMSC_TX_LBREQ_OFFSET)
#define USIF_IMSC_TX_LBREQ_INT_EN (0x1 << USIF_IMSC_TX_LBREQ_OFFSET)
#define USIF_IMSC_TX_SREQ_OFFSET 0x5
#define USIF_IMSC_TX_SREQ_WIDTH 0x1
#define USIF_IMSC_TX_SREQ_MASK 0x20
#define USIF_IMSC_TX_SREQ(_reg) (((_reg) & 0x20) >> 0x5)
#define USIF_IMSC_TX_SREQ_INT_DIS (0x0 << USIF_IMSC_TX_SREQ_OFFSET)
#define USIF_IMSC_TX_SREQ_INT_EN (0x1 << USIF_IMSC_TX_SREQ_OFFSET)
#define USIF_IMSC_TX_LSREQ_OFFSET 0x4
#define USIF_IMSC_TX_LSREQ_WIDTH 0x1
#define USIF_IMSC_TX_LSREQ_MASK 0x10
#define USIF_IMSC_TX_LSREQ(_reg) (((_reg) & 0x10) >> 0x4)
#define USIF_IMSC_TX_LSREQ_INT_DIS (0x0 << USIF_IMSC_TX_LSREQ_OFFSET)
#define USIF_IMSC_TX_LSREQ_INT_EN (0x1 << USIF_IMSC_TX_LSREQ_OFFSET)
#define USIF_IMSC_RX_BREQ_OFFSET 0x3
#define USIF_IMSC_RX_BREQ_WIDTH 0x1
#define USIF_IMSC_RX_BREQ_MASK 0x8
#define USIF_IMSC_RX_BREQ(_reg) (((_reg) & 0x8) >> 0x3)
#define USIF_IMSC_RX_BREQ_INT_DIS (0x0 << USIF_IMSC_RX_BREQ_OFFSET)
#define USIF_IMSC_RX_BREQ_INT_EN (0x1 << USIF_IMSC_RX_BREQ_OFFSET)
#define USIF_IMSC_RX_LBREQ_OFFSET 0x2
#define USIF_IMSC_RX_LBREQ_WIDTH 0x1
#define USIF_IMSC_RX_LBREQ_MASK 0x4
#define USIF_IMSC_RX_LBREQ(_reg) (((_reg) & 0x4) >> 0x2)
#define USIF_IMSC_RX_LBREQ_INT_DIS (0x0 << USIF_IMSC_RX_LBREQ_OFFSET)
#define USIF_IMSC_RX_LBREQ_INT_EN (0x1 << USIF_IMSC_RX_LBREQ_OFFSET)
#define USIF_IMSC_RX_SREQ_OFFSET 0x1
#define USIF_IMSC_RX_SREQ_WIDTH 0x1
#define USIF_IMSC_RX_SREQ_MASK 0x2
#define USIF_IMSC_RX_SREQ(_reg) (((_reg) & 0x2) >> 0x1)
#define USIF_IMSC_RX_SREQ_INT_DIS (0x0 << USIF_IMSC_RX_SREQ_OFFSET)
#define USIF_IMSC_RX_SREQ_INT_EN (0x1 << USIF_IMSC_RX_SREQ_OFFSET)
#define USIF_IMSC_RX_LSREQ_OFFSET 0x0
#define USIF_IMSC_RX_LSREQ_WIDTH 0x1
#define USIF_IMSC_RX_LSREQ_MASK 0x1
#define USIF_IMSC_RX_LSREQ(_reg) (((_reg) & 0x1) >> 0x0)
#define USIF_IMSC_RX_LSREQ_INT_DIS (0x0 << USIF_IMSC_RX_LSREQ_OFFSET)
#define USIF_IMSC_RX_LSREQ_INT_EN (0x1 << USIF_IMSC_RX_LSREQ_OFFSET)

#define USIF_MIS_OFFSET		  0x88
#define USIF_MIS(_base) ((_base) + 0x88)
#define USIF_MIS_TMO_OFFSET 0x1f
#define USIF_MIS_TMO_WIDTH 0x1
#define USIF_MIS_TMO_MASK 0x80000000
#define USIF_MIS_TMO(_reg) (((_reg) & 0x80000000) >> 0x1f)
#define USIF_MIS_TMO_NO_INT (0x0 << USIF_MIS_TMO_OFFSET)
#define USIF_MIS_TMO_INT_PEND (0x1 << USIF_MIS_TMO_OFFSET)
#define USIF_MIS_FRM_PAUSE_OFFSET 0x1e
#define USIF_MIS_FRM_PAUSE_WIDTH 0x1
#define USIF_MIS_FRM_PAUSE_MASK 0x40000000
#define USIF_MIS_FRM_PAUSE(_reg) (((_reg) & 0x40000000) >> 0x1e)
#define USIF_MIS_FRM_PAUSE_NO_INT (0x0 << USIF_MIS_FRM_PAUSE_OFFSET)
#define USIF_MIS_FRM_PAUSE_INT_PEND (0x1 << USIF_MIS_FRM_PAUSE_OFFSET)
#define USIF_MIS_TX_FIN_OFFSET 0x1d
#define USIF_MIS_TX_FIN_WIDTH 0x1
#define USIF_MIS_TX_FIN_MASK 0x20000000
#define USIF_MIS_TX_FIN(_reg) (((_reg) & 0x20000000) >> 0x1d)
#define USIF_MIS_TX_FIN_NO_INT (0x0 << USIF_MIS_TX_FIN_OFFSET)
#define USIF_MIS_TX_FIN_INT_PEND (0x1 << USIF_MIS_TX_FIN_OFFSET)
#define USIF_MIS_RI_OFFSET 0x1c
#define USIF_MIS_RI_WIDTH 0x1
#define USIF_MIS_RI_MASK 0x10000000
#define USIF_MIS_RI(_reg) (((_reg) & 0x10000000) >> 0x1c)
#define USIF_MIS_RI_NO_INT (0x0 << USIF_MIS_RI_OFFSET)
#define USIF_MIS_RI_INT_PEND (0x1 << USIF_MIS_RI_OFFSET)
#define USIF_MIS_DCD_OFFSET 0x1b
#define USIF_MIS_DCD_WIDTH 0x1
#define USIF_MIS_DCD_MASK 0x8000000
#define USIF_MIS_DCD(_reg) (((_reg) & 0x8000000) >> 0x1b)
#define USIF_MIS_DCD_NO_INT (0x0 << USIF_MIS_DCD_OFFSET)
#define USIF_MIS_DCD_INT_PEND (0x1 << USIF_MIS_DCD_OFFSET)
#define USIF_MIS_DSR_OFFSET 0x1a
#define USIF_MIS_DSR_WIDTH 0x1
#define USIF_MIS_DSR_MASK 0x4000000
#define USIF_MIS_DSR(_reg) (((_reg) & 0x4000000) >> 0x1a)
#define USIF_MIS_DSR_NO_INT (0x0 << USIF_MIS_DSR_OFFSET)
#define USIF_MIS_DSR_INT_PEND (0x1 << USIF_MIS_DSR_OFFSET)
#define USIF_MIS_DTR_OFFSET 0x19
#define USIF_MIS_DTR_WIDTH 0x1
#define USIF_MIS_DTR_MASK 0x2000000
#define USIF_MIS_DTR(_reg) (((_reg) & 0x2000000) >> 0x19)
#define USIF_MIS_DTR_NO_INT (0x0 << USIF_MIS_DTR_OFFSET)
#define USIF_MIS_DTR_INT_PEND (0x1 << USIF_MIS_DTR_OFFSET)
#define USIF_MIS_FCI_OFFSET 0x18
#define USIF_MIS_FCI_WIDTH 0x1
#define USIF_MIS_FCI_MASK 0x1000000
#define USIF_MIS_FCI(_reg) (((_reg) & 0x1000000) >> 0x18)
#define USIF_MIS_FCI_NO_INT (0x0 << USIF_MIS_FCI_OFFSET)
#define USIF_MIS_FCI_INT_PEND (0x1 << USIF_MIS_FCI_OFFSET)
#define USIF_MIS_FCO_OFFSET 0x17
#define USIF_MIS_FCO_WIDTH 0x1
#define USIF_MIS_FCO_MASK 0x800000
#define USIF_MIS_FCO(_reg) (((_reg) & 0x800000) >> 0x17)
#define USIF_MIS_FCO_NO_INT (0x0 << USIF_MIS_FCO_OFFSET)
#define USIF_MIS_FCO_INT_PEND (0x1 << USIF_MIS_FCO_OFFSET)
#define USIF_MIS_MC_OFFSET 0x15
#define USIF_MIS_MC_WIDTH 0x1
#define USIF_MIS_MC_MASK 0x200000
#define USIF_MIS_MC(_reg) (((_reg) & 0x200000) >> 0x15)
#define USIF_MIS_MC_NO_INT (0x0 << USIF_MIS_MC_OFFSET)
#define USIF_MIS_MC_INT_PEND (0x1 << USIF_MIS_MC_OFFSET)
#define USIF_MIS_SLIP_OFFSET 0x14
#define USIF_MIS_SLIP_WIDTH 0x1
#define USIF_MIS_SLIP_MASK 0x100000
#define USIF_MIS_SLIP(_reg) (((_reg) & 0x100000) >> 0x14)
#define USIF_MIS_SLIP_NO_INT (0x0 << USIF_MIS_SLIP_OFFSET)
#define USIF_MIS_SLIP_INT_PEND (0x1 << USIF_MIS_SLIP_OFFSET)
#define USIF_MIS_CRC_OFFSET 0x13
#define USIF_MIS_CRC_WIDTH 0x1
#define USIF_MIS_CRC_MASK 0x80000
#define USIF_MIS_CRC(_reg) (((_reg) & 0x80000) >> 0x13)
#define USIF_MIS_CRC_NO_INT (0x0 << USIF_MIS_CRC_OFFSET)
#define USIF_MIS_CRC_INT_PEND (0x1 << USIF_MIS_CRC_OFFSET)
#define USIF_MIS_PHE_OFFSET 0x11
#define USIF_MIS_PHE_WIDTH 0x1
#define USIF_MIS_PHE_MASK 0x20000
#define USIF_MIS_PHE(_reg) (((_reg) & 0x20000) >> 0x11)
#define USIF_MIS_PHE_NO_INT (0x0 << USIF_MIS_PHE_OFFSET)
#define USIF_MIS_PHE_INT_PEND (0x1 << USIF_MIS_PHE_OFFSET)
#define USIF_MIS_FE_OFFSET 0x10
#define USIF_MIS_FE_WIDTH 0x1
#define USIF_MIS_FE_MASK 0x10000
#define USIF_MIS_FE(_reg) (((_reg) & 0x10000) >> 0x10)
#define USIF_MIS_FE_NO_INT (0x0 << USIF_MIS_FE_OFFSET)
#define USIF_MIS_FE_INT_PEND (0x1 << USIF_MIS_FE_OFFSET)
#define USIF_MIS_PE_OFFSET 0xf
#define USIF_MIS_PE_WIDTH 0x1
#define USIF_MIS_PE_MASK 0x8000
#define USIF_MIS_PE(_reg) (((_reg) & 0x8000) >> 0xf)
#define USIF_MIS_PE_NO_INT (0x0 << USIF_MIS_PE_OFFSET)
#define USIF_MIS_PE_INT_PEND (0x1 << USIF_MIS_PE_OFFSET)
#define USIF_MIS_TXOF_OFFSET 0xe
#define USIF_MIS_TXOF_WIDTH 0x1
#define USIF_MIS_TXOF_MASK 0x4000
#define USIF_MIS_TXOF(_reg) (((_reg) & 0x4000) >> 0xe)
#define USIF_MIS_TXOF_NO_INT (0x0 << USIF_MIS_TXOF_OFFSET)
#define USIF_MIS_TXOF_INT_PEND (0x1 << USIF_MIS_TXOF_OFFSET)
#define USIF_MIS_TXUR_OFFSET 0xd
#define USIF_MIS_TXUR_WIDTH 0x1
#define USIF_MIS_TXUR_MASK 0x2000
#define USIF_MIS_TXUR(_reg) (((_reg) & 0x2000) >> 0xd)
#define USIF_MIS_TXUR_NO_INT (0x0 << USIF_MIS_TXUR_OFFSET)
#define USIF_MIS_TXUR_INT_PEND (0x1 << USIF_MIS_TXUR_OFFSET)
#define USIF_MIS_RXOF_OFFSET 0xc
#define USIF_MIS_RXOF_WIDTH 0x1
#define USIF_MIS_RXOF_MASK 0x1000
#define USIF_MIS_RXOF(_reg) (((_reg) & 0x1000) >> 0xc)
#define USIF_MIS_RXOF_NO_INT (0x0 << USIF_MIS_RXOF_OFFSET)
#define USIF_MIS_RXOF_INT_PEND (0x1 << USIF_MIS_RXOF_OFFSET)
#define USIF_MIS_RXUR_OFFSET 0xb
#define USIF_MIS_RXUR_WIDTH 0x1
#define USIF_MIS_RXUR_MASK 0x800
#define USIF_MIS_RXUR(_reg) (((_reg) & 0x800) >> 0xb)
#define USIF_MIS_RXUR_NO_INT (0x0 << USIF_MIS_RXUR_OFFSET)
#define USIF_MIS_RXUR_INT_PEND (0x1 << USIF_MIS_RXUR_OFFSET)
#define USIF_MIS_WKP_OFFSET 0x9
#define USIF_MIS_WKP_WIDTH 0x1
#define USIF_MIS_WKP_MASK 0x200
#define USIF_MIS_WKP(_reg) (((_reg) & 0x200) >> 0x9)
#define USIF_MIS_WKP_NO_INT (0x0 << USIF_MIS_WKP_OFFSET)
#define USIF_MIS_WKP_INT_PEND (0x1 << USIF_MIS_WKP_OFFSET)
#define USIF_MIS_AB_OFFSET 0x8
#define USIF_MIS_AB_WIDTH 0x1
#define USIF_MIS_AB_MASK 0x100
#define USIF_MIS_AB(_reg) (((_reg) & 0x100) >> 0x8)
#define USIF_MIS_AB_NO_INT (0x0 << USIF_MIS_AB_OFFSET)
#define USIF_MIS_AB_INT_PEND (0x1 << USIF_MIS_AB_OFFSET)
#define USIF_MIS_TX_BREQ_OFFSET 0x7
#define USIF_MIS_TX_BREQ_WIDTH 0x1
#define USIF_MIS_TX_BREQ_MASK 0x80
#define USIF_MIS_TX_BREQ(_reg) (((_reg) & 0x80) >> 0x7)
#define USIF_MIS_TX_BREQ_NO_INT (0x0 << USIF_MIS_TX_BREQ_OFFSET)
#define USIF_MIS_TX_BREQ_INT_PEND (0x1 << USIF_MIS_TX_BREQ_OFFSET)
#define USIF_MIS_TX_LBREQ_OFFSET 0x6
#define USIF_MIS_TX_LBREQ_WIDTH 0x1
#define USIF_MIS_TX_LBREQ_MASK 0x40
#define USIF_MIS_TX_LBREQ(_reg) (((_reg) & 0x40) >> 0x6)
#define USIF_MIS_TX_LBREQ_NO_INT (0x0 << USIF_MIS_TX_LBREQ_OFFSET)
#define USIF_MIS_TX_LBREQ_INT_PEND (0x1 << USIF_MIS_TX_LBREQ_OFFSET)
#define USIF_MIS_TX_SREQ_OFFSET 0x5
#define USIF_MIS_TX_SREQ_WIDTH 0x1
#define USIF_MIS_TX_SREQ_MASK 0x20
#define USIF_MIS_TX_SREQ(_reg) (((_reg) & 0x20) >> 0x5)
#define USIF_MIS_TX_SREQ_NO_INT (0x0 << USIF_MIS_TX_SREQ_OFFSET)
#define USIF_MIS_TX_SREQ_INT_PEND (0x1 << USIF_MIS_TX_SREQ_OFFSET)
#define USIF_MIS_TX_LSREQ_OFFSET 0x4
#define USIF_MIS_TX_LSREQ_WIDTH 0x1
#define USIF_MIS_TX_LSREQ_MASK 0x10
#define USIF_MIS_TX_LSREQ(_reg) (((_reg) & 0x10) >> 0x4)
#define USIF_MIS_TX_LSREQ_NO_INT (0x0 << USIF_MIS_TX_LSREQ_OFFSET)
#define USIF_MIS_TX_LSREQ_INT_PEND (0x1 << USIF_MIS_TX_LSREQ_OFFSET)
#define USIF_MIS_RX_BREQ_OFFSET 0x3
#define USIF_MIS_RX_BREQ_WIDTH 0x1
#define USIF_MIS_RX_BREQ_MASK 0x8
#define USIF_MIS_RX_BREQ(_reg) (((_reg) & 0x8) >> 0x3)
#define USIF_MIS_RX_BREQ_NO_INT (0x0 << USIF_MIS_RX_BREQ_OFFSET)
#define USIF_MIS_RX_BREQ_INT_PEND (0x1 << USIF_MIS_RX_BREQ_OFFSET)
#define USIF_MIS_RX_LBREQ_OFFSET 0x2
#define USIF_MIS_RX_LBREQ_WIDTH 0x1
#define USIF_MIS_RX_LBREQ_MASK 0x4
#define USIF_MIS_RX_LBREQ(_reg) (((_reg) & 0x4) >> 0x2)
#define USIF_MIS_RX_LBREQ_NO_INT (0x0 << USIF_MIS_RX_LBREQ_OFFSET)
#define USIF_MIS_RX_LBREQ_INT_PEND (0x1 << USIF_MIS_RX_LBREQ_OFFSET)
#define USIF_MIS_RX_SREQ_OFFSET 0x1
#define USIF_MIS_RX_SREQ_WIDTH 0x1
#define USIF_MIS_RX_SREQ_MASK 0x2
#define USIF_MIS_RX_SREQ(_reg) (((_reg) & 0x2) >> 0x1)
#define USIF_MIS_RX_SREQ_NO_INT (0x0 << USIF_MIS_RX_SREQ_OFFSET)
#define USIF_MIS_RX_SREQ_INT_PEND (0x1 << USIF_MIS_RX_SREQ_OFFSET)
#define USIF_MIS_RX_LSREQ_OFFSET 0x0
#define USIF_MIS_RX_LSREQ_WIDTH 0x1
#define USIF_MIS_RX_LSREQ_MASK 0x1
#define USIF_MIS_RX_LSREQ(_reg) (((_reg) & 0x1) >> 0x0)
#define USIF_MIS_RX_LSREQ_NO_INT (0x0 << USIF_MIS_RX_LSREQ_OFFSET)
#define USIF_MIS_RX_LSREQ_INT_PEND (0x1 << USIF_MIS_RX_LSREQ_OFFSET)

#define USIF_ISR_OFFSET		  0x90
#define USIF_ISR(_base) ((_base) + 0x90)
#define USIF_ISR_TMO_OFFSET 0x1f
#define USIF_ISR_TMO_WIDTH 0x1
#define USIF_ISR_TMO_MASK 0x80000000
#define USIF_ISR_TMO(_reg) (((_reg) & 0x80000000) >> 0x1f)
#define USIF_ISR_TMO_NO_CHANGE (0x0 << USIF_ISR_TMO_OFFSET)
#define USIF_ISR_TMO_SET_INT (0x1 << USIF_ISR_TMO_OFFSET)
#define USIF_ISR_FRM_PAUSE_OFFSET 0x1e
#define USIF_ISR_FRM_PAUSE_WIDTH 0x1
#define USIF_ISR_FRM_PAUSE_MASK 0x40000000
#define USIF_ISR_FRM_PAUSE(_reg) (((_reg) & 0x40000000) >> 0x1e)
#define USIF_ISR_FRM_PAUSE_NO_CHANGE (0x0 << USIF_ISR_FRM_PAUSE_OFFSET)
#define USIF_ISR_FRM_PAUSE_SET_INT (0x1 << USIF_ISR_FRM_PAUSE_OFFSET)
#define USIF_ISR_TX_FIN_OFFSET 0x1d
#define USIF_ISR_TX_FIN_WIDTH 0x1
#define USIF_ISR_TX_FIN_MASK 0x20000000
#define USIF_ISR_TX_FIN(_reg) (((_reg) & 0x20000000) >> 0x1d)
#define USIF_ISR_TX_FIN_NO_CHANGE (0x0 << USIF_ISR_TX_FIN_OFFSET)
#define USIF_ISR_TX_FIN_SET_INT (0x1 << USIF_ISR_TX_FIN_OFFSET)
#define USIF_ISR_RI_OFFSET 0x1c
#define USIF_ISR_RI_WIDTH 0x1
#define USIF_ISR_RI_MASK 0x10000000
#define USIF_ISR_RI(_reg) (((_reg) & 0x10000000) >> 0x1c)
#define USIF_ISR_RI_NO_CHANGE (0x0 << USIF_ISR_RI_OFFSET)
#define USIF_ISR_RI_SET_INT (0x1 << USIF_ISR_RI_OFFSET)
#define USIF_ISR_DCD_OFFSET 0x1b
#define USIF_ISR_DCD_WIDTH 0x1
#define USIF_ISR_DCD_MASK 0x8000000
#define USIF_ISR_DCD(_reg) (((_reg) & 0x8000000) >> 0x1b)
#define USIF_ISR_DCD_NO_CHANGE (0x0 << USIF_ISR_DCD_OFFSET)
#define USIF_ISR_DCD_SET_INT (0x1 << USIF_ISR_DCD_OFFSET)
#define USIF_ISR_DSR_OFFSET 0x1a
#define USIF_ISR_DSR_WIDTH 0x1
#define USIF_ISR_DSR_MASK 0x4000000
#define USIF_ISR_DSR(_reg) (((_reg) & 0x4000000) >> 0x1a)
#define USIF_ISR_DSR_NO_CHANGE (0x0 << USIF_ISR_DSR_OFFSET)
#define USIF_ISR_DSR_SET_INT (0x1 << USIF_ISR_DSR_OFFSET)
#define USIF_ISR_DTR_OFFSET 0x19
#define USIF_ISR_DTR_WIDTH 0x1
#define USIF_ISR_DTR_MASK 0x2000000
#define USIF_ISR_DTR(_reg) (((_reg) & 0x2000000) >> 0x19)
#define USIF_ISR_DTR_NO_CHANGE (0x0 << USIF_ISR_DTR_OFFSET)
#define USIF_ISR_DTR_SET_INT (0x1 << USIF_ISR_DTR_OFFSET)
#define USIF_ISR_FCI_OFFSET 0x18
#define USIF_ISR_FCI_WIDTH 0x1
#define USIF_ISR_FCI_MASK 0x1000000
#define USIF_ISR_FCI(_reg) (((_reg) & 0x1000000) >> 0x18)
#define USIF_ISR_FCI_NO_CHANGE (0x0 << USIF_ISR_FCI_OFFSET)
#define USIF_ISR_FCI_SET_INT (0x1 << USIF_ISR_FCI_OFFSET)
#define USIF_ISR_FCO_OFFSET 0x17
#define USIF_ISR_FCO_WIDTH 0x1
#define USIF_ISR_FCO_MASK 0x800000
#define USIF_ISR_FCO(_reg) (((_reg) & 0x800000) >> 0x17)
#define USIF_ISR_FCO_NO_CHANGE (0x0 << USIF_ISR_FCO_OFFSET)
#define USIF_ISR_FCO_SET_INT (0x1 << USIF_ISR_FCO_OFFSET)
#define USIF_ISR_MC_OFFSET 0x15
#define USIF_ISR_MC_WIDTH 0x1
#define USIF_ISR_MC_MASK 0x200000
#define USIF_ISR_MC(_reg) (((_reg) & 0x200000) >> 0x15)
#define USIF_ISR_MC_NO_CHANGE (0x0 << USIF_ISR_MC_OFFSET)
#define USIF_ISR_MC_SET_INT (0x1 << USIF_ISR_MC_OFFSET)
#define USIF_ISR_SLIP_OFFSET 0x14
#define USIF_ISR_SLIP_WIDTH 0x1
#define USIF_ISR_SLIP_MASK 0x100000
#define USIF_ISR_SLIP(_reg) (((_reg) & 0x100000) >> 0x14)
#define USIF_ISR_SLIP_NO_CHANGE (0x0 << USIF_ISR_SLIP_OFFSET)
#define USIF_ISR_SLIP_SET_INT (0x1 << USIF_ISR_SLIP_OFFSET)
#define USIF_ISR_CRC_OFFSET 0x13
#define USIF_ISR_CRC_WIDTH 0x1
#define USIF_ISR_CRC_MASK 0x80000
#define USIF_ISR_CRC(_reg) (((_reg) & 0x80000) >> 0x13)
#define USIF_ISR_CRC_NO_CHANGE (0x0 << USIF_ISR_CRC_OFFSET)
#define USIF_ISR_CRC_SET_INT (0x1 << USIF_ISR_CRC_OFFSET)
#define USIF_ISR_PHE_OFFSET 0x11
#define USIF_ISR_PHE_WIDTH 0x1
#define USIF_ISR_PHE_MASK 0x20000
#define USIF_ISR_PHE(_reg) (((_reg) & 0x20000) >> 0x11)
#define USIF_ISR_PHE_NO_CHANGE (0x0 << USIF_ISR_PHE_OFFSET)
#define USIF_ISR_PHE_SET_INT (0x1 << USIF_ISR_PHE_OFFSET)
#define USIF_ISR_FE_OFFSET 0x10
#define USIF_ISR_FE_WIDTH 0x1
#define USIF_ISR_FE_MASK 0x10000
#define USIF_ISR_FE(_reg) (((_reg) & 0x10000) >> 0x10)
#define USIF_ISR_FE_NO_CHANGE (0x0 << USIF_ISR_FE_OFFSET)
#define USIF_ISR_FE_SET_INT (0x1 << USIF_ISR_FE_OFFSET)
#define USIF_ISR_PE_OFFSET 0xf
#define USIF_ISR_PE_WIDTH 0x1
#define USIF_ISR_PE_MASK 0x8000
#define USIF_ISR_PE(_reg) (((_reg) & 0x8000) >> 0xf)
#define USIF_ISR_PE_NO_CHANGE (0x0 << USIF_ISR_PE_OFFSET)
#define USIF_ISR_PE_SET_INT (0x1 << USIF_ISR_PE_OFFSET)
#define USIF_ISR_TXOF_OFFSET 0xe
#define USIF_ISR_TXOF_WIDTH 0x1
#define USIF_ISR_TXOF_MASK 0x4000
#define USIF_ISR_TXOF(_reg) (((_reg) & 0x4000) >> 0xe)
#define USIF_ISR_TXOF_NO_CHANGE (0x0 << USIF_ISR_TXOF_OFFSET)
#define USIF_ISR_TXOF_SET_INT (0x1 << USIF_ISR_TXOF_OFFSET)
#define USIF_ISR_TXUR_OFFSET 0xd
#define USIF_ISR_TXUR_WIDTH 0x1
#define USIF_ISR_TXUR_MASK 0x2000
#define USIF_ISR_TXUR(_reg) (((_reg) & 0x2000) >> 0xd)
#define USIF_ISR_TXUR_NO_CHANGE (0x0 << USIF_ISR_TXUR_OFFSET)
#define USIF_ISR_TXUR_SET_INT (0x1 << USIF_ISR_TXUR_OFFSET)
#define USIF_ISR_RXOF_OFFSET 0xc
#define USIF_ISR_RXOF_WIDTH 0x1
#define USIF_ISR_RXOF_MASK 0x1000
#define USIF_ISR_RXOF(_reg) (((_reg) & 0x1000) >> 0xc)
#define USIF_ISR_RXOF_NO_CHANGE (0x0 << USIF_ISR_RXOF_OFFSET)
#define USIF_ISR_RXOF_SET_INT (0x1 << USIF_ISR_RXOF_OFFSET)
#define USIF_ISR_RXUR_OFFSET 0xb
#define USIF_ISR_RXUR_WIDTH 0x1
#define USIF_ISR_RXUR_MASK 0x800
#define USIF_ISR_RXUR(_reg) (((_reg) & 0x800) >> 0xb)
#define USIF_ISR_RXUR_NO_CHANGE (0x0 << USIF_ISR_RXUR_OFFSET)
#define USIF_ISR_RXUR_SET_INT (0x1 << USIF_ISR_RXUR_OFFSET)
#define USIF_ISR_WKP_OFFSET 0x9
#define USIF_ISR_WKP_WIDTH 0x1
#define USIF_ISR_WKP_MASK 0x200
#define USIF_ISR_WKP(_reg) (((_reg) & 0x200) >> 0x9)
#define USIF_ISR_WKP_NO_CHANGE (0x0 << USIF_ISR_WKP_OFFSET)
#define USIF_ISR_WKP_SET_INT (0x1 << USIF_ISR_WKP_OFFSET)
#define USIF_ISR_AB_OFFSET 0x8
#define USIF_ISR_AB_WIDTH 0x1
#define USIF_ISR_AB_MASK 0x100
#define USIF_ISR_AB(_reg) (((_reg) & 0x100) >> 0x8)
#define USIF_ISR_AB_NO_CHANGE (0x0 << USIF_ISR_AB_OFFSET)
#define USIF_ISR_AB_SET_INT (0x1 << USIF_ISR_AB_OFFSET)
#define USIF_ISR_TX_BREQ_OFFSET 0x7
#define USIF_ISR_TX_BREQ_WIDTH 0x1
#define USIF_ISR_TX_BREQ_MASK 0x80
#define USIF_ISR_TX_BREQ(_reg) (((_reg) & 0x80) >> 0x7)
#define USIF_ISR_TX_BREQ_NO_CHANGE (0x0 << USIF_ISR_TX_BREQ_OFFSET)
#define USIF_ISR_TX_BREQ_SET_INT (0x1 << USIF_ISR_TX_BREQ_OFFSET)
#define USIF_ISR_TX_LBREQ_OFFSET 0x6
#define USIF_ISR_TX_LBREQ_WIDTH 0x1
#define USIF_ISR_TX_LBREQ_MASK 0x40
#define USIF_ISR_TX_LBREQ(_reg) (((_reg) & 0x40) >> 0x6)
#define USIF_ISR_TX_LBREQ_NO_CHANGE (0x0 << USIF_ISR_TX_LBREQ_OFFSET)
#define USIF_ISR_TX_LBREQ_SET_INT (0x1 << USIF_ISR_TX_LBREQ_OFFSET)
#define USIF_ISR_TX_SREQ_OFFSET 0x5
#define USIF_ISR_TX_SREQ_WIDTH 0x1
#define USIF_ISR_TX_SREQ_MASK 0x20
#define USIF_ISR_TX_SREQ(_reg) (((_reg) & 0x20) >> 0x5)
#define USIF_ISR_TX_SREQ_NO_CHANGE (0x0 << USIF_ISR_TX_SREQ_OFFSET)
#define USIF_ISR_TX_SREQ_SET_INT (0x1 << USIF_ISR_TX_SREQ_OFFSET)
#define USIF_ISR_TX_LSREQ_OFFSET 0x4
#define USIF_ISR_TX_LSREQ_WIDTH 0x1
#define USIF_ISR_TX_LSREQ_MASK 0x10
#define USIF_ISR_TX_LSREQ(_reg) (((_reg) & 0x10) >> 0x4)
#define USIF_ISR_TX_LSREQ_NO_CHANGE (0x0 << USIF_ISR_TX_LSREQ_OFFSET)
#define USIF_ISR_TX_LSREQ_SET_INT (0x1 << USIF_ISR_TX_LSREQ_OFFSET)
#define USIF_ISR_RX_BREQ_OFFSET 0x3
#define USIF_ISR_RX_BREQ_WIDTH 0x1
#define USIF_ISR_RX_BREQ_MASK 0x8
#define USIF_ISR_RX_BREQ(_reg) (((_reg) & 0x8) >> 0x3)
#define USIF_ISR_RX_BREQ_NO_CHANGE (0x0 << USIF_ISR_RX_BREQ_OFFSET)
#define USIF_ISR_RX_BREQ_SET_INT (0x1 << USIF_ISR_RX_BREQ_OFFSET)
#define USIF_ISR_RX_LBREQ_OFFSET 0x2
#define USIF_ISR_RX_LBREQ_WIDTH 0x1
#define USIF_ISR_RX_LBREQ_MASK 0x4
#define USIF_ISR_RX_LBREQ(_reg) (((_reg) & 0x4) >> 0x2)
#define USIF_ISR_RX_LBREQ_NO_CHANGE (0x0 << USIF_ISR_RX_LBREQ_OFFSET)
#define USIF_ISR_RX_LBREQ_SET_INT (0x1 << USIF_ISR_RX_LBREQ_OFFSET)
#define USIF_ISR_RX_SREQ_OFFSET 0x1
#define USIF_ISR_RX_SREQ_WIDTH 0x1
#define USIF_ISR_RX_SREQ_MASK 0x2
#define USIF_ISR_RX_SREQ(_reg) (((_reg) & 0x2) >> 0x1)
#define USIF_ISR_RX_SREQ_NO_CHANGE (0x0 << USIF_ISR_RX_SREQ_OFFSET)
#define USIF_ISR_RX_SREQ_SET_INT (0x1 << USIF_ISR_RX_SREQ_OFFSET)
#define USIF_ISR_RX_LSREQ_OFFSET 0x0
#define USIF_ISR_RX_LSREQ_WIDTH 0x1
#define USIF_ISR_RX_LSREQ_MASK 0x1
#define USIF_ISR_RX_LSREQ(_reg) (((_reg) & 0x1) >> 0x0)
#define USIF_ISR_RX_LSREQ_NO_CHANGE (0x0 << USIF_ISR_RX_LSREQ_OFFSET)
#define USIF_ISR_RX_LSREQ_SET_INT (0x1 << USIF_ISR_RX_LSREQ_OFFSET)

#define USIF_DMAE_OFFSET	  0x94
#define USIF_DMAE(_base) ((_base) + 0x94)
#define USIF_DMAE_TX_BREQ_OFFSET 0x7
#define USIF_DMAE_TX_BREQ_WIDTH 0x1
#define USIF_DMAE_TX_BREQ_MASK 0x80
#define USIF_DMAE_TX_BREQ(_reg) (((_reg) & 0x80) >> 0x7)
#define USIF_DMAE_TX_BREQ_CPU_CTRL (0x0 << USIF_DMAE_TX_BREQ_OFFSET)
#define USIF_DMAE_TX_BREQ_DMA_CTRL (0x1 << USIF_DMAE_TX_BREQ_OFFSET)
#define USIF_DMAE_TX_LBREQ_OFFSET 0x6
#define USIF_DMAE_TX_LBREQ_WIDTH 0x1
#define USIF_DMAE_TX_LBREQ_MASK 0x40
#define USIF_DMAE_TX_LBREQ(_reg) (((_reg) & 0x40) >> 0x6)
#define USIF_DMAE_TX_LBREQ_CPU_CTRL (0x0 << USIF_DMAE_TX_LBREQ_OFFSET)
#define USIF_DMAE_TX_LBREQ_DMA_CTRL (0x1 << USIF_DMAE_TX_LBREQ_OFFSET)
#define USIF_DMAE_TX_SREQ_OFFSET 0x5
#define USIF_DMAE_TX_SREQ_WIDTH 0x1
#define USIF_DMAE_TX_SREQ_MASK 0x20
#define USIF_DMAE_TX_SREQ(_reg) (((_reg) & 0x20) >> 0x5)
#define USIF_DMAE_TX_SREQ_CPU_CTRL (0x0 << USIF_DMAE_TX_SREQ_OFFSET)
#define USIF_DMAE_TX_SREQ_DMA_CTRL (0x1 << USIF_DMAE_TX_SREQ_OFFSET)
#define USIF_DMAE_TX_LSREQ_OFFSET 0x4
#define USIF_DMAE_TX_LSREQ_WIDTH 0x1
#define USIF_DMAE_TX_LSREQ_MASK 0x10
#define USIF_DMAE_TX_LSREQ(_reg) (((_reg) & 0x10) >> 0x4)
#define USIF_DMAE_TX_LSREQ_CPU_CTRL (0x0 << USIF_DMAE_TX_LSREQ_OFFSET)
#define USIF_DMAE_TX_LSREQ_DMA_CTRL (0x1 << USIF_DMAE_TX_LSREQ_OFFSET)
#define USIF_DMAE_RX_BREQ_OFFSET 0x3
#define USIF_DMAE_RX_BREQ_WIDTH 0x1
#define USIF_DMAE_RX_BREQ_MASK 0x8
#define USIF_DMAE_RX_BREQ(_reg) (((_reg) & 0x8) >> 0x3)
#define USIF_DMAE_RX_BREQ_CPU_CTRL (0x0 << USIF_DMAE_RX_BREQ_OFFSET)
#define USIF_DMAE_RX_BREQ_DMA_CTRL (0x1 << USIF_DMAE_RX_BREQ_OFFSET)
#define USIF_DMAE_RX_LBREQ_OFFSET 0x2
#define USIF_DMAE_RX_LBREQ_WIDTH 0x1
#define USIF_DMAE_RX_LBREQ_MASK 0x4
#define USIF_DMAE_RX_LBREQ(_reg) (((_reg) & 0x4) >> 0x2)
#define USIF_DMAE_RX_LBREQ_CPU_CTRL (0x0 << USIF_DMAE_RX_LBREQ_OFFSET)
#define USIF_DMAE_RX_LBREQ_DMA_CTRL (0x1 << USIF_DMAE_RX_LBREQ_OFFSET)
#define USIF_DMAE_RX_SREQ_OFFSET 0x1
#define USIF_DMAE_RX_SREQ_WIDTH 0x1
#define USIF_DMAE_RX_SREQ_MASK 0x2
#define USIF_DMAE_RX_SREQ(_reg) (((_reg) & 0x2) >> 0x1)
#define USIF_DMAE_RX_SREQ_CPU_CTRL (0x0 << USIF_DMAE_RX_SREQ_OFFSET)
#define USIF_DMAE_RX_SREQ_DMA_CTRL (0x1 << USIF_DMAE_RX_SREQ_OFFSET)
#define USIF_DMAE_RX_LSREQ_OFFSET 0x0
#define USIF_DMAE_RX_LSREQ_WIDTH 0x1
#define USIF_DMAE_RX_LSREQ_MASK 0x1
#define USIF_DMAE_RX_LSREQ(_reg) (((_reg) & 0x1) >> 0x0)
#define USIF_DMAE_RX_LSREQ_CPU_CTRL (0x0 << USIF_DMAE_RX_LSREQ_OFFSET)
#define USIF_DMAE_RX_LSREQ_DMA_CTRL (0x1 << USIF_DMAE_RX_LSREQ_OFFSET)

#define USIF_ICR_OFFSET		  0x98
#define USIF_ICR(_base) ((_base) + 0x98)
#define USIF_ICR_TMO_OFFSET 0x1f
#define USIF_ICR_TMO_WIDTH 0x1
#define USIF_ICR_TMO_MASK 0x80000000
#define USIF_ICR_TMO(_reg) (((_reg) & 0x80000000) >> 0x1f)
#define USIF_ICR_TMO_NO_CHANGE (0x0 << USIF_ICR_TMO_OFFSET)
#define USIF_ICR_TMO_CLR_INT (0x1 << USIF_ICR_TMO_OFFSET)
#define USIF_ICR_FRM_PAUSE_OFFSET 0x1e
#define USIF_ICR_FRM_PAUSE_WIDTH 0x1
#define USIF_ICR_FRM_PAUSE_MASK 0x40000000
#define USIF_ICR_FRM_PAUSE(_reg) (((_reg) & 0x40000000) >> 0x1e)
#define USIF_ICR_FRM_PAUSE_NO_CHANGE (0x0 << USIF_ICR_FRM_PAUSE_OFFSET)
#define USIF_ICR_FRM_PAUSE_CLR_INT (0x1 << USIF_ICR_FRM_PAUSE_OFFSET)
#define USIF_ICR_TX_FIN_OFFSET 0x1d
#define USIF_ICR_TX_FIN_WIDTH 0x1
#define USIF_ICR_TX_FIN_MASK 0x20000000
#define USIF_ICR_TX_FIN(_reg) (((_reg) & 0x20000000) >> 0x1d)
#define USIF_ICR_TX_FIN_NO_CHANGE (0x0 << USIF_ICR_TX_FIN_OFFSET)
#define USIF_ICR_TX_FIN_CLR_INT (0x1 << USIF_ICR_TX_FIN_OFFSET)
#define USIF_ICR_RI_OFFSET 0x1c
#define USIF_ICR_RI_WIDTH 0x1
#define USIF_ICR_RI_MASK 0x10000000
#define USIF_ICR_RI(_reg) (((_reg) & 0x10000000) >> 0x1c)
#define USIF_ICR_RI_NO_CHANGE (0x0 << USIF_ICR_RI_OFFSET)
#define USIF_ICR_RI_CLR_INT (0x1 << USIF_ICR_RI_OFFSET)
#define USIF_ICR_DCD_OFFSET 0x1b
#define USIF_ICR_DCD_WIDTH 0x1
#define USIF_ICR_DCD_MASK 0x8000000
#define USIF_ICR_DCD(_reg) (((_reg) & 0x8000000) >> 0x1b)
#define USIF_ICR_DCD_NO_CHANGE (0x0 << USIF_ICR_DCD_OFFSET)
#define USIF_ICR_DCD_CLR_INT (0x1 << USIF_ICR_DCD_OFFSET)
#define USIF_ICR_DSR_OFFSET 0x1a
#define USIF_ICR_DSR_WIDTH 0x1
#define USIF_ICR_DSR_MASK 0x4000000
#define USIF_ICR_DSR(_reg) (((_reg) & 0x4000000) >> 0x1a)
#define USIF_ICR_DSR_NO_CHANGE (0x0 << USIF_ICR_DSR_OFFSET)
#define USIF_ICR_DSR_CLR_INT (0x1 << USIF_ICR_DSR_OFFSET)
#define USIF_ICR_DTR_OFFSET 0x19
#define USIF_ICR_DTR_WIDTH 0x1
#define USIF_ICR_DTR_MASK 0x2000000
#define USIF_ICR_DTR(_reg) (((_reg) & 0x2000000) >> 0x19)
#define USIF_ICR_DTR_NO_CHANGE (0x0 << USIF_ICR_DTR_OFFSET)
#define USIF_ICR_DTR_CLR_INT (0x1 << USIF_ICR_DTR_OFFSET)
#define USIF_ICR_FCI_OFFSET 0x18
#define USIF_ICR_FCI_WIDTH 0x1
#define USIF_ICR_FCI_MASK 0x1000000
#define USIF_ICR_FCI(_reg) (((_reg) & 0x1000000) >> 0x18)
#define USIF_ICR_FCI_NO_CHANGE (0x0 << USIF_ICR_FCI_OFFSET)
#define USIF_ICR_FCI_CLR_INT (0x1 << USIF_ICR_FCI_OFFSET)
#define USIF_ICR_FCO_OFFSET 0x17
#define USIF_ICR_FCO_WIDTH 0x1
#define USIF_ICR_FCO_MASK 0x800000
#define USIF_ICR_FCO(_reg) (((_reg) & 0x800000) >> 0x17)
#define USIF_ICR_FCO_NO_CHANGE (0x0 << USIF_ICR_FCO_OFFSET)
#define USIF_ICR_FCO_CLR_INT (0x1 << USIF_ICR_FCO_OFFSET)
#define USIF_ICR_MC_OFFSET 0x15
#define USIF_ICR_MC_WIDTH 0x1
#define USIF_ICR_MC_MASK 0x200000
#define USIF_ICR_MC(_reg) (((_reg) & 0x200000) >> 0x15)
#define USIF_ICR_MC_NO_CHANGE (0x0 << USIF_ICR_MC_OFFSET)
#define USIF_ICR_MC_CLR_INT (0x1 << USIF_ICR_MC_OFFSET)
#define USIF_ICR_SLIP_OFFSET 0x14
#define USIF_ICR_SLIP_WIDTH 0x1
#define USIF_ICR_SLIP_MASK 0x100000
#define USIF_ICR_SLIP(_reg) (((_reg) & 0x100000) >> 0x14)
#define USIF_ICR_SLIP_NO_CHANGE (0x0 << USIF_ICR_SLIP_OFFSET)
#define USIF_ICR_SLIP_CLR_INT (0x1 << USIF_ICR_SLIP_OFFSET)
#define USIF_ICR_CRC_OFFSET 0x13
#define USIF_ICR_CRC_WIDTH 0x1
#define USIF_ICR_CRC_MASK 0x80000
#define USIF_ICR_CRC(_reg) (((_reg) & 0x80000) >> 0x13)
#define USIF_ICR_CRC_NO_CHANGE (0x0 << USIF_ICR_CRC_OFFSET)
#define USIF_ICR_CRC_CLR_INT (0x1 << USIF_ICR_CRC_OFFSET)
#define USIF_ICR_PHE_OFFSET 0x11
#define USIF_ICR_PHE_WIDTH 0x1
#define USIF_ICR_PHE_MASK 0x20000
#define USIF_ICR_PHE(_reg) (((_reg) & 0x20000) >> 0x11)
#define USIF_ICR_PHE_NO_CHANGE (0x0 << USIF_ICR_PHE_OFFSET)
#define USIF_ICR_PHE_CLR_INT (0x1 << USIF_ICR_PHE_OFFSET)
#define USIF_ICR_FE_OFFSET 0x10
#define USIF_ICR_FE_WIDTH 0x1
#define USIF_ICR_FE_MASK 0x10000
#define USIF_ICR_FE(_reg) (((_reg) & 0x10000) >> 0x10)
#define USIF_ICR_FE_NO_CHANGE (0x0 << USIF_ICR_FE_OFFSET)
#define USIF_ICR_FE_CLR_INT (0x1 << USIF_ICR_FE_OFFSET)
#define USIF_ICR_PE_OFFSET 0xf
#define USIF_ICR_PE_WIDTH 0x1
#define USIF_ICR_PE_MASK 0x8000
#define USIF_ICR_PE(_reg) (((_reg) & 0x8000) >> 0xf)
#define USIF_ICR_PE_NO_CHANGE (0x0 << USIF_ICR_PE_OFFSET)
#define USIF_ICR_PE_CLR_INT (0x1 << USIF_ICR_PE_OFFSET)
#define USIF_ICR_TXOF_OFFSET 0xe
#define USIF_ICR_TXOF_WIDTH 0x1
#define USIF_ICR_TXOF_MASK 0x4000
#define USIF_ICR_TXOF(_reg) (((_reg) & 0x4000) >> 0xe)
#define USIF_ICR_TXOF_NO_CHANGE (0x0 << USIF_ICR_TXOF_OFFSET)
#define USIF_ICR_TXOF_CLR_INT (0x1 << USIF_ICR_TXOF_OFFSET)
#define USIF_ICR_TXUR_OFFSET 0xd
#define USIF_ICR_TXUR_WIDTH 0x1
#define USIF_ICR_TXUR_MASK 0x2000
#define USIF_ICR_TXUR(_reg) (((_reg) & 0x2000) >> 0xd)
#define USIF_ICR_TXUR_NO_CHANGE (0x0 << USIF_ICR_TXUR_OFFSET)
#define USIF_ICR_TXUR_CLR_INT (0x1 << USIF_ICR_TXUR_OFFSET)
#define USIF_ICR_RXOF_OFFSET 0xc
#define USIF_ICR_RXOF_WIDTH 0x1
#define USIF_ICR_RXOF_MASK 0x1000
#define USIF_ICR_RXOF(_reg) (((_reg) & 0x1000) >> 0xc)
#define USIF_ICR_RXOF_NO_CHANGE (0x0 << USIF_ICR_RXOF_OFFSET)
#define USIF_ICR_RXOF_CLR_INT (0x1 << USIF_ICR_RXOF_OFFSET)
#define USIF_ICR_RXUR_OFFSET 0xb
#define USIF_ICR_RXUR_WIDTH 0x1
#define USIF_ICR_RXUR_MASK 0x800
#define USIF_ICR_RXUR(_reg) (((_reg) & 0x800) >> 0xb)
#define USIF_ICR_RXUR_NO_CHANGE (0x0 << USIF_ICR_RXUR_OFFSET)
#define USIF_ICR_RXUR_CLR_INT (0x1 << USIF_ICR_RXUR_OFFSET)
#define USIF_ICR_WKP_OFFSET 0x9
#define USIF_ICR_WKP_WIDTH 0x1
#define USIF_ICR_WKP_MASK 0x200
#define USIF_ICR_WKP(_reg) (((_reg) & 0x200) >> 0x9)
#define USIF_ICR_WKP_NO_CHANGE (0x0 << USIF_ICR_WKP_OFFSET)
#define USIF_ICR_WKP_CLR_INT (0x1 << USIF_ICR_WKP_OFFSET)
#define USIF_ICR_AB_OFFSET 0x8
#define USIF_ICR_AB_WIDTH 0x1
#define USIF_ICR_AB_MASK 0x100
#define USIF_ICR_AB(_reg) (((_reg) & 0x100) >> 0x8)
#define USIF_ICR_AB_NO_CHANGE (0x0 << USIF_ICR_AB_OFFSET)
#define USIF_ICR_AB_CLR_INT (0x1 << USIF_ICR_AB_OFFSET)
#define USIF_ICR_TX_BREQ_OFFSET 0x7
#define USIF_ICR_TX_BREQ_WIDTH 0x1
#define USIF_ICR_TX_BREQ_MASK 0x80
#define USIF_ICR_TX_BREQ(_reg) (((_reg) & 0x80) >> 0x7)
#define USIF_ICR_TX_BREQ_NO_CHANGE (0x0 << USIF_ICR_TX_BREQ_OFFSET)
#define USIF_ICR_TX_BREQ_CLR_INT (0x1 << USIF_ICR_TX_BREQ_OFFSET)
#define USIF_ICR_TX_LBREQ_OFFSET 0x6
#define USIF_ICR_TX_LBREQ_WIDTH 0x1
#define USIF_ICR_TX_LBREQ_MASK 0x40
#define USIF_ICR_TX_LBREQ(_reg) (((_reg) & 0x40) >> 0x6)
#define USIF_ICR_TX_LBREQ_NO_CHANGE (0x0 << USIF_ICR_TX_LBREQ_OFFSET)
#define USIF_ICR_TX_LBREQ_CLR_INT (0x1 << USIF_ICR_TX_LBREQ_OFFSET)
#define USIF_ICR_TX_SREQ_OFFSET 0x5
#define USIF_ICR_TX_SREQ_WIDTH 0x1
#define USIF_ICR_TX_SREQ_MASK 0x20
#define USIF_ICR_TX_SREQ(_reg) (((_reg) & 0x20) >> 0x5)
#define USIF_ICR_TX_SREQ_NO_CHANGE (0x0 << USIF_ICR_TX_SREQ_OFFSET)
#define USIF_ICR_TX_SREQ_CLR_INT (0x1 << USIF_ICR_TX_SREQ_OFFSET)
#define USIF_ICR_TX_LSREQ_OFFSET 0x4
#define USIF_ICR_TX_LSREQ_WIDTH 0x1
#define USIF_ICR_TX_LSREQ_MASK 0x10
#define USIF_ICR_TX_LSREQ(_reg) (((_reg) & 0x10) >> 0x4)
#define USIF_ICR_TX_LSREQ_NO_CHANGE (0x0 << USIF_ICR_TX_LSREQ_OFFSET)
#define USIF_ICR_TX_LSREQ_CLR_INT (0x1 << USIF_ICR_TX_LSREQ_OFFSET)
#define USIF_ICR_RX_BREQ_OFFSET 0x3
#define USIF_ICR_RX_BREQ_WIDTH 0x1
#define USIF_ICR_RX_BREQ_MASK 0x8
#define USIF_ICR_RX_BREQ(_reg) (((_reg) & 0x8) >> 0x3)
#define USIF_ICR_RX_BREQ_NO_CHANGE (0x0 << USIF_ICR_RX_BREQ_OFFSET)
#define USIF_ICR_RX_BREQ_CLR_INT (0x1 << USIF_ICR_RX_BREQ_OFFSET)
#define USIF_ICR_RX_LBREQ_OFFSET 0x2
#define USIF_ICR_RX_LBREQ_WIDTH 0x1
#define USIF_ICR_RX_LBREQ_MASK 0x4
#define USIF_ICR_RX_LBREQ(_reg) (((_reg) & 0x4) >> 0x2)
#define USIF_ICR_RX_LBREQ_NO_CHANGE (0x0 << USIF_ICR_RX_LBREQ_OFFSET)
#define USIF_ICR_RX_LBREQ_CLR_INT (0x1 << USIF_ICR_RX_LBREQ_OFFSET)
#define USIF_ICR_RX_SREQ_OFFSET 0x1
#define USIF_ICR_RX_SREQ_WIDTH 0x1
#define USIF_ICR_RX_SREQ_MASK 0x2
#define USIF_ICR_RX_SREQ(_reg) (((_reg) & 0x2) >> 0x1)
#define USIF_ICR_RX_SREQ_NO_CHANGE (0x0 << USIF_ICR_RX_SREQ_OFFSET)
#define USIF_ICR_RX_SREQ_CLR_INT (0x1 << USIF_ICR_RX_SREQ_OFFSET)
#define USIF_ICR_RX_LSREQ_OFFSET 0x0
#define USIF_ICR_RX_LSREQ_WIDTH 0x1
#define USIF_ICR_RX_LSREQ_MASK 0x1
#define USIF_ICR_RX_LSREQ(_reg) (((_reg) & 0x1) >> 0x0)
#define USIF_ICR_RX_LSREQ_NO_CHANGE (0x0 << USIF_ICR_RX_LSREQ_OFFSET)
#define USIF_ICR_RX_LSREQ_CLR_INT (0x1 << USIF_ICR_RX_LSREQ_OFFSET)

#endif /* _XGOLD_USIF_H */
